# Generated by rboto-codegen. DO NOT EDIT.
from __future__ import annotations

from typing import TYPE_CHECKING

from .session import Session

if TYPE_CHECKING:
    from rboto_dynamodb import DynamoDBClient
    from rboto_s3 import S3Client
    from rboto_sqs import SQSClient


def _resolve_config(
    session: Session | None,
    region: str | None,
    profile: str | None,
    endpoint_url: str | None,
) -> tuple[str | None, str | None, str | None]:
    if session is None:
        return region, profile, endpoint_url
    if any(value is not None for value in (region, profile, endpoint_url)):
        raise ValueError("session cannot be combined with explicit service configuration")
    return session.region, session.profile, session.endpoint_url


def dynamodb(
    *,
    session: Session | None = None,
    region: str | None = None,
    profile: str | None = None,
    endpoint_url: str | None = None,
) -> DynamoDBClient:
    try:
        from rboto_dynamodb import DynamoDBClient
    except ImportError as error:
        raise ImportError(
            'dynamodb support is not installed. Install it with: '
            'pip install "rboto[dynamodb]"'
        ) from error
    region, profile, endpoint_url = _resolve_config(
        session, region, profile, endpoint_url
    )
    return DynamoDBClient(
        region=region,
        profile=profile,
        endpoint_url=endpoint_url,
    )


def s3(
    *,
    session: Session | None = None,
    region: str | None = None,
    profile: str | None = None,
    endpoint_url: str | None = None,
) -> S3Client:
    try:
        from rboto_s3 import S3Client
    except ImportError as error:
        raise ImportError(
            's3 support is not installed. Install it with: '
            'pip install "rboto[s3]"'
        ) from error
    region, profile, endpoint_url = _resolve_config(
        session, region, profile, endpoint_url
    )
    return S3Client(
        region=region,
        profile=profile,
        endpoint_url=endpoint_url,
    )


def sqs(
    *,
    session: Session | None = None,
    region: str | None = None,
    profile: str | None = None,
    endpoint_url: str | None = None,
) -> SQSClient:
    try:
        from rboto_sqs import SQSClient
    except ImportError as error:
        raise ImportError(
            'sqs support is not installed. Install it with: '
            'pip install "rboto[sqs]"'
        ) from error
    region, profile, endpoint_url = _resolve_config(
        session, region, profile, endpoint_url
    )
    return SQSClient(
        region=region,
        profile=profile,
        endpoint_url=endpoint_url,
    )


