from __future__ import annotations

from collections.abc import AsyncIterator
from typing import final

from .types import SelectObjectContentOutput


@final
class ByteStream:
    def __aiter__(self) -> AsyncIterator[bytes]: ...
    async def __anext__(self) -> bytes: ...
    async def read(self) -> bytes: ...

@final
class SelectObjectContentEventStreamReceiver:
    def __aiter__(self) -> AsyncIterator[dict[str, object]]: ...
    async def __anext__(self) -> dict[str, object]: ...


@final
class AbacStatus:
    @property
    def status(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class AbortIncompleteMultipartUpload:
    @property
    def days_after_initiation(self) -> int | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class AccessControlTranslation:
    @property
    def owner(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class AnalyticsConfiguration:
    @property
    def id(self) -> str: ...
    @property
    def filter(self) -> dict[str, object] | None: ...
    @property
    def storage_class_analysis(self) -> StorageClassAnalysis | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class AnalyticsExportDestination:
    @property
    def s3_bucket_destination(self) -> AnalyticsS3BucketDestination | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class AnalyticsS3BucketDestination:
    @property
    def format(self) -> str: ...
    @property
    def bucket_account_id(self) -> str | None: ...
    @property
    def bucket(self) -> str: ...
    @property
    def prefix(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class BlockedEncryptionTypes:
    @property
    def encryption_type(self) -> list[str] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Bucket:
    @property
    def name(self) -> str | None: ...
    @property
    def creation_date(self) -> str | None: ...
    @property
    def bucket_region(self) -> str | None: ...
    @property
    def bucket_arn(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Checksum:
    @property
    def checksum_crc32(self) -> str | None: ...
    @property
    def checksum_crc32_c(self) -> str | None: ...
    @property
    def checksum_crc64_nvme(self) -> str | None: ...
    @property
    def checksum_sha1(self) -> str | None: ...
    @property
    def checksum_sha256(self) -> str | None: ...
    @property
    def checksum_type(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CommonPrefix:
    @property
    def prefix(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Condition:
    @property
    def http_error_code_returned_equals(self) -> str | None: ...
    @property
    def key_prefix_equals(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CopyObjectResult:
    @property
    def e_tag(self) -> str | None: ...
    @property
    def last_modified(self) -> str | None: ...
    @property
    def checksum_type(self) -> str | None: ...
    @property
    def checksum_crc32(self) -> str | None: ...
    @property
    def checksum_crc32_c(self) -> str | None: ...
    @property
    def checksum_crc64_nvme(self) -> str | None: ...
    @property
    def checksum_sha1(self) -> str | None: ...
    @property
    def checksum_sha256(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CopyPartResult:
    @property
    def e_tag(self) -> str | None: ...
    @property
    def last_modified(self) -> str | None: ...
    @property
    def checksum_crc32(self) -> str | None: ...
    @property
    def checksum_crc32_c(self) -> str | None: ...
    @property
    def checksum_crc64_nvme(self) -> str | None: ...
    @property
    def checksum_sha1(self) -> str | None: ...
    @property
    def checksum_sha256(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CorsRule:
    @property
    def id(self) -> str | None: ...
    @property
    def allowed_headers(self) -> list[str] | None: ...
    @property
    def allowed_methods(self) -> list[str]: ...
    @property
    def allowed_origins(self) -> list[str]: ...
    @property
    def expose_headers(self) -> list[str] | None: ...
    @property
    def max_age_seconds(self) -> int | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DefaultRetention:
    @property
    def mode(self) -> str | None: ...
    @property
    def days(self) -> int | None: ...
    @property
    def years(self) -> int | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DeleteMarkerEntry:
    @property
    def owner(self) -> Owner | None: ...
    @property
    def key(self) -> str | None: ...
    @property
    def version_id(self) -> str | None: ...
    @property
    def is_latest(self) -> bool | None: ...
    @property
    def last_modified(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DeleteMarkerReplication:
    @property
    def status(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DeletedObject:
    @property
    def key(self) -> str | None: ...
    @property
    def version_id(self) -> str | None: ...
    @property
    def delete_marker(self) -> bool | None: ...
    @property
    def delete_marker_version_id(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Destination:
    @property
    def bucket(self) -> str: ...
    @property
    def account(self) -> str | None: ...
    @property
    def storage_class(self) -> str | None: ...
    @property
    def access_control_translation(self) -> AccessControlTranslation | None: ...
    @property
    def encryption_configuration(self) -> EncryptionConfiguration | None: ...
    @property
    def replication_time(self) -> ReplicationTime | None: ...
    @property
    def metrics(self) -> Metrics | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DestinationResult:
    @property
    def table_bucket_type(self) -> str | None: ...
    @property
    def table_bucket_arn(self) -> str | None: ...
    @property
    def table_namespace(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class EncryptionConfiguration:
    @property
    def replica_kms_key_id(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Error:
    @property
    def key(self) -> str | None: ...
    @property
    def version_id(self) -> str | None: ...
    @property
    def code(self) -> str | None: ...
    @property
    def message(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ErrorDetails:
    @property
    def error_code(self) -> str | None: ...
    @property
    def error_message(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ErrorDocument:
    @property
    def key(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class EventBridgeConfiguration:
    def to_dict(self) -> dict[str, object]: ...

@final
class ExistingObjectReplication:
    @property
    def status(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class FilterRule:
    @property
    def name(self) -> str | None: ...
    @property
    def value(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketMetadataConfigurationResult:
    @property
    def metadata_configuration_result(self) -> MetadataConfigurationResult | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketMetadataTableConfigurationResult:
    @property
    def metadata_table_configuration_result(self) -> MetadataTableConfigurationResult | None: ...
    @property
    def status(self) -> str: ...
    @property
    def error(self) -> ErrorDetails | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetObjectAttributesParts:
    @property
    def total_parts_count(self) -> int | None: ...
    @property
    def part_number_marker(self) -> str | None: ...
    @property
    def next_part_number_marker(self) -> str | None: ...
    @property
    def max_parts(self) -> int | None: ...
    @property
    def is_truncated(self) -> bool | None: ...
    @property
    def parts(self) -> list[ObjectPart] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Grant:
    @property
    def grantee(self) -> Grantee | None: ...
    @property
    def permission(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Grantee:
    @property
    def display_name(self) -> str | None: ...
    @property
    def email_address(self) -> str | None: ...
    @property
    def id(self) -> str | None: ...
    @property
    def uri(self) -> str | None: ...
    @property
    def type(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class IndexDocument:
    @property
    def suffix(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Initiator:
    @property
    def id(self) -> str | None: ...
    @property
    def display_name(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class IntelligentTieringAndOperator:
    @property
    def prefix(self) -> str | None: ...
    @property
    def tags(self) -> list[Tag] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class IntelligentTieringConfiguration:
    @property
    def id(self) -> str: ...
    @property
    def filter(self) -> IntelligentTieringFilter | None: ...
    @property
    def status(self) -> str: ...
    @property
    def tierings(self) -> list[Tiering]: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class IntelligentTieringFilter:
    @property
    def prefix(self) -> str | None: ...
    @property
    def tag(self) -> Tag | None: ...
    @property
    def and_(self) -> IntelligentTieringAndOperator | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class InventoryConfiguration:
    @property
    def destination(self) -> InventoryDestination | None: ...
    @property
    def is_enabled(self) -> bool: ...
    @property
    def filter(self) -> InventoryFilter | None: ...
    @property
    def id(self) -> str: ...
    @property
    def included_object_versions(self) -> str: ...
    @property
    def optional_fields(self) -> list[str] | None: ...
    @property
    def schedule(self) -> InventorySchedule | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class InventoryDestination:
    @property
    def s3_bucket_destination(self) -> InventoryS3BucketDestination | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class InventoryEncryption:
    @property
    def sses3(self) -> Sses3 | None: ...
    @property
    def ssekms(self) -> Ssekms | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class InventoryFilter:
    @property
    def prefix(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class InventoryS3BucketDestination:
    @property
    def account_id(self) -> str | None: ...
    @property
    def bucket(self) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def prefix(self) -> str | None: ...
    @property
    def encryption(self) -> InventoryEncryption | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class InventorySchedule:
    @property
    def frequency(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class InventoryTableConfigurationResult:
    @property
    def configuration_state(self) -> str: ...
    @property
    def table_status(self) -> str | None: ...
    @property
    def error(self) -> ErrorDetails | None: ...
    @property
    def table_name(self) -> str | None: ...
    @property
    def table_arn(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class JournalTableConfigurationResult:
    @property
    def table_status(self) -> str: ...
    @property
    def error(self) -> ErrorDetails | None: ...
    @property
    def table_name(self) -> str: ...
    @property
    def table_arn(self) -> str | None: ...
    @property
    def record_expiration(self) -> RecordExpiration | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class LambdaFunctionConfiguration:
    @property
    def id(self) -> str | None: ...
    @property
    def lambda_function_arn(self) -> str: ...
    @property
    def events(self) -> list[str]: ...
    @property
    def filter(self) -> NotificationConfigurationFilter | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class LifecycleExpiration:
    @property
    def date(self) -> str | None: ...
    @property
    def days(self) -> int | None: ...
    @property
    def expired_object_delete_marker(self) -> bool | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class LifecycleRule:
    @property
    def expiration(self) -> LifecycleExpiration | None: ...
    @property
    def id(self) -> str | None: ...
    @property
    def prefix(self) -> str | None: ...
    @property
    def filter(self) -> LifecycleRuleFilter | None: ...
    @property
    def status(self) -> str: ...
    @property
    def transitions(self) -> list[Transition] | None: ...
    @property
    def noncurrent_version_transitions(self) -> list[NoncurrentVersionTransition] | None: ...
    @property
    def noncurrent_version_expiration(self) -> NoncurrentVersionExpiration | None: ...
    @property
    def abort_incomplete_multipart_upload(self) -> AbortIncompleteMultipartUpload | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class LifecycleRuleAndOperator:
    @property
    def prefix(self) -> str | None: ...
    @property
    def tags(self) -> list[Tag] | None: ...
    @property
    def object_size_greater_than(self) -> int | None: ...
    @property
    def object_size_less_than(self) -> int | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class LifecycleRuleFilter:
    @property
    def prefix(self) -> str | None: ...
    @property
    def tag(self) -> Tag | None: ...
    @property
    def object_size_greater_than(self) -> int | None: ...
    @property
    def object_size_less_than(self) -> int | None: ...
    @property
    def and_(self) -> LifecycleRuleAndOperator | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class LoggingEnabled:
    @property
    def target_bucket(self) -> str: ...
    @property
    def target_grants(self) -> list[TargetGrant] | None: ...
    @property
    def target_prefix(self) -> str: ...
    @property
    def target_object_key_format(self) -> TargetObjectKeyFormat | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class MetadataConfigurationResult:
    @property
    def destination_result(self) -> DestinationResult | None: ...
    @property
    def journal_table_configuration_result(self) -> JournalTableConfigurationResult | None: ...
    @property
    def inventory_table_configuration_result(self) -> InventoryTableConfigurationResult | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class MetadataTableConfigurationResult:
    @property
    def s3_tables_destination_result(self) -> S3TablesDestinationResult | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Metrics:
    @property
    def status(self) -> str: ...
    @property
    def event_threshold(self) -> ReplicationTimeValue | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class MetricsConfiguration:
    @property
    def id(self) -> str: ...
    @property
    def filter(self) -> dict[str, object] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class MultipartUpload:
    @property
    def upload_id(self) -> str | None: ...
    @property
    def key(self) -> str | None: ...
    @property
    def initiated(self) -> str | None: ...
    @property
    def storage_class(self) -> str | None: ...
    @property
    def owner(self) -> Owner | None: ...
    @property
    def initiator(self) -> Initiator | None: ...
    @property
    def checksum_algorithm(self) -> str | None: ...
    @property
    def checksum_type(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class NoncurrentVersionExpiration:
    @property
    def noncurrent_days(self) -> int | None: ...
    @property
    def newer_noncurrent_versions(self) -> int | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class NoncurrentVersionTransition:
    @property
    def noncurrent_days(self) -> int | None: ...
    @property
    def storage_class(self) -> str | None: ...
    @property
    def newer_noncurrent_versions(self) -> int | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class NotificationConfigurationFilter:
    @property
    def key(self) -> S3KeyFilter | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Object:
    @property
    def key(self) -> str | None: ...
    @property
    def last_modified(self) -> str | None: ...
    @property
    def e_tag(self) -> str | None: ...
    @property
    def checksum_algorithm(self) -> list[str] | None: ...
    @property
    def checksum_type(self) -> str | None: ...
    @property
    def size(self) -> int | None: ...
    @property
    def storage_class(self) -> str | None: ...
    @property
    def owner(self) -> Owner | None: ...
    @property
    def restore_status(self) -> RestoreStatus | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ObjectLockConfiguration:
    @property
    def object_lock_enabled(self) -> str | None: ...
    @property
    def rule(self) -> ObjectLockRule | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ObjectLockLegalHold:
    @property
    def status(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ObjectLockRetention:
    @property
    def mode(self) -> str | None: ...
    @property
    def retain_until_date(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ObjectLockRule:
    @property
    def default_retention(self) -> DefaultRetention | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ObjectPart:
    @property
    def part_number(self) -> int | None: ...
    @property
    def size(self) -> int | None: ...
    @property
    def checksum_crc32(self) -> str | None: ...
    @property
    def checksum_crc32_c(self) -> str | None: ...
    @property
    def checksum_crc64_nvme(self) -> str | None: ...
    @property
    def checksum_sha1(self) -> str | None: ...
    @property
    def checksum_sha256(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ObjectVersion:
    @property
    def e_tag(self) -> str | None: ...
    @property
    def checksum_algorithm(self) -> list[str] | None: ...
    @property
    def checksum_type(self) -> str | None: ...
    @property
    def size(self) -> int | None: ...
    @property
    def storage_class(self) -> str | None: ...
    @property
    def key(self) -> str | None: ...
    @property
    def version_id(self) -> str | None: ...
    @property
    def is_latest(self) -> bool | None: ...
    @property
    def last_modified(self) -> str | None: ...
    @property
    def owner(self) -> Owner | None: ...
    @property
    def restore_status(self) -> RestoreStatus | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Owner:
    @property
    def display_name(self) -> str | None: ...
    @property
    def id(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class OwnershipControls:
    @property
    def rules(self) -> list[OwnershipControlsRule]: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class OwnershipControlsRule:
    @property
    def object_ownership(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Part:
    @property
    def part_number(self) -> int | None: ...
    @property
    def last_modified(self) -> str | None: ...
    @property
    def e_tag(self) -> str | None: ...
    @property
    def size(self) -> int | None: ...
    @property
    def checksum_crc32(self) -> str | None: ...
    @property
    def checksum_crc32_c(self) -> str | None: ...
    @property
    def checksum_crc64_nvme(self) -> str | None: ...
    @property
    def checksum_sha1(self) -> str | None: ...
    @property
    def checksum_sha256(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class PartitionedPrefix:
    @property
    def partition_date_source(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class PolicyStatus:
    @property
    def is_public(self) -> bool | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class PublicAccessBlockConfiguration:
    @property
    def block_public_acls(self) -> bool | None: ...
    @property
    def ignore_public_acls(self) -> bool | None: ...
    @property
    def block_public_policy(self) -> bool | None: ...
    @property
    def restrict_public_buckets(self) -> bool | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class QueueConfiguration:
    @property
    def id(self) -> str | None: ...
    @property
    def queue_arn(self) -> str: ...
    @property
    def events(self) -> list[str]: ...
    @property
    def filter(self) -> NotificationConfigurationFilter | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class RecordExpiration:
    @property
    def expiration(self) -> str: ...
    @property
    def days(self) -> int | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Redirect:
    @property
    def host_name(self) -> str | None: ...
    @property
    def http_redirect_code(self) -> str | None: ...
    @property
    def protocol(self) -> str | None: ...
    @property
    def replace_key_prefix_with(self) -> str | None: ...
    @property
    def replace_key_with(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class RedirectAllRequestsTo:
    @property
    def host_name(self) -> str: ...
    @property
    def protocol(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ReplicaModifications:
    @property
    def status(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ReplicationConfiguration:
    @property
    def role(self) -> str: ...
    @property
    def rules(self) -> list[ReplicationRule]: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ReplicationRule:
    @property
    def id(self) -> str | None: ...
    @property
    def priority(self) -> int | None: ...
    @property
    def prefix(self) -> str | None: ...
    @property
    def filter(self) -> ReplicationRuleFilter | None: ...
    @property
    def status(self) -> str: ...
    @property
    def source_selection_criteria(self) -> SourceSelectionCriteria | None: ...
    @property
    def existing_object_replication(self) -> ExistingObjectReplication | None: ...
    @property
    def destination(self) -> Destination | None: ...
    @property
    def delete_marker_replication(self) -> DeleteMarkerReplication | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ReplicationRuleAndOperator:
    @property
    def prefix(self) -> str | None: ...
    @property
    def tags(self) -> list[Tag] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ReplicationRuleFilter:
    @property
    def prefix(self) -> str | None: ...
    @property
    def tag(self) -> Tag | None: ...
    @property
    def and_(self) -> ReplicationRuleAndOperator | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ReplicationTime:
    @property
    def status(self) -> str: ...
    @property
    def time(self) -> ReplicationTimeValue | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ReplicationTimeValue:
    @property
    def minutes(self) -> int | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class RestoreStatus:
    @property
    def is_restore_in_progress(self) -> bool | None: ...
    @property
    def restore_expiry_date(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class RoutingRule:
    @property
    def condition(self) -> Condition | None: ...
    @property
    def redirect(self) -> Redirect | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class S3KeyFilter:
    @property
    def filter_rules(self) -> list[FilterRule] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class S3TablesDestinationResult:
    @property
    def table_bucket_arn(self) -> str: ...
    @property
    def table_name(self) -> str: ...
    @property
    def table_arn(self) -> str: ...
    @property
    def table_namespace(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ServerSideEncryptionByDefault:
    @property
    def sse_algorithm(self) -> str: ...
    @property
    def kms_master_key_id(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ServerSideEncryptionConfiguration:
    @property
    def rules(self) -> list[ServerSideEncryptionRule]: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ServerSideEncryptionRule:
    @property
    def apply_server_side_encryption_by_default(self) -> ServerSideEncryptionByDefault | None: ...
    @property
    def bucket_key_enabled(self) -> bool | None: ...
    @property
    def blocked_encryption_types(self) -> BlockedEncryptionTypes | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class SessionCredentials:
    @property
    def access_key_id(self) -> str: ...
    @property
    def secret_access_key(self) -> str: ...
    @property
    def session_token(self) -> str: ...
    @property
    def expiration(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class SimplePrefix:
    def to_dict(self) -> dict[str, object]: ...

@final
class SourceSelectionCriteria:
    @property
    def sse_kms_encrypted_objects(self) -> SseKmsEncryptedObjects | None: ...
    @property
    def replica_modifications(self) -> ReplicaModifications | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class SseKmsEncryptedObjects:
    @property
    def status(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Ssekms:
    @property
    def key_id(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Sses3:
    def to_dict(self) -> dict[str, object]: ...

@final
class StorageClassAnalysis:
    @property
    def data_export(self) -> StorageClassAnalysisDataExport | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class StorageClassAnalysisDataExport:
    @property
    def output_schema_version(self) -> str: ...
    @property
    def destination(self) -> AnalyticsExportDestination | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Tag:
    @property
    def key(self) -> str: ...
    @property
    def value(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class TargetGrant:
    @property
    def grantee(self) -> Grantee | None: ...
    @property
    def permission(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class TargetObjectKeyFormat:
    @property
    def simple_prefix(self) -> SimplePrefix | None: ...
    @property
    def partitioned_prefix(self) -> PartitionedPrefix | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Tiering:
    @property
    def days(self) -> int: ...
    @property
    def access_tier(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class TopicConfiguration:
    @property
    def id(self) -> str | None: ...
    @property
    def topic_arn(self) -> str: ...
    @property
    def events(self) -> list[str]: ...
    @property
    def filter(self) -> NotificationConfigurationFilter | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Transition:
    @property
    def date(self) -> str | None: ...
    @property
    def days(self) -> int | None: ...
    @property
    def storage_class(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class AbortMultipartUploadOutput:
    @property
    def request_charged(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CompleteMultipartUploadOutput:
    @property
    def location(self) -> str | None: ...
    @property
    def bucket(self) -> str | None: ...
    @property
    def key(self) -> str | None: ...
    @property
    def expiration(self) -> str | None: ...
    @property
    def e_tag(self) -> str | None: ...
    @property
    def checksum_crc32(self) -> str | None: ...
    @property
    def checksum_crc32_c(self) -> str | None: ...
    @property
    def checksum_crc64_nvme(self) -> str | None: ...
    @property
    def checksum_sha1(self) -> str | None: ...
    @property
    def checksum_sha256(self) -> str | None: ...
    @property
    def checksum_type(self) -> str | None: ...
    @property
    def server_side_encryption(self) -> str | None: ...
    @property
    def version_id(self) -> str | None: ...
    @property
    def ssekms_key_id(self) -> str | None: ...
    @property
    def bucket_key_enabled(self) -> bool | None: ...
    @property
    def request_charged(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CopyObjectOutput:
    @property
    def copy_object_result(self) -> CopyObjectResult | None: ...
    @property
    def expiration(self) -> str | None: ...
    @property
    def copy_source_version_id(self) -> str | None: ...
    @property
    def version_id(self) -> str | None: ...
    @property
    def server_side_encryption(self) -> str | None: ...
    @property
    def sse_customer_algorithm(self) -> str | None: ...
    @property
    def sse_customer_key_md5(self) -> str | None: ...
    @property
    def ssekms_key_id(self) -> str | None: ...
    @property
    def ssekms_encryption_context(self) -> str | None: ...
    @property
    def bucket_key_enabled(self) -> bool | None: ...
    @property
    def request_charged(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CreateBucketOutput:
    @property
    def location(self) -> str | None: ...
    @property
    def bucket_arn(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CreateMultipartUploadOutput:
    @property
    def abort_date(self) -> str | None: ...
    @property
    def abort_rule_id(self) -> str | None: ...
    @property
    def bucket(self) -> str | None: ...
    @property
    def key(self) -> str | None: ...
    @property
    def upload_id(self) -> str | None: ...
    @property
    def server_side_encryption(self) -> str | None: ...
    @property
    def sse_customer_algorithm(self) -> str | None: ...
    @property
    def sse_customer_key_md5(self) -> str | None: ...
    @property
    def ssekms_key_id(self) -> str | None: ...
    @property
    def ssekms_encryption_context(self) -> str | None: ...
    @property
    def bucket_key_enabled(self) -> bool | None: ...
    @property
    def request_charged(self) -> str | None: ...
    @property
    def checksum_algorithm(self) -> str | None: ...
    @property
    def checksum_type(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CreateSessionOutput:
    @property
    def server_side_encryption(self) -> str | None: ...
    @property
    def ssekms_key_id(self) -> str | None: ...
    @property
    def ssekms_encryption_context(self) -> str | None: ...
    @property
    def bucket_key_enabled(self) -> bool | None: ...
    @property
    def credentials(self) -> SessionCredentials | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DeleteObjectOutput:
    @property
    def delete_marker(self) -> bool | None: ...
    @property
    def version_id(self) -> str | None: ...
    @property
    def request_charged(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DeleteObjectsOutput:
    @property
    def deleted(self) -> list[DeletedObject] | None: ...
    @property
    def request_charged(self) -> str | None: ...
    @property
    def errors(self) -> list[Error] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DeleteObjectTaggingOutput:
    @property
    def version_id(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketAbacOutput:
    @property
    def abac_status(self) -> AbacStatus | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketAccelerateConfigurationOutput:
    @property
    def status(self) -> str | None: ...
    @property
    def request_charged(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketAclOutput:
    @property
    def owner(self) -> Owner | None: ...
    @property
    def grants(self) -> list[Grant] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketAnalyticsConfigurationOutput:
    @property
    def analytics_configuration(self) -> AnalyticsConfiguration | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketCorsOutput:
    @property
    def cors_rules(self) -> list[CorsRule] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketEncryptionOutput:
    @property
    def server_side_encryption_configuration(self) -> ServerSideEncryptionConfiguration | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketIntelligentTieringConfigurationOutput:
    @property
    def intelligent_tiering_configuration(self) -> IntelligentTieringConfiguration | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketInventoryConfigurationOutput:
    @property
    def inventory_configuration(self) -> InventoryConfiguration | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketLifecycleConfigurationOutput:
    @property
    def rules(self) -> list[LifecycleRule] | None: ...
    @property
    def transition_default_minimum_object_size(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketLocationOutput:
    @property
    def location_constraint(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketLoggingOutput:
    @property
    def logging_enabled(self) -> LoggingEnabled | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketMetadataConfigurationOutput:
    @property
    def get_bucket_metadata_configuration_result(self) -> GetBucketMetadataConfigurationResult | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketMetadataTableConfigurationOutput:
    @property
    def get_bucket_metadata_table_configuration_result(self) -> GetBucketMetadataTableConfigurationResult | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketMetricsConfigurationOutput:
    @property
    def metrics_configuration(self) -> MetricsConfiguration | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketNotificationConfigurationOutput:
    @property
    def topic_configurations(self) -> list[TopicConfiguration] | None: ...
    @property
    def queue_configurations(self) -> list[QueueConfiguration] | None: ...
    @property
    def lambda_function_configurations(self) -> list[LambdaFunctionConfiguration] | None: ...
    @property
    def event_bridge_configuration(self) -> EventBridgeConfiguration | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketOwnershipControlsOutput:
    @property
    def ownership_controls(self) -> OwnershipControls | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketPolicyOutput:
    @property
    def policy(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketPolicyStatusOutput:
    @property
    def policy_status(self) -> PolicyStatus | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketReplicationOutput:
    @property
    def replication_configuration(self) -> ReplicationConfiguration | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketRequestPaymentOutput:
    @property
    def payer(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketTaggingOutput:
    @property
    def tag_set(self) -> list[Tag]: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketVersioningOutput:
    @property
    def status(self) -> str | None: ...
    @property
    def mfa_delete(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetBucketWebsiteOutput:
    @property
    def redirect_all_requests_to(self) -> RedirectAllRequestsTo | None: ...
    @property
    def index_document(self) -> IndexDocument | None: ...
    @property
    def error_document(self) -> ErrorDocument | None: ...
    @property
    def routing_rules(self) -> list[RoutingRule] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetObjectOutput:
    @property
    def body(self) -> ByteStream: ...
    @property
    def delete_marker(self) -> bool | None: ...
    @property
    def accept_ranges(self) -> str | None: ...
    @property
    def expiration(self) -> str | None: ...
    @property
    def restore(self) -> str | None: ...
    @property
    def last_modified(self) -> str | None: ...
    @property
    def content_length(self) -> int | None: ...
    @property
    def e_tag(self) -> str | None: ...
    @property
    def checksum_crc32(self) -> str | None: ...
    @property
    def checksum_crc32_c(self) -> str | None: ...
    @property
    def checksum_crc64_nvme(self) -> str | None: ...
    @property
    def checksum_sha1(self) -> str | None: ...
    @property
    def checksum_sha256(self) -> str | None: ...
    @property
    def checksum_type(self) -> str | None: ...
    @property
    def missing_meta(self) -> int | None: ...
    @property
    def version_id(self) -> str | None: ...
    @property
    def cache_control(self) -> str | None: ...
    @property
    def content_disposition(self) -> str | None: ...
    @property
    def content_encoding(self) -> str | None: ...
    @property
    def content_language(self) -> str | None: ...
    @property
    def content_range(self) -> str | None: ...
    @property
    def content_type(self) -> str | None: ...
    @property
    def website_redirect_location(self) -> str | None: ...
    @property
    def server_side_encryption(self) -> str | None: ...
    @property
    def metadata(self) -> dict[str, str] | None: ...
    @property
    def sse_customer_algorithm(self) -> str | None: ...
    @property
    def sse_customer_key_md5(self) -> str | None: ...
    @property
    def ssekms_key_id(self) -> str | None: ...
    @property
    def bucket_key_enabled(self) -> bool | None: ...
    @property
    def storage_class(self) -> str | None: ...
    @property
    def request_charged(self) -> str | None: ...
    @property
    def replication_status(self) -> str | None: ...
    @property
    def parts_count(self) -> int | None: ...
    @property
    def tag_count(self) -> int | None: ...
    @property
    def object_lock_mode(self) -> str | None: ...
    @property
    def object_lock_retain_until_date(self) -> str | None: ...
    @property
    def object_lock_legal_hold_status(self) -> str | None: ...
    @property
    def expires(self) -> str | None: ...
    @property
    def expires_string(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetObjectAclOutput:
    @property
    def owner(self) -> Owner | None: ...
    @property
    def grants(self) -> list[Grant] | None: ...
    @property
    def request_charged(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetObjectAttributesOutput:
    @property
    def delete_marker(self) -> bool | None: ...
    @property
    def last_modified(self) -> str | None: ...
    @property
    def version_id(self) -> str | None: ...
    @property
    def request_charged(self) -> str | None: ...
    @property
    def e_tag(self) -> str | None: ...
    @property
    def checksum(self) -> Checksum | None: ...
    @property
    def object_parts(self) -> GetObjectAttributesParts | None: ...
    @property
    def storage_class(self) -> str | None: ...
    @property
    def object_size(self) -> int | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetObjectLegalHoldOutput:
    @property
    def legal_hold(self) -> ObjectLockLegalHold | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetObjectLockConfigurationOutput:
    @property
    def object_lock_configuration(self) -> ObjectLockConfiguration | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetObjectRetentionOutput:
    @property
    def retention(self) -> ObjectLockRetention | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetObjectTaggingOutput:
    @property
    def version_id(self) -> str | None: ...
    @property
    def tag_set(self) -> list[Tag]: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetObjectTorrentOutput:
    @property
    def body(self) -> ByteStream: ...
    @property
    def request_charged(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetPublicAccessBlockOutput:
    @property
    def public_access_block_configuration(self) -> PublicAccessBlockConfiguration | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class HeadBucketOutput:
    @property
    def bucket_arn(self) -> str | None: ...
    @property
    def bucket_location_type(self) -> str | None: ...
    @property
    def bucket_location_name(self) -> str | None: ...
    @property
    def bucket_region(self) -> str | None: ...
    @property
    def access_point_alias(self) -> bool | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class HeadObjectOutput:
    @property
    def delete_marker(self) -> bool | None: ...
    @property
    def accept_ranges(self) -> str | None: ...
    @property
    def expiration(self) -> str | None: ...
    @property
    def restore(self) -> str | None: ...
    @property
    def archive_status(self) -> str | None: ...
    @property
    def last_modified(self) -> str | None: ...
    @property
    def content_length(self) -> int | None: ...
    @property
    def checksum_crc32(self) -> str | None: ...
    @property
    def checksum_crc32_c(self) -> str | None: ...
    @property
    def checksum_crc64_nvme(self) -> str | None: ...
    @property
    def checksum_sha1(self) -> str | None: ...
    @property
    def checksum_sha256(self) -> str | None: ...
    @property
    def checksum_type(self) -> str | None: ...
    @property
    def e_tag(self) -> str | None: ...
    @property
    def missing_meta(self) -> int | None: ...
    @property
    def version_id(self) -> str | None: ...
    @property
    def cache_control(self) -> str | None: ...
    @property
    def content_disposition(self) -> str | None: ...
    @property
    def content_encoding(self) -> str | None: ...
    @property
    def content_language(self) -> str | None: ...
    @property
    def content_type(self) -> str | None: ...
    @property
    def content_range(self) -> str | None: ...
    @property
    def website_redirect_location(self) -> str | None: ...
    @property
    def server_side_encryption(self) -> str | None: ...
    @property
    def metadata(self) -> dict[str, str] | None: ...
    @property
    def sse_customer_algorithm(self) -> str | None: ...
    @property
    def sse_customer_key_md5(self) -> str | None: ...
    @property
    def ssekms_key_id(self) -> str | None: ...
    @property
    def bucket_key_enabled(self) -> bool | None: ...
    @property
    def storage_class(self) -> str | None: ...
    @property
    def request_charged(self) -> str | None: ...
    @property
    def replication_status(self) -> str | None: ...
    @property
    def parts_count(self) -> int | None: ...
    @property
    def tag_count(self) -> int | None: ...
    @property
    def object_lock_mode(self) -> str | None: ...
    @property
    def object_lock_retain_until_date(self) -> str | None: ...
    @property
    def object_lock_legal_hold_status(self) -> str | None: ...
    @property
    def expires(self) -> str | None: ...
    @property
    def expires_string(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListBucketAnalyticsConfigurationsOutput:
    @property
    def is_truncated(self) -> bool | None: ...
    @property
    def continuation_token(self) -> str | None: ...
    @property
    def next_continuation_token(self) -> str | None: ...
    @property
    def analytics_configuration_list(self) -> list[AnalyticsConfiguration] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListBucketIntelligentTieringConfigurationsOutput:
    @property
    def is_truncated(self) -> bool | None: ...
    @property
    def continuation_token(self) -> str | None: ...
    @property
    def next_continuation_token(self) -> str | None: ...
    @property
    def intelligent_tiering_configuration_list(self) -> list[IntelligentTieringConfiguration] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListBucketInventoryConfigurationsOutput:
    @property
    def continuation_token(self) -> str | None: ...
    @property
    def inventory_configuration_list(self) -> list[InventoryConfiguration] | None: ...
    @property
    def is_truncated(self) -> bool | None: ...
    @property
    def next_continuation_token(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListBucketMetricsConfigurationsOutput:
    @property
    def is_truncated(self) -> bool | None: ...
    @property
    def continuation_token(self) -> str | None: ...
    @property
    def next_continuation_token(self) -> str | None: ...
    @property
    def metrics_configuration_list(self) -> list[MetricsConfiguration] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListBucketsOutput:
    @property
    def buckets(self) -> list[Bucket] | None: ...
    @property
    def owner(self) -> Owner | None: ...
    @property
    def continuation_token(self) -> str | None: ...
    @property
    def prefix(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListDirectoryBucketsOutput:
    @property
    def buckets(self) -> list[Bucket] | None: ...
    @property
    def continuation_token(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListMultipartUploadsOutput:
    @property
    def bucket(self) -> str | None: ...
    @property
    def key_marker(self) -> str | None: ...
    @property
    def upload_id_marker(self) -> str | None: ...
    @property
    def next_key_marker(self) -> str | None: ...
    @property
    def prefix(self) -> str | None: ...
    @property
    def delimiter(self) -> str | None: ...
    @property
    def next_upload_id_marker(self) -> str | None: ...
    @property
    def max_uploads(self) -> int | None: ...
    @property
    def is_truncated(self) -> bool | None: ...
    @property
    def uploads(self) -> list[MultipartUpload] | None: ...
    @property
    def common_prefixes(self) -> list[CommonPrefix] | None: ...
    @property
    def encoding_type(self) -> str | None: ...
    @property
    def request_charged(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListObjectsOutput:
    @property
    def is_truncated(self) -> bool | None: ...
    @property
    def marker(self) -> str | None: ...
    @property
    def next_marker(self) -> str | None: ...
    @property
    def contents(self) -> list[Object] | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def prefix(self) -> str | None: ...
    @property
    def delimiter(self) -> str | None: ...
    @property
    def max_keys(self) -> int | None: ...
    @property
    def common_prefixes(self) -> list[CommonPrefix] | None: ...
    @property
    def encoding_type(self) -> str | None: ...
    @property
    def request_charged(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListObjectsV2Output:
    @property
    def is_truncated(self) -> bool | None: ...
    @property
    def contents(self) -> list[Object] | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def prefix(self) -> str | None: ...
    @property
    def delimiter(self) -> str | None: ...
    @property
    def max_keys(self) -> int | None: ...
    @property
    def common_prefixes(self) -> list[CommonPrefix] | None: ...
    @property
    def encoding_type(self) -> str | None: ...
    @property
    def key_count(self) -> int | None: ...
    @property
    def continuation_token(self) -> str | None: ...
    @property
    def next_continuation_token(self) -> str | None: ...
    @property
    def start_after(self) -> str | None: ...
    @property
    def request_charged(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListObjectVersionsOutput:
    @property
    def is_truncated(self) -> bool | None: ...
    @property
    def key_marker(self) -> str | None: ...
    @property
    def version_id_marker(self) -> str | None: ...
    @property
    def next_key_marker(self) -> str | None: ...
    @property
    def next_version_id_marker(self) -> str | None: ...
    @property
    def versions(self) -> list[ObjectVersion] | None: ...
    @property
    def delete_markers(self) -> list[DeleteMarkerEntry] | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def prefix(self) -> str | None: ...
    @property
    def delimiter(self) -> str | None: ...
    @property
    def max_keys(self) -> int | None: ...
    @property
    def common_prefixes(self) -> list[CommonPrefix] | None: ...
    @property
    def encoding_type(self) -> str | None: ...
    @property
    def request_charged(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListPartsOutput:
    @property
    def abort_date(self) -> str | None: ...
    @property
    def abort_rule_id(self) -> str | None: ...
    @property
    def bucket(self) -> str | None: ...
    @property
    def key(self) -> str | None: ...
    @property
    def upload_id(self) -> str | None: ...
    @property
    def part_number_marker(self) -> str | None: ...
    @property
    def next_part_number_marker(self) -> str | None: ...
    @property
    def max_parts(self) -> int | None: ...
    @property
    def is_truncated(self) -> bool | None: ...
    @property
    def parts(self) -> list[Part] | None: ...
    @property
    def initiator(self) -> Initiator | None: ...
    @property
    def owner(self) -> Owner | None: ...
    @property
    def storage_class(self) -> str | None: ...
    @property
    def request_charged(self) -> str | None: ...
    @property
    def checksum_algorithm(self) -> str | None: ...
    @property
    def checksum_type(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class PutBucketLifecycleConfigurationOutput:
    @property
    def transition_default_minimum_object_size(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class PutObjectOutput:
    @property
    def expiration(self) -> str | None: ...
    @property
    def e_tag(self) -> str | None: ...
    @property
    def checksum_crc32(self) -> str | None: ...
    @property
    def checksum_crc32_c(self) -> str | None: ...
    @property
    def checksum_crc64_nvme(self) -> str | None: ...
    @property
    def checksum_sha1(self) -> str | None: ...
    @property
    def checksum_sha256(self) -> str | None: ...
    @property
    def checksum_type(self) -> str | None: ...
    @property
    def server_side_encryption(self) -> str | None: ...
    @property
    def version_id(self) -> str | None: ...
    @property
    def sse_customer_algorithm(self) -> str | None: ...
    @property
    def sse_customer_key_md5(self) -> str | None: ...
    @property
    def ssekms_key_id(self) -> str | None: ...
    @property
    def ssekms_encryption_context(self) -> str | None: ...
    @property
    def bucket_key_enabled(self) -> bool | None: ...
    @property
    def size(self) -> int | None: ...
    @property
    def request_charged(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class PutObjectAclOutput:
    @property
    def request_charged(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class PutObjectLegalHoldOutput:
    @property
    def request_charged(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class PutObjectLockConfigurationOutput:
    @property
    def request_charged(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class PutObjectRetentionOutput:
    @property
    def request_charged(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class PutObjectTaggingOutput:
    @property
    def version_id(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class RenameObjectOutput:
    def to_dict(self) -> dict[str, object]: ...

@final
class RestoreObjectOutput:
    @property
    def request_charged(self) -> str | None: ...
    @property
    def restore_output_path(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class UploadPartOutput:
    @property
    def server_side_encryption(self) -> str | None: ...
    @property
    def e_tag(self) -> str | None: ...
    @property
    def checksum_crc32(self) -> str | None: ...
    @property
    def checksum_crc32_c(self) -> str | None: ...
    @property
    def checksum_crc64_nvme(self) -> str | None: ...
    @property
    def checksum_sha1(self) -> str | None: ...
    @property
    def checksum_sha256(self) -> str | None: ...
    @property
    def sse_customer_algorithm(self) -> str | None: ...
    @property
    def sse_customer_key_md5(self) -> str | None: ...
    @property
    def ssekms_key_id(self) -> str | None: ...
    @property
    def bucket_key_enabled(self) -> bool | None: ...
    @property
    def request_charged(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class UploadPartCopyOutput:
    @property
    def copy_source_version_id(self) -> str | None: ...
    @property
    def copy_part_result(self) -> CopyPartResult | None: ...
    @property
    def server_side_encryption(self) -> str | None: ...
    @property
    def sse_customer_algorithm(self) -> str | None: ...
    @property
    def sse_customer_key_md5(self) -> str | None: ...
    @property
    def ssekms_key_id(self) -> str | None: ...
    @property
    def bucket_key_enabled(self) -> bool | None: ...
    @property
    def request_charged(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...



@final
class S3Client:
    def __init__(
        self,
        *,
        region: str | None = None,
        profile: str | None = None,
        endpoint_url: str | None = None,
    ) -> None: ...

    async def abort_multipart_upload(self, params: dict[str, object]) -> AbortMultipartUploadOutput: ...

    async def complete_multipart_upload(self, params: dict[str, object]) -> CompleteMultipartUploadOutput: ...

    async def copy_object(self, params: dict[str, object]) -> CopyObjectOutput: ...

    async def create_bucket(self, params: dict[str, object]) -> CreateBucketOutput: ...

    async def create_bucket_metadata_configuration(self, params: dict[str, object]) -> None: ...

    async def create_bucket_metadata_table_configuration(self, params: dict[str, object]) -> None: ...

    async def create_multipart_upload(self, params: dict[str, object]) -> CreateMultipartUploadOutput: ...

    async def create_session(self, params: dict[str, object]) -> CreateSessionOutput: ...

    async def delete_bucket(self, params: dict[str, object]) -> None: ...

    async def delete_bucket_analytics_configuration(self, params: dict[str, object]) -> None: ...

    async def delete_bucket_cors(self, params: dict[str, object]) -> None: ...

    async def delete_bucket_encryption(self, params: dict[str, object]) -> None: ...

    async def delete_bucket_intelligent_tiering_configuration(self, params: dict[str, object]) -> None: ...

    async def delete_bucket_inventory_configuration(self, params: dict[str, object]) -> None: ...

    async def delete_bucket_lifecycle(self, params: dict[str, object]) -> None: ...

    async def delete_bucket_metadata_configuration(self, params: dict[str, object]) -> None: ...

    async def delete_bucket_metadata_table_configuration(self, params: dict[str, object]) -> None: ...

    async def delete_bucket_metrics_configuration(self, params: dict[str, object]) -> None: ...

    async def delete_bucket_ownership_controls(self, params: dict[str, object]) -> None: ...

    async def delete_bucket_policy(self, params: dict[str, object]) -> None: ...

    async def delete_bucket_replication(self, params: dict[str, object]) -> None: ...

    async def delete_bucket_tagging(self, params: dict[str, object]) -> None: ...

    async def delete_bucket_website(self, params: dict[str, object]) -> None: ...

    async def delete_object(self, params: dict[str, object]) -> DeleteObjectOutput: ...

    async def delete_objects(self, params: dict[str, object]) -> DeleteObjectsOutput: ...

    async def delete_object_tagging(self, params: dict[str, object]) -> DeleteObjectTaggingOutput: ...

    async def delete_public_access_block(self, params: dict[str, object]) -> None: ...

    async def get_bucket_abac(self, params: dict[str, object]) -> GetBucketAbacOutput: ...

    async def get_bucket_accelerate_configuration(self, params: dict[str, object]) -> GetBucketAccelerateConfigurationOutput: ...

    async def get_bucket_acl(self, params: dict[str, object]) -> GetBucketAclOutput: ...

    async def get_bucket_analytics_configuration(self, params: dict[str, object]) -> GetBucketAnalyticsConfigurationOutput: ...

    async def get_bucket_cors(self, params: dict[str, object]) -> GetBucketCorsOutput: ...

    async def get_bucket_encryption(self, params: dict[str, object]) -> GetBucketEncryptionOutput: ...

    async def get_bucket_intelligent_tiering_configuration(self, params: dict[str, object]) -> GetBucketIntelligentTieringConfigurationOutput: ...

    async def get_bucket_inventory_configuration(self, params: dict[str, object]) -> GetBucketInventoryConfigurationOutput: ...

    async def get_bucket_lifecycle_configuration(self, params: dict[str, object]) -> GetBucketLifecycleConfigurationOutput: ...

    async def get_bucket_location(self, params: dict[str, object]) -> GetBucketLocationOutput: ...

    async def get_bucket_logging(self, params: dict[str, object]) -> GetBucketLoggingOutput: ...

    async def get_bucket_metadata_configuration(self, params: dict[str, object]) -> GetBucketMetadataConfigurationOutput: ...

    async def get_bucket_metadata_table_configuration(self, params: dict[str, object]) -> GetBucketMetadataTableConfigurationOutput: ...

    async def get_bucket_metrics_configuration(self, params: dict[str, object]) -> GetBucketMetricsConfigurationOutput: ...

    async def get_bucket_notification_configuration(self, params: dict[str, object]) -> GetBucketNotificationConfigurationOutput: ...

    async def get_bucket_ownership_controls(self, params: dict[str, object]) -> GetBucketOwnershipControlsOutput: ...

    async def get_bucket_policy(self, params: dict[str, object]) -> GetBucketPolicyOutput: ...

    async def get_bucket_policy_status(self, params: dict[str, object]) -> GetBucketPolicyStatusOutput: ...

    async def get_bucket_replication(self, params: dict[str, object]) -> GetBucketReplicationOutput: ...

    async def get_bucket_request_payment(self, params: dict[str, object]) -> GetBucketRequestPaymentOutput: ...

    async def get_bucket_tagging(self, params: dict[str, object]) -> GetBucketTaggingOutput: ...

    async def get_bucket_versioning(self, params: dict[str, object]) -> GetBucketVersioningOutput: ...

    async def get_bucket_website(self, params: dict[str, object]) -> GetBucketWebsiteOutput: ...

    async def get_object(self, params: dict[str, object]) -> GetObjectOutput: ...

    async def get_object_acl(self, params: dict[str, object]) -> GetObjectAclOutput: ...

    async def get_object_attributes(self, params: dict[str, object]) -> GetObjectAttributesOutput: ...

    async def get_object_legal_hold(self, params: dict[str, object]) -> GetObjectLegalHoldOutput: ...

    async def get_object_lock_configuration(self, params: dict[str, object]) -> GetObjectLockConfigurationOutput: ...

    async def get_object_retention(self, params: dict[str, object]) -> GetObjectRetentionOutput: ...

    async def get_object_tagging(self, params: dict[str, object]) -> GetObjectTaggingOutput: ...

    async def get_object_torrent(self, params: dict[str, object]) -> GetObjectTorrentOutput: ...

    async def get_public_access_block(self, params: dict[str, object]) -> GetPublicAccessBlockOutput: ...

    async def head_bucket(self, params: dict[str, object]) -> HeadBucketOutput: ...

    async def head_object(self, params: dict[str, object]) -> HeadObjectOutput: ...

    async def list_bucket_analytics_configurations(self, params: dict[str, object]) -> ListBucketAnalyticsConfigurationsOutput: ...

    async def list_bucket_intelligent_tiering_configurations(self, params: dict[str, object]) -> ListBucketIntelligentTieringConfigurationsOutput: ...

    async def list_bucket_inventory_configurations(self, params: dict[str, object]) -> ListBucketInventoryConfigurationsOutput: ...

    async def list_bucket_metrics_configurations(self, params: dict[str, object]) -> ListBucketMetricsConfigurationsOutput: ...

    async def list_buckets(self, params: dict[str, object]) -> ListBucketsOutput: ...

    async def list_directory_buckets(self, params: dict[str, object]) -> ListDirectoryBucketsOutput: ...

    async def list_multipart_uploads(self, params: dict[str, object]) -> ListMultipartUploadsOutput: ...

    async def list_objects(self, params: dict[str, object]) -> ListObjectsOutput: ...

    async def list_objects_v2(self, params: dict[str, object]) -> ListObjectsV2Output: ...

    async def list_object_versions(self, params: dict[str, object]) -> ListObjectVersionsOutput: ...

    async def list_parts(self, params: dict[str, object]) -> ListPartsOutput: ...

    async def put_bucket_abac(self, params: dict[str, object]) -> None: ...

    async def put_bucket_accelerate_configuration(self, params: dict[str, object]) -> None: ...

    async def put_bucket_acl(self, params: dict[str, object]) -> None: ...

    async def put_bucket_analytics_configuration(self, params: dict[str, object]) -> None: ...

    async def put_bucket_cors(self, params: dict[str, object]) -> None: ...

    async def put_bucket_encryption(self, params: dict[str, object]) -> None: ...

    async def put_bucket_intelligent_tiering_configuration(self, params: dict[str, object]) -> None: ...

    async def put_bucket_inventory_configuration(self, params: dict[str, object]) -> None: ...

    async def put_bucket_lifecycle_configuration(self, params: dict[str, object]) -> PutBucketLifecycleConfigurationOutput: ...

    async def put_bucket_logging(self, params: dict[str, object]) -> None: ...

    async def put_bucket_metrics_configuration(self, params: dict[str, object]) -> None: ...

    async def put_bucket_notification_configuration(self, params: dict[str, object]) -> None: ...

    async def put_bucket_ownership_controls(self, params: dict[str, object]) -> None: ...

    async def put_bucket_policy(self, params: dict[str, object]) -> None: ...

    async def put_bucket_replication(self, params: dict[str, object]) -> None: ...

    async def put_bucket_request_payment(self, params: dict[str, object]) -> None: ...

    async def put_bucket_tagging(self, params: dict[str, object]) -> None: ...

    async def put_bucket_versioning(self, params: dict[str, object]) -> None: ...

    async def put_bucket_website(self, params: dict[str, object]) -> None: ...

    async def put_object(self, params: dict[str, object]) -> PutObjectOutput: ...

    async def put_object_acl(self, params: dict[str, object]) -> PutObjectAclOutput: ...

    async def put_object_legal_hold(self, params: dict[str, object]) -> PutObjectLegalHoldOutput: ...

    async def put_object_lock_configuration(self, params: dict[str, object]) -> PutObjectLockConfigurationOutput: ...

    async def put_object_retention(self, params: dict[str, object]) -> PutObjectRetentionOutput: ...

    async def put_object_tagging(self, params: dict[str, object]) -> PutObjectTaggingOutput: ...

    async def put_public_access_block(self, params: dict[str, object]) -> None: ...

    async def rename_object(self, params: dict[str, object]) -> RenameObjectOutput: ...

    async def restore_object(self, params: dict[str, object]) -> RestoreObjectOutput: ...

    async def select_object_content(self, params: dict[str, object]) -> SelectObjectContentOutput: ...

    async def update_bucket_metadata_inventory_table_configuration(self, params: dict[str, object]) -> None: ...

    async def update_bucket_metadata_journal_table_configuration(self, params: dict[str, object]) -> None: ...

    async def upload_part(self, params: dict[str, object]) -> UploadPartOutput: ...

    async def upload_part_copy(self, params: dict[str, object]) -> UploadPartCopyOutput: ...

    async def write_get_object_response(self, params: dict[str, object]) -> None: ...
