from collections.abc import AsyncIterator
from typing import final

@final
class ByteStream:
    def __aiter__(self) -> AsyncIterator[bytes]: ...
    async def __anext__(self) -> bytes: ...
    async def read(self) -> bytes: ...

@final
class SelectObjectContentEventStreamReceiver:
    def __aiter__(self) -> AsyncIterator[dict[str, object]]: ...
    async def __anext__(self) -> dict[str, object]: ...


@final
class S3Client:
    def __init__(
        self,
        *,
        region: str | None = None,
        profile: str | None = None,
        endpoint_url: str | None = None,
    ) -> None: ...

    async def abort_multipart_upload(self, params: dict[str, object]) -> object: ...

    async def complete_multipart_upload(self, params: dict[str, object]) -> object: ...

    async def copy_object(self, params: dict[str, object]) -> object: ...

    async def create_bucket(self, params: dict[str, object]) -> object: ...

    async def create_bucket_metadata_configuration(self, params: dict[str, object]) -> object: ...

    async def create_bucket_metadata_table_configuration(self, params: dict[str, object]) -> object: ...

    async def create_multipart_upload(self, params: dict[str, object]) -> object: ...

    async def create_session(self, params: dict[str, object]) -> object: ...

    async def delete_bucket(self, params: dict[str, object]) -> object: ...

    async def delete_bucket_analytics_configuration(self, params: dict[str, object]) -> object: ...

    async def delete_bucket_cors(self, params: dict[str, object]) -> object: ...

    async def delete_bucket_encryption(self, params: dict[str, object]) -> object: ...

    async def delete_bucket_intelligent_tiering_configuration(self, params: dict[str, object]) -> object: ...

    async def delete_bucket_inventory_configuration(self, params: dict[str, object]) -> object: ...

    async def delete_bucket_lifecycle(self, params: dict[str, object]) -> object: ...

    async def delete_bucket_metadata_configuration(self, params: dict[str, object]) -> object: ...

    async def delete_bucket_metadata_table_configuration(self, params: dict[str, object]) -> object: ...

    async def delete_bucket_metrics_configuration(self, params: dict[str, object]) -> object: ...

    async def delete_bucket_ownership_controls(self, params: dict[str, object]) -> object: ...

    async def delete_bucket_policy(self, params: dict[str, object]) -> object: ...

    async def delete_bucket_replication(self, params: dict[str, object]) -> object: ...

    async def delete_bucket_tagging(self, params: dict[str, object]) -> object: ...

    async def delete_bucket_website(self, params: dict[str, object]) -> object: ...

    async def delete_object(self, params: dict[str, object]) -> object: ...

    async def delete_objects(self, params: dict[str, object]) -> object: ...

    async def delete_object_tagging(self, params: dict[str, object]) -> object: ...

    async def delete_public_access_block(self, params: dict[str, object]) -> object: ...

    async def get_bucket_abac(self, params: dict[str, object]) -> object: ...

    async def get_bucket_accelerate_configuration(self, params: dict[str, object]) -> object: ...

    async def get_bucket_acl(self, params: dict[str, object]) -> object: ...

    async def get_bucket_analytics_configuration(self, params: dict[str, object]) -> object: ...

    async def get_bucket_cors(self, params: dict[str, object]) -> object: ...

    async def get_bucket_encryption(self, params: dict[str, object]) -> object: ...

    async def get_bucket_intelligent_tiering_configuration(self, params: dict[str, object]) -> object: ...

    async def get_bucket_inventory_configuration(self, params: dict[str, object]) -> object: ...

    async def get_bucket_lifecycle_configuration(self, params: dict[str, object]) -> object: ...

    async def get_bucket_location(self, params: dict[str, object]) -> object: ...

    async def get_bucket_logging(self, params: dict[str, object]) -> object: ...

    async def get_bucket_metadata_configuration(self, params: dict[str, object]) -> object: ...

    async def get_bucket_metadata_table_configuration(self, params: dict[str, object]) -> object: ...

    async def get_bucket_metrics_configuration(self, params: dict[str, object]) -> object: ...

    async def get_bucket_notification_configuration(self, params: dict[str, object]) -> object: ...

    async def get_bucket_ownership_controls(self, params: dict[str, object]) -> object: ...

    async def get_bucket_policy(self, params: dict[str, object]) -> object: ...

    async def get_bucket_policy_status(self, params: dict[str, object]) -> object: ...

    async def get_bucket_replication(self, params: dict[str, object]) -> object: ...

    async def get_bucket_request_payment(self, params: dict[str, object]) -> object: ...

    async def get_bucket_tagging(self, params: dict[str, object]) -> object: ...

    async def get_bucket_versioning(self, params: dict[str, object]) -> object: ...

    async def get_bucket_website(self, params: dict[str, object]) -> object: ...

    async def get_object(self, params: dict[str, object]) -> object: ...

    async def get_object_acl(self, params: dict[str, object]) -> object: ...

    async def get_object_attributes(self, params: dict[str, object]) -> object: ...

    async def get_object_legal_hold(self, params: dict[str, object]) -> object: ...

    async def get_object_lock_configuration(self, params: dict[str, object]) -> object: ...

    async def get_object_retention(self, params: dict[str, object]) -> object: ...

    async def get_object_tagging(self, params: dict[str, object]) -> object: ...

    async def get_object_torrent(self, params: dict[str, object]) -> object: ...

    async def get_public_access_block(self, params: dict[str, object]) -> object: ...

    async def head_bucket(self, params: dict[str, object]) -> object: ...

    async def head_object(self, params: dict[str, object]) -> object: ...

    async def list_bucket_analytics_configurations(self, params: dict[str, object]) -> object: ...

    async def list_bucket_intelligent_tiering_configurations(self, params: dict[str, object]) -> object: ...

    async def list_bucket_inventory_configurations(self, params: dict[str, object]) -> object: ...

    async def list_bucket_metrics_configurations(self, params: dict[str, object]) -> object: ...

    async def list_buckets(self, params: dict[str, object]) -> object: ...

    async def list_directory_buckets(self, params: dict[str, object]) -> object: ...

    async def list_multipart_uploads(self, params: dict[str, object]) -> object: ...

    async def list_objects(self, params: dict[str, object]) -> object: ...

    async def list_objects_v2(self, params: dict[str, object]) -> object: ...

    async def list_object_versions(self, params: dict[str, object]) -> object: ...

    async def list_parts(self, params: dict[str, object]) -> object: ...

    async def put_bucket_abac(self, params: dict[str, object]) -> object: ...

    async def put_bucket_accelerate_configuration(self, params: dict[str, object]) -> object: ...

    async def put_bucket_acl(self, params: dict[str, object]) -> object: ...

    async def put_bucket_analytics_configuration(self, params: dict[str, object]) -> object: ...

    async def put_bucket_cors(self, params: dict[str, object]) -> object: ...

    async def put_bucket_encryption(self, params: dict[str, object]) -> object: ...

    async def put_bucket_intelligent_tiering_configuration(self, params: dict[str, object]) -> object: ...

    async def put_bucket_inventory_configuration(self, params: dict[str, object]) -> object: ...

    async def put_bucket_lifecycle_configuration(self, params: dict[str, object]) -> object: ...

    async def put_bucket_logging(self, params: dict[str, object]) -> object: ...

    async def put_bucket_metrics_configuration(self, params: dict[str, object]) -> object: ...

    async def put_bucket_notification_configuration(self, params: dict[str, object]) -> object: ...

    async def put_bucket_ownership_controls(self, params: dict[str, object]) -> object: ...

    async def put_bucket_policy(self, params: dict[str, object]) -> object: ...

    async def put_bucket_replication(self, params: dict[str, object]) -> object: ...

    async def put_bucket_request_payment(self, params: dict[str, object]) -> object: ...

    async def put_bucket_tagging(self, params: dict[str, object]) -> object: ...

    async def put_bucket_versioning(self, params: dict[str, object]) -> object: ...

    async def put_bucket_website(self, params: dict[str, object]) -> object: ...

    async def put_object(self, params: dict[str, object]) -> object: ...

    async def put_object_acl(self, params: dict[str, object]) -> object: ...

    async def put_object_legal_hold(self, params: dict[str, object]) -> object: ...

    async def put_object_lock_configuration(self, params: dict[str, object]) -> object: ...

    async def put_object_retention(self, params: dict[str, object]) -> object: ...

    async def put_object_tagging(self, params: dict[str, object]) -> object: ...

    async def put_public_access_block(self, params: dict[str, object]) -> object: ...

    async def rename_object(self, params: dict[str, object]) -> object: ...

    async def restore_object(self, params: dict[str, object]) -> object: ...

    async def select_object_content(self, params: dict[str, object]) -> object: ...

    async def update_bucket_metadata_inventory_table_configuration(self, params: dict[str, object]) -> object: ...

    async def update_bucket_metadata_journal_table_configuration(self, params: dict[str, object]) -> object: ...

    async def upload_part(self, params: dict[str, object]) -> object: ...

    async def upload_part_copy(self, params: dict[str, object]) -> object: ...

    async def write_get_object_response(self, params: dict[str, object]) -> object: ...

