# Generated by rboto-codegen. DO NOT EDIT.
from rboto.exceptions import ServiceError


class S3Error(ServiceError):
    """Base exception for errors returned by s3."""


class BucketAlreadyExistsError(S3Error):
    """Modeled s3 error: BucketAlreadyExists."""


class BucketAlreadyOwnedByYouError(S3Error):
    """Modeled s3 error: BucketAlreadyOwnedByYou."""


class EncryptionTypeMismatchError(S3Error):
    """Modeled s3 error: EncryptionTypeMismatch."""


class IdempotencyParameterMismatchError(S3Error):
    """Modeled s3 error: IdempotencyParameterMismatch."""


class InvalidObjectStateError(S3Error):
    """Modeled s3 error: InvalidObjectState."""


class InvalidRequestError(S3Error):
    """Modeled s3 error: InvalidRequest."""


class InvalidWriteOffsetError(S3Error):
    """Modeled s3 error: InvalidWriteOffset."""


class NoSuchBucketError(S3Error):
    """Modeled s3 error: NoSuchBucket."""


class NoSuchKeyError(S3Error):
    """Modeled s3 error: NoSuchKey."""


class NoSuchUploadError(S3Error):
    """Modeled s3 error: NoSuchUpload."""


class NotFoundError(S3Error):
    """Modeled s3 error: NotFound."""


class ObjectAlreadyInActiveTierError(S3Error):
    """Modeled s3 error: ObjectAlreadyInActiveTierError."""


class ObjectNotInActiveTierError(S3Error):
    """Modeled s3 error: ObjectNotInActiveTierError."""


class TooManyPartsError(S3Error):
    """Modeled s3 error: TooManyParts."""
