# Generated by rboto-codegen. DO NOT EDIT.
from __future__ import annotations

from typing import Literal, NotRequired, Required, TypeAlias, TypedDict
from collections.abc import AsyncIterator

from ._native import ByteStream as ByteStream

AnalyticsS3ExportFileFormat: TypeAlias = Literal['CSV']
ArchiveStatus: TypeAlias = Literal['ARCHIVE_ACCESS', 'DEEP_ARCHIVE_ACCESS']
BucketAbacStatus: TypeAlias = Literal['Enabled', 'Disabled']
BucketAccelerateStatus: TypeAlias = Literal['Enabled', 'Suspended']
BucketCannedACL: TypeAlias = Literal['private', 'public-read', 'public-read-write', 'authenticated-read']
BucketLocationConstraint: TypeAlias = Literal['af-south-1', 'ap-east-1', 'ap-northeast-1', 'ap-northeast-2', 'ap-northeast-3', 'ap-south-1', 'ap-south-2', 'ap-southeast-1', 'ap-southeast-2', 'ap-southeast-3', 'ap-southeast-4', 'ap-southeast-5', 'ca-central-1', 'cn-north-1', 'cn-northwest-1', 'EU', 'eu-central-1', 'eu-central-2', 'eu-north-1', 'eu-south-1', 'eu-south-2', 'eu-west-1', 'eu-west-2', 'eu-west-3', 'il-central-1', 'me-central-1', 'me-south-1', 'sa-east-1', 'us-east-2', 'us-gov-east-1', 'us-gov-west-1', 'us-west-1', 'us-west-2']
BucketLogsPermission: TypeAlias = Literal['FULL_CONTROL', 'READ', 'WRITE']
BucketType: TypeAlias = Literal['Directory']
BucketVersioningStatus: TypeAlias = Literal['Enabled', 'Suspended']
ChecksumAlgorithm: TypeAlias = Literal['CRC32', 'CRC32C', 'SHA1', 'SHA256', 'CRC64NVME']
ChecksumMode: TypeAlias = Literal['ENABLED']
ChecksumType: TypeAlias = Literal['COMPOSITE', 'FULL_OBJECT']
CompressionType: TypeAlias = Literal['NONE', 'GZIP', 'BZIP2']
DataRedundancy: TypeAlias = Literal['SingleAvailabilityZone', 'SingleLocalZone']
DeleteMarkerReplicationStatus: TypeAlias = Literal['Enabled', 'Disabled']
EncodingType: TypeAlias = Literal['url']
EncryptionType: TypeAlias = Literal['NONE', 'SSE-C']
Event: TypeAlias = Literal['s3:ReducedRedundancyLostObject', 's3:ObjectCreated:*', 's3:ObjectCreated:Put', 's3:ObjectCreated:Post', 's3:ObjectCreated:Copy', 's3:ObjectCreated:CompleteMultipartUpload', 's3:ObjectRemoved:*', 's3:ObjectRemoved:Delete', 's3:ObjectRemoved:DeleteMarkerCreated', 's3:ObjectRestore:*', 's3:ObjectRestore:Post', 's3:ObjectRestore:Completed', 's3:Replication:*', 's3:Replication:OperationFailedReplication', 's3:Replication:OperationNotTracked', 's3:Replication:OperationMissedThreshold', 's3:Replication:OperationReplicatedAfterThreshold', 's3:ObjectRestore:Delete', 's3:LifecycleTransition', 's3:IntelligentTiering', 's3:ObjectAcl:Put', 's3:LifecycleExpiration:*', 's3:LifecycleExpiration:Delete', 's3:LifecycleExpiration:DeleteMarkerCreated', 's3:ObjectTagging:*', 's3:ObjectTagging:Put', 's3:ObjectTagging:Delete']
ExistingObjectReplicationStatus: TypeAlias = Literal['Enabled', 'Disabled']
ExpirationState: TypeAlias = Literal['ENABLED', 'DISABLED']
ExpirationStatus: TypeAlias = Literal['Enabled', 'Disabled']
ExpressionType: TypeAlias = Literal['SQL']
FileHeaderInfo: TypeAlias = Literal['USE', 'IGNORE', 'NONE']
FilterRuleName: TypeAlias = Literal['prefix', 'suffix']
IntelligentTieringAccessTier: TypeAlias = Literal['ARCHIVE_ACCESS', 'DEEP_ARCHIVE_ACCESS']
IntelligentTieringStatus: TypeAlias = Literal['Enabled', 'Disabled']
InventoryConfigurationState: TypeAlias = Literal['ENABLED', 'DISABLED']
InventoryFormat: TypeAlias = Literal['CSV', 'ORC', 'Parquet']
InventoryFrequency: TypeAlias = Literal['Daily', 'Weekly']
InventoryIncludedObjectVersions: TypeAlias = Literal['All', 'Current']
InventoryOptionalField: TypeAlias = Literal['Size', 'LastModifiedDate', 'StorageClass', 'ETag', 'IsMultipartUploaded', 'ReplicationStatus', 'EncryptionStatus', 'ObjectLockRetainUntilDate', 'ObjectLockMode', 'ObjectLockLegalHoldStatus', 'IntelligentTieringAccessTier', 'BucketKeyStatus', 'ChecksumAlgorithm', 'ObjectAccessControlList', 'ObjectOwner', 'LifecycleExpirationDate']
JSONType: TypeAlias = Literal['DOCUMENT', 'LINES']
LocationType: TypeAlias = Literal['AvailabilityZone', 'LocalZone']
MFADelete: TypeAlias = Literal['Enabled', 'Disabled']
MFADeleteStatus: TypeAlias = Literal['Enabled', 'Disabled']
MetadataDirective: TypeAlias = Literal['COPY', 'REPLACE']
MetricsStatus: TypeAlias = Literal['Enabled', 'Disabled']
ObjectAttributes: TypeAlias = Literal['ETag', 'Checksum', 'ObjectParts', 'StorageClass', 'ObjectSize']
ObjectCannedACL: TypeAlias = Literal['private', 'public-read', 'public-read-write', 'authenticated-read', 'aws-exec-read', 'bucket-owner-read', 'bucket-owner-full-control']
ObjectLockEnabled: TypeAlias = Literal['Enabled']
ObjectLockLegalHoldStatus: TypeAlias = Literal['ON', 'OFF']
ObjectLockMode: TypeAlias = Literal['GOVERNANCE', 'COMPLIANCE']
ObjectLockRetentionMode: TypeAlias = Literal['GOVERNANCE', 'COMPLIANCE']
ObjectOwnership: TypeAlias = Literal['BucketOwnerPreferred', 'ObjectWriter', 'BucketOwnerEnforced']
ObjectStorageClass: TypeAlias = Literal['STANDARD', 'REDUCED_REDUNDANCY', 'GLACIER', 'STANDARD_IA', 'ONEZONE_IA', 'INTELLIGENT_TIERING', 'DEEP_ARCHIVE', 'OUTPOSTS', 'GLACIER_IR', 'SNOW', 'EXPRESS_ONEZONE', 'FSX_OPENZFS', 'FSX_ONTAP']
ObjectVersionStorageClass: TypeAlias = Literal['STANDARD']
OptionalObjectAttributes: TypeAlias = Literal['RestoreStatus']
OwnerOverride: TypeAlias = Literal['Destination']
PartitionDateSource: TypeAlias = Literal['EventTime', 'DeliveryTime']
Payer: TypeAlias = Literal['Requester', 'BucketOwner']
Permission: TypeAlias = Literal['FULL_CONTROL', 'WRITE', 'WRITE_ACP', 'READ', 'READ_ACP']
Protocol: TypeAlias = Literal['http', 'https']
QuoteFields: TypeAlias = Literal['ALWAYS', 'ASNEEDED']
ReplicaModificationsStatus: TypeAlias = Literal['Enabled', 'Disabled']
ReplicationRuleStatus: TypeAlias = Literal['Enabled', 'Disabled']
ReplicationStatus: TypeAlias = Literal['COMPLETE', 'PENDING', 'FAILED', 'REPLICA', 'COMPLETED']
ReplicationTimeStatus: TypeAlias = Literal['Enabled', 'Disabled']
RequestCharged: TypeAlias = Literal['requester']
RequestPayer: TypeAlias = Literal['requester']
RestoreRequestType: TypeAlias = Literal['SELECT']
S3TablesBucketType: TypeAlias = Literal['aws', 'customer']
ServerSideEncryption: TypeAlias = Literal['AES256', 'aws:fsx', 'aws:kms', 'aws:kms:dsse']
SessionMode: TypeAlias = Literal['ReadOnly', 'ReadWrite']
SseKmsEncryptedObjectsStatus: TypeAlias = Literal['Enabled', 'Disabled']
StorageClass: TypeAlias = Literal['STANDARD', 'REDUCED_REDUNDANCY', 'STANDARD_IA', 'ONEZONE_IA', 'INTELLIGENT_TIERING', 'GLACIER', 'DEEP_ARCHIVE', 'OUTPOSTS', 'GLACIER_IR', 'SNOW', 'EXPRESS_ONEZONE', 'FSX_OPENZFS', 'FSX_ONTAP']
StorageClassAnalysisSchemaVersion: TypeAlias = Literal['V_1']
TableSseAlgorithm: TypeAlias = Literal['aws:kms', 'AES256']
TaggingDirective: TypeAlias = Literal['COPY', 'REPLACE']
Tier: TypeAlias = Literal['Standard', 'Bulk', 'Expedited']
TransitionDefaultMinimumObjectSize: TypeAlias = Literal['varies_by_storage_class', 'all_storage_classes_128K']
TransitionStorageClass: TypeAlias = Literal['GLACIER', 'STANDARD_IA', 'ONEZONE_IA', 'INTELLIGENT_TIERING', 'DEEP_ARCHIVE', 'GLACIER_IR']
Type: TypeAlias = Literal['CanonicalUser', 'AmazonCustomerByEmail', 'Group']

AbacStatus = TypedDict(
    "AbacStatus",
    {
    "status": NotRequired["BucketAbacStatus"],
    },
)

AbortIncompleteMultipartUpload = TypedDict(
    "AbortIncompleteMultipartUpload",
    {
    "days_after_initiation": NotRequired["int"],
    },
)

AbortMultipartUploadRequest = TypedDict(
    "AbortMultipartUploadRequest",
    {
    "bucket": Required["str"],
    "key": Required["str"],
    "upload_id": Required["str"],
    "request_payer": NotRequired["RequestPayer"],
    "expected_bucket_owner": NotRequired["str"],
    "if_match_initiated_time": NotRequired["str"],
    },
)

AccelerateConfiguration = TypedDict(
    "AccelerateConfiguration",
    {
    "status": NotRequired["BucketAccelerateStatus"],
    },
)

AccessControlPolicy = TypedDict(
    "AccessControlPolicy",
    {
    "grants": NotRequired["list[Grant]"],
    "owner": NotRequired["Owner"],
    },
)

AccessControlTranslation = TypedDict(
    "AccessControlTranslation",
    {
    "owner": Required["OwnerOverride"],
    },
)

AnalyticsAndOperator = TypedDict(
    "AnalyticsAndOperator",
    {
    "prefix": NotRequired["str"],
    "tags": NotRequired["list[Tag]"],
    },
)

AnalyticsConfiguration = TypedDict(
    "AnalyticsConfiguration",
    {
    "id": Required["str"],
    "filter": NotRequired["AnalyticsFilter"],
    "storage_class_analysis": Required["StorageClassAnalysis"],
    },
)

AnalyticsExportDestination = TypedDict(
    "AnalyticsExportDestination",
    {
    "s3_bucket_destination": Required["AnalyticsS3BucketDestination"],
    },
)

AnalyticsFilterPrefix = TypedDict("AnalyticsFilterPrefix", {"prefix": Required["str"]})
AnalyticsFilterTag = TypedDict("AnalyticsFilterTag", {"tag": Required["Tag"]})
AnalyticsFilterAnd = TypedDict("AnalyticsFilterAnd", {"and": Required["AnalyticsAndOperator"]})
AnalyticsFilterUnknown = TypedDict("AnalyticsFilterUnknown", {"unknown": Required[bool]})
AnalyticsFilter: TypeAlias = AnalyticsFilterPrefix | AnalyticsFilterTag | AnalyticsFilterAnd | AnalyticsFilterUnknown

AnalyticsS3BucketDestination = TypedDict(
    "AnalyticsS3BucketDestination",
    {
    "format": Required["AnalyticsS3ExportFileFormat"],
    "bucket_account_id": NotRequired["str"],
    "bucket": Required["str"],
    "prefix": NotRequired["str"],
    },
)

BlockedEncryptionTypes = TypedDict(
    "BlockedEncryptionTypes",
    {
    "encryption_type": NotRequired["list[EncryptionType]"],
    },
)

Bucket = TypedDict(
    "Bucket",
    {
    "name": NotRequired["str"],
    "creation_date": NotRequired["str"],
    "bucket_region": NotRequired["str"],
    "bucket_arn": NotRequired["str"],
    },
)

BucketInfo = TypedDict(
    "BucketInfo",
    {
    "data_redundancy": NotRequired["DataRedundancy"],
    "type": NotRequired["BucketType"],
    },
)

BucketLifecycleConfiguration = TypedDict(
    "BucketLifecycleConfiguration",
    {
    "rules": Required["list[LifecycleRule]"],
    },
)

BucketLoggingStatus = TypedDict(
    "BucketLoggingStatus",
    {
    "logging_enabled": NotRequired["LoggingEnabled"],
    },
)

CORSConfiguration = TypedDict(
    "CORSConfiguration",
    {
    "cors_rules": Required["list[CORSRule]"],
    },
)

CORSRule = TypedDict(
    "CORSRule",
    {
    "id": NotRequired["str"],
    "allowed_headers": NotRequired["list[str]"],
    "allowed_methods": Required["list[str]"],
    "allowed_origins": Required["list[str]"],
    "expose_headers": NotRequired["list[str]"],
    "max_age_seconds": NotRequired["int"],
    },
)

CSVInput = TypedDict(
    "CSVInput",
    {
    "file_header_info": NotRequired["FileHeaderInfo"],
    "comments": NotRequired["str"],
    "quote_escape_character": NotRequired["str"],
    "record_delimiter": NotRequired["str"],
    "field_delimiter": NotRequired["str"],
    "quote_character": NotRequired["str"],
    "allow_quoted_record_delimiter": NotRequired["bool"],
    },
)

CSVOutput = TypedDict(
    "CSVOutput",
    {
    "quote_fields": NotRequired["QuoteFields"],
    "quote_escape_character": NotRequired["str"],
    "record_delimiter": NotRequired["str"],
    "field_delimiter": NotRequired["str"],
    "quote_character": NotRequired["str"],
    },
)

Checksum = TypedDict(
    "Checksum",
    {
    "checksum_crc32": NotRequired["str"],
    "checksum_crc32_c": NotRequired["str"],
    "checksum_crc64_nvme": NotRequired["str"],
    "checksum_sha1": NotRequired["str"],
    "checksum_sha256": NotRequired["str"],
    "checksum_type": NotRequired["ChecksumType"],
    },
)

CommonPrefix = TypedDict(
    "CommonPrefix",
    {
    "prefix": NotRequired["str"],
    },
)

CompleteMultipartUploadRequest = TypedDict(
    "CompleteMultipartUploadRequest",
    {
    "bucket": Required["str"],
    "key": Required["str"],
    "multipart_upload": NotRequired["CompletedMultipartUpload"],
    "upload_id": Required["str"],
    "checksum_crc32": NotRequired["str"],
    "checksum_crc32_c": NotRequired["str"],
    "checksum_crc64_nvme": NotRequired["str"],
    "checksum_sha1": NotRequired["str"],
    "checksum_sha256": NotRequired["str"],
    "checksum_type": NotRequired["ChecksumType"],
    "mpu_object_size": NotRequired["int"],
    "request_payer": NotRequired["RequestPayer"],
    "expected_bucket_owner": NotRequired["str"],
    "if_match": NotRequired["str"],
    "if_none_match": NotRequired["str"],
    "sse_customer_algorithm": NotRequired["str"],
    "sse_customer_key": NotRequired["str"],
    "sse_customer_key_md5": NotRequired["str"],
    },
)

CompletedMultipartUpload = TypedDict(
    "CompletedMultipartUpload",
    {
    "parts": NotRequired["list[CompletedPart]"],
    },
)

CompletedPart = TypedDict(
    "CompletedPart",
    {
    "e_tag": NotRequired["str"],
    "checksum_crc32": NotRequired["str"],
    "checksum_crc32_c": NotRequired["str"],
    "checksum_crc64_nvme": NotRequired["str"],
    "checksum_sha1": NotRequired["str"],
    "checksum_sha256": NotRequired["str"],
    "part_number": NotRequired["int"],
    },
)

Condition = TypedDict(
    "Condition",
    {
    "http_error_code_returned_equals": NotRequired["str"],
    "key_prefix_equals": NotRequired["str"],
    },
)

ContinuationEvent = TypedDict(
    "ContinuationEvent",
    {
    },
)

CopyObjectRequest = TypedDict(
    "CopyObjectRequest",
    {
    "acl": NotRequired["ObjectCannedACL"],
    "bucket": Required["str"],
    "cache_control": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "content_disposition": NotRequired["str"],
    "content_encoding": NotRequired["str"],
    "content_language": NotRequired["str"],
    "content_type": NotRequired["str"],
    "copy_source": Required["str"],
    "copy_source_if_match": NotRequired["str"],
    "copy_source_if_modified_since": NotRequired["str"],
    "copy_source_if_none_match": NotRequired["str"],
    "copy_source_if_unmodified_since": NotRequired["str"],
    "expires": NotRequired["str"],
    "grant_full_control": NotRequired["str"],
    "grant_read": NotRequired["str"],
    "grant_read_acp": NotRequired["str"],
    "grant_write_acp": NotRequired["str"],
    "if_match": NotRequired["str"],
    "if_none_match": NotRequired["str"],
    "key": Required["str"],
    "metadata": NotRequired["dict[str, str]"],
    "metadata_directive": NotRequired["MetadataDirective"],
    "tagging_directive": NotRequired["TaggingDirective"],
    "server_side_encryption": NotRequired["ServerSideEncryption"],
    "storage_class": NotRequired["StorageClass"],
    "website_redirect_location": NotRequired["str"],
    "sse_customer_algorithm": NotRequired["str"],
    "sse_customer_key": NotRequired["str"],
    "sse_customer_key_md5": NotRequired["str"],
    "ssekms_key_id": NotRequired["str"],
    "ssekms_encryption_context": NotRequired["str"],
    "bucket_key_enabled": NotRequired["bool"],
    "copy_source_sse_customer_algorithm": NotRequired["str"],
    "copy_source_sse_customer_key": NotRequired["str"],
    "copy_source_sse_customer_key_md5": NotRequired["str"],
    "request_payer": NotRequired["RequestPayer"],
    "tagging": NotRequired["str"],
    "object_lock_mode": NotRequired["ObjectLockMode"],
    "object_lock_retain_until_date": NotRequired["str"],
    "object_lock_legal_hold_status": NotRequired["ObjectLockLegalHoldStatus"],
    "expected_bucket_owner": NotRequired["str"],
    "expected_source_bucket_owner": NotRequired["str"],
    },
)

CopyObjectResult = TypedDict(
    "CopyObjectResult",
    {
    "e_tag": NotRequired["str"],
    "last_modified": NotRequired["str"],
    "checksum_type": NotRequired["ChecksumType"],
    "checksum_crc32": NotRequired["str"],
    "checksum_crc32_c": NotRequired["str"],
    "checksum_crc64_nvme": NotRequired["str"],
    "checksum_sha1": NotRequired["str"],
    "checksum_sha256": NotRequired["str"],
    },
)

CopyPartResult = TypedDict(
    "CopyPartResult",
    {
    "e_tag": NotRequired["str"],
    "last_modified": NotRequired["str"],
    "checksum_crc32": NotRequired["str"],
    "checksum_crc32_c": NotRequired["str"],
    "checksum_crc64_nvme": NotRequired["str"],
    "checksum_sha1": NotRequired["str"],
    "checksum_sha256": NotRequired["str"],
    },
)

CreateBucketConfiguration = TypedDict(
    "CreateBucketConfiguration",
    {
    "location_constraint": NotRequired["BucketLocationConstraint"],
    "location": NotRequired["LocationInfo"],
    "bucket": NotRequired["BucketInfo"],
    "tags": NotRequired["list[Tag]"],
    },
)

CreateBucketMetadataConfigurationRequest = TypedDict(
    "CreateBucketMetadataConfigurationRequest",
    {
    "bucket": Required["str"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "metadata_configuration": Required["MetadataConfiguration"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

CreateBucketMetadataTableConfigurationRequest = TypedDict(
    "CreateBucketMetadataTableConfigurationRequest",
    {
    "bucket": Required["str"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "metadata_table_configuration": Required["MetadataTableConfiguration"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

CreateBucketRequest = TypedDict(
    "CreateBucketRequest",
    {
    "acl": NotRequired["BucketCannedACL"],
    "bucket": Required["str"],
    "create_bucket_configuration": NotRequired["CreateBucketConfiguration"],
    "grant_full_control": NotRequired["str"],
    "grant_read": NotRequired["str"],
    "grant_read_acp": NotRequired["str"],
    "grant_write": NotRequired["str"],
    "grant_write_acp": NotRequired["str"],
    "object_lock_enabled_for_bucket": NotRequired["bool"],
    "object_ownership": NotRequired["ObjectOwnership"],
    },
)

CreateMultipartUploadRequest = TypedDict(
    "CreateMultipartUploadRequest",
    {
    "acl": NotRequired["ObjectCannedACL"],
    "bucket": Required["str"],
    "cache_control": NotRequired["str"],
    "content_disposition": NotRequired["str"],
    "content_encoding": NotRequired["str"],
    "content_language": NotRequired["str"],
    "content_type": NotRequired["str"],
    "expires": NotRequired["str"],
    "grant_full_control": NotRequired["str"],
    "grant_read": NotRequired["str"],
    "grant_read_acp": NotRequired["str"],
    "grant_write_acp": NotRequired["str"],
    "key": Required["str"],
    "metadata": NotRequired["dict[str, str]"],
    "server_side_encryption": NotRequired["ServerSideEncryption"],
    "storage_class": NotRequired["StorageClass"],
    "website_redirect_location": NotRequired["str"],
    "sse_customer_algorithm": NotRequired["str"],
    "sse_customer_key": NotRequired["str"],
    "sse_customer_key_md5": NotRequired["str"],
    "ssekms_key_id": NotRequired["str"],
    "ssekms_encryption_context": NotRequired["str"],
    "bucket_key_enabled": NotRequired["bool"],
    "request_payer": NotRequired["RequestPayer"],
    "tagging": NotRequired["str"],
    "object_lock_mode": NotRequired["ObjectLockMode"],
    "object_lock_retain_until_date": NotRequired["str"],
    "object_lock_legal_hold_status": NotRequired["ObjectLockLegalHoldStatus"],
    "expected_bucket_owner": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "checksum_type": NotRequired["ChecksumType"],
    },
)

CreateSessionRequest = TypedDict(
    "CreateSessionRequest",
    {
    "session_mode": NotRequired["SessionMode"],
    "bucket": Required["str"],
    "server_side_encryption": NotRequired["ServerSideEncryption"],
    "ssekms_key_id": NotRequired["str"],
    "ssekms_encryption_context": NotRequired["str"],
    "bucket_key_enabled": NotRequired["bool"],
    },
)

DefaultRetention = TypedDict(
    "DefaultRetention",
    {
    "mode": NotRequired["ObjectLockRetentionMode"],
    "days": NotRequired["int"],
    "years": NotRequired["int"],
    },
)

Delete = TypedDict(
    "Delete",
    {
    "objects": Required["list[ObjectIdentifier]"],
    "quiet": NotRequired["bool"],
    },
)

DeleteBucketAnalyticsConfigurationRequest = TypedDict(
    "DeleteBucketAnalyticsConfigurationRequest",
    {
    "bucket": Required["str"],
    "id": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

DeleteBucketCorsRequest = TypedDict(
    "DeleteBucketCorsRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

DeleteBucketEncryptionRequest = TypedDict(
    "DeleteBucketEncryptionRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

DeleteBucketIntelligentTieringConfigurationRequest = TypedDict(
    "DeleteBucketIntelligentTieringConfigurationRequest",
    {
    "bucket": Required["str"],
    "id": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

DeleteBucketInventoryConfigurationRequest = TypedDict(
    "DeleteBucketInventoryConfigurationRequest",
    {
    "bucket": Required["str"],
    "id": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

DeleteBucketLifecycleRequest = TypedDict(
    "DeleteBucketLifecycleRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

DeleteBucketMetadataConfigurationRequest = TypedDict(
    "DeleteBucketMetadataConfigurationRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

DeleteBucketMetadataTableConfigurationRequest = TypedDict(
    "DeleteBucketMetadataTableConfigurationRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

DeleteBucketMetricsConfigurationRequest = TypedDict(
    "DeleteBucketMetricsConfigurationRequest",
    {
    "bucket": Required["str"],
    "id": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

DeleteBucketOwnershipControlsRequest = TypedDict(
    "DeleteBucketOwnershipControlsRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

DeleteBucketPolicyRequest = TypedDict(
    "DeleteBucketPolicyRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

DeleteBucketReplicationRequest = TypedDict(
    "DeleteBucketReplicationRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

DeleteBucketRequest = TypedDict(
    "DeleteBucketRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

DeleteBucketTaggingRequest = TypedDict(
    "DeleteBucketTaggingRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

DeleteBucketWebsiteRequest = TypedDict(
    "DeleteBucketWebsiteRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

DeleteMarkerEntry = TypedDict(
    "DeleteMarkerEntry",
    {
    "owner": NotRequired["Owner"],
    "key": NotRequired["str"],
    "version_id": NotRequired["str"],
    "is_latest": NotRequired["bool"],
    "last_modified": NotRequired["str"],
    },
)

DeleteMarkerReplication = TypedDict(
    "DeleteMarkerReplication",
    {
    "status": NotRequired["DeleteMarkerReplicationStatus"],
    },
)

DeleteObjectRequest = TypedDict(
    "DeleteObjectRequest",
    {
    "bucket": Required["str"],
    "key": Required["str"],
    "mfa": NotRequired["str"],
    "version_id": NotRequired["str"],
    "request_payer": NotRequired["RequestPayer"],
    "bypass_governance_retention": NotRequired["bool"],
    "expected_bucket_owner": NotRequired["str"],
    "if_match": NotRequired["str"],
    "if_match_last_modified_time": NotRequired["str"],
    "if_match_size": NotRequired["int"],
    },
)

DeleteObjectTaggingRequest = TypedDict(
    "DeleteObjectTaggingRequest",
    {
    "bucket": Required["str"],
    "key": Required["str"],
    "version_id": NotRequired["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

DeleteObjectsRequest = TypedDict(
    "DeleteObjectsRequest",
    {
    "bucket": Required["str"],
    "delete": Required["Delete"],
    "mfa": NotRequired["str"],
    "request_payer": NotRequired["RequestPayer"],
    "bypass_governance_retention": NotRequired["bool"],
    "expected_bucket_owner": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    },
)

DeletePublicAccessBlockRequest = TypedDict(
    "DeletePublicAccessBlockRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

DeletedObject = TypedDict(
    "DeletedObject",
    {
    "key": NotRequired["str"],
    "version_id": NotRequired["str"],
    "delete_marker": NotRequired["bool"],
    "delete_marker_version_id": NotRequired["str"],
    },
)

Destination = TypedDict(
    "Destination",
    {
    "bucket": Required["str"],
    "account": NotRequired["str"],
    "storage_class": NotRequired["StorageClass"],
    "access_control_translation": NotRequired["AccessControlTranslation"],
    "encryption_configuration": NotRequired["EncryptionConfiguration"],
    "replication_time": NotRequired["ReplicationTime"],
    "metrics": NotRequired["Metrics"],
    },
)

DestinationResult = TypedDict(
    "DestinationResult",
    {
    "table_bucket_type": NotRequired["S3TablesBucketType"],
    "table_bucket_arn": NotRequired["str"],
    "table_namespace": NotRequired["str"],
    },
)

Encryption = TypedDict(
    "Encryption",
    {
    "encryption_type": Required["ServerSideEncryption"],
    "kms_key_id": NotRequired["str"],
    "kms_context": NotRequired["str"],
    },
)

EncryptionConfiguration = TypedDict(
    "EncryptionConfiguration",
    {
    "replica_kms_key_id": NotRequired["str"],
    },
)

EndEvent = TypedDict(
    "EndEvent",
    {
    },
)

Error = TypedDict(
    "Error",
    {
    "key": NotRequired["str"],
    "version_id": NotRequired["str"],
    "code": NotRequired["str"],
    "message": NotRequired["str"],
    },
)

ErrorDetails = TypedDict(
    "ErrorDetails",
    {
    "error_code": NotRequired["str"],
    "error_message": NotRequired["str"],
    },
)

ErrorDocument = TypedDict(
    "ErrorDocument",
    {
    "key": Required["str"],
    },
)

EventBridgeConfiguration = TypedDict(
    "EventBridgeConfiguration",
    {
    },
)

ExistingObjectReplication = TypedDict(
    "ExistingObjectReplication",
    {
    "status": Required["ExistingObjectReplicationStatus"],
    },
)

FilterRule = TypedDict(
    "FilterRule",
    {
    "name": NotRequired["FilterRuleName"],
    "value": NotRequired["str"],
    },
)

GetBucketAbacRequest = TypedDict(
    "GetBucketAbacRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketAccelerateConfigurationRequest = TypedDict(
    "GetBucketAccelerateConfigurationRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    "request_payer": NotRequired["RequestPayer"],
    },
)

GetBucketAclRequest = TypedDict(
    "GetBucketAclRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketAnalyticsConfigurationRequest = TypedDict(
    "GetBucketAnalyticsConfigurationRequest",
    {
    "bucket": Required["str"],
    "id": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketCorsRequest = TypedDict(
    "GetBucketCorsRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketEncryptionRequest = TypedDict(
    "GetBucketEncryptionRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketIntelligentTieringConfigurationRequest = TypedDict(
    "GetBucketIntelligentTieringConfigurationRequest",
    {
    "bucket": Required["str"],
    "id": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketInventoryConfigurationRequest = TypedDict(
    "GetBucketInventoryConfigurationRequest",
    {
    "bucket": Required["str"],
    "id": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketLifecycleConfigurationRequest = TypedDict(
    "GetBucketLifecycleConfigurationRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketLocationRequest = TypedDict(
    "GetBucketLocationRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketLoggingRequest = TypedDict(
    "GetBucketLoggingRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketMetadataConfigurationRequest = TypedDict(
    "GetBucketMetadataConfigurationRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketMetadataConfigurationResult = TypedDict(
    "GetBucketMetadataConfigurationResult",
    {
    "metadata_configuration_result": Required["MetadataConfigurationResult"],
    },
)

GetBucketMetadataTableConfigurationRequest = TypedDict(
    "GetBucketMetadataTableConfigurationRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketMetadataTableConfigurationResult = TypedDict(
    "GetBucketMetadataTableConfigurationResult",
    {
    "metadata_table_configuration_result": Required["MetadataTableConfigurationResult"],
    "status": Required["str"],
    "error": NotRequired["ErrorDetails"],
    },
)

GetBucketMetricsConfigurationRequest = TypedDict(
    "GetBucketMetricsConfigurationRequest",
    {
    "bucket": Required["str"],
    "id": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketNotificationConfigurationRequest = TypedDict(
    "GetBucketNotificationConfigurationRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketOwnershipControlsRequest = TypedDict(
    "GetBucketOwnershipControlsRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketPolicyRequest = TypedDict(
    "GetBucketPolicyRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketPolicyStatusRequest = TypedDict(
    "GetBucketPolicyStatusRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketReplicationRequest = TypedDict(
    "GetBucketReplicationRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketRequestPaymentRequest = TypedDict(
    "GetBucketRequestPaymentRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketTaggingRequest = TypedDict(
    "GetBucketTaggingRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketVersioningRequest = TypedDict(
    "GetBucketVersioningRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetBucketWebsiteRequest = TypedDict(
    "GetBucketWebsiteRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetObjectAclRequest = TypedDict(
    "GetObjectAclRequest",
    {
    "bucket": Required["str"],
    "key": Required["str"],
    "version_id": NotRequired["str"],
    "request_payer": NotRequired["RequestPayer"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetObjectAttributesParts = TypedDict(
    "GetObjectAttributesParts",
    {
    "total_parts_count": NotRequired["int"],
    "part_number_marker": NotRequired["str"],
    "next_part_number_marker": NotRequired["str"],
    "max_parts": NotRequired["int"],
    "is_truncated": NotRequired["bool"],
    "parts": NotRequired["list[ObjectPart]"],
    },
)

GetObjectAttributesRequest = TypedDict(
    "GetObjectAttributesRequest",
    {
    "bucket": Required["str"],
    "key": Required["str"],
    "version_id": NotRequired["str"],
    "max_parts": NotRequired["int"],
    "part_number_marker": NotRequired["str"],
    "sse_customer_algorithm": NotRequired["str"],
    "sse_customer_key": NotRequired["str"],
    "sse_customer_key_md5": NotRequired["str"],
    "request_payer": NotRequired["RequestPayer"],
    "expected_bucket_owner": NotRequired["str"],
    "object_attributes": Required["list[ObjectAttributes]"],
    },
)

GetObjectLegalHoldRequest = TypedDict(
    "GetObjectLegalHoldRequest",
    {
    "bucket": Required["str"],
    "key": Required["str"],
    "version_id": NotRequired["str"],
    "request_payer": NotRequired["RequestPayer"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetObjectLockConfigurationRequest = TypedDict(
    "GetObjectLockConfigurationRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetObjectRequest = TypedDict(
    "GetObjectRequest",
    {
    "bucket": Required["str"],
    "if_match": NotRequired["str"],
    "if_modified_since": NotRequired["str"],
    "if_none_match": NotRequired["str"],
    "if_unmodified_since": NotRequired["str"],
    "key": Required["str"],
    "range": NotRequired["str"],
    "response_cache_control": NotRequired["str"],
    "response_content_disposition": NotRequired["str"],
    "response_content_encoding": NotRequired["str"],
    "response_content_language": NotRequired["str"],
    "response_content_type": NotRequired["str"],
    "response_expires": NotRequired["str"],
    "version_id": NotRequired["str"],
    "sse_customer_algorithm": NotRequired["str"],
    "sse_customer_key": NotRequired["str"],
    "sse_customer_key_md5": NotRequired["str"],
    "request_payer": NotRequired["RequestPayer"],
    "part_number": NotRequired["int"],
    "expected_bucket_owner": NotRequired["str"],
    "checksum_mode": NotRequired["ChecksumMode"],
    },
)

GetObjectRetentionRequest = TypedDict(
    "GetObjectRetentionRequest",
    {
    "bucket": Required["str"],
    "key": Required["str"],
    "version_id": NotRequired["str"],
    "request_payer": NotRequired["RequestPayer"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetObjectTaggingRequest = TypedDict(
    "GetObjectTaggingRequest",
    {
    "bucket": Required["str"],
    "key": Required["str"],
    "version_id": NotRequired["str"],
    "expected_bucket_owner": NotRequired["str"],
    "request_payer": NotRequired["RequestPayer"],
    },
)

GetObjectTorrentRequest = TypedDict(
    "GetObjectTorrentRequest",
    {
    "bucket": Required["str"],
    "key": Required["str"],
    "request_payer": NotRequired["RequestPayer"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GetPublicAccessBlockRequest = TypedDict(
    "GetPublicAccessBlockRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

GlacierJobParameters = TypedDict(
    "GlacierJobParameters",
    {
    "tier": Required["Tier"],
    },
)

Grant = TypedDict(
    "Grant",
    {
    "grantee": NotRequired["Grantee"],
    "permission": NotRequired["Permission"],
    },
)

Grantee = TypedDict(
    "Grantee",
    {
    "display_name": NotRequired["str"],
    "email_address": NotRequired["str"],
    "id": NotRequired["str"],
    "uri": NotRequired["str"],
    "type": Required["Type"],
    },
)

HeadBucketRequest = TypedDict(
    "HeadBucketRequest",
    {
    "bucket": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

HeadObjectRequest = TypedDict(
    "HeadObjectRequest",
    {
    "bucket": Required["str"],
    "if_match": NotRequired["str"],
    "if_modified_since": NotRequired["str"],
    "if_none_match": NotRequired["str"],
    "if_unmodified_since": NotRequired["str"],
    "key": Required["str"],
    "range": NotRequired["str"],
    "response_cache_control": NotRequired["str"],
    "response_content_disposition": NotRequired["str"],
    "response_content_encoding": NotRequired["str"],
    "response_content_language": NotRequired["str"],
    "response_content_type": NotRequired["str"],
    "response_expires": NotRequired["str"],
    "version_id": NotRequired["str"],
    "sse_customer_algorithm": NotRequired["str"],
    "sse_customer_key": NotRequired["str"],
    "sse_customer_key_md5": NotRequired["str"],
    "request_payer": NotRequired["RequestPayer"],
    "part_number": NotRequired["int"],
    "expected_bucket_owner": NotRequired["str"],
    "checksum_mode": NotRequired["ChecksumMode"],
    },
)

IndexDocument = TypedDict(
    "IndexDocument",
    {
    "suffix": Required["str"],
    },
)

Initiator = TypedDict(
    "Initiator",
    {
    "id": NotRequired["str"],
    "display_name": NotRequired["str"],
    },
)

InputSerialization = TypedDict(
    "InputSerialization",
    {
    "csv": NotRequired["CSVInput"],
    "compression_type": NotRequired["CompressionType"],
    "json": NotRequired["JSONInput"],
    "parquet": NotRequired["ParquetInput"],
    },
)

IntelligentTieringAndOperator = TypedDict(
    "IntelligentTieringAndOperator",
    {
    "prefix": NotRequired["str"],
    "tags": NotRequired["list[Tag]"],
    },
)

IntelligentTieringConfiguration = TypedDict(
    "IntelligentTieringConfiguration",
    {
    "id": Required["str"],
    "filter": NotRequired["IntelligentTieringFilter"],
    "status": Required["IntelligentTieringStatus"],
    "tierings": Required["list[Tiering]"],
    },
)

IntelligentTieringFilter = TypedDict(
    "IntelligentTieringFilter",
    {
    "prefix": NotRequired["str"],
    "tag": NotRequired["Tag"],
    "and": NotRequired["IntelligentTieringAndOperator"],
    },
)

InventoryConfiguration = TypedDict(
    "InventoryConfiguration",
    {
    "destination": Required["InventoryDestination"],
    "is_enabled": Required["bool"],
    "filter": NotRequired["InventoryFilter"],
    "id": Required["str"],
    "included_object_versions": Required["InventoryIncludedObjectVersions"],
    "optional_fields": NotRequired["list[InventoryOptionalField]"],
    "schedule": Required["InventorySchedule"],
    },
)

InventoryDestination = TypedDict(
    "InventoryDestination",
    {
    "s3_bucket_destination": Required["InventoryS3BucketDestination"],
    },
)

InventoryEncryption = TypedDict(
    "InventoryEncryption",
    {
    "sses3": NotRequired["SSES3"],
    "ssekms": NotRequired["SSEKMS"],
    },
)

InventoryFilter = TypedDict(
    "InventoryFilter",
    {
    "prefix": Required["str"],
    },
)

InventoryS3BucketDestination = TypedDict(
    "InventoryS3BucketDestination",
    {
    "account_id": NotRequired["str"],
    "bucket": Required["str"],
    "format": Required["InventoryFormat"],
    "prefix": NotRequired["str"],
    "encryption": NotRequired["InventoryEncryption"],
    },
)

InventorySchedule = TypedDict(
    "InventorySchedule",
    {
    "frequency": Required["InventoryFrequency"],
    },
)

InventoryTableConfiguration = TypedDict(
    "InventoryTableConfiguration",
    {
    "configuration_state": Required["InventoryConfigurationState"],
    "encryption_configuration": NotRequired["MetadataTableEncryptionConfiguration"],
    },
)

InventoryTableConfigurationResult = TypedDict(
    "InventoryTableConfigurationResult",
    {
    "configuration_state": Required["InventoryConfigurationState"],
    "table_status": NotRequired["str"],
    "error": NotRequired["ErrorDetails"],
    "table_name": NotRequired["str"],
    "table_arn": NotRequired["str"],
    },
)

InventoryTableConfigurationUpdates = TypedDict(
    "InventoryTableConfigurationUpdates",
    {
    "configuration_state": Required["InventoryConfigurationState"],
    "encryption_configuration": NotRequired["MetadataTableEncryptionConfiguration"],
    },
)

JSONInput = TypedDict(
    "JSONInput",
    {
    "type": NotRequired["JSONType"],
    },
)

JSONOutput = TypedDict(
    "JSONOutput",
    {
    "record_delimiter": NotRequired["str"],
    },
)

JournalTableConfiguration = TypedDict(
    "JournalTableConfiguration",
    {
    "record_expiration": Required["RecordExpiration"],
    "encryption_configuration": NotRequired["MetadataTableEncryptionConfiguration"],
    },
)

JournalTableConfigurationResult = TypedDict(
    "JournalTableConfigurationResult",
    {
    "table_status": Required["str"],
    "error": NotRequired["ErrorDetails"],
    "table_name": Required["str"],
    "table_arn": NotRequired["str"],
    "record_expiration": Required["RecordExpiration"],
    },
)

JournalTableConfigurationUpdates = TypedDict(
    "JournalTableConfigurationUpdates",
    {
    "record_expiration": Required["RecordExpiration"],
    },
)

LambdaFunctionConfiguration = TypedDict(
    "LambdaFunctionConfiguration",
    {
    "id": NotRequired["str"],
    "lambda_function_arn": Required["str"],
    "events": Required["list[Event]"],
    "filter": NotRequired["NotificationConfigurationFilter"],
    },
)

LifecycleExpiration = TypedDict(
    "LifecycleExpiration",
    {
    "date": NotRequired["str"],
    "days": NotRequired["int"],
    "expired_object_delete_marker": NotRequired["bool"],
    },
)

LifecycleRule = TypedDict(
    "LifecycleRule",
    {
    "expiration": NotRequired["LifecycleExpiration"],
    "id": NotRequired["str"],
    "prefix": NotRequired["str"],
    "filter": NotRequired["LifecycleRuleFilter"],
    "status": Required["ExpirationStatus"],
    "transitions": NotRequired["list[Transition]"],
    "noncurrent_version_transitions": NotRequired["list[NoncurrentVersionTransition]"],
    "noncurrent_version_expiration": NotRequired["NoncurrentVersionExpiration"],
    "abort_incomplete_multipart_upload": NotRequired["AbortIncompleteMultipartUpload"],
    },
)

LifecycleRuleAndOperator = TypedDict(
    "LifecycleRuleAndOperator",
    {
    "prefix": NotRequired["str"],
    "tags": NotRequired["list[Tag]"],
    "object_size_greater_than": NotRequired["int"],
    "object_size_less_than": NotRequired["int"],
    },
)

LifecycleRuleFilter = TypedDict(
    "LifecycleRuleFilter",
    {
    "prefix": NotRequired["str"],
    "tag": NotRequired["Tag"],
    "object_size_greater_than": NotRequired["int"],
    "object_size_less_than": NotRequired["int"],
    "and": NotRequired["LifecycleRuleAndOperator"],
    },
)

ListBucketAnalyticsConfigurationsRequest = TypedDict(
    "ListBucketAnalyticsConfigurationsRequest",
    {
    "bucket": Required["str"],
    "continuation_token": NotRequired["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

ListBucketIntelligentTieringConfigurationsRequest = TypedDict(
    "ListBucketIntelligentTieringConfigurationsRequest",
    {
    "bucket": Required["str"],
    "continuation_token": NotRequired["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

ListBucketInventoryConfigurationsRequest = TypedDict(
    "ListBucketInventoryConfigurationsRequest",
    {
    "bucket": Required["str"],
    "continuation_token": NotRequired["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

ListBucketMetricsConfigurationsRequest = TypedDict(
    "ListBucketMetricsConfigurationsRequest",
    {
    "bucket": Required["str"],
    "continuation_token": NotRequired["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

ListBucketsRequest = TypedDict(
    "ListBucketsRequest",
    {
    "max_buckets": NotRequired["int"],
    "continuation_token": NotRequired["str"],
    "prefix": NotRequired["str"],
    "bucket_region": NotRequired["str"],
    },
)

ListDirectoryBucketsRequest = TypedDict(
    "ListDirectoryBucketsRequest",
    {
    "continuation_token": NotRequired["str"],
    "max_directory_buckets": NotRequired["int"],
    },
)

ListMultipartUploadsRequest = TypedDict(
    "ListMultipartUploadsRequest",
    {
    "bucket": Required["str"],
    "delimiter": NotRequired["str"],
    "encoding_type": NotRequired["EncodingType"],
    "key_marker": NotRequired["str"],
    "max_uploads": NotRequired["int"],
    "prefix": NotRequired["str"],
    "upload_id_marker": NotRequired["str"],
    "expected_bucket_owner": NotRequired["str"],
    "request_payer": NotRequired["RequestPayer"],
    },
)

ListObjectVersionsRequest = TypedDict(
    "ListObjectVersionsRequest",
    {
    "bucket": Required["str"],
    "delimiter": NotRequired["str"],
    "encoding_type": NotRequired["EncodingType"],
    "key_marker": NotRequired["str"],
    "max_keys": NotRequired["int"],
    "prefix": NotRequired["str"],
    "version_id_marker": NotRequired["str"],
    "expected_bucket_owner": NotRequired["str"],
    "request_payer": NotRequired["RequestPayer"],
    "optional_object_attributes": NotRequired["list[OptionalObjectAttributes]"],
    },
)

ListObjectsRequest = TypedDict(
    "ListObjectsRequest",
    {
    "bucket": Required["str"],
    "delimiter": NotRequired["str"],
    "encoding_type": NotRequired["EncodingType"],
    "marker": NotRequired["str"],
    "max_keys": NotRequired["int"],
    "prefix": NotRequired["str"],
    "request_payer": NotRequired["RequestPayer"],
    "expected_bucket_owner": NotRequired["str"],
    "optional_object_attributes": NotRequired["list[OptionalObjectAttributes]"],
    },
)

ListObjectsV2Request = TypedDict(
    "ListObjectsV2Request",
    {
    "bucket": Required["str"],
    "delimiter": NotRequired["str"],
    "encoding_type": NotRequired["EncodingType"],
    "max_keys": NotRequired["int"],
    "prefix": NotRequired["str"],
    "continuation_token": NotRequired["str"],
    "fetch_owner": NotRequired["bool"],
    "start_after": NotRequired["str"],
    "request_payer": NotRequired["RequestPayer"],
    "expected_bucket_owner": NotRequired["str"],
    "optional_object_attributes": NotRequired["list[OptionalObjectAttributes]"],
    },
)

ListPartsRequest = TypedDict(
    "ListPartsRequest",
    {
    "bucket": Required["str"],
    "key": Required["str"],
    "max_parts": NotRequired["int"],
    "part_number_marker": NotRequired["str"],
    "upload_id": Required["str"],
    "request_payer": NotRequired["RequestPayer"],
    "expected_bucket_owner": NotRequired["str"],
    "sse_customer_algorithm": NotRequired["str"],
    "sse_customer_key": NotRequired["str"],
    "sse_customer_key_md5": NotRequired["str"],
    },
)

LocationInfo = TypedDict(
    "LocationInfo",
    {
    "type": NotRequired["LocationType"],
    "name": NotRequired["str"],
    },
)

LoggingEnabled = TypedDict(
    "LoggingEnabled",
    {
    "target_bucket": Required["str"],
    "target_grants": NotRequired["list[TargetGrant]"],
    "target_prefix": Required["str"],
    "target_object_key_format": NotRequired["TargetObjectKeyFormat"],
    },
)

MetadataConfiguration = TypedDict(
    "MetadataConfiguration",
    {
    "journal_table_configuration": Required["JournalTableConfiguration"],
    "inventory_table_configuration": NotRequired["InventoryTableConfiguration"],
    },
)

MetadataConfigurationResult = TypedDict(
    "MetadataConfigurationResult",
    {
    "destination_result": Required["DestinationResult"],
    "journal_table_configuration_result": NotRequired["JournalTableConfigurationResult"],
    "inventory_table_configuration_result": NotRequired["InventoryTableConfigurationResult"],
    },
)

MetadataEntry = TypedDict(
    "MetadataEntry",
    {
    "name": NotRequired["str"],
    "value": NotRequired["str"],
    },
)

MetadataTableConfiguration = TypedDict(
    "MetadataTableConfiguration",
    {
    "s3_tables_destination": Required["S3TablesDestination"],
    },
)

MetadataTableConfigurationResult = TypedDict(
    "MetadataTableConfigurationResult",
    {
    "s3_tables_destination_result": Required["S3TablesDestinationResult"],
    },
)

MetadataTableEncryptionConfiguration = TypedDict(
    "MetadataTableEncryptionConfiguration",
    {
    "sse_algorithm": Required["TableSseAlgorithm"],
    "kms_key_arn": NotRequired["str"],
    },
)

Metrics = TypedDict(
    "Metrics",
    {
    "status": Required["MetricsStatus"],
    "event_threshold": NotRequired["ReplicationTimeValue"],
    },
)

MetricsAndOperator = TypedDict(
    "MetricsAndOperator",
    {
    "prefix": NotRequired["str"],
    "tags": NotRequired["list[Tag]"],
    "access_point_arn": NotRequired["str"],
    },
)

MetricsConfiguration = TypedDict(
    "MetricsConfiguration",
    {
    "id": Required["str"],
    "filter": NotRequired["MetricsFilter"],
    },
)

MetricsFilterPrefix = TypedDict("MetricsFilterPrefix", {"prefix": Required["str"]})
MetricsFilterTag = TypedDict("MetricsFilterTag", {"tag": Required["Tag"]})
MetricsFilterAccessPointArn = TypedDict("MetricsFilterAccessPointArn", {"access_point_arn": Required["str"]})
MetricsFilterAnd = TypedDict("MetricsFilterAnd", {"and": Required["MetricsAndOperator"]})
MetricsFilterUnknown = TypedDict("MetricsFilterUnknown", {"unknown": Required[bool]})
MetricsFilter: TypeAlias = MetricsFilterPrefix | MetricsFilterTag | MetricsFilterAccessPointArn | MetricsFilterAnd | MetricsFilterUnknown

MultipartUpload = TypedDict(
    "MultipartUpload",
    {
    "upload_id": NotRequired["str"],
    "key": NotRequired["str"],
    "initiated": NotRequired["str"],
    "storage_class": NotRequired["StorageClass"],
    "owner": NotRequired["Owner"],
    "initiator": NotRequired["Initiator"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "checksum_type": NotRequired["ChecksumType"],
    },
)

NoncurrentVersionExpiration = TypedDict(
    "NoncurrentVersionExpiration",
    {
    "noncurrent_days": NotRequired["int"],
    "newer_noncurrent_versions": NotRequired["int"],
    },
)

NoncurrentVersionTransition = TypedDict(
    "NoncurrentVersionTransition",
    {
    "noncurrent_days": NotRequired["int"],
    "storage_class": NotRequired["TransitionStorageClass"],
    "newer_noncurrent_versions": NotRequired["int"],
    },
)

NotificationConfiguration = TypedDict(
    "NotificationConfiguration",
    {
    "topic_configurations": NotRequired["list[TopicConfiguration]"],
    "queue_configurations": NotRequired["list[QueueConfiguration]"],
    "lambda_function_configurations": NotRequired["list[LambdaFunctionConfiguration]"],
    "event_bridge_configuration": NotRequired["EventBridgeConfiguration"],
    },
)

NotificationConfigurationFilter = TypedDict(
    "NotificationConfigurationFilter",
    {
    "key": NotRequired["S3KeyFilter"],
    },
)

Object = TypedDict(
    "Object",
    {
    "key": NotRequired["str"],
    "last_modified": NotRequired["str"],
    "e_tag": NotRequired["str"],
    "checksum_algorithm": NotRequired["list[ChecksumAlgorithm]"],
    "checksum_type": NotRequired["ChecksumType"],
    "size": NotRequired["int"],
    "storage_class": NotRequired["ObjectStorageClass"],
    "owner": NotRequired["Owner"],
    "restore_status": NotRequired["RestoreStatus"],
    },
)

ObjectIdentifier = TypedDict(
    "ObjectIdentifier",
    {
    "key": Required["str"],
    "version_id": NotRequired["str"],
    "e_tag": NotRequired["str"],
    "last_modified_time": NotRequired["str"],
    "size": NotRequired["int"],
    },
)

ObjectLockConfiguration = TypedDict(
    "ObjectLockConfiguration",
    {
    "object_lock_enabled": NotRequired["ObjectLockEnabled"],
    "rule": NotRequired["ObjectLockRule"],
    },
)

ObjectLockLegalHold = TypedDict(
    "ObjectLockLegalHold",
    {
    "status": NotRequired["ObjectLockLegalHoldStatus"],
    },
)

ObjectLockRetention = TypedDict(
    "ObjectLockRetention",
    {
    "mode": NotRequired["ObjectLockRetentionMode"],
    "retain_until_date": NotRequired["str"],
    },
)

ObjectLockRule = TypedDict(
    "ObjectLockRule",
    {
    "default_retention": NotRequired["DefaultRetention"],
    },
)

ObjectPart = TypedDict(
    "ObjectPart",
    {
    "part_number": NotRequired["int"],
    "size": NotRequired["int"],
    "checksum_crc32": NotRequired["str"],
    "checksum_crc32_c": NotRequired["str"],
    "checksum_crc64_nvme": NotRequired["str"],
    "checksum_sha1": NotRequired["str"],
    "checksum_sha256": NotRequired["str"],
    },
)

ObjectVersion = TypedDict(
    "ObjectVersion",
    {
    "e_tag": NotRequired["str"],
    "checksum_algorithm": NotRequired["list[ChecksumAlgorithm]"],
    "checksum_type": NotRequired["ChecksumType"],
    "size": NotRequired["int"],
    "storage_class": NotRequired["ObjectVersionStorageClass"],
    "key": NotRequired["str"],
    "version_id": NotRequired["str"],
    "is_latest": NotRequired["bool"],
    "last_modified": NotRequired["str"],
    "owner": NotRequired["Owner"],
    "restore_status": NotRequired["RestoreStatus"],
    },
)

OutputLocation = TypedDict(
    "OutputLocation",
    {
    "s3": NotRequired["S3Location"],
    },
)

OutputSerialization = TypedDict(
    "OutputSerialization",
    {
    "csv": NotRequired["CSVOutput"],
    "json": NotRequired["JSONOutput"],
    },
)

Owner = TypedDict(
    "Owner",
    {
    "display_name": NotRequired["str"],
    "id": NotRequired["str"],
    },
)

OwnershipControls = TypedDict(
    "OwnershipControls",
    {
    "rules": Required["list[OwnershipControlsRule]"],
    },
)

OwnershipControlsRule = TypedDict(
    "OwnershipControlsRule",
    {
    "object_ownership": Required["ObjectOwnership"],
    },
)

ParquetInput = TypedDict(
    "ParquetInput",
    {
    },
)

Part = TypedDict(
    "Part",
    {
    "part_number": NotRequired["int"],
    "last_modified": NotRequired["str"],
    "e_tag": NotRequired["str"],
    "size": NotRequired["int"],
    "checksum_crc32": NotRequired["str"],
    "checksum_crc32_c": NotRequired["str"],
    "checksum_crc64_nvme": NotRequired["str"],
    "checksum_sha1": NotRequired["str"],
    "checksum_sha256": NotRequired["str"],
    },
)

PartitionedPrefix = TypedDict(
    "PartitionedPrefix",
    {
    "partition_date_source": NotRequired["PartitionDateSource"],
    },
)

PolicyStatus = TypedDict(
    "PolicyStatus",
    {
    "is_public": NotRequired["bool"],
    },
)

Progress = TypedDict(
    "Progress",
    {
    "bytes_scanned": NotRequired["int"],
    "bytes_processed": NotRequired["int"],
    "bytes_returned": NotRequired["int"],
    },
)

ProgressEvent = TypedDict(
    "ProgressEvent",
    {
    "details": NotRequired["Progress"],
    },
)

PublicAccessBlockConfiguration = TypedDict(
    "PublicAccessBlockConfiguration",
    {
    "block_public_acls": NotRequired["bool"],
    "ignore_public_acls": NotRequired["bool"],
    "block_public_policy": NotRequired["bool"],
    "restrict_public_buckets": NotRequired["bool"],
    },
)

PutBucketAbacRequest = TypedDict(
    "PutBucketAbacRequest",
    {
    "bucket": Required["str"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "expected_bucket_owner": NotRequired["str"],
    "abac_status": Required["AbacStatus"],
    },
)

PutBucketAccelerateConfigurationRequest = TypedDict(
    "PutBucketAccelerateConfigurationRequest",
    {
    "bucket": Required["str"],
    "accelerate_configuration": Required["AccelerateConfiguration"],
    "expected_bucket_owner": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    },
)

PutBucketAclRequest = TypedDict(
    "PutBucketAclRequest",
    {
    "acl": NotRequired["BucketCannedACL"],
    "access_control_policy": NotRequired["AccessControlPolicy"],
    "bucket": Required["str"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "grant_full_control": NotRequired["str"],
    "grant_read": NotRequired["str"],
    "grant_read_acp": NotRequired["str"],
    "grant_write": NotRequired["str"],
    "grant_write_acp": NotRequired["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

PutBucketAnalyticsConfigurationRequest = TypedDict(
    "PutBucketAnalyticsConfigurationRequest",
    {
    "bucket": Required["str"],
    "id": Required["str"],
    "analytics_configuration": Required["AnalyticsConfiguration"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

PutBucketCorsRequest = TypedDict(
    "PutBucketCorsRequest",
    {
    "bucket": Required["str"],
    "cors_configuration": Required["CORSConfiguration"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

PutBucketEncryptionRequest = TypedDict(
    "PutBucketEncryptionRequest",
    {
    "bucket": Required["str"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "server_side_encryption_configuration": Required["ServerSideEncryptionConfiguration"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

PutBucketIntelligentTieringConfigurationRequest = TypedDict(
    "PutBucketIntelligentTieringConfigurationRequest",
    {
    "bucket": Required["str"],
    "id": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    "intelligent_tiering_configuration": Required["IntelligentTieringConfiguration"],
    },
)

PutBucketInventoryConfigurationRequest = TypedDict(
    "PutBucketInventoryConfigurationRequest",
    {
    "bucket": Required["str"],
    "id": Required["str"],
    "inventory_configuration": Required["InventoryConfiguration"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

PutBucketLifecycleConfigurationRequest = TypedDict(
    "PutBucketLifecycleConfigurationRequest",
    {
    "bucket": Required["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "lifecycle_configuration": NotRequired["BucketLifecycleConfiguration"],
    "expected_bucket_owner": NotRequired["str"],
    "transition_default_minimum_object_size": NotRequired["TransitionDefaultMinimumObjectSize"],
    },
)

PutBucketLoggingRequest = TypedDict(
    "PutBucketLoggingRequest",
    {
    "bucket": Required["str"],
    "bucket_logging_status": Required["BucketLoggingStatus"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

PutBucketMetricsConfigurationRequest = TypedDict(
    "PutBucketMetricsConfigurationRequest",
    {
    "bucket": Required["str"],
    "id": Required["str"],
    "metrics_configuration": Required["MetricsConfiguration"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

PutBucketNotificationConfigurationRequest = TypedDict(
    "PutBucketNotificationConfigurationRequest",
    {
    "bucket": Required["str"],
    "notification_configuration": Required["NotificationConfiguration"],
    "expected_bucket_owner": NotRequired["str"],
    "skip_destination_validation": NotRequired["bool"],
    },
)

PutBucketOwnershipControlsRequest = TypedDict(
    "PutBucketOwnershipControlsRequest",
    {
    "bucket": Required["str"],
    "content_md5": NotRequired["str"],
    "expected_bucket_owner": NotRequired["str"],
    "ownership_controls": Required["OwnershipControls"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    },
)

PutBucketPolicyRequest = TypedDict(
    "PutBucketPolicyRequest",
    {
    "bucket": Required["str"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "confirm_remove_self_bucket_access": NotRequired["bool"],
    "policy": Required["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

PutBucketReplicationRequest = TypedDict(
    "PutBucketReplicationRequest",
    {
    "bucket": Required["str"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "replication_configuration": Required["ReplicationConfiguration"],
    "token": NotRequired["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

PutBucketRequestPaymentRequest = TypedDict(
    "PutBucketRequestPaymentRequest",
    {
    "bucket": Required["str"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "request_payment_configuration": Required["RequestPaymentConfiguration"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

PutBucketTaggingRequest = TypedDict(
    "PutBucketTaggingRequest",
    {
    "bucket": Required["str"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "tagging": Required["Tagging"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

PutBucketVersioningRequest = TypedDict(
    "PutBucketVersioningRequest",
    {
    "bucket": Required["str"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "mfa": NotRequired["str"],
    "versioning_configuration": Required["VersioningConfiguration"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

PutBucketWebsiteRequest = TypedDict(
    "PutBucketWebsiteRequest",
    {
    "bucket": Required["str"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "website_configuration": Required["WebsiteConfiguration"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

PutObjectAclRequest = TypedDict(
    "PutObjectAclRequest",
    {
    "acl": NotRequired["ObjectCannedACL"],
    "access_control_policy": NotRequired["AccessControlPolicy"],
    "bucket": Required["str"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "grant_full_control": NotRequired["str"],
    "grant_read": NotRequired["str"],
    "grant_read_acp": NotRequired["str"],
    "grant_write": NotRequired["str"],
    "grant_write_acp": NotRequired["str"],
    "key": Required["str"],
    "request_payer": NotRequired["RequestPayer"],
    "version_id": NotRequired["str"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

PutObjectLegalHoldRequest = TypedDict(
    "PutObjectLegalHoldRequest",
    {
    "bucket": Required["str"],
    "key": Required["str"],
    "legal_hold": NotRequired["ObjectLockLegalHold"],
    "request_payer": NotRequired["RequestPayer"],
    "version_id": NotRequired["str"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

PutObjectLockConfigurationRequest = TypedDict(
    "PutObjectLockConfigurationRequest",
    {
    "bucket": Required["str"],
    "object_lock_configuration": NotRequired["ObjectLockConfiguration"],
    "request_payer": NotRequired["RequestPayer"],
    "token": NotRequired["str"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

PutObjectRequest = TypedDict(
    "PutObjectRequest",
    {
    "acl": NotRequired["ObjectCannedACL"],
    "body": NotRequired["ByteStream"],
    "bucket": Required["str"],
    "cache_control": NotRequired["str"],
    "content_disposition": NotRequired["str"],
    "content_encoding": NotRequired["str"],
    "content_language": NotRequired["str"],
    "content_length": NotRequired["int"],
    "content_md5": NotRequired["str"],
    "content_type": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "checksum_crc32": NotRequired["str"],
    "checksum_crc32_c": NotRequired["str"],
    "checksum_crc64_nvme": NotRequired["str"],
    "checksum_sha1": NotRequired["str"],
    "checksum_sha256": NotRequired["str"],
    "expires": NotRequired["str"],
    "if_match": NotRequired["str"],
    "if_none_match": NotRequired["str"],
    "grant_full_control": NotRequired["str"],
    "grant_read": NotRequired["str"],
    "grant_read_acp": NotRequired["str"],
    "grant_write_acp": NotRequired["str"],
    "key": Required["str"],
    "write_offset_bytes": NotRequired["int"],
    "metadata": NotRequired["dict[str, str]"],
    "server_side_encryption": NotRequired["ServerSideEncryption"],
    "storage_class": NotRequired["StorageClass"],
    "website_redirect_location": NotRequired["str"],
    "sse_customer_algorithm": NotRequired["str"],
    "sse_customer_key": NotRequired["str"],
    "sse_customer_key_md5": NotRequired["str"],
    "ssekms_key_id": NotRequired["str"],
    "ssekms_encryption_context": NotRequired["str"],
    "bucket_key_enabled": NotRequired["bool"],
    "request_payer": NotRequired["RequestPayer"],
    "tagging": NotRequired["str"],
    "object_lock_mode": NotRequired["ObjectLockMode"],
    "object_lock_retain_until_date": NotRequired["str"],
    "object_lock_legal_hold_status": NotRequired["ObjectLockLegalHoldStatus"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

PutObjectRetentionRequest = TypedDict(
    "PutObjectRetentionRequest",
    {
    "bucket": Required["str"],
    "key": Required["str"],
    "retention": NotRequired["ObjectLockRetention"],
    "request_payer": NotRequired["RequestPayer"],
    "version_id": NotRequired["str"],
    "bypass_governance_retention": NotRequired["bool"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

PutObjectTaggingRequest = TypedDict(
    "PutObjectTaggingRequest",
    {
    "bucket": Required["str"],
    "key": Required["str"],
    "version_id": NotRequired["str"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "tagging": Required["Tagging"],
    "expected_bucket_owner": NotRequired["str"],
    "request_payer": NotRequired["RequestPayer"],
    },
)

PutPublicAccessBlockRequest = TypedDict(
    "PutPublicAccessBlockRequest",
    {
    "bucket": Required["str"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "public_access_block_configuration": Required["PublicAccessBlockConfiguration"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

QueueConfiguration = TypedDict(
    "QueueConfiguration",
    {
    "id": NotRequired["str"],
    "queue_arn": Required["str"],
    "events": Required["list[Event]"],
    "filter": NotRequired["NotificationConfigurationFilter"],
    },
)

RecordExpiration = TypedDict(
    "RecordExpiration",
    {
    "expiration": Required["ExpirationState"],
    "days": NotRequired["int"],
    },
)

RecordsEvent = TypedDict(
    "RecordsEvent",
    {
    "payload": NotRequired["bytes"],
    },
)

Redirect = TypedDict(
    "Redirect",
    {
    "host_name": NotRequired["str"],
    "http_redirect_code": NotRequired["str"],
    "protocol": NotRequired["Protocol"],
    "replace_key_prefix_with": NotRequired["str"],
    "replace_key_with": NotRequired["str"],
    },
)

RedirectAllRequestsTo = TypedDict(
    "RedirectAllRequestsTo",
    {
    "host_name": Required["str"],
    "protocol": NotRequired["Protocol"],
    },
)

RenameObjectRequest = TypedDict(
    "RenameObjectRequest",
    {
    "bucket": Required["str"],
    "key": Required["str"],
    "rename_source": Required["str"],
    "destination_if_match": NotRequired["str"],
    "destination_if_none_match": NotRequired["str"],
    "destination_if_modified_since": NotRequired["str"],
    "destination_if_unmodified_since": NotRequired["str"],
    "source_if_match": NotRequired["str"],
    "source_if_none_match": NotRequired["str"],
    "source_if_modified_since": NotRequired["str"],
    "source_if_unmodified_since": NotRequired["str"],
    "client_token": NotRequired["str"],
    },
)

ReplicaModifications = TypedDict(
    "ReplicaModifications",
    {
    "status": Required["ReplicaModificationsStatus"],
    },
)

ReplicationConfiguration = TypedDict(
    "ReplicationConfiguration",
    {
    "role": Required["str"],
    "rules": Required["list[ReplicationRule]"],
    },
)

ReplicationRule = TypedDict(
    "ReplicationRule",
    {
    "id": NotRequired["str"],
    "priority": NotRequired["int"],
    "prefix": NotRequired["str"],
    "filter": NotRequired["ReplicationRuleFilter"],
    "status": Required["ReplicationRuleStatus"],
    "source_selection_criteria": NotRequired["SourceSelectionCriteria"],
    "existing_object_replication": NotRequired["ExistingObjectReplication"],
    "destination": Required["Destination"],
    "delete_marker_replication": NotRequired["DeleteMarkerReplication"],
    },
)

ReplicationRuleAndOperator = TypedDict(
    "ReplicationRuleAndOperator",
    {
    "prefix": NotRequired["str"],
    "tags": NotRequired["list[Tag]"],
    },
)

ReplicationRuleFilter = TypedDict(
    "ReplicationRuleFilter",
    {
    "prefix": NotRequired["str"],
    "tag": NotRequired["Tag"],
    "and": NotRequired["ReplicationRuleAndOperator"],
    },
)

ReplicationTime = TypedDict(
    "ReplicationTime",
    {
    "status": Required["ReplicationTimeStatus"],
    "time": Required["ReplicationTimeValue"],
    },
)

ReplicationTimeValue = TypedDict(
    "ReplicationTimeValue",
    {
    "minutes": NotRequired["int"],
    },
)

RequestPaymentConfiguration = TypedDict(
    "RequestPaymentConfiguration",
    {
    "payer": Required["Payer"],
    },
)

RequestProgress = TypedDict(
    "RequestProgress",
    {
    "enabled": NotRequired["bool"],
    },
)

RestoreObjectRequest = TypedDict(
    "RestoreObjectRequest",
    {
    "bucket": Required["str"],
    "key": Required["str"],
    "version_id": NotRequired["str"],
    "restore_request": NotRequired["RestoreRequest"],
    "request_payer": NotRequired["RequestPayer"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

RestoreRequest = TypedDict(
    "RestoreRequest",
    {
    "days": NotRequired["int"],
    "glacier_job_parameters": NotRequired["GlacierJobParameters"],
    "type": NotRequired["RestoreRequestType"],
    "tier": NotRequired["Tier"],
    "description": NotRequired["str"],
    "select_parameters": NotRequired["SelectParameters"],
    "output_location": NotRequired["OutputLocation"],
    },
)

RestoreStatus = TypedDict(
    "RestoreStatus",
    {
    "is_restore_in_progress": NotRequired["bool"],
    "restore_expiry_date": NotRequired["str"],
    },
)

RoutingRule = TypedDict(
    "RoutingRule",
    {
    "condition": NotRequired["Condition"],
    "redirect": Required["Redirect"],
    },
)

S3KeyFilter = TypedDict(
    "S3KeyFilter",
    {
    "filter_rules": NotRequired["list[FilterRule]"],
    },
)

S3Location = TypedDict(
    "S3Location",
    {
    "bucket_name": Required["str"],
    "prefix": Required["str"],
    "encryption": NotRequired["Encryption"],
    "canned_acl": NotRequired["ObjectCannedACL"],
    "access_control_list": NotRequired["list[Grant]"],
    "tagging": NotRequired["Tagging"],
    "user_metadata": NotRequired["list[MetadataEntry]"],
    "storage_class": NotRequired["StorageClass"],
    },
)

S3TablesDestination = TypedDict(
    "S3TablesDestination",
    {
    "table_bucket_arn": Required["str"],
    "table_name": Required["str"],
    },
)

S3TablesDestinationResult = TypedDict(
    "S3TablesDestinationResult",
    {
    "table_bucket_arn": Required["str"],
    "table_name": Required["str"],
    "table_arn": Required["str"],
    "table_namespace": Required["str"],
    },
)

SSEKMS = TypedDict(
    "SSEKMS",
    {
    "key_id": Required["str"],
    },
)

SSES3 = TypedDict(
    "SSES3",
    {
    },
)

ScanRange = TypedDict(
    "ScanRange",
    {
    "start": NotRequired["int"],
    "end": NotRequired["int"],
    },
)

SelectObjectContentEventStreamRecords = TypedDict("SelectObjectContentEventStreamRecords", {"records": Required["RecordsEvent"]})
SelectObjectContentEventStreamStats = TypedDict("SelectObjectContentEventStreamStats", {"stats": Required["StatsEvent"]})
SelectObjectContentEventStreamProgress = TypedDict("SelectObjectContentEventStreamProgress", {"progress": Required["ProgressEvent"]})
SelectObjectContentEventStreamCont = TypedDict("SelectObjectContentEventStreamCont", {"cont": Required["ContinuationEvent"]})
SelectObjectContentEventStreamEnd = TypedDict("SelectObjectContentEventStreamEnd", {"end": Required["EndEvent"]})
SelectObjectContentEventStreamUnknown = TypedDict("SelectObjectContentEventStreamUnknown", {"unknown": Required[bool]})
SelectObjectContentEventStream: TypeAlias = SelectObjectContentEventStreamRecords | SelectObjectContentEventStreamStats | SelectObjectContentEventStreamProgress | SelectObjectContentEventStreamCont | SelectObjectContentEventStreamEnd | SelectObjectContentEventStreamUnknown

SelectObjectContentOutput = TypedDict(
    "SelectObjectContentOutput",
    {
    "payload": Required["AsyncIterator[SelectObjectContentEventStream]"],
    },
)

SelectObjectContentRequest = TypedDict(
    "SelectObjectContentRequest",
    {
    "bucket": Required["str"],
    "key": Required["str"],
    "sse_customer_algorithm": NotRequired["str"],
    "sse_customer_key": NotRequired["str"],
    "sse_customer_key_md5": NotRequired["str"],
    "expression": Required["str"],
    "expression_type": Required["ExpressionType"],
    "request_progress": NotRequired["RequestProgress"],
    "input_serialization": Required["InputSerialization"],
    "output_serialization": Required["OutputSerialization"],
    "scan_range": NotRequired["ScanRange"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

SelectParameters = TypedDict(
    "SelectParameters",
    {
    "input_serialization": Required["InputSerialization"],
    "expression_type": Required["ExpressionType"],
    "expression": Required["str"],
    "output_serialization": Required["OutputSerialization"],
    },
)

ServerSideEncryptionByDefault = TypedDict(
    "ServerSideEncryptionByDefault",
    {
    "sse_algorithm": Required["ServerSideEncryption"],
    "kms_master_key_id": NotRequired["str"],
    },
)

ServerSideEncryptionConfiguration = TypedDict(
    "ServerSideEncryptionConfiguration",
    {
    "rules": Required["list[ServerSideEncryptionRule]"],
    },
)

ServerSideEncryptionRule = TypedDict(
    "ServerSideEncryptionRule",
    {
    "apply_server_side_encryption_by_default": NotRequired["ServerSideEncryptionByDefault"],
    "bucket_key_enabled": NotRequired["bool"],
    "blocked_encryption_types": NotRequired["BlockedEncryptionTypes"],
    },
)

SessionCredentials = TypedDict(
    "SessionCredentials",
    {
    "access_key_id": Required["str"],
    "secret_access_key": Required["str"],
    "session_token": Required["str"],
    "expiration": Required["str"],
    },
)

SimplePrefix = TypedDict(
    "SimplePrefix",
    {
    },
)

SourceSelectionCriteria = TypedDict(
    "SourceSelectionCriteria",
    {
    "sse_kms_encrypted_objects": NotRequired["SseKmsEncryptedObjects"],
    "replica_modifications": NotRequired["ReplicaModifications"],
    },
)

SseKmsEncryptedObjects = TypedDict(
    "SseKmsEncryptedObjects",
    {
    "status": Required["SseKmsEncryptedObjectsStatus"],
    },
)

Stats = TypedDict(
    "Stats",
    {
    "bytes_scanned": NotRequired["int"],
    "bytes_processed": NotRequired["int"],
    "bytes_returned": NotRequired["int"],
    },
)

StatsEvent = TypedDict(
    "StatsEvent",
    {
    "details": NotRequired["Stats"],
    },
)

StorageClassAnalysis = TypedDict(
    "StorageClassAnalysis",
    {
    "data_export": NotRequired["StorageClassAnalysisDataExport"],
    },
)

StorageClassAnalysisDataExport = TypedDict(
    "StorageClassAnalysisDataExport",
    {
    "output_schema_version": Required["StorageClassAnalysisSchemaVersion"],
    "destination": Required["AnalyticsExportDestination"],
    },
)

Tag = TypedDict(
    "Tag",
    {
    "key": Required["str"],
    "value": Required["str"],
    },
)

Tagging = TypedDict(
    "Tagging",
    {
    "tag_set": Required["list[Tag]"],
    },
)

TargetGrant = TypedDict(
    "TargetGrant",
    {
    "grantee": NotRequired["Grantee"],
    "permission": NotRequired["BucketLogsPermission"],
    },
)

TargetObjectKeyFormat = TypedDict(
    "TargetObjectKeyFormat",
    {
    "simple_prefix": NotRequired["SimplePrefix"],
    "partitioned_prefix": NotRequired["PartitionedPrefix"],
    },
)

Tiering = TypedDict(
    "Tiering",
    {
    "days": Required["int"],
    "access_tier": Required["IntelligentTieringAccessTier"],
    },
)

TopicConfiguration = TypedDict(
    "TopicConfiguration",
    {
    "id": NotRequired["str"],
    "topic_arn": Required["str"],
    "events": Required["list[Event]"],
    "filter": NotRequired["NotificationConfigurationFilter"],
    },
)

Transition = TypedDict(
    "Transition",
    {
    "date": NotRequired["str"],
    "days": NotRequired["int"],
    "storage_class": NotRequired["TransitionStorageClass"],
    },
)

UpdateBucketMetadataInventoryTableConfigurationRequest = TypedDict(
    "UpdateBucketMetadataInventoryTableConfigurationRequest",
    {
    "bucket": Required["str"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "inventory_table_configuration": Required["InventoryTableConfigurationUpdates"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

UpdateBucketMetadataJournalTableConfigurationRequest = TypedDict(
    "UpdateBucketMetadataJournalTableConfigurationRequest",
    {
    "bucket": Required["str"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "journal_table_configuration": Required["JournalTableConfigurationUpdates"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

UploadPartCopyRequest = TypedDict(
    "UploadPartCopyRequest",
    {
    "bucket": Required["str"],
    "copy_source": Required["str"],
    "copy_source_if_match": NotRequired["str"],
    "copy_source_if_modified_since": NotRequired["str"],
    "copy_source_if_none_match": NotRequired["str"],
    "copy_source_if_unmodified_since": NotRequired["str"],
    "copy_source_range": NotRequired["str"],
    "key": Required["str"],
    "part_number": Required["int"],
    "upload_id": Required["str"],
    "sse_customer_algorithm": NotRequired["str"],
    "sse_customer_key": NotRequired["str"],
    "sse_customer_key_md5": NotRequired["str"],
    "copy_source_sse_customer_algorithm": NotRequired["str"],
    "copy_source_sse_customer_key": NotRequired["str"],
    "copy_source_sse_customer_key_md5": NotRequired["str"],
    "request_payer": NotRequired["RequestPayer"],
    "expected_bucket_owner": NotRequired["str"],
    "expected_source_bucket_owner": NotRequired["str"],
    },
)

UploadPartRequest = TypedDict(
    "UploadPartRequest",
    {
    "body": NotRequired["ByteStream"],
    "bucket": Required["str"],
    "content_length": NotRequired["int"],
    "content_md5": NotRequired["str"],
    "checksum_algorithm": NotRequired["ChecksumAlgorithm"],
    "checksum_crc32": NotRequired["str"],
    "checksum_crc32_c": NotRequired["str"],
    "checksum_crc64_nvme": NotRequired["str"],
    "checksum_sha1": NotRequired["str"],
    "checksum_sha256": NotRequired["str"],
    "key": Required["str"],
    "part_number": Required["int"],
    "upload_id": Required["str"],
    "sse_customer_algorithm": NotRequired["str"],
    "sse_customer_key": NotRequired["str"],
    "sse_customer_key_md5": NotRequired["str"],
    "request_payer": NotRequired["RequestPayer"],
    "expected_bucket_owner": NotRequired["str"],
    },
)

VersioningConfiguration = TypedDict(
    "VersioningConfiguration",
    {
    "mfa_delete": NotRequired["MFADelete"],
    "status": NotRequired["BucketVersioningStatus"],
    },
)

WebsiteConfiguration = TypedDict(
    "WebsiteConfiguration",
    {
    "error_document": NotRequired["ErrorDocument"],
    "index_document": NotRequired["IndexDocument"],
    "redirect_all_requests_to": NotRequired["RedirectAllRequestsTo"],
    "routing_rules": NotRequired["list[RoutingRule]"],
    },
)

WriteGetObjectResponseRequest = TypedDict(
    "WriteGetObjectResponseRequest",
    {
    "request_route": Required["str"],
    "request_token": Required["str"],
    "body": NotRequired["ByteStream"],
    "status_code": NotRequired["int"],
    "error_code": NotRequired["str"],
    "error_message": NotRequired["str"],
    "accept_ranges": NotRequired["str"],
    "cache_control": NotRequired["str"],
    "content_disposition": NotRequired["str"],
    "content_encoding": NotRequired["str"],
    "content_language": NotRequired["str"],
    "content_length": NotRequired["int"],
    "content_range": NotRequired["str"],
    "content_type": NotRequired["str"],
    "checksum_crc32": NotRequired["str"],
    "checksum_crc32_c": NotRequired["str"],
    "checksum_crc64_nvme": NotRequired["str"],
    "checksum_sha1": NotRequired["str"],
    "checksum_sha256": NotRequired["str"],
    "delete_marker": NotRequired["bool"],
    "e_tag": NotRequired["str"],
    "expires": NotRequired["str"],
    "expiration": NotRequired["str"],
    "last_modified": NotRequired["str"],
    "missing_meta": NotRequired["int"],
    "metadata": NotRequired["dict[str, str]"],
    "object_lock_mode": NotRequired["ObjectLockMode"],
    "object_lock_legal_hold_status": NotRequired["ObjectLockLegalHoldStatus"],
    "object_lock_retain_until_date": NotRequired["str"],
    "parts_count": NotRequired["int"],
    "replication_status": NotRequired["ReplicationStatus"],
    "request_charged": NotRequired["RequestCharged"],
    "restore": NotRequired["str"],
    "server_side_encryption": NotRequired["ServerSideEncryption"],
    "sse_customer_algorithm": NotRequired["str"],
    "ssekms_key_id": NotRequired["str"],
    "sse_customer_key_md5": NotRequired["str"],
    "storage_class": NotRequired["StorageClass"],
    "tag_count": NotRequired["int"],
    "version_id": NotRequired["str"],
    "bucket_key_enabled": NotRequired["bool"],
    },
)
