from __future__ import annotations

from collections.abc import AsyncIterator
from typing import final


@final
class ByteStream:
    def __aiter__(self) -> AsyncIterator[bytes]: ...
    async def __anext__(self) -> bytes: ...
    async def read(self) -> bytes: ...



@final
class BatchResultErrorEntry:
    @property
    def id(self) -> str: ...
    @property
    def sender_fault(self) -> bool: ...
    @property
    def code(self) -> str: ...
    @property
    def message(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ChangeMessageVisibilityBatchResultEntry:
    @property
    def id(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DeleteMessageBatchResultEntry:
    @property
    def id(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListMessageMoveTasksResultEntry:
    @property
    def task_handle(self) -> str | None: ...
    @property
    def status(self) -> str | None: ...
    @property
    def source_arn(self) -> str | None: ...
    @property
    def destination_arn(self) -> str | None: ...
    @property
    def max_number_of_messages_per_second(self) -> int | None: ...
    @property
    def approximate_number_of_messages_moved(self) -> int: ...
    @property
    def approximate_number_of_messages_to_move(self) -> int | None: ...
    @property
    def failure_reason(self) -> str | None: ...
    @property
    def started_timestamp(self) -> int: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Message:
    @property
    def message_id(self) -> str | None: ...
    @property
    def receipt_handle(self) -> str | None: ...
    @property
    def md5_of_body(self) -> str | None: ...
    @property
    def body(self) -> str | None: ...
    @property
    def attributes(self) -> dict[str, str] | None: ...
    @property
    def md5_of_message_attributes(self) -> str | None: ...
    @property
    def message_attributes(self) -> dict[str, MessageAttributeValue] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class MessageAttributeValue:
    @property
    def string_value(self) -> str | None: ...
    @property
    def binary_value(self) -> bytes | None: ...
    @property
    def string_list_values(self) -> list[str] | None: ...
    @property
    def binary_list_values(self) -> list[bytes] | None: ...
    @property
    def data_type(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class SendMessageBatchResultEntry:
    @property
    def id(self) -> str: ...
    @property
    def message_id(self) -> str: ...
    @property
    def md5_of_message_body(self) -> str: ...
    @property
    def md5_of_message_attributes(self) -> str | None: ...
    @property
    def md5_of_message_system_attributes(self) -> str | None: ...
    @property
    def sequence_number(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CancelMessageMoveTaskResult:
    @property
    def approximate_number_of_messages_moved(self) -> int: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ChangeMessageVisibilityBatchResult:
    @property
    def successful(self) -> list[ChangeMessageVisibilityBatchResultEntry]: ...
    @property
    def failed(self) -> list[BatchResultErrorEntry]: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CreateQueueResult:
    @property
    def queue_url(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DeleteMessageBatchResult:
    @property
    def successful(self) -> list[DeleteMessageBatchResultEntry]: ...
    @property
    def failed(self) -> list[BatchResultErrorEntry]: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetQueueAttributesResult:
    @property
    def attributes(self) -> dict[str, str] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetQueueUrlResult:
    @property
    def queue_url(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListDeadLetterSourceQueuesResult:
    @property
    def queue_urls(self) -> list[str]: ...
    @property
    def next_token(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListMessageMoveTasksResult:
    @property
    def results(self) -> list[ListMessageMoveTasksResultEntry] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListQueuesResult:
    @property
    def queue_urls(self) -> list[str] | None: ...
    @property
    def next_token(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListQueueTagsResult:
    @property
    def tags(self) -> dict[str, str] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ReceiveMessageResult:
    @property
    def messages(self) -> list[Message] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class SendMessageResult:
    @property
    def md5_of_message_body(self) -> str | None: ...
    @property
    def md5_of_message_attributes(self) -> str | None: ...
    @property
    def md5_of_message_system_attributes(self) -> str | None: ...
    @property
    def message_id(self) -> str | None: ...
    @property
    def sequence_number(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class SendMessageBatchResult:
    @property
    def successful(self) -> list[SendMessageBatchResultEntry]: ...
    @property
    def failed(self) -> list[BatchResultErrorEntry]: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class StartMessageMoveTaskResult:
    @property
    def task_handle(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...



@final
class SQSClient:
    def __init__(
        self,
        *,
        region: str | None = None,
        profile: str | None = None,
        endpoint_url: str | None = None,
    ) -> None: ...

    async def add_permission(self, params: dict[str, object]) -> None: ...

    async def cancel_message_move_task(self, params: dict[str, object]) -> CancelMessageMoveTaskResult: ...

    async def change_message_visibility(self, params: dict[str, object]) -> None: ...

    async def change_message_visibility_batch(self, params: dict[str, object]) -> ChangeMessageVisibilityBatchResult: ...

    async def create_queue(self, params: dict[str, object]) -> CreateQueueResult: ...

    async def delete_message(self, params: dict[str, object]) -> None: ...

    async def delete_message_batch(self, params: dict[str, object]) -> DeleteMessageBatchResult: ...

    async def delete_queue(self, params: dict[str, object]) -> None: ...

    async def get_queue_attributes(self, params: dict[str, object]) -> GetQueueAttributesResult: ...

    async def get_queue_url(self, params: dict[str, object]) -> GetQueueUrlResult: ...

    async def list_dead_letter_source_queues(self, params: dict[str, object]) -> ListDeadLetterSourceQueuesResult: ...

    async def list_message_move_tasks(self, params: dict[str, object]) -> ListMessageMoveTasksResult: ...

    async def list_queues(self, params: dict[str, object]) -> ListQueuesResult: ...

    async def list_queue_tags(self, params: dict[str, object]) -> ListQueueTagsResult: ...

    async def purge_queue(self, params: dict[str, object]) -> None: ...

    async def receive_message(self, params: dict[str, object]) -> ReceiveMessageResult: ...

    async def remove_permission(self, params: dict[str, object]) -> None: ...

    async def send_message(self, params: dict[str, object]) -> SendMessageResult: ...

    async def send_message_batch(self, params: dict[str, object]) -> SendMessageBatchResult: ...

    async def set_queue_attributes(self, params: dict[str, object]) -> None: ...

    async def start_message_move_task(self, params: dict[str, object]) -> StartMessageMoveTaskResult: ...

    async def tag_queue(self, params: dict[str, object]) -> None: ...

    async def untag_queue(self, params: dict[str, object]) -> None: ...

