from collections.abc import AsyncIterator
from typing import final

@final
class ByteStream:
    def __aiter__(self) -> AsyncIterator[bytes]: ...
    async def __anext__(self) -> bytes: ...
    async def read(self) -> bytes: ...



@final
class SQSClient:
    def __init__(
        self,
        *,
        region: str | None = None,
        profile: str | None = None,
        endpoint_url: str | None = None,
    ) -> None: ...

    async def add_permission(self, params: dict[str, object]) -> object: ...

    async def cancel_message_move_task(self, params: dict[str, object]) -> object: ...

    async def change_message_visibility(self, params: dict[str, object]) -> object: ...

    async def change_message_visibility_batch(self, params: dict[str, object]) -> object: ...

    async def create_queue(self, params: dict[str, object]) -> object: ...

    async def delete_message(self, params: dict[str, object]) -> object: ...

    async def delete_message_batch(self, params: dict[str, object]) -> object: ...

    async def delete_queue(self, params: dict[str, object]) -> object: ...

    async def get_queue_attributes(self, params: dict[str, object]) -> object: ...

    async def get_queue_url(self, params: dict[str, object]) -> object: ...

    async def list_dead_letter_source_queues(self, params: dict[str, object]) -> object: ...

    async def list_message_move_tasks(self, params: dict[str, object]) -> object: ...

    async def list_queues(self, params: dict[str, object]) -> object: ...

    async def list_queue_tags(self, params: dict[str, object]) -> object: ...

    async def purge_queue(self, params: dict[str, object]) -> object: ...

    async def receive_message(self, params: dict[str, object]) -> object: ...

    async def remove_permission(self, params: dict[str, object]) -> object: ...

    async def send_message(self, params: dict[str, object]) -> object: ...

    async def send_message_batch(self, params: dict[str, object]) -> object: ...

    async def set_queue_attributes(self, params: dict[str, object]) -> object: ...

    async def start_message_move_task(self, params: dict[str, object]) -> object: ...

    async def tag_queue(self, params: dict[str, object]) -> object: ...

    async def untag_queue(self, params: dict[str, object]) -> object: ...

