# Generated by rboto-codegen. DO NOT EDIT.
from __future__ import annotations



from ._native import SQSClient as NativeClient, CancelMessageMoveTaskResult, ChangeMessageVisibilityBatchResult, CreateQueueResult, DeleteMessageBatchResult, GetQueueAttributesResult, GetQueueUrlResult, ListDeadLetterSourceQueuesResult, ListMessageMoveTasksResult, ListQueueTagsResult, ListQueuesResult, ReceiveMessageResult, SendMessageBatchResult, SendMessageResult, StartMessageMoveTaskResult
from .types import (
    ChangeMessageVisibilityBatchRequestEntry,
    DeleteMessageBatchRequestEntry,
    MessageAttributeValue,
    MessageSystemAttributeName,
    MessageSystemAttributeNameForSends,
    MessageSystemAttributeValue,
    QueueAttributeName,
    SendMessageBatchRequestEntry,
)


class SQSClient:
    def __init__(
        self,
        *,
        region: str | None = None,
        profile: str | None = None,
        endpoint_url: str | None = None,
    ) -> None:
        self._native = NativeClient(
            region=region,
            profile=profile,
            endpoint_url=endpoint_url,
        )


    async def add_permission(
        self,
        *,
        queue_url: str,
        label: str,
        aws_account_ids: list[str],
        actions: list[str],
    ) -> None:
        params: dict[str, object] = {
            "queue_url": queue_url,
            "label": label,
            "aws_account_ids": aws_account_ids,
            "actions": actions,
        }
        await self._native.add_permission(params)
        return None


    async def cancel_message_move_task(
        self,
        *,
        task_handle: str,
    ) -> CancelMessageMoveTaskResult:
        params: dict[str, object] = {
            "task_handle": task_handle,
        }
        result = await self._native.cancel_message_move_task(params)
        return result


    async def change_message_visibility(
        self,
        *,
        queue_url: str,
        receipt_handle: str,
        visibility_timeout: int,
    ) -> None:
        params: dict[str, object] = {
            "queue_url": queue_url,
            "receipt_handle": receipt_handle,
            "visibility_timeout": visibility_timeout,
        }
        await self._native.change_message_visibility(params)
        return None


    async def change_message_visibility_batch(
        self,
        *,
        queue_url: str,
        entries: list[ChangeMessageVisibilityBatchRequestEntry],
    ) -> ChangeMessageVisibilityBatchResult:
        params: dict[str, object] = {
            "queue_url": queue_url,
            "entries": entries,
        }
        result = await self._native.change_message_visibility_batch(params)
        return result


    async def create_queue(
        self,
        *,
        queue_name: str,
        attributes: dict[QueueAttributeName, str] | None = None,
        tags: dict[str, str] | None = None,
    ) -> CreateQueueResult:
        params: dict[str, object] = {
            "queue_name": queue_name,
        }
        if attributes is not None:
            params["attributes"] = attributes
        if tags is not None:
            params["tags"] = tags
        result = await self._native.create_queue(params)
        return result


    async def delete_message(
        self,
        *,
        queue_url: str,
        receipt_handle: str,
    ) -> None:
        params: dict[str, object] = {
            "queue_url": queue_url,
            "receipt_handle": receipt_handle,
        }
        await self._native.delete_message(params)
        return None


    async def delete_message_batch(
        self,
        *,
        queue_url: str,
        entries: list[DeleteMessageBatchRequestEntry],
    ) -> DeleteMessageBatchResult:
        params: dict[str, object] = {
            "queue_url": queue_url,
            "entries": entries,
        }
        result = await self._native.delete_message_batch(params)
        return result


    async def delete_queue(
        self,
        *,
        queue_url: str,
    ) -> None:
        params: dict[str, object] = {
            "queue_url": queue_url,
        }
        await self._native.delete_queue(params)
        return None


    async def get_queue_attributes(
        self,
        *,
        queue_url: str,
        attribute_names: list[QueueAttributeName] | None = None,
    ) -> GetQueueAttributesResult:
        params: dict[str, object] = {
            "queue_url": queue_url,
        }
        if attribute_names is not None:
            params["attribute_names"] = attribute_names
        result = await self._native.get_queue_attributes(params)
        return result


    async def get_queue_url(
        self,
        *,
        queue_name: str,
        queue_owner_aws_account_id: str | None = None,
    ) -> GetQueueUrlResult:
        params: dict[str, object] = {
            "queue_name": queue_name,
        }
        if queue_owner_aws_account_id is not None:
            params["queue_owner_aws_account_id"] = queue_owner_aws_account_id
        result = await self._native.get_queue_url(params)
        return result


    async def list_dead_letter_source_queues(
        self,
        *,
        queue_url: str,
        next_token: str | None = None,
        max_results: int | None = None,
    ) -> ListDeadLetterSourceQueuesResult:
        params: dict[str, object] = {
            "queue_url": queue_url,
        }
        if next_token is not None:
            params["next_token"] = next_token
        if max_results is not None:
            params["max_results"] = max_results
        result = await self._native.list_dead_letter_source_queues(params)
        return result


    async def list_message_move_tasks(
        self,
        *,
        source_arn: str,
        max_results: int | None = None,
    ) -> ListMessageMoveTasksResult:
        params: dict[str, object] = {
            "source_arn": source_arn,
        }
        if max_results is not None:
            params["max_results"] = max_results
        result = await self._native.list_message_move_tasks(params)
        return result


    async def list_queues(
        self,
        *,
        queue_name_prefix: str | None = None,
        next_token: str | None = None,
        max_results: int | None = None,
    ) -> ListQueuesResult:
        params: dict[str, object] = {
        }
        if queue_name_prefix is not None:
            params["queue_name_prefix"] = queue_name_prefix
        if next_token is not None:
            params["next_token"] = next_token
        if max_results is not None:
            params["max_results"] = max_results
        result = await self._native.list_queues(params)
        return result


    async def list_queue_tags(
        self,
        *,
        queue_url: str,
    ) -> ListQueueTagsResult:
        params: dict[str, object] = {
            "queue_url": queue_url,
        }
        result = await self._native.list_queue_tags(params)
        return result


    async def purge_queue(
        self,
        *,
        queue_url: str,
    ) -> None:
        params: dict[str, object] = {
            "queue_url": queue_url,
        }
        await self._native.purge_queue(params)
        return None


    async def receive_message(
        self,
        *,
        queue_url: str,
        attribute_names: list[QueueAttributeName] | None = None,
        message_system_attribute_names: list[MessageSystemAttributeName] | None = None,
        message_attribute_names: list[str] | None = None,
        max_number_of_messages: int | None = None,
        visibility_timeout: int | None = None,
        wait_time_seconds: int | None = None,
        receive_request_attempt_id: str | None = None,
    ) -> ReceiveMessageResult:
        params: dict[str, object] = {
            "queue_url": queue_url,
        }
        if attribute_names is not None:
            params["attribute_names"] = attribute_names
        if message_system_attribute_names is not None:
            params["message_system_attribute_names"] = message_system_attribute_names
        if message_attribute_names is not None:
            params["message_attribute_names"] = message_attribute_names
        if max_number_of_messages is not None:
            params["max_number_of_messages"] = max_number_of_messages
        if visibility_timeout is not None:
            params["visibility_timeout"] = visibility_timeout
        if wait_time_seconds is not None:
            params["wait_time_seconds"] = wait_time_seconds
        if receive_request_attempt_id is not None:
            params["receive_request_attempt_id"] = receive_request_attempt_id
        result = await self._native.receive_message(params)
        return result


    async def remove_permission(
        self,
        *,
        queue_url: str,
        label: str,
    ) -> None:
        params: dict[str, object] = {
            "queue_url": queue_url,
            "label": label,
        }
        await self._native.remove_permission(params)
        return None


    async def send_message(
        self,
        *,
        queue_url: str,
        message_body: str,
        delay_seconds: int | None = None,
        message_attributes: dict[str, MessageAttributeValue] | None = None,
        message_system_attributes: dict[MessageSystemAttributeNameForSends, MessageSystemAttributeValue] | None = None,
        message_deduplication_id: str | None = None,
        message_group_id: str | None = None,
    ) -> SendMessageResult:
        params: dict[str, object] = {
            "queue_url": queue_url,
            "message_body": message_body,
        }
        if delay_seconds is not None:
            params["delay_seconds"] = delay_seconds
        if message_attributes is not None:
            params["message_attributes"] = message_attributes
        if message_system_attributes is not None:
            params["message_system_attributes"] = message_system_attributes
        if message_deduplication_id is not None:
            params["message_deduplication_id"] = message_deduplication_id
        if message_group_id is not None:
            params["message_group_id"] = message_group_id
        result = await self._native.send_message(params)
        return result


    async def send_message_batch(
        self,
        *,
        queue_url: str,
        entries: list[SendMessageBatchRequestEntry],
    ) -> SendMessageBatchResult:
        params: dict[str, object] = {
            "queue_url": queue_url,
            "entries": entries,
        }
        result = await self._native.send_message_batch(params)
        return result


    async def set_queue_attributes(
        self,
        *,
        queue_url: str,
        attributes: dict[QueueAttributeName, str],
    ) -> None:
        params: dict[str, object] = {
            "queue_url": queue_url,
            "attributes": attributes,
        }
        await self._native.set_queue_attributes(params)
        return None


    async def start_message_move_task(
        self,
        *,
        source_arn: str,
        destination_arn: str | None = None,
        max_number_of_messages_per_second: int | None = None,
    ) -> StartMessageMoveTaskResult:
        params: dict[str, object] = {
            "source_arn": source_arn,
        }
        if destination_arn is not None:
            params["destination_arn"] = destination_arn
        if max_number_of_messages_per_second is not None:
            params["max_number_of_messages_per_second"] = max_number_of_messages_per_second
        result = await self._native.start_message_move_task(params)
        return result


    async def tag_queue(
        self,
        *,
        queue_url: str,
        tags: dict[str, str],
    ) -> None:
        params: dict[str, object] = {
            "queue_url": queue_url,
            "tags": tags,
        }
        await self._native.tag_queue(params)
        return None


    async def untag_queue(
        self,
        *,
        queue_url: str,
        tag_keys: list[str],
    ) -> None:
        params: dict[str, object] = {
            "queue_url": queue_url,
            "tag_keys": tag_keys,
        }
        await self._native.untag_queue(params)
        return None

