# Generated by rboto-codegen. DO NOT EDIT.
from rboto.exceptions import ServiceError


class SQSError(ServiceError):
    """Base exception for errors returned by sqs."""


class BatchEntryIdsNotDistinctError(SQSError):
    """Modeled sqs error: BatchEntryIdsNotDistinct."""


class BatchRequestTooLongError(SQSError):
    """Modeled sqs error: BatchRequestTooLong."""


class EmptyBatchRequestError(SQSError):
    """Modeled sqs error: EmptyBatchRequest."""


class InvalidAddressError(SQSError):
    """Modeled sqs error: InvalidAddress."""


class InvalidAttributeNameError(SQSError):
    """Modeled sqs error: InvalidAttributeName."""


class InvalidAttributeValueError(SQSError):
    """Modeled sqs error: InvalidAttributeValue."""


class InvalidBatchEntryIdError(SQSError):
    """Modeled sqs error: InvalidBatchEntryId."""


class InvalidIdFormatError(SQSError):
    """Modeled sqs error: InvalidIdFormat."""


class InvalidMessageContentsError(SQSError):
    """Modeled sqs error: InvalidMessageContents."""


class InvalidSecurityError(SQSError):
    """Modeled sqs error: InvalidSecurity."""


class KmsAccessDeniedError(SQSError):
    """Modeled sqs error: KmsAccessDenied."""


class KmsDisabledError(SQSError):
    """Modeled sqs error: KmsDisabled."""


class KmsInvalidKeyUsageError(SQSError):
    """Modeled sqs error: KmsInvalidKeyUsage."""


class KmsInvalidStateError(SQSError):
    """Modeled sqs error: KmsInvalidState."""


class KmsNotFoundError(SQSError):
    """Modeled sqs error: KmsNotFound."""


class KmsOptInRequiredError(SQSError):
    """Modeled sqs error: KmsOptInRequired."""


class KmsThrottledError(SQSError):
    """Modeled sqs error: KmsThrottled."""


class MessageNotInflightError(SQSError):
    """Modeled sqs error: MessageNotInflight."""


class OverLimitError(SQSError):
    """Modeled sqs error: OverLimit."""


class PurgeQueueInProgressError(SQSError):
    """Modeled sqs error: PurgeQueueInProgress."""


class QueueDeletedRecentlyError(SQSError):
    """Modeled sqs error: QueueDeletedRecently."""


class QueueDoesNotExistError(SQSError):
    """Modeled sqs error: QueueDoesNotExist."""


class QueueNameExistsError(SQSError):
    """Modeled sqs error: QueueNameExists."""


class ReceiptHandleIsInvalidError(SQSError):
    """Modeled sqs error: ReceiptHandleIsInvalid."""


class RequestThrottledError(SQSError):
    """Modeled sqs error: RequestThrottled."""


class ResourceNotFoundError(SQSError):
    """Modeled sqs error: ResourceNotFoundException."""


class TooManyEntriesInBatchRequestError(SQSError):
    """Modeled sqs error: TooManyEntriesInBatchRequest."""


class UnsupportedOperationError(SQSError):
    """Modeled sqs error: UnsupportedOperation."""
