# Generated by rboto-codegen. DO NOT EDIT.
from __future__ import annotations

from typing import Literal, NotRequired, Required, TypeAlias, TypedDict

from ._native import ByteStream as ByteStream

MessageSystemAttributeName: TypeAlias = Literal['All', 'SenderId', 'SentTimestamp', 'ApproximateReceiveCount', 'ApproximateFirstReceiveTimestamp', 'SequenceNumber', 'MessageDeduplicationId', 'MessageGroupId', 'AWSTraceHeader', 'DeadLetterQueueSourceArn']
MessageSystemAttributeNameForSends: TypeAlias = Literal['AWSTraceHeader']
QueueAttributeName: TypeAlias = Literal['All', 'Policy', 'VisibilityTimeout', 'MaximumMessageSize', 'MessageRetentionPeriod', 'ApproximateNumberOfMessages', 'ApproximateNumberOfMessagesNotVisible', 'CreatedTimestamp', 'LastModifiedTimestamp', 'QueueArn', 'ApproximateNumberOfMessagesDelayed', 'DelaySeconds', 'ReceiveMessageWaitTimeSeconds', 'RedrivePolicy', 'FifoQueue', 'ContentBasedDeduplication', 'KmsMasterKeyId', 'KmsDataKeyReusePeriodSeconds', 'DeduplicationScope', 'FifoThroughputLimit', 'RedriveAllowPolicy', 'SqsManagedSseEnabled']

AddPermissionRequest = TypedDict(
    "AddPermissionRequest",
    {
    "queue_url": Required["str"],
    "label": Required["str"],
    "aws_account_ids": Required["list[str]"],
    "actions": Required["list[str]"],
    },
)

BatchResultErrorEntry = TypedDict(
    "BatchResultErrorEntry",
    {
    "id": Required["str"],
    "sender_fault": Required["bool"],
    "code": Required["str"],
    "message": NotRequired["str"],
    },
)

CancelMessageMoveTaskRequest = TypedDict(
    "CancelMessageMoveTaskRequest",
    {
    "task_handle": Required["str"],
    },
)

CancelMessageMoveTaskResult = TypedDict(
    "CancelMessageMoveTaskResult",
    {
    "approximate_number_of_messages_moved": Required["int"],
    },
)

ChangeMessageVisibilityBatchRequest = TypedDict(
    "ChangeMessageVisibilityBatchRequest",
    {
    "queue_url": Required["str"],
    "entries": Required["list[ChangeMessageVisibilityBatchRequestEntry]"],
    },
)

ChangeMessageVisibilityBatchRequestEntry = TypedDict(
    "ChangeMessageVisibilityBatchRequestEntry",
    {
    "id": Required["str"],
    "receipt_handle": Required["str"],
    "visibility_timeout": NotRequired["int"],
    },
)

ChangeMessageVisibilityBatchResult = TypedDict(
    "ChangeMessageVisibilityBatchResult",
    {
    "successful": Required["list[ChangeMessageVisibilityBatchResultEntry]"],
    "failed": Required["list[BatchResultErrorEntry]"],
    },
)

ChangeMessageVisibilityBatchResultEntry = TypedDict(
    "ChangeMessageVisibilityBatchResultEntry",
    {
    "id": Required["str"],
    },
)

ChangeMessageVisibilityRequest = TypedDict(
    "ChangeMessageVisibilityRequest",
    {
    "queue_url": Required["str"],
    "receipt_handle": Required["str"],
    "visibility_timeout": Required["int"],
    },
)

CreateQueueRequest = TypedDict(
    "CreateQueueRequest",
    {
    "queue_name": Required["str"],
    "attributes": NotRequired["dict[QueueAttributeName, str]"],
    "tags": NotRequired["dict[str, str]"],
    },
)

CreateQueueResult = TypedDict(
    "CreateQueueResult",
    {
    "queue_url": NotRequired["str"],
    },
)

DeleteMessageBatchRequest = TypedDict(
    "DeleteMessageBatchRequest",
    {
    "queue_url": Required["str"],
    "entries": Required["list[DeleteMessageBatchRequestEntry]"],
    },
)

DeleteMessageBatchRequestEntry = TypedDict(
    "DeleteMessageBatchRequestEntry",
    {
    "id": Required["str"],
    "receipt_handle": Required["str"],
    },
)

DeleteMessageBatchResult = TypedDict(
    "DeleteMessageBatchResult",
    {
    "successful": Required["list[DeleteMessageBatchResultEntry]"],
    "failed": Required["list[BatchResultErrorEntry]"],
    },
)

DeleteMessageBatchResultEntry = TypedDict(
    "DeleteMessageBatchResultEntry",
    {
    "id": Required["str"],
    },
)

DeleteMessageRequest = TypedDict(
    "DeleteMessageRequest",
    {
    "queue_url": Required["str"],
    "receipt_handle": Required["str"],
    },
)

DeleteQueueRequest = TypedDict(
    "DeleteQueueRequest",
    {
    "queue_url": Required["str"],
    },
)

GetQueueAttributesRequest = TypedDict(
    "GetQueueAttributesRequest",
    {
    "queue_url": Required["str"],
    "attribute_names": NotRequired["list[QueueAttributeName]"],
    },
)

GetQueueAttributesResult = TypedDict(
    "GetQueueAttributesResult",
    {
    "attributes": NotRequired["dict[QueueAttributeName, str]"],
    },
)

GetQueueUrlRequest = TypedDict(
    "GetQueueUrlRequest",
    {
    "queue_name": Required["str"],
    "queue_owner_aws_account_id": NotRequired["str"],
    },
)

GetQueueUrlResult = TypedDict(
    "GetQueueUrlResult",
    {
    "queue_url": NotRequired["str"],
    },
)

ListDeadLetterSourceQueuesRequest = TypedDict(
    "ListDeadLetterSourceQueuesRequest",
    {
    "queue_url": Required["str"],
    "next_token": NotRequired["str"],
    "max_results": NotRequired["int"],
    },
)

ListDeadLetterSourceQueuesResult = TypedDict(
    "ListDeadLetterSourceQueuesResult",
    {
    "queue_urls": Required["list[str]"],
    "next_token": NotRequired["str"],
    },
)

ListMessageMoveTasksRequest = TypedDict(
    "ListMessageMoveTasksRequest",
    {
    "source_arn": Required["str"],
    "max_results": NotRequired["int"],
    },
)

ListMessageMoveTasksResult = TypedDict(
    "ListMessageMoveTasksResult",
    {
    "results": NotRequired["list[ListMessageMoveTasksResultEntry]"],
    },
)

ListMessageMoveTasksResultEntry = TypedDict(
    "ListMessageMoveTasksResultEntry",
    {
    "task_handle": NotRequired["str"],
    "status": NotRequired["str"],
    "source_arn": NotRequired["str"],
    "destination_arn": NotRequired["str"],
    "max_number_of_messages_per_second": NotRequired["int"],
    "approximate_number_of_messages_moved": NotRequired["int"],
    "approximate_number_of_messages_to_move": NotRequired["int"],
    "failure_reason": NotRequired["str"],
    "started_timestamp": NotRequired["int"],
    },
)

ListQueueTagsRequest = TypedDict(
    "ListQueueTagsRequest",
    {
    "queue_url": Required["str"],
    },
)

ListQueueTagsResult = TypedDict(
    "ListQueueTagsResult",
    {
    "tags": NotRequired["dict[str, str]"],
    },
)

ListQueuesRequest = TypedDict(
    "ListQueuesRequest",
    {
    "queue_name_prefix": NotRequired["str"],
    "next_token": NotRequired["str"],
    "max_results": NotRequired["int"],
    },
)

ListQueuesResult = TypedDict(
    "ListQueuesResult",
    {
    "queue_urls": NotRequired["list[str]"],
    "next_token": NotRequired["str"],
    },
)

Message = TypedDict(
    "Message",
    {
    "message_id": NotRequired["str"],
    "receipt_handle": NotRequired["str"],
    "md5_of_body": NotRequired["str"],
    "body": NotRequired["str"],
    "attributes": NotRequired["dict[MessageSystemAttributeName, str]"],
    "md5_of_message_attributes": NotRequired["str"],
    "message_attributes": NotRequired["dict[str, MessageAttributeValue]"],
    },
)

MessageAttributeValue = TypedDict(
    "MessageAttributeValue",
    {
    "string_value": NotRequired["str"],
    "binary_value": NotRequired["bytes"],
    "string_list_values": NotRequired["list[str]"],
    "binary_list_values": NotRequired["list[bytes]"],
    "data_type": Required["str"],
    },
)

MessageSystemAttributeValue = TypedDict(
    "MessageSystemAttributeValue",
    {
    "string_value": NotRequired["str"],
    "binary_value": NotRequired["bytes"],
    "string_list_values": NotRequired["list[str]"],
    "binary_list_values": NotRequired["list[bytes]"],
    "data_type": Required["str"],
    },
)

PurgeQueueRequest = TypedDict(
    "PurgeQueueRequest",
    {
    "queue_url": Required["str"],
    },
)

ReceiveMessageRequest = TypedDict(
    "ReceiveMessageRequest",
    {
    "queue_url": Required["str"],
    "attribute_names": NotRequired["list[QueueAttributeName]"],
    "message_system_attribute_names": NotRequired["list[MessageSystemAttributeName]"],
    "message_attribute_names": NotRequired["list[str]"],
    "max_number_of_messages": NotRequired["int"],
    "visibility_timeout": NotRequired["int"],
    "wait_time_seconds": NotRequired["int"],
    "receive_request_attempt_id": NotRequired["str"],
    },
)

ReceiveMessageResult = TypedDict(
    "ReceiveMessageResult",
    {
    "messages": NotRequired["list[Message]"],
    },
)

RemovePermissionRequest = TypedDict(
    "RemovePermissionRequest",
    {
    "queue_url": Required["str"],
    "label": Required["str"],
    },
)

SendMessageBatchRequest = TypedDict(
    "SendMessageBatchRequest",
    {
    "queue_url": Required["str"],
    "entries": Required["list[SendMessageBatchRequestEntry]"],
    },
)

SendMessageBatchRequestEntry = TypedDict(
    "SendMessageBatchRequestEntry",
    {
    "id": Required["str"],
    "message_body": Required["str"],
    "delay_seconds": NotRequired["int"],
    "message_attributes": NotRequired["dict[str, MessageAttributeValue]"],
    "message_system_attributes": NotRequired["dict[MessageSystemAttributeNameForSends, MessageSystemAttributeValue]"],
    "message_deduplication_id": NotRequired["str"],
    "message_group_id": NotRequired["str"],
    },
)

SendMessageBatchResult = TypedDict(
    "SendMessageBatchResult",
    {
    "successful": Required["list[SendMessageBatchResultEntry]"],
    "failed": Required["list[BatchResultErrorEntry]"],
    },
)

SendMessageBatchResultEntry = TypedDict(
    "SendMessageBatchResultEntry",
    {
    "id": Required["str"],
    "message_id": Required["str"],
    "md5_of_message_body": Required["str"],
    "md5_of_message_attributes": NotRequired["str"],
    "md5_of_message_system_attributes": NotRequired["str"],
    "sequence_number": NotRequired["str"],
    },
)

SendMessageRequest = TypedDict(
    "SendMessageRequest",
    {
    "queue_url": Required["str"],
    "message_body": Required["str"],
    "delay_seconds": NotRequired["int"],
    "message_attributes": NotRequired["dict[str, MessageAttributeValue]"],
    "message_system_attributes": NotRequired["dict[MessageSystemAttributeNameForSends, MessageSystemAttributeValue]"],
    "message_deduplication_id": NotRequired["str"],
    "message_group_id": NotRequired["str"],
    },
)

SendMessageResult = TypedDict(
    "SendMessageResult",
    {
    "md5_of_message_body": NotRequired["str"],
    "md5_of_message_attributes": NotRequired["str"],
    "md5_of_message_system_attributes": NotRequired["str"],
    "message_id": NotRequired["str"],
    "sequence_number": NotRequired["str"],
    },
)

SetQueueAttributesRequest = TypedDict(
    "SetQueueAttributesRequest",
    {
    "queue_url": Required["str"],
    "attributes": Required["dict[QueueAttributeName, str]"],
    },
)

StartMessageMoveTaskRequest = TypedDict(
    "StartMessageMoveTaskRequest",
    {
    "source_arn": Required["str"],
    "destination_arn": NotRequired["str"],
    "max_number_of_messages_per_second": NotRequired["int"],
    },
)

StartMessageMoveTaskResult = TypedDict(
    "StartMessageMoveTaskResult",
    {
    "task_handle": NotRequired["str"],
    },
)

TagQueueRequest = TypedDict(
    "TagQueueRequest",
    {
    "queue_url": Required["str"],
    "tags": Required["dict[str, str]"],
    },
)

UntagQueueRequest = TypedDict(
    "UntagQueueRequest",
    {
    "queue_url": Required["str"],
    "tag_keys": Required["list[str]"],
    },
)
