// Generated by rboto-codegen. DO NOT EDIT.
#![allow(
    clippy::needless_borrow,
    dead_code,
    deprecated,
    unused_mut,
    unused_variables
)]
use super::*;

fn batch_result_error_entry_from_py(
    value: &Bound<'_, PyAny>,
) -> PyResult<aws_sdk_sqs::types::BatchResultErrorEntry> {
    let values = value.cast::<PyDict>()?;
    let mut builder = aws_sdk_sqs::types::BatchResultErrorEntry::builder();
    if let Some(value) = dict_value(values, "id")? {
        let converted_1: String = value.extract()?;
        builder = builder.set_id(Some(converted_1));
    }
    if let Some(value) = dict_value(values, "sender_fault")? {
        let converted_2: bool = value.extract()?;
        builder = builder.set_sender_fault(Some(converted_2));
    }
    if let Some(value) = dict_value(values, "code")? {
        let converted_3: String = value.extract()?;
        builder = builder.set_code(Some(converted_3));
    }
    if let Some(value) = dict_value(values, "message")? {
        let converted_4: String = value.extract()?;
        builder = builder.set_message(Some(converted_4));
    }
    builder
        .build()
        .map_err(|error| PyValueError::new_err(error.to_string()))
}

fn batch_result_error_entry_to_py(
    py: Python<'_>,
    value: &aws_sdk_sqs::types::BatchResultErrorEntry,
) -> PyResult<Py<PyAny>> {
    let result = PyDict::new(py);
    let converted_5 = &value.id.as_str().into_py_any(py)?;
    result.set_item("id", converted_5)?;
    let converted_6 = (&value.sender_fault).to_owned().into_py_any(py)?;
    result.set_item("sender_fault", converted_6)?;
    let converted_7 = &value.code.as_str().into_py_any(py)?;
    result.set_item("code", converted_7)?;
    if let Some(value) = &value.message {
        let converted_8 = value.as_str().into_py_any(py)?;
        result.set_item("message", converted_8)?;
    } else {
        result.set_item("message", py.None())?;
    }
    Ok(result.into_any().unbind())
}

fn change_message_visibility_batch_request_entry_from_py(
    value: &Bound<'_, PyAny>,
) -> PyResult<aws_sdk_sqs::types::ChangeMessageVisibilityBatchRequestEntry> {
    let values = value.cast::<PyDict>()?;
    let mut builder = aws_sdk_sqs::types::ChangeMessageVisibilityBatchRequestEntry::builder();
    if let Some(value) = dict_value(values, "id")? {
        let converted_9: String = value.extract()?;
        builder = builder.set_id(Some(converted_9));
    }
    if let Some(value) = dict_value(values, "receipt_handle")? {
        let converted_10: String = value.extract()?;
        builder = builder.set_receipt_handle(Some(converted_10));
    }
    if let Some(value) = dict_value(values, "visibility_timeout")? {
        let converted_11: i32 = value.extract()?;
        builder = builder.set_visibility_timeout(Some(converted_11));
    }
    builder
        .build()
        .map_err(|error| PyValueError::new_err(error.to_string()))
}

fn change_message_visibility_batch_request_entry_to_py(
    py: Python<'_>,
    value: &aws_sdk_sqs::types::ChangeMessageVisibilityBatchRequestEntry,
) -> PyResult<Py<PyAny>> {
    let result = PyDict::new(py);
    let converted_12 = &value.id.as_str().into_py_any(py)?;
    result.set_item("id", converted_12)?;
    let converted_13 = &value.receipt_handle.as_str().into_py_any(py)?;
    result.set_item("receipt_handle", converted_13)?;
    if let Some(value) = &value.visibility_timeout {
        let converted_14 = (value).to_owned().into_py_any(py)?;
        result.set_item("visibility_timeout", converted_14)?;
    } else {
        result.set_item("visibility_timeout", py.None())?;
    }
    Ok(result.into_any().unbind())
}

fn change_message_visibility_batch_result_entry_from_py(
    value: &Bound<'_, PyAny>,
) -> PyResult<aws_sdk_sqs::types::ChangeMessageVisibilityBatchResultEntry> {
    let values = value.cast::<PyDict>()?;
    let mut builder = aws_sdk_sqs::types::ChangeMessageVisibilityBatchResultEntry::builder();
    if let Some(value) = dict_value(values, "id")? {
        let converted_15: String = value.extract()?;
        builder = builder.set_id(Some(converted_15));
    }
    builder
        .build()
        .map_err(|error| PyValueError::new_err(error.to_string()))
}

fn change_message_visibility_batch_result_entry_to_py(
    py: Python<'_>,
    value: &aws_sdk_sqs::types::ChangeMessageVisibilityBatchResultEntry,
) -> PyResult<Py<PyAny>> {
    let result = PyDict::new(py);
    let converted_16 = &value.id.as_str().into_py_any(py)?;
    result.set_item("id", converted_16)?;
    Ok(result.into_any().unbind())
}

fn delete_message_batch_request_entry_from_py(
    value: &Bound<'_, PyAny>,
) -> PyResult<aws_sdk_sqs::types::DeleteMessageBatchRequestEntry> {
    let values = value.cast::<PyDict>()?;
    let mut builder = aws_sdk_sqs::types::DeleteMessageBatchRequestEntry::builder();
    if let Some(value) = dict_value(values, "id")? {
        let converted_17: String = value.extract()?;
        builder = builder.set_id(Some(converted_17));
    }
    if let Some(value) = dict_value(values, "receipt_handle")? {
        let converted_18: String = value.extract()?;
        builder = builder.set_receipt_handle(Some(converted_18));
    }
    builder
        .build()
        .map_err(|error| PyValueError::new_err(error.to_string()))
}

fn delete_message_batch_request_entry_to_py(
    py: Python<'_>,
    value: &aws_sdk_sqs::types::DeleteMessageBatchRequestEntry,
) -> PyResult<Py<PyAny>> {
    let result = PyDict::new(py);
    let converted_19 = &value.id.as_str().into_py_any(py)?;
    result.set_item("id", converted_19)?;
    let converted_20 = &value.receipt_handle.as_str().into_py_any(py)?;
    result.set_item("receipt_handle", converted_20)?;
    Ok(result.into_any().unbind())
}

fn delete_message_batch_result_entry_from_py(
    value: &Bound<'_, PyAny>,
) -> PyResult<aws_sdk_sqs::types::DeleteMessageBatchResultEntry> {
    let values = value.cast::<PyDict>()?;
    let mut builder = aws_sdk_sqs::types::DeleteMessageBatchResultEntry::builder();
    if let Some(value) = dict_value(values, "id")? {
        let converted_21: String = value.extract()?;
        builder = builder.set_id(Some(converted_21));
    }
    builder
        .build()
        .map_err(|error| PyValueError::new_err(error.to_string()))
}

fn delete_message_batch_result_entry_to_py(
    py: Python<'_>,
    value: &aws_sdk_sqs::types::DeleteMessageBatchResultEntry,
) -> PyResult<Py<PyAny>> {
    let result = PyDict::new(py);
    let converted_22 = &value.id.as_str().into_py_any(py)?;
    result.set_item("id", converted_22)?;
    Ok(result.into_any().unbind())
}

fn list_message_move_tasks_result_entry_from_py(
    value: &Bound<'_, PyAny>,
) -> PyResult<aws_sdk_sqs::types::ListMessageMoveTasksResultEntry> {
    let values = value.cast::<PyDict>()?;
    let mut builder = aws_sdk_sqs::types::ListMessageMoveTasksResultEntry::builder();
    if let Some(value) = dict_value(values, "task_handle")? {
        let converted_23: String = value.extract()?;
        builder = builder.set_task_handle(Some(converted_23));
    }
    if let Some(value) = dict_value(values, "status")? {
        let converted_24: String = value.extract()?;
        builder = builder.set_status(Some(converted_24));
    }
    if let Some(value) = dict_value(values, "source_arn")? {
        let converted_25: String = value.extract()?;
        builder = builder.set_source_arn(Some(converted_25));
    }
    if let Some(value) = dict_value(values, "destination_arn")? {
        let converted_26: String = value.extract()?;
        builder = builder.set_destination_arn(Some(converted_26));
    }
    if let Some(value) = dict_value(values, "max_number_of_messages_per_second")? {
        let converted_27: i32 = value.extract()?;
        builder = builder.set_max_number_of_messages_per_second(Some(converted_27));
    }
    if let Some(value) = dict_value(values, "approximate_number_of_messages_moved")? {
        let converted_28: i64 = value.extract()?;
        builder = builder.set_approximate_number_of_messages_moved(Some(converted_28));
    }
    if let Some(value) = dict_value(values, "approximate_number_of_messages_to_move")? {
        let converted_29: i64 = value.extract()?;
        builder = builder.set_approximate_number_of_messages_to_move(Some(converted_29));
    }
    if let Some(value) = dict_value(values, "failure_reason")? {
        let converted_30: String = value.extract()?;
        builder = builder.set_failure_reason(Some(converted_30));
    }
    if let Some(value) = dict_value(values, "started_timestamp")? {
        let converted_31: i64 = value.extract()?;
        builder = builder.set_started_timestamp(Some(converted_31));
    }
    Ok(builder.build())
}

fn list_message_move_tasks_result_entry_to_py(
    py: Python<'_>,
    value: &aws_sdk_sqs::types::ListMessageMoveTasksResultEntry,
) -> PyResult<Py<PyAny>> {
    let result = PyDict::new(py);
    if let Some(value) = &value.task_handle {
        let converted_32 = value.as_str().into_py_any(py)?;
        result.set_item("task_handle", converted_32)?;
    } else {
        result.set_item("task_handle", py.None())?;
    }
    if let Some(value) = &value.status {
        let converted_33 = value.as_str().into_py_any(py)?;
        result.set_item("status", converted_33)?;
    } else {
        result.set_item("status", py.None())?;
    }
    if let Some(value) = &value.source_arn {
        let converted_34 = value.as_str().into_py_any(py)?;
        result.set_item("source_arn", converted_34)?;
    } else {
        result.set_item("source_arn", py.None())?;
    }
    if let Some(value) = &value.destination_arn {
        let converted_35 = value.as_str().into_py_any(py)?;
        result.set_item("destination_arn", converted_35)?;
    } else {
        result.set_item("destination_arn", py.None())?;
    }
    if let Some(value) = &value.max_number_of_messages_per_second {
        let converted_36 = (value).to_owned().into_py_any(py)?;
        result.set_item("max_number_of_messages_per_second", converted_36)?;
    } else {
        result.set_item("max_number_of_messages_per_second", py.None())?;
    }
    let converted_37 = (&value.approximate_number_of_messages_moved)
        .to_owned()
        .into_py_any(py)?;
    result.set_item("approximate_number_of_messages_moved", converted_37)?;
    if let Some(value) = &value.approximate_number_of_messages_to_move {
        let converted_38 = (value).to_owned().into_py_any(py)?;
        result.set_item("approximate_number_of_messages_to_move", converted_38)?;
    } else {
        result.set_item("approximate_number_of_messages_to_move", py.None())?;
    }
    if let Some(value) = &value.failure_reason {
        let converted_39 = value.as_str().into_py_any(py)?;
        result.set_item("failure_reason", converted_39)?;
    } else {
        result.set_item("failure_reason", py.None())?;
    }
    let converted_40 = (&value.started_timestamp).to_owned().into_py_any(py)?;
    result.set_item("started_timestamp", converted_40)?;
    Ok(result.into_any().unbind())
}

fn message_from_py(value: &Bound<'_, PyAny>) -> PyResult<aws_sdk_sqs::types::Message> {
    let values = value.cast::<PyDict>()?;
    let mut builder = aws_sdk_sqs::types::Message::builder();
    if let Some(value) = dict_value(values, "message_id")? {
        let converted_41: String = value.extract()?;
        builder = builder.set_message_id(Some(converted_41));
    }
    if let Some(value) = dict_value(values, "receipt_handle")? {
        let converted_42: String = value.extract()?;
        builder = builder.set_receipt_handle(Some(converted_42));
    }
    if let Some(value) = dict_value(values, "md5_of_body")? {
        let converted_43: String = value.extract()?;
        builder = builder.set_md5_of_body(Some(converted_43));
    }
    if let Some(value) = dict_value(values, "body")? {
        let converted_44: String = value.extract()?;
        builder = builder.set_body(Some(converted_44));
    }
    if let Some(value) = dict_value(values, "attributes")? {
        let mapping_46 = value.cast::<PyDict>()?;
        let mut converted_45 = HashMap::new();
        for (key_47, value_48) in mapping_46.iter() {
            let enum_value_51: String = key_47.extract()?;
            let converted_key_49 =
                aws_sdk_sqs::types::MessageSystemAttributeName::from(enum_value_51.as_str());
            let converted_value_50: String = value_48.extract()?;
            converted_45.insert(converted_key_49, converted_value_50);
        }
        builder = builder.set_attributes(Some(converted_45));
    }
    if let Some(value) = dict_value(values, "md5_of_message_attributes")? {
        let converted_52: String = value.extract()?;
        builder = builder.set_md5_of_message_attributes(Some(converted_52));
    }
    if let Some(value) = dict_value(values, "message_attributes")? {
        let mapping_54 = value.cast::<PyDict>()?;
        let mut converted_53 = HashMap::new();
        for (key_55, value_56) in mapping_54.iter() {
            let converted_key_57: String = key_55.extract()?;
            let converted_value_58 = message_attribute_value_from_py(&value_56)?;
            converted_53.insert(converted_key_57, converted_value_58);
        }
        builder = builder.set_message_attributes(Some(converted_53));
    }
    Ok(builder.build())
}

fn message_to_py(py: Python<'_>, value: &aws_sdk_sqs::types::Message) -> PyResult<Py<PyAny>> {
    let result = PyDict::new(py);
    if let Some(value) = &value.message_id {
        let converted_59 = value.as_str().into_py_any(py)?;
        result.set_item("message_id", converted_59)?;
    } else {
        result.set_item("message_id", py.None())?;
    }
    if let Some(value) = &value.receipt_handle {
        let converted_60 = value.as_str().into_py_any(py)?;
        result.set_item("receipt_handle", converted_60)?;
    } else {
        result.set_item("receipt_handle", py.None())?;
    }
    if let Some(value) = &value.md5_of_body {
        let converted_61 = value.as_str().into_py_any(py)?;
        result.set_item("md5_of_body", converted_61)?;
    } else {
        result.set_item("md5_of_body", py.None())?;
    }
    if let Some(value) = &value.body {
        let converted_62 = value.as_str().into_py_any(py)?;
        result.set_item("body", converted_62)?;
    } else {
        result.set_item("body", py.None())?;
    }
    if let Some(value) = &value.attributes {
        let converted_63_dict = PyDict::new(py);
        for (key_64, value_65) in value {
            let converted_key_66 = key_64.as_str().into_py_any(py)?;
            let converted_value_67 = value_65.as_str().into_py_any(py)?;
            converted_63_dict.set_item(converted_key_66, converted_value_67)?;
        }
        let converted_63 = converted_63_dict.into_any().unbind();
        result.set_item("attributes", converted_63)?;
    } else {
        result.set_item("attributes", py.None())?;
    }
    if let Some(value) = &value.md5_of_message_attributes {
        let converted_68 = value.as_str().into_py_any(py)?;
        result.set_item("md5_of_message_attributes", converted_68)?;
    } else {
        result.set_item("md5_of_message_attributes", py.None())?;
    }
    if let Some(value) = &value.message_attributes {
        let converted_69_dict = PyDict::new(py);
        for (key_70, value_71) in value {
            let converted_key_72 = key_70.as_str().into_py_any(py)?;
            let converted_value_73 = message_attribute_value_to_py(py, value_71)?;
            converted_69_dict.set_item(converted_key_72, converted_value_73)?;
        }
        let converted_69 = converted_69_dict.into_any().unbind();
        result.set_item("message_attributes", converted_69)?;
    } else {
        result.set_item("message_attributes", py.None())?;
    }
    Ok(result.into_any().unbind())
}

fn message_attribute_value_from_py(
    value: &Bound<'_, PyAny>,
) -> PyResult<aws_sdk_sqs::types::MessageAttributeValue> {
    let values = value.cast::<PyDict>()?;
    let mut builder = aws_sdk_sqs::types::MessageAttributeValue::builder();
    if let Some(value) = dict_value(values, "string_value")? {
        let converted_74: String = value.extract()?;
        builder = builder.set_string_value(Some(converted_74));
    }
    if let Some(value) = dict_value(values, "binary_value")? {
        let bytes_76: Vec<u8> = value.extract()?;
        let converted_75 = ::aws_smithy_types::Blob::new(bytes_76);
        builder = builder.set_binary_value(Some(converted_75));
    }
    if let Some(value) = dict_value(values, "string_list_values")? {
        let mut converted_77 = Vec::new();
        for item_result_78 in value.try_iter()? {
            let item_79 = item_result_78?;
            let converted_item_80: String = item_79.extract()?;
            converted_77.push(converted_item_80);
        }
        builder = builder.set_string_list_values(Some(converted_77));
    }
    if let Some(value) = dict_value(values, "binary_list_values")? {
        let mut converted_81 = Vec::new();
        for item_result_82 in value.try_iter()? {
            let item_83 = item_result_82?;
            let bytes_85: Vec<u8> = item_83.extract()?;
            let converted_item_84 = ::aws_smithy_types::Blob::new(bytes_85);
            converted_81.push(converted_item_84);
        }
        builder = builder.set_binary_list_values(Some(converted_81));
    }
    if let Some(value) = dict_value(values, "data_type")? {
        let converted_86: String = value.extract()?;
        builder = builder.set_data_type(Some(converted_86));
    }
    builder
        .build()
        .map_err(|error| PyValueError::new_err(error.to_string()))
}

fn message_attribute_value_to_py(
    py: Python<'_>,
    value: &aws_sdk_sqs::types::MessageAttributeValue,
) -> PyResult<Py<PyAny>> {
    let result = PyDict::new(py);
    if let Some(value) = &value.string_value {
        let converted_87 = value.as_str().into_py_any(py)?;
        result.set_item("string_value", converted_87)?;
    } else {
        result.set_item("string_value", py.None())?;
    }
    if let Some(value) = &value.binary_value {
        let converted_88 = PyBytes::new(py, value.as_ref()).into_any().unbind();
        result.set_item("binary_value", converted_88)?;
    } else {
        result.set_item("binary_value", py.None())?;
    }
    if let Some(value) = &value.string_list_values {
        let converted_89_list = PyList::empty(py);
        for item_90 in value {
            let converted_item_91 = item_90.as_str().into_py_any(py)?;
            converted_89_list.append(converted_item_91)?;
        }
        let converted_89 = converted_89_list.into_any().unbind();
        result.set_item("string_list_values", converted_89)?;
    } else {
        result.set_item("string_list_values", py.None())?;
    }
    if let Some(value) = &value.binary_list_values {
        let converted_92_list = PyList::empty(py);
        for item_93 in value {
            let converted_item_94 = PyBytes::new(py, item_93.as_ref()).into_any().unbind();
            converted_92_list.append(converted_item_94)?;
        }
        let converted_92 = converted_92_list.into_any().unbind();
        result.set_item("binary_list_values", converted_92)?;
    } else {
        result.set_item("binary_list_values", py.None())?;
    }
    let converted_95 = &value.data_type.as_str().into_py_any(py)?;
    result.set_item("data_type", converted_95)?;
    Ok(result.into_any().unbind())
}

fn message_system_attribute_value_from_py(
    value: &Bound<'_, PyAny>,
) -> PyResult<aws_sdk_sqs::types::MessageSystemAttributeValue> {
    let values = value.cast::<PyDict>()?;
    let mut builder = aws_sdk_sqs::types::MessageSystemAttributeValue::builder();
    if let Some(value) = dict_value(values, "string_value")? {
        let converted_96: String = value.extract()?;
        builder = builder.set_string_value(Some(converted_96));
    }
    if let Some(value) = dict_value(values, "binary_value")? {
        let bytes_98: Vec<u8> = value.extract()?;
        let converted_97 = ::aws_smithy_types::Blob::new(bytes_98);
        builder = builder.set_binary_value(Some(converted_97));
    }
    if let Some(value) = dict_value(values, "string_list_values")? {
        let mut converted_99 = Vec::new();
        for item_result_100 in value.try_iter()? {
            let item_101 = item_result_100?;
            let converted_item_102: String = item_101.extract()?;
            converted_99.push(converted_item_102);
        }
        builder = builder.set_string_list_values(Some(converted_99));
    }
    if let Some(value) = dict_value(values, "binary_list_values")? {
        let mut converted_103 = Vec::new();
        for item_result_104 in value.try_iter()? {
            let item_105 = item_result_104?;
            let bytes_107: Vec<u8> = item_105.extract()?;
            let converted_item_106 = ::aws_smithy_types::Blob::new(bytes_107);
            converted_103.push(converted_item_106);
        }
        builder = builder.set_binary_list_values(Some(converted_103));
    }
    if let Some(value) = dict_value(values, "data_type")? {
        let converted_108: String = value.extract()?;
        builder = builder.set_data_type(Some(converted_108));
    }
    builder
        .build()
        .map_err(|error| PyValueError::new_err(error.to_string()))
}

fn message_system_attribute_value_to_py(
    py: Python<'_>,
    value: &aws_sdk_sqs::types::MessageSystemAttributeValue,
) -> PyResult<Py<PyAny>> {
    let result = PyDict::new(py);
    if let Some(value) = &value.string_value {
        let converted_109 = value.as_str().into_py_any(py)?;
        result.set_item("string_value", converted_109)?;
    } else {
        result.set_item("string_value", py.None())?;
    }
    if let Some(value) = &value.binary_value {
        let converted_110 = PyBytes::new(py, value.as_ref()).into_any().unbind();
        result.set_item("binary_value", converted_110)?;
    } else {
        result.set_item("binary_value", py.None())?;
    }
    if let Some(value) = &value.string_list_values {
        let converted_111_list = PyList::empty(py);
        for item_112 in value {
            let converted_item_113 = item_112.as_str().into_py_any(py)?;
            converted_111_list.append(converted_item_113)?;
        }
        let converted_111 = converted_111_list.into_any().unbind();
        result.set_item("string_list_values", converted_111)?;
    } else {
        result.set_item("string_list_values", py.None())?;
    }
    if let Some(value) = &value.binary_list_values {
        let converted_114_list = PyList::empty(py);
        for item_115 in value {
            let converted_item_116 = PyBytes::new(py, item_115.as_ref()).into_any().unbind();
            converted_114_list.append(converted_item_116)?;
        }
        let converted_114 = converted_114_list.into_any().unbind();
        result.set_item("binary_list_values", converted_114)?;
    } else {
        result.set_item("binary_list_values", py.None())?;
    }
    let converted_117 = &value.data_type.as_str().into_py_any(py)?;
    result.set_item("data_type", converted_117)?;
    Ok(result.into_any().unbind())
}

fn send_message_batch_request_entry_from_py(
    value: &Bound<'_, PyAny>,
) -> PyResult<aws_sdk_sqs::types::SendMessageBatchRequestEntry> {
    let values = value.cast::<PyDict>()?;
    let mut builder = aws_sdk_sqs::types::SendMessageBatchRequestEntry::builder();
    if let Some(value) = dict_value(values, "id")? {
        let converted_118: String = value.extract()?;
        builder = builder.set_id(Some(converted_118));
    }
    if let Some(value) = dict_value(values, "message_body")? {
        let converted_119: String = value.extract()?;
        builder = builder.set_message_body(Some(converted_119));
    }
    if let Some(value) = dict_value(values, "delay_seconds")? {
        let converted_120: i32 = value.extract()?;
        builder = builder.set_delay_seconds(Some(converted_120));
    }
    if let Some(value) = dict_value(values, "message_attributes")? {
        let mapping_122 = value.cast::<PyDict>()?;
        let mut converted_121 = HashMap::new();
        for (key_123, value_124) in mapping_122.iter() {
            let converted_key_125: String = key_123.extract()?;
            let converted_value_126 = message_attribute_value_from_py(&value_124)?;
            converted_121.insert(converted_key_125, converted_value_126);
        }
        builder = builder.set_message_attributes(Some(converted_121));
    }
    if let Some(value) = dict_value(values, "message_system_attributes")? {
        let mapping_128 = value.cast::<PyDict>()?;
        let mut converted_127 = HashMap::new();
        for (key_129, value_130) in mapping_128.iter() {
            let enum_value_133: String = key_129.extract()?;
            let converted_key_131 = aws_sdk_sqs::types::MessageSystemAttributeNameForSends::from(
                enum_value_133.as_str(),
            );
            let converted_value_132 = message_system_attribute_value_from_py(&value_130)?;
            converted_127.insert(converted_key_131, converted_value_132);
        }
        builder = builder.set_message_system_attributes(Some(converted_127));
    }
    if let Some(value) = dict_value(values, "message_deduplication_id")? {
        let converted_134: String = value.extract()?;
        builder = builder.set_message_deduplication_id(Some(converted_134));
    }
    if let Some(value) = dict_value(values, "message_group_id")? {
        let converted_135: String = value.extract()?;
        builder = builder.set_message_group_id(Some(converted_135));
    }
    builder
        .build()
        .map_err(|error| PyValueError::new_err(error.to_string()))
}

fn send_message_batch_request_entry_to_py(
    py: Python<'_>,
    value: &aws_sdk_sqs::types::SendMessageBatchRequestEntry,
) -> PyResult<Py<PyAny>> {
    let result = PyDict::new(py);
    let converted_136 = &value.id.as_str().into_py_any(py)?;
    result.set_item("id", converted_136)?;
    let converted_137 = &value.message_body.as_str().into_py_any(py)?;
    result.set_item("message_body", converted_137)?;
    if let Some(value) = &value.delay_seconds {
        let converted_138 = (value).to_owned().into_py_any(py)?;
        result.set_item("delay_seconds", converted_138)?;
    } else {
        result.set_item("delay_seconds", py.None())?;
    }
    if let Some(value) = &value.message_attributes {
        let converted_139_dict = PyDict::new(py);
        for (key_140, value_141) in value {
            let converted_key_142 = key_140.as_str().into_py_any(py)?;
            let converted_value_143 = message_attribute_value_to_py(py, value_141)?;
            converted_139_dict.set_item(converted_key_142, converted_value_143)?;
        }
        let converted_139 = converted_139_dict.into_any().unbind();
        result.set_item("message_attributes", converted_139)?;
    } else {
        result.set_item("message_attributes", py.None())?;
    }
    if let Some(value) = &value.message_system_attributes {
        let converted_144_dict = PyDict::new(py);
        for (key_145, value_146) in value {
            let converted_key_147 = key_145.as_str().into_py_any(py)?;
            let converted_value_148 = message_system_attribute_value_to_py(py, value_146)?;
            converted_144_dict.set_item(converted_key_147, converted_value_148)?;
        }
        let converted_144 = converted_144_dict.into_any().unbind();
        result.set_item("message_system_attributes", converted_144)?;
    } else {
        result.set_item("message_system_attributes", py.None())?;
    }
    if let Some(value) = &value.message_deduplication_id {
        let converted_149 = value.as_str().into_py_any(py)?;
        result.set_item("message_deduplication_id", converted_149)?;
    } else {
        result.set_item("message_deduplication_id", py.None())?;
    }
    if let Some(value) = &value.message_group_id {
        let converted_150 = value.as_str().into_py_any(py)?;
        result.set_item("message_group_id", converted_150)?;
    } else {
        result.set_item("message_group_id", py.None())?;
    }
    Ok(result.into_any().unbind())
}

fn send_message_batch_result_entry_from_py(
    value: &Bound<'_, PyAny>,
) -> PyResult<aws_sdk_sqs::types::SendMessageBatchResultEntry> {
    let values = value.cast::<PyDict>()?;
    let mut builder = aws_sdk_sqs::types::SendMessageBatchResultEntry::builder();
    if let Some(value) = dict_value(values, "id")? {
        let converted_151: String = value.extract()?;
        builder = builder.set_id(Some(converted_151));
    }
    if let Some(value) = dict_value(values, "message_id")? {
        let converted_152: String = value.extract()?;
        builder = builder.set_message_id(Some(converted_152));
    }
    if let Some(value) = dict_value(values, "md5_of_message_body")? {
        let converted_153: String = value.extract()?;
        builder = builder.set_md5_of_message_body(Some(converted_153));
    }
    if let Some(value) = dict_value(values, "md5_of_message_attributes")? {
        let converted_154: String = value.extract()?;
        builder = builder.set_md5_of_message_attributes(Some(converted_154));
    }
    if let Some(value) = dict_value(values, "md5_of_message_system_attributes")? {
        let converted_155: String = value.extract()?;
        builder = builder.set_md5_of_message_system_attributes(Some(converted_155));
    }
    if let Some(value) = dict_value(values, "sequence_number")? {
        let converted_156: String = value.extract()?;
        builder = builder.set_sequence_number(Some(converted_156));
    }
    builder
        .build()
        .map_err(|error| PyValueError::new_err(error.to_string()))
}

fn send_message_batch_result_entry_to_py(
    py: Python<'_>,
    value: &aws_sdk_sqs::types::SendMessageBatchResultEntry,
) -> PyResult<Py<PyAny>> {
    let result = PyDict::new(py);
    let converted_157 = &value.id.as_str().into_py_any(py)?;
    result.set_item("id", converted_157)?;
    let converted_158 = &value.message_id.as_str().into_py_any(py)?;
    result.set_item("message_id", converted_158)?;
    let converted_159 = &value.md5_of_message_body.as_str().into_py_any(py)?;
    result.set_item("md5_of_message_body", converted_159)?;
    if let Some(value) = &value.md5_of_message_attributes {
        let converted_160 = value.as_str().into_py_any(py)?;
        result.set_item("md5_of_message_attributes", converted_160)?;
    } else {
        result.set_item("md5_of_message_attributes", py.None())?;
    }
    if let Some(value) = &value.md5_of_message_system_attributes {
        let converted_161 = value.as_str().into_py_any(py)?;
        result.set_item("md5_of_message_system_attributes", converted_161)?;
    } else {
        result.set_item("md5_of_message_system_attributes", py.None())?;
    }
    if let Some(value) = &value.sequence_number {
        let converted_162 = value.as_str().into_py_any(py)?;
        result.set_item("sequence_number", converted_162)?;
    } else {
        result.set_item("sequence_number", py.None())?;
    }
    Ok(result.into_any().unbind())
}

pub(super) fn add_generated_classes(module: &Bound<'_, PyModule>) -> PyResult<()> {
    Ok(())
}

#[pymethods]
impl SQSClient {
    #[new]
    #[pyo3(signature = (*, region=None, profile=None, endpoint_url=None))]
    fn new(region: Option<String>, profile: Option<String>, endpoint_url: Option<String>) -> Self {
        Self {
            state: Arc::new(ClientState {
                config: ClientConfig {
                    region,
                    profile,
                    endpoint_url,
                },
                client: OnceCell::new(),
            }),
        }
    }

    #[pyo3(signature = (params))]
    fn add_permission<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_url_value = if let Some(value) = dict_value(params, "queue_url")? {
            let converted_163: String = value.extract()?;
            Some(converted_163)
        } else {
            None
        };
        let label_value = if let Some(value) = dict_value(params, "label")? {
            let converted_164: String = value.extract()?;
            Some(converted_164)
        } else {
            None
        };
        let aws_account_ids_value = if let Some(value) = dict_value(params, "aws_account_ids")? {
            let mut converted_165 = Vec::new();
            for item_result_166 in value.try_iter()? {
                let item_167 = item_result_166?;
                let converted_item_168: String = item_167.extract()?;
                converted_165.push(converted_item_168);
            }
            Some(converted_165)
        } else {
            None
        };
        let actions_value = if let Some(value) = dict_value(params, "actions")? {
            let mut converted_169 = Vec::new();
            for item_result_170 in value.try_iter()? {
                let item_171 = item_result_170?;
                let converted_item_172: String = item_171.extract()?;
                converted_169.push(converted_item_172);
            }
            Some(converted_169)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .add_permission()
                .set_queue_url(queue_url_value)
                .set_label(label_value)
                .set_aws_account_ids(aws_account_ids_value)
                .set_actions(actions_value);
            let output = request.send().await.map_err(|error| {
                Python::attach(|py| sdk_error_to_py(py, &error, "AddPermission"))
            })?;
            Python::attach(|py| Ok(py.None()))
        })
    }

    #[pyo3(signature = (params))]
    fn cancel_message_move_task<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let task_handle_value = if let Some(value) = dict_value(params, "task_handle")? {
            let converted_173: String = value.extract()?;
            Some(converted_173)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .cancel_message_move_task()
                .set_task_handle(task_handle_value);
            let output = request.send().await.map_err(|error| {
                Python::attach(|py| sdk_error_to_py(py, &error, "CancelMessageMoveTask"))
            })?;
            Python::attach(|py| {
                let result = PyDict::new(py);
                let converted_174 = (&output.approximate_number_of_messages_moved)
                    .to_owned()
                    .into_py_any(py)?;
                result.set_item("approximate_number_of_messages_moved", converted_174)?;
                Ok(result.into_any().unbind())
            })
        })
    }

    #[pyo3(signature = (params))]
    fn change_message_visibility<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_url_value = if let Some(value) = dict_value(params, "queue_url")? {
            let converted_175: String = value.extract()?;
            Some(converted_175)
        } else {
            None
        };
        let receipt_handle_value = if let Some(value) = dict_value(params, "receipt_handle")? {
            let converted_176: String = value.extract()?;
            Some(converted_176)
        } else {
            None
        };
        let visibility_timeout_value =
            if let Some(value) = dict_value(params, "visibility_timeout")? {
                let converted_177: i32 = value.extract()?;
                Some(converted_177)
            } else {
                None
            };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .change_message_visibility()
                .set_queue_url(queue_url_value)
                .set_receipt_handle(receipt_handle_value)
                .set_visibility_timeout(visibility_timeout_value);
            let output = request.send().await.map_err(|error| {
                Python::attach(|py| sdk_error_to_py(py, &error, "ChangeMessageVisibility"))
            })?;
            Python::attach(|py| Ok(py.None()))
        })
    }

    #[pyo3(signature = (params))]
    fn change_message_visibility_batch<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_url_value = if let Some(value) = dict_value(params, "queue_url")? {
            let converted_178: String = value.extract()?;
            Some(converted_178)
        } else {
            None
        };
        let entries_value = if let Some(value) = dict_value(params, "entries")? {
            let mut converted_179 = Vec::new();
            for item_result_180 in value.try_iter()? {
                let item_181 = item_result_180?;
                let converted_item_182 =
                    change_message_visibility_batch_request_entry_from_py(&item_181)?;
                converted_179.push(converted_item_182);
            }
            Some(converted_179)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .change_message_visibility_batch()
                .set_queue_url(queue_url_value)
                .set_entries(entries_value);
            let output = request.send().await.map_err(|error| {
                Python::attach(|py| sdk_error_to_py(py, &error, "ChangeMessageVisibilityBatch"))
            })?;
            Python::attach(|py| {
                let result = PyDict::new(py);
                let converted_183_list = PyList::empty(py);
                for item_184 in &output.successful {
                    let converted_item_185 =
                        change_message_visibility_batch_result_entry_to_py(py, item_184)?;
                    converted_183_list.append(converted_item_185)?;
                }
                let converted_183 = converted_183_list.into_any().unbind();
                result.set_item("successful", converted_183)?;
                let converted_186_list = PyList::empty(py);
                for item_187 in &output.failed {
                    let converted_item_188 = batch_result_error_entry_to_py(py, item_187)?;
                    converted_186_list.append(converted_item_188)?;
                }
                let converted_186 = converted_186_list.into_any().unbind();
                result.set_item("failed", converted_186)?;
                Ok(result.into_any().unbind())
            })
        })
    }

    #[pyo3(signature = (params))]
    fn create_queue<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_name_value = if let Some(value) = dict_value(params, "queue_name")? {
            let converted_189: String = value.extract()?;
            Some(converted_189)
        } else {
            None
        };
        let attributes_value = if let Some(value) = dict_value(params, "attributes")? {
            let mapping_191 = value.cast::<PyDict>()?;
            let mut converted_190 = HashMap::new();
            for (key_192, value_193) in mapping_191.iter() {
                let enum_value_196: String = key_192.extract()?;
                let converted_key_194 =
                    aws_sdk_sqs::types::QueueAttributeName::from(enum_value_196.as_str());
                let converted_value_195: String = value_193.extract()?;
                converted_190.insert(converted_key_194, converted_value_195);
            }
            Some(converted_190)
        } else {
            None
        };
        let tags_value = if let Some(value) = dict_value(params, "tags")? {
            let mapping_198 = value.cast::<PyDict>()?;
            let mut converted_197 = HashMap::new();
            for (key_199, value_200) in mapping_198.iter() {
                let converted_key_201: String = key_199.extract()?;
                let converted_value_202: String = value_200.extract()?;
                converted_197.insert(converted_key_201, converted_value_202);
            }
            Some(converted_197)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .create_queue()
                .set_queue_name(queue_name_value)
                .set_attributes(attributes_value)
                .set_tags(tags_value);
            let output = request
                .send()
                .await
                .map_err(|error| Python::attach(|py| sdk_error_to_py(py, &error, "CreateQueue")))?;
            Python::attach(|py| {
                let result = PyDict::new(py);
                if let Some(value) = &output.queue_url {
                    let converted_203 = value.as_str().into_py_any(py)?;
                    result.set_item("queue_url", converted_203)?;
                } else {
                    result.set_item("queue_url", py.None())?;
                }
                Ok(result.into_any().unbind())
            })
        })
    }

    #[pyo3(signature = (params))]
    fn delete_message<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_url_value = if let Some(value) = dict_value(params, "queue_url")? {
            let converted_204: String = value.extract()?;
            Some(converted_204)
        } else {
            None
        };
        let receipt_handle_value = if let Some(value) = dict_value(params, "receipt_handle")? {
            let converted_205: String = value.extract()?;
            Some(converted_205)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .delete_message()
                .set_queue_url(queue_url_value)
                .set_receipt_handle(receipt_handle_value);
            let output = request.send().await.map_err(|error| {
                Python::attach(|py| sdk_error_to_py(py, &error, "DeleteMessage"))
            })?;
            Python::attach(|py| Ok(py.None()))
        })
    }

    #[pyo3(signature = (params))]
    fn delete_message_batch<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_url_value = if let Some(value) = dict_value(params, "queue_url")? {
            let converted_206: String = value.extract()?;
            Some(converted_206)
        } else {
            None
        };
        let entries_value = if let Some(value) = dict_value(params, "entries")? {
            let mut converted_207 = Vec::new();
            for item_result_208 in value.try_iter()? {
                let item_209 = item_result_208?;
                let converted_item_210 = delete_message_batch_request_entry_from_py(&item_209)?;
                converted_207.push(converted_item_210);
            }
            Some(converted_207)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .delete_message_batch()
                .set_queue_url(queue_url_value)
                .set_entries(entries_value);
            let output = request.send().await.map_err(|error| {
                Python::attach(|py| sdk_error_to_py(py, &error, "DeleteMessageBatch"))
            })?;
            Python::attach(|py| {
                let result = PyDict::new(py);
                let converted_211_list = PyList::empty(py);
                for item_212 in &output.successful {
                    let converted_item_213 = delete_message_batch_result_entry_to_py(py, item_212)?;
                    converted_211_list.append(converted_item_213)?;
                }
                let converted_211 = converted_211_list.into_any().unbind();
                result.set_item("successful", converted_211)?;
                let converted_214_list = PyList::empty(py);
                for item_215 in &output.failed {
                    let converted_item_216 = batch_result_error_entry_to_py(py, item_215)?;
                    converted_214_list.append(converted_item_216)?;
                }
                let converted_214 = converted_214_list.into_any().unbind();
                result.set_item("failed", converted_214)?;
                Ok(result.into_any().unbind())
            })
        })
    }

    #[pyo3(signature = (params))]
    fn delete_queue<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_url_value = if let Some(value) = dict_value(params, "queue_url")? {
            let converted_217: String = value.extract()?;
            Some(converted_217)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .delete_queue()
                .set_queue_url(queue_url_value);
            let output = request
                .send()
                .await
                .map_err(|error| Python::attach(|py| sdk_error_to_py(py, &error, "DeleteQueue")))?;
            Python::attach(|py| Ok(py.None()))
        })
    }

    #[pyo3(signature = (params))]
    fn get_queue_attributes<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_url_value = if let Some(value) = dict_value(params, "queue_url")? {
            let converted_218: String = value.extract()?;
            Some(converted_218)
        } else {
            None
        };
        let attribute_names_value = if let Some(value) = dict_value(params, "attribute_names")? {
            let mut converted_219 = Vec::new();
            for item_result_220 in value.try_iter()? {
                let item_221 = item_result_220?;
                let enum_value_223: String = item_221.extract()?;
                let converted_item_222 =
                    aws_sdk_sqs::types::QueueAttributeName::from(enum_value_223.as_str());
                converted_219.push(converted_item_222);
            }
            Some(converted_219)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .get_queue_attributes()
                .set_queue_url(queue_url_value)
                .set_attribute_names(attribute_names_value);
            let output = request.send().await.map_err(|error| {
                Python::attach(|py| sdk_error_to_py(py, &error, "GetQueueAttributes"))
            })?;
            Python::attach(|py| {
                let result = PyDict::new(py);
                if let Some(value) = &output.attributes {
                    let converted_224_dict = PyDict::new(py);
                    for (key_225, value_226) in value {
                        let converted_key_227 = key_225.as_str().into_py_any(py)?;
                        let converted_value_228 = value_226.as_str().into_py_any(py)?;
                        converted_224_dict.set_item(converted_key_227, converted_value_228)?;
                    }
                    let converted_224 = converted_224_dict.into_any().unbind();
                    result.set_item("attributes", converted_224)?;
                } else {
                    result.set_item("attributes", py.None())?;
                }
                Ok(result.into_any().unbind())
            })
        })
    }

    #[pyo3(signature = (params))]
    fn get_queue_url<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_name_value = if let Some(value) = dict_value(params, "queue_name")? {
            let converted_229: String = value.extract()?;
            Some(converted_229)
        } else {
            None
        };
        let queue_owner_aws_account_id_value =
            if let Some(value) = dict_value(params, "queue_owner_aws_account_id")? {
                let converted_230: String = value.extract()?;
                Some(converted_230)
            } else {
                None
            };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .get_queue_url()
                .set_queue_name(queue_name_value)
                .set_queue_owner_aws_account_id(queue_owner_aws_account_id_value);
            let output = request
                .send()
                .await
                .map_err(|error| Python::attach(|py| sdk_error_to_py(py, &error, "GetQueueUrl")))?;
            Python::attach(|py| {
                let result = PyDict::new(py);
                if let Some(value) = &output.queue_url {
                    let converted_231 = value.as_str().into_py_any(py)?;
                    result.set_item("queue_url", converted_231)?;
                } else {
                    result.set_item("queue_url", py.None())?;
                }
                Ok(result.into_any().unbind())
            })
        })
    }

    #[pyo3(signature = (params))]
    fn list_dead_letter_source_queues<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_url_value = if let Some(value) = dict_value(params, "queue_url")? {
            let converted_232: String = value.extract()?;
            Some(converted_232)
        } else {
            None
        };
        let next_token_value = if let Some(value) = dict_value(params, "next_token")? {
            let converted_233: String = value.extract()?;
            Some(converted_233)
        } else {
            None
        };
        let max_results_value = if let Some(value) = dict_value(params, "max_results")? {
            let converted_234: i32 = value.extract()?;
            Some(converted_234)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .list_dead_letter_source_queues()
                .set_queue_url(queue_url_value)
                .set_next_token(next_token_value)
                .set_max_results(max_results_value);
            let output = request.send().await.map_err(|error| {
                Python::attach(|py| sdk_error_to_py(py, &error, "ListDeadLetterSourceQueues"))
            })?;
            Python::attach(|py| {
                let result = PyDict::new(py);
                let converted_235_list = PyList::empty(py);
                for item_236 in &output.queue_urls {
                    let converted_item_237 = item_236.as_str().into_py_any(py)?;
                    converted_235_list.append(converted_item_237)?;
                }
                let converted_235 = converted_235_list.into_any().unbind();
                result.set_item("queue_urls", converted_235)?;
                if let Some(value) = &output.next_token {
                    let converted_238 = value.as_str().into_py_any(py)?;
                    result.set_item("next_token", converted_238)?;
                } else {
                    result.set_item("next_token", py.None())?;
                }
                Ok(result.into_any().unbind())
            })
        })
    }

    #[pyo3(signature = (params))]
    fn list_message_move_tasks<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let source_arn_value = if let Some(value) = dict_value(params, "source_arn")? {
            let converted_239: String = value.extract()?;
            Some(converted_239)
        } else {
            None
        };
        let max_results_value = if let Some(value) = dict_value(params, "max_results")? {
            let converted_240: i32 = value.extract()?;
            Some(converted_240)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .list_message_move_tasks()
                .set_source_arn(source_arn_value)
                .set_max_results(max_results_value);
            let output = request.send().await.map_err(|error| {
                Python::attach(|py| sdk_error_to_py(py, &error, "ListMessageMoveTasks"))
            })?;
            Python::attach(|py| {
                let result = PyDict::new(py);
                if let Some(value) = &output.results {
                    let converted_241_list = PyList::empty(py);
                    for item_242 in value {
                        let converted_item_243 =
                            list_message_move_tasks_result_entry_to_py(py, item_242)?;
                        converted_241_list.append(converted_item_243)?;
                    }
                    let converted_241 = converted_241_list.into_any().unbind();
                    result.set_item("results", converted_241)?;
                } else {
                    result.set_item("results", py.None())?;
                }
                Ok(result.into_any().unbind())
            })
        })
    }

    #[pyo3(signature = (params))]
    fn list_queues<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_name_prefix_value = if let Some(value) = dict_value(params, "queue_name_prefix")?
        {
            let converted_244: String = value.extract()?;
            Some(converted_244)
        } else {
            None
        };
        let next_token_value = if let Some(value) = dict_value(params, "next_token")? {
            let converted_245: String = value.extract()?;
            Some(converted_245)
        } else {
            None
        };
        let max_results_value = if let Some(value) = dict_value(params, "max_results")? {
            let converted_246: i32 = value.extract()?;
            Some(converted_246)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .list_queues()
                .set_queue_name_prefix(queue_name_prefix_value)
                .set_next_token(next_token_value)
                .set_max_results(max_results_value);
            let output = request
                .send()
                .await
                .map_err(|error| Python::attach(|py| sdk_error_to_py(py, &error, "ListQueues")))?;
            Python::attach(|py| {
                let result = PyDict::new(py);
                if let Some(value) = &output.queue_urls {
                    let converted_247_list = PyList::empty(py);
                    for item_248 in value {
                        let converted_item_249 = item_248.as_str().into_py_any(py)?;
                        converted_247_list.append(converted_item_249)?;
                    }
                    let converted_247 = converted_247_list.into_any().unbind();
                    result.set_item("queue_urls", converted_247)?;
                } else {
                    result.set_item("queue_urls", py.None())?;
                }
                if let Some(value) = &output.next_token {
                    let converted_250 = value.as_str().into_py_any(py)?;
                    result.set_item("next_token", converted_250)?;
                } else {
                    result.set_item("next_token", py.None())?;
                }
                Ok(result.into_any().unbind())
            })
        })
    }

    #[pyo3(signature = (params))]
    fn list_queue_tags<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_url_value = if let Some(value) = dict_value(params, "queue_url")? {
            let converted_251: String = value.extract()?;
            Some(converted_251)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .list_queue_tags()
                .set_queue_url(queue_url_value);
            let output = request.send().await.map_err(|error| {
                Python::attach(|py| sdk_error_to_py(py, &error, "ListQueueTags"))
            })?;
            Python::attach(|py| {
                let result = PyDict::new(py);
                if let Some(value) = &output.tags {
                    let converted_252_dict = PyDict::new(py);
                    for (key_253, value_254) in value {
                        let converted_key_255 = key_253.as_str().into_py_any(py)?;
                        let converted_value_256 = value_254.as_str().into_py_any(py)?;
                        converted_252_dict.set_item(converted_key_255, converted_value_256)?;
                    }
                    let converted_252 = converted_252_dict.into_any().unbind();
                    result.set_item("tags", converted_252)?;
                } else {
                    result.set_item("tags", py.None())?;
                }
                Ok(result.into_any().unbind())
            })
        })
    }

    #[pyo3(signature = (params))]
    fn purge_queue<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_url_value = if let Some(value) = dict_value(params, "queue_url")? {
            let converted_257: String = value.extract()?;
            Some(converted_257)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .purge_queue()
                .set_queue_url(queue_url_value);
            let output = request
                .send()
                .await
                .map_err(|error| Python::attach(|py| sdk_error_to_py(py, &error, "PurgeQueue")))?;
            Python::attach(|py| Ok(py.None()))
        })
    }

    #[pyo3(signature = (params))]
    fn receive_message<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_url_value = if let Some(value) = dict_value(params, "queue_url")? {
            let converted_258: String = value.extract()?;
            Some(converted_258)
        } else {
            None
        };
        let attribute_names_value = if let Some(value) = dict_value(params, "attribute_names")? {
            let mut converted_259 = Vec::new();
            for item_result_260 in value.try_iter()? {
                let item_261 = item_result_260?;
                let enum_value_263: String = item_261.extract()?;
                let converted_item_262 =
                    aws_sdk_sqs::types::QueueAttributeName::from(enum_value_263.as_str());
                converted_259.push(converted_item_262);
            }
            Some(converted_259)
        } else {
            None
        };
        let message_system_attribute_names_value = if let Some(value) =
            dict_value(params, "message_system_attribute_names")?
        {
            let mut converted_264 = Vec::new();
            for item_result_265 in value.try_iter()? {
                let item_266 = item_result_265?;
                let enum_value_268: String = item_266.extract()?;
                let converted_item_267 =
                    aws_sdk_sqs::types::MessageSystemAttributeName::from(enum_value_268.as_str());
                converted_264.push(converted_item_267);
            }
            Some(converted_264)
        } else {
            None
        };
        let message_attribute_names_value =
            if let Some(value) = dict_value(params, "message_attribute_names")? {
                let mut converted_269 = Vec::new();
                for item_result_270 in value.try_iter()? {
                    let item_271 = item_result_270?;
                    let converted_item_272: String = item_271.extract()?;
                    converted_269.push(converted_item_272);
                }
                Some(converted_269)
            } else {
                None
            };
        let max_number_of_messages_value =
            if let Some(value) = dict_value(params, "max_number_of_messages")? {
                let converted_273: i32 = value.extract()?;
                Some(converted_273)
            } else {
                None
            };
        let visibility_timeout_value =
            if let Some(value) = dict_value(params, "visibility_timeout")? {
                let converted_274: i32 = value.extract()?;
                Some(converted_274)
            } else {
                None
            };
        let wait_time_seconds_value = if let Some(value) = dict_value(params, "wait_time_seconds")?
        {
            let converted_275: i32 = value.extract()?;
            Some(converted_275)
        } else {
            None
        };
        let receive_request_attempt_id_value =
            if let Some(value) = dict_value(params, "receive_request_attempt_id")? {
                let converted_276: String = value.extract()?;
                Some(converted_276)
            } else {
                None
            };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .receive_message()
                .set_queue_url(queue_url_value)
                .set_attribute_names(attribute_names_value)
                .set_message_system_attribute_names(message_system_attribute_names_value)
                .set_message_attribute_names(message_attribute_names_value)
                .set_max_number_of_messages(max_number_of_messages_value)
                .set_visibility_timeout(visibility_timeout_value)
                .set_wait_time_seconds(wait_time_seconds_value)
                .set_receive_request_attempt_id(receive_request_attempt_id_value);
            let output = request.send().await.map_err(|error| {
                Python::attach(|py| sdk_error_to_py(py, &error, "ReceiveMessage"))
            })?;
            Python::attach(|py| {
                let result = PyDict::new(py);
                if let Some(value) = &output.messages {
                    let converted_277_list = PyList::empty(py);
                    for item_278 in value {
                        let converted_item_279 = message_to_py(py, item_278)?;
                        converted_277_list.append(converted_item_279)?;
                    }
                    let converted_277 = converted_277_list.into_any().unbind();
                    result.set_item("messages", converted_277)?;
                } else {
                    result.set_item("messages", py.None())?;
                }
                Ok(result.into_any().unbind())
            })
        })
    }

    #[pyo3(signature = (params))]
    fn remove_permission<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_url_value = if let Some(value) = dict_value(params, "queue_url")? {
            let converted_280: String = value.extract()?;
            Some(converted_280)
        } else {
            None
        };
        let label_value = if let Some(value) = dict_value(params, "label")? {
            let converted_281: String = value.extract()?;
            Some(converted_281)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .remove_permission()
                .set_queue_url(queue_url_value)
                .set_label(label_value);
            let output = request.send().await.map_err(|error| {
                Python::attach(|py| sdk_error_to_py(py, &error, "RemovePermission"))
            })?;
            Python::attach(|py| Ok(py.None()))
        })
    }

    #[pyo3(signature = (params))]
    fn send_message<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_url_value = if let Some(value) = dict_value(params, "queue_url")? {
            let converted_282: String = value.extract()?;
            Some(converted_282)
        } else {
            None
        };
        let message_body_value = if let Some(value) = dict_value(params, "message_body")? {
            let converted_283: String = value.extract()?;
            Some(converted_283)
        } else {
            None
        };
        let delay_seconds_value = if let Some(value) = dict_value(params, "delay_seconds")? {
            let converted_284: i32 = value.extract()?;
            Some(converted_284)
        } else {
            None
        };
        let message_attributes_value =
            if let Some(value) = dict_value(params, "message_attributes")? {
                let mapping_286 = value.cast::<PyDict>()?;
                let mut converted_285 = HashMap::new();
                for (key_287, value_288) in mapping_286.iter() {
                    let converted_key_289: String = key_287.extract()?;
                    let converted_value_290 = message_attribute_value_from_py(&value_288)?;
                    converted_285.insert(converted_key_289, converted_value_290);
                }
                Some(converted_285)
            } else {
                None
            };
        let message_system_attributes_value =
            if let Some(value) = dict_value(params, "message_system_attributes")? {
                let mapping_292 = value.cast::<PyDict>()?;
                let mut converted_291 = HashMap::new();
                for (key_293, value_294) in mapping_292.iter() {
                    let enum_value_297: String = key_293.extract()?;
                    let converted_key_295 =
                        aws_sdk_sqs::types::MessageSystemAttributeNameForSends::from(
                            enum_value_297.as_str(),
                        );
                    let converted_value_296 = message_system_attribute_value_from_py(&value_294)?;
                    converted_291.insert(converted_key_295, converted_value_296);
                }
                Some(converted_291)
            } else {
                None
            };
        let message_deduplication_id_value =
            if let Some(value) = dict_value(params, "message_deduplication_id")? {
                let converted_298: String = value.extract()?;
                Some(converted_298)
            } else {
                None
            };
        let message_group_id_value = if let Some(value) = dict_value(params, "message_group_id")? {
            let converted_299: String = value.extract()?;
            Some(converted_299)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .send_message()
                .set_queue_url(queue_url_value)
                .set_message_body(message_body_value)
                .set_delay_seconds(delay_seconds_value)
                .set_message_attributes(message_attributes_value)
                .set_message_system_attributes(message_system_attributes_value)
                .set_message_deduplication_id(message_deduplication_id_value)
                .set_message_group_id(message_group_id_value);
            let output = request
                .send()
                .await
                .map_err(|error| Python::attach(|py| sdk_error_to_py(py, &error, "SendMessage")))?;
            Python::attach(|py| {
                let result = PyDict::new(py);
                if let Some(value) = &output.md5_of_message_body {
                    let converted_300 = value.as_str().into_py_any(py)?;
                    result.set_item("md5_of_message_body", converted_300)?;
                } else {
                    result.set_item("md5_of_message_body", py.None())?;
                }
                if let Some(value) = &output.md5_of_message_attributes {
                    let converted_301 = value.as_str().into_py_any(py)?;
                    result.set_item("md5_of_message_attributes", converted_301)?;
                } else {
                    result.set_item("md5_of_message_attributes", py.None())?;
                }
                if let Some(value) = &output.md5_of_message_system_attributes {
                    let converted_302 = value.as_str().into_py_any(py)?;
                    result.set_item("md5_of_message_system_attributes", converted_302)?;
                } else {
                    result.set_item("md5_of_message_system_attributes", py.None())?;
                }
                if let Some(value) = &output.message_id {
                    let converted_303 = value.as_str().into_py_any(py)?;
                    result.set_item("message_id", converted_303)?;
                } else {
                    result.set_item("message_id", py.None())?;
                }
                if let Some(value) = &output.sequence_number {
                    let converted_304 = value.as_str().into_py_any(py)?;
                    result.set_item("sequence_number", converted_304)?;
                } else {
                    result.set_item("sequence_number", py.None())?;
                }
                Ok(result.into_any().unbind())
            })
        })
    }

    #[pyo3(signature = (params))]
    fn send_message_batch<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_url_value = if let Some(value) = dict_value(params, "queue_url")? {
            let converted_305: String = value.extract()?;
            Some(converted_305)
        } else {
            None
        };
        let entries_value = if let Some(value) = dict_value(params, "entries")? {
            let mut converted_306 = Vec::new();
            for item_result_307 in value.try_iter()? {
                let item_308 = item_result_307?;
                let converted_item_309 = send_message_batch_request_entry_from_py(&item_308)?;
                converted_306.push(converted_item_309);
            }
            Some(converted_306)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .send_message_batch()
                .set_queue_url(queue_url_value)
                .set_entries(entries_value);
            let output = request.send().await.map_err(|error| {
                Python::attach(|py| sdk_error_to_py(py, &error, "SendMessageBatch"))
            })?;
            Python::attach(|py| {
                let result = PyDict::new(py);
                let converted_310_list = PyList::empty(py);
                for item_311 in &output.successful {
                    let converted_item_312 = send_message_batch_result_entry_to_py(py, item_311)?;
                    converted_310_list.append(converted_item_312)?;
                }
                let converted_310 = converted_310_list.into_any().unbind();
                result.set_item("successful", converted_310)?;
                let converted_313_list = PyList::empty(py);
                for item_314 in &output.failed {
                    let converted_item_315 = batch_result_error_entry_to_py(py, item_314)?;
                    converted_313_list.append(converted_item_315)?;
                }
                let converted_313 = converted_313_list.into_any().unbind();
                result.set_item("failed", converted_313)?;
                Ok(result.into_any().unbind())
            })
        })
    }

    #[pyo3(signature = (params))]
    fn set_queue_attributes<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_url_value = if let Some(value) = dict_value(params, "queue_url")? {
            let converted_316: String = value.extract()?;
            Some(converted_316)
        } else {
            None
        };
        let attributes_value = if let Some(value) = dict_value(params, "attributes")? {
            let mapping_318 = value.cast::<PyDict>()?;
            let mut converted_317 = HashMap::new();
            for (key_319, value_320) in mapping_318.iter() {
                let enum_value_323: String = key_319.extract()?;
                let converted_key_321 =
                    aws_sdk_sqs::types::QueueAttributeName::from(enum_value_323.as_str());
                let converted_value_322: String = value_320.extract()?;
                converted_317.insert(converted_key_321, converted_value_322);
            }
            Some(converted_317)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .set_queue_attributes()
                .set_queue_url(queue_url_value)
                .set_attributes(attributes_value);
            let output = request.send().await.map_err(|error| {
                Python::attach(|py| sdk_error_to_py(py, &error, "SetQueueAttributes"))
            })?;
            Python::attach(|py| Ok(py.None()))
        })
    }

    #[pyo3(signature = (params))]
    fn start_message_move_task<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let source_arn_value = if let Some(value) = dict_value(params, "source_arn")? {
            let converted_324: String = value.extract()?;
            Some(converted_324)
        } else {
            None
        };
        let destination_arn_value = if let Some(value) = dict_value(params, "destination_arn")? {
            let converted_325: String = value.extract()?;
            Some(converted_325)
        } else {
            None
        };
        let max_number_of_messages_per_second_value =
            if let Some(value) = dict_value(params, "max_number_of_messages_per_second")? {
                let converted_326: i32 = value.extract()?;
                Some(converted_326)
            } else {
                None
            };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .start_message_move_task()
                .set_source_arn(source_arn_value)
                .set_destination_arn(destination_arn_value)
                .set_max_number_of_messages_per_second(max_number_of_messages_per_second_value);
            let output = request.send().await.map_err(|error| {
                Python::attach(|py| sdk_error_to_py(py, &error, "StartMessageMoveTask"))
            })?;
            Python::attach(|py| {
                let result = PyDict::new(py);
                if let Some(value) = &output.task_handle {
                    let converted_327 = value.as_str().into_py_any(py)?;
                    result.set_item("task_handle", converted_327)?;
                } else {
                    result.set_item("task_handle", py.None())?;
                }
                Ok(result.into_any().unbind())
            })
        })
    }

    #[pyo3(signature = (params))]
    fn tag_queue<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_url_value = if let Some(value) = dict_value(params, "queue_url")? {
            let converted_328: String = value.extract()?;
            Some(converted_328)
        } else {
            None
        };
        let tags_value = if let Some(value) = dict_value(params, "tags")? {
            let mapping_330 = value.cast::<PyDict>()?;
            let mut converted_329 = HashMap::new();
            for (key_331, value_332) in mapping_330.iter() {
                let converted_key_333: String = key_331.extract()?;
                let converted_value_334: String = value_332.extract()?;
                converted_329.insert(converted_key_333, converted_value_334);
            }
            Some(converted_329)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .tag_queue()
                .set_queue_url(queue_url_value)
                .set_tags(tags_value);
            let output = request
                .send()
                .await
                .map_err(|error| Python::attach(|py| sdk_error_to_py(py, &error, "TagQueue")))?;
            Python::attach(|py| Ok(py.None()))
        })
    }

    #[pyo3(signature = (params))]
    fn untag_queue<'py>(
        &self,
        py: Python<'py>,
        params: &Bound<'py, PyDict>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let state = self.state.clone();
        let queue_url_value = if let Some(value) = dict_value(params, "queue_url")? {
            let converted_335: String = value.extract()?;
            Some(converted_335)
        } else {
            None
        };
        let tag_keys_value = if let Some(value) = dict_value(params, "tag_keys")? {
            let mut converted_336 = Vec::new();
            for item_result_337 in value.try_iter()? {
                let item_338 = item_result_337?;
                let converted_item_339: String = item_338.extract()?;
                converted_336.push(converted_item_339);
            }
            Some(converted_336)
        } else {
            None
        };
        future_into_py(py, async move {
            let request = state
                .client()
                .await
                .untag_queue()
                .set_queue_url(queue_url_value)
                .set_tag_keys(tag_keys_value);
            let output = request
                .send()
                .await
                .map_err(|error| Python::attach(|py| sdk_error_to_py(py, &error, "UntagQueue")))?;
            Python::attach(|py| Ok(py.None()))
        })
    }
}
