// Generated by rboto-codegen. DO NOT EDIT.
mod generated;

use std::collections::HashMap;
use std::fmt::Debug;
use std::sync::Arc;

use aws_config::BehaviorVersion;
use aws_sdk_sqs::Client;
use aws_smithy_runtime_api::client::result::SdkError;
use aws_smithy_types::byte_stream::ByteStream as AwsByteStream;
use aws_smithy_types::error::metadata::ProvideErrorMetadata;
use pyo3::conversion::IntoPyObjectExt;
use pyo3::exceptions::{PyOSError, PyStopAsyncIteration, PyValueError};
use pyo3::prelude::*;
use pyo3::types::{PyBytes, PyDict, PyList};
use pyo3_async_runtimes::tokio::future_into_py;
use rboto_core::raise_service_error;
use tokio::sync::{Mutex, OnceCell};

#[derive(Clone)]
struct ClientConfig {
    region: Option<String>,
    profile: Option<String>,
    endpoint_url: Option<String>,
}

struct ClientState {
    config: ClientConfig,
    client: OnceCell<Client>,
}

impl ClientState {
    async fn client(&self) -> &Client {
        self.client
            .get_or_init(|| async {
                let mut loader = aws_config::defaults(BehaviorVersion::latest());
                if let Some(region) = &self.config.region {
                    loader = loader.region(aws_config::Region::new(region.clone()));
                }
                if let Some(profile) = &self.config.profile {
                    loader = loader.profile_name(profile);
                }
                let shared = loader.load().await;
                let mut service = aws_sdk_sqs::config::Builder::from(&shared);
                if let Some(endpoint) = &self.config.endpoint_url {
                    service = service.endpoint_url(endpoint);
                }
                Client::from_conf(service.build())
            })
            .await
    }
}

#[pyclass(name = "ByteStream")]
struct PyByteStream {
    inner: Arc<Mutex<Option<AwsByteStream>>>,
}

#[allow(dead_code)]
impl PyByteStream {
    fn new(stream: AwsByteStream) -> Self {
        Self {
            inner: Arc::new(Mutex::new(Some(stream))),
        }
    }
}

#[pymethods]
impl PyByteStream {
    fn __aiter__(slf: Py<Self>) -> Py<Self> {
        slf
    }

    fn __anext__<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        let inner = self.inner.clone();
        future_into_py(py, async move {
            let mut guard = inner.lock().await;
            let Some(stream) = guard.as_mut() else {
                return Err(PyStopAsyncIteration::new_err(()));
            };
            match stream.try_next().await {
                Ok(Some(chunk)) => Python::attach(|py| Ok(PyBytes::new(py, &chunk).unbind())),
                Ok(None) => {
                    *guard = None;
                    Err(PyStopAsyncIteration::new_err(()))
                }
                Err(error) => {
                    *guard = None;
                    Err(PyOSError::new_err(format!("stream failed: {error}")))
                }
            }
        })
    }

    fn read<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        let inner = self.inner.clone();
        future_into_py(py, async move {
            let stream = inner.lock().await.take();
            let Some(stream) = stream else {
                return Python::attach(|py| Ok(PyBytes::new(py, b"").unbind()));
            };
            let bytes = stream
                .collect()
                .await
                .map_err(|error| PyOSError::new_err(error.to_string()))?
                .into_bytes();
            Python::attach(|py| Ok(PyBytes::new(py, &bytes).unbind()))
        })
    }
}

#[pyclass]
struct SQSClient {
    state: Arc<ClientState>,
}

fn dict_value<'py>(values: &Bound<'py, PyDict>, name: &str) -> PyResult<Option<Bound<'py, PyAny>>> {
    Ok(values.get_item(name)?.filter(|value| !value.is_none()))
}

fn sdk_error_to_py<E, R>(py: Python<'_>, error: &SdkError<E, R>, operation: &str) -> PyErr
where
    E: ProvideErrorMetadata + Debug,
    R: Debug,
{
    let service_error = error.as_service_error();
    let code = service_error
        .and_then(ProvideErrorMetadata::code)
        .unwrap_or("UnknownError");
    let message = service_error
        .and_then(ProvideErrorMetadata::message)
        .map(str::to_owned)
        .unwrap_or_else(|| format!("{error:?}"));
    raise_service_error(
        py,
        "rboto_sqs.exceptions",
        "SQSError",
        code,
        &message,
        operation,
        None,
    )
}

#[pymodule]
fn _native(module: &Bound<'_, PyModule>) -> PyResult<()> {
    module.add_class::<SQSClient>()?;
    module.add_class::<PyByteStream>()?;
    generated::add_generated_classes(module)?;
    Ok(())
}
