from __future__ import annotations

from collections.abc import AsyncIterator
from typing import final


@final
class ByteStream:
    def __aiter__(self) -> AsyncIterator[bytes]: ...
    async def __anext__(self) -> bytes: ...
    async def read(self) -> bytes: ...



@final
class BatchResultErrorEntry:
    @property
    def id(self) -> str: ...
    @property
    def code(self) -> str: ...
    @property
    def message(self) -> str | None: ...
    @property
    def sender_fault(self) -> bool: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Endpoint:
    @property
    def endpoint_arn(self) -> str | None: ...
    @property
    def attributes(self) -> dict[str, str] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class PhoneNumberInformation:
    @property
    def created_at(self) -> str | None: ...
    @property
    def phone_number(self) -> str | None: ...
    @property
    def status(self) -> str | None: ...
    @property
    def iso2_country_code(self) -> str | None: ...
    @property
    def route_type(self) -> str | None: ...
    @property
    def number_capabilities(self) -> list[str] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class PlatformApplication:
    @property
    def platform_application_arn(self) -> str | None: ...
    @property
    def attributes(self) -> dict[str, str] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class PublishBatchResultEntry:
    @property
    def id(self) -> str | None: ...
    @property
    def message_id(self) -> str | None: ...
    @property
    def sequence_number(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class SmsSandboxPhoneNumber:
    @property
    def phone_number(self) -> str | None: ...
    @property
    def status(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Subscription:
    @property
    def subscription_arn(self) -> str | None: ...
    @property
    def owner(self) -> str | None: ...
    @property
    def protocol(self) -> str | None: ...
    @property
    def endpoint(self) -> str | None: ...
    @property
    def topic_arn(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Tag:
    @property
    def key(self) -> str: ...
    @property
    def value(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Topic:
    @property
    def topic_arn(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CheckIfPhoneNumberIsOptedOutResponse:
    @property
    def is_opted_out(self) -> bool: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ConfirmSubscriptionResponse:
    @property
    def subscription_arn(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CreatePlatformApplicationResponse:
    @property
    def platform_application_arn(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CreateEndpointResponse:
    @property
    def endpoint_arn(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CreateSMSSandboxPhoneNumberResult:
    def to_dict(self) -> dict[str, object]: ...

@final
class CreateTopicResponse:
    @property
    def topic_arn(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DeleteSMSSandboxPhoneNumberResult:
    def to_dict(self) -> dict[str, object]: ...

@final
class GetDataProtectionPolicyResponse:
    @property
    def data_protection_policy(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetEndpointAttributesResponse:
    @property
    def attributes(self) -> dict[str, str] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetPlatformApplicationAttributesResponse:
    @property
    def attributes(self) -> dict[str, str] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetSMSAttributesResponse:
    @property
    def attributes(self) -> dict[str, str] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetSMSSandboxAccountStatusResult:
    @property
    def is_in_sandbox(self) -> bool: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetSubscriptionAttributesResponse:
    @property
    def attributes(self) -> dict[str, str] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetTopicAttributesResponse:
    @property
    def attributes(self) -> dict[str, str] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListEndpointsByPlatformApplicationResponse:
    @property
    def endpoints(self) -> list[Endpoint] | None: ...
    @property
    def next_token(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListOriginationNumbersResult:
    @property
    def next_token(self) -> str | None: ...
    @property
    def phone_numbers(self) -> list[PhoneNumberInformation] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListPhoneNumbersOptedOutResponse:
    @property
    def phone_numbers(self) -> list[str] | None: ...
    @property
    def next_token(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListPlatformApplicationsResponse:
    @property
    def platform_applications(self) -> list[PlatformApplication] | None: ...
    @property
    def next_token(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListSMSSandboxPhoneNumbersResult:
    @property
    def phone_numbers(self) -> list[SmsSandboxPhoneNumber]: ...
    @property
    def next_token(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListSubscriptionsResponse:
    @property
    def subscriptions(self) -> list[Subscription] | None: ...
    @property
    def next_token(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListSubscriptionsByTopicResponse:
    @property
    def subscriptions(self) -> list[Subscription] | None: ...
    @property
    def next_token(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListTagsForResourceResponse:
    @property
    def tags(self) -> list[Tag] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListTopicsResponse:
    @property
    def topics(self) -> list[Topic] | None: ...
    @property
    def next_token(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class OptInPhoneNumberResponse:
    def to_dict(self) -> dict[str, object]: ...

@final
class PublishResponse:
    @property
    def message_id(self) -> str | None: ...
    @property
    def sequence_number(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class PublishBatchResponse:
    @property
    def successful(self) -> list[PublishBatchResultEntry] | None: ...
    @property
    def failed(self) -> list[BatchResultErrorEntry] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class SetSMSAttributesResponse:
    def to_dict(self) -> dict[str, object]: ...

@final
class SubscribeResponse:
    @property
    def subscription_arn(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class TagResourceResponse:
    def to_dict(self) -> dict[str, object]: ...

@final
class UntagResourceResponse:
    def to_dict(self) -> dict[str, object]: ...

@final
class VerifySMSSandboxPhoneNumberResult:
    def to_dict(self) -> dict[str, object]: ...



@final
class SNSClient:
    def __init__(
        self,
        *,
        region: str | None = None,
        profile: str | None = None,
        endpoint_url: str | None = None,
    ) -> None: ...

    async def add_permission(self, params: dict[str, object]) -> None: ...

    async def check_if_phone_number_is_opted_out(self, params: dict[str, object]) -> CheckIfPhoneNumberIsOptedOutResponse: ...

    async def confirm_subscription(self, params: dict[str, object]) -> ConfirmSubscriptionResponse: ...

    async def create_platform_application(self, params: dict[str, object]) -> CreatePlatformApplicationResponse: ...

    async def create_platform_endpoint(self, params: dict[str, object]) -> CreateEndpointResponse: ...

    async def create_sms_sandbox_phone_number(self, params: dict[str, object]) -> CreateSMSSandboxPhoneNumberResult: ...

    async def create_topic(self, params: dict[str, object]) -> CreateTopicResponse: ...

    async def delete_endpoint(self, params: dict[str, object]) -> None: ...

    async def delete_platform_application(self, params: dict[str, object]) -> None: ...

    async def delete_sms_sandbox_phone_number(self, params: dict[str, object]) -> DeleteSMSSandboxPhoneNumberResult: ...

    async def delete_topic(self, params: dict[str, object]) -> None: ...

    async def get_data_protection_policy(self, params: dict[str, object]) -> GetDataProtectionPolicyResponse: ...

    async def get_endpoint_attributes(self, params: dict[str, object]) -> GetEndpointAttributesResponse: ...

    async def get_platform_application_attributes(self, params: dict[str, object]) -> GetPlatformApplicationAttributesResponse: ...

    async def get_sms_attributes(self, params: dict[str, object]) -> GetSMSAttributesResponse: ...

    async def get_sms_sandbox_account_status(self, params: dict[str, object]) -> GetSMSSandboxAccountStatusResult: ...

    async def get_subscription_attributes(self, params: dict[str, object]) -> GetSubscriptionAttributesResponse: ...

    async def get_topic_attributes(self, params: dict[str, object]) -> GetTopicAttributesResponse: ...

    async def list_endpoints_by_platform_application(self, params: dict[str, object]) -> ListEndpointsByPlatformApplicationResponse: ...

    async def list_origination_numbers(self, params: dict[str, object]) -> ListOriginationNumbersResult: ...

    async def list_phone_numbers_opted_out(self, params: dict[str, object]) -> ListPhoneNumbersOptedOutResponse: ...

    async def list_platform_applications(self, params: dict[str, object]) -> ListPlatformApplicationsResponse: ...

    async def list_sms_sandbox_phone_numbers(self, params: dict[str, object]) -> ListSMSSandboxPhoneNumbersResult: ...

    async def list_subscriptions(self, params: dict[str, object]) -> ListSubscriptionsResponse: ...

    async def list_subscriptions_by_topic(self, params: dict[str, object]) -> ListSubscriptionsByTopicResponse: ...

    async def list_tags_for_resource(self, params: dict[str, object]) -> ListTagsForResourceResponse: ...

    async def list_topics(self, params: dict[str, object]) -> ListTopicsResponse: ...

    async def opt_in_phone_number(self, params: dict[str, object]) -> OptInPhoneNumberResponse: ...

    async def publish(self, params: dict[str, object]) -> PublishResponse: ...

    async def publish_batch(self, params: dict[str, object]) -> PublishBatchResponse: ...

    async def put_data_protection_policy(self, params: dict[str, object]) -> None: ...

    async def remove_permission(self, params: dict[str, object]) -> None: ...

    async def set_endpoint_attributes(self, params: dict[str, object]) -> None: ...

    async def set_platform_application_attributes(self, params: dict[str, object]) -> None: ...

    async def set_sms_attributes(self, params: dict[str, object]) -> SetSMSAttributesResponse: ...

    async def set_subscription_attributes(self, params: dict[str, object]) -> None: ...

    async def set_topic_attributes(self, params: dict[str, object]) -> None: ...

    async def subscribe(self, params: dict[str, object]) -> SubscribeResponse: ...

    async def tag_resource(self, params: dict[str, object]) -> TagResourceResponse: ...

    async def unsubscribe(self, params: dict[str, object]) -> None: ...

    async def untag_resource(self, params: dict[str, object]) -> UntagResourceResponse: ...

    async def verify_sms_sandbox_phone_number(self, params: dict[str, object]) -> VerifySMSSandboxPhoneNumberResult: ...
