# Generated by rboto-codegen. DO NOT EDIT.
from __future__ import annotations



from ._native import SNSClient as NativeClient, CheckIfPhoneNumberIsOptedOutResponse, ConfirmSubscriptionResponse, CreateEndpointResponse, CreatePlatformApplicationResponse, CreateSMSSandboxPhoneNumberResult, CreateTopicResponse, DeleteSMSSandboxPhoneNumberResult, GetDataProtectionPolicyResponse, GetEndpointAttributesResponse, GetPlatformApplicationAttributesResponse, GetSMSAttributesResponse, GetSMSSandboxAccountStatusResult, GetSubscriptionAttributesResponse, GetTopicAttributesResponse, ListEndpointsByPlatformApplicationResponse, ListOriginationNumbersResult, ListPhoneNumbersOptedOutResponse, ListPlatformApplicationsResponse, ListSMSSandboxPhoneNumbersResult, ListSubscriptionsByTopicResponse, ListSubscriptionsResponse, ListTagsForResourceResponse, ListTopicsResponse, OptInPhoneNumberResponse, PublishBatchResponse, PublishResponse, SetSMSAttributesResponse, SubscribeResponse, TagResourceResponse, UntagResourceResponse, VerifySMSSandboxPhoneNumberResult
from .types import (
    LanguageCodeString,
    MessageAttributeValue,
    PublishBatchRequestEntry,
    Tag,
)


class SNSClient:
    def __init__(
        self,
        *,
        region: str | None = None,
        profile: str | None = None,
        endpoint_url: str | None = None,
    ) -> None:
        self._native = NativeClient(
            region=region,
            profile=profile,
            endpoint_url=endpoint_url,
        )


    async def add_permission(
        self,
        *,
        topic_arn: str,
        label: str,
        aws_account_id: list[str],
        action_name: list[str],
    ) -> None:
        params: dict[str, object] = {
            "topic_arn": topic_arn,
            "label": label,
            "aws_account_id": aws_account_id,
            "action_name": action_name,
        }
        await self._native.add_permission(params)
        return None


    async def check_if_phone_number_is_opted_out(
        self,
        *,
        phone_number: str,
    ) -> CheckIfPhoneNumberIsOptedOutResponse:
        params: dict[str, object] = {
            "phone_number": phone_number,
        }
        result = await self._native.check_if_phone_number_is_opted_out(params)
        return result


    async def confirm_subscription(
        self,
        *,
        topic_arn: str,
        token: str,
        authenticate_on_unsubscribe: str | None = None,
    ) -> ConfirmSubscriptionResponse:
        params: dict[str, object] = {
            "topic_arn": topic_arn,
            "token": token,
        }
        if authenticate_on_unsubscribe is not None:
            params["authenticate_on_unsubscribe"] = authenticate_on_unsubscribe
        result = await self._native.confirm_subscription(params)
        return result


    async def create_platform_application(
        self,
        *,
        name: str,
        platform: str,
        attributes: dict[str, str],
    ) -> CreatePlatformApplicationResponse:
        params: dict[str, object] = {
            "name": name,
            "platform": platform,
            "attributes": attributes,
        }
        result = await self._native.create_platform_application(params)
        return result


    async def create_platform_endpoint(
        self,
        *,
        platform_application_arn: str,
        token: str,
        custom_user_data: str | None = None,
        attributes: dict[str, str] | None = None,
    ) -> CreateEndpointResponse:
        params: dict[str, object] = {
            "platform_application_arn": platform_application_arn,
            "token": token,
        }
        if custom_user_data is not None:
            params["custom_user_data"] = custom_user_data
        if attributes is not None:
            params["attributes"] = attributes
        result = await self._native.create_platform_endpoint(params)
        return result


    async def create_sms_sandbox_phone_number(
        self,
        *,
        phone_number: str,
        language_code: LanguageCodeString | None = None,
    ) -> CreateSMSSandboxPhoneNumberResult:
        params: dict[str, object] = {
            "phone_number": phone_number,
        }
        if language_code is not None:
            params["language_code"] = language_code
        result = await self._native.create_sms_sandbox_phone_number(params)
        return result


    async def create_topic(
        self,
        *,
        name: str,
        attributes: dict[str, str] | None = None,
        tags: list[Tag] | None = None,
        data_protection_policy: str | None = None,
    ) -> CreateTopicResponse:
        params: dict[str, object] = {
            "name": name,
        }
        if attributes is not None:
            params["attributes"] = attributes
        if tags is not None:
            params["tags"] = tags
        if data_protection_policy is not None:
            params["data_protection_policy"] = data_protection_policy
        result = await self._native.create_topic(params)
        return result


    async def delete_endpoint(
        self,
        *,
        endpoint_arn: str,
    ) -> None:
        params: dict[str, object] = {
            "endpoint_arn": endpoint_arn,
        }
        await self._native.delete_endpoint(params)
        return None


    async def delete_platform_application(
        self,
        *,
        platform_application_arn: str,
    ) -> None:
        params: dict[str, object] = {
            "platform_application_arn": platform_application_arn,
        }
        await self._native.delete_platform_application(params)
        return None


    async def delete_sms_sandbox_phone_number(
        self,
        *,
        phone_number: str,
    ) -> DeleteSMSSandboxPhoneNumberResult:
        params: dict[str, object] = {
            "phone_number": phone_number,
        }
        result = await self._native.delete_sms_sandbox_phone_number(params)
        return result


    async def delete_topic(
        self,
        *,
        topic_arn: str,
    ) -> None:
        params: dict[str, object] = {
            "topic_arn": topic_arn,
        }
        await self._native.delete_topic(params)
        return None


    async def get_data_protection_policy(
        self,
        *,
        resource_arn: str,
    ) -> GetDataProtectionPolicyResponse:
        params: dict[str, object] = {
            "resource_arn": resource_arn,
        }
        result = await self._native.get_data_protection_policy(params)
        return result


    async def get_endpoint_attributes(
        self,
        *,
        endpoint_arn: str,
    ) -> GetEndpointAttributesResponse:
        params: dict[str, object] = {
            "endpoint_arn": endpoint_arn,
        }
        result = await self._native.get_endpoint_attributes(params)
        return result


    async def get_platform_application_attributes(
        self,
        *,
        platform_application_arn: str,
    ) -> GetPlatformApplicationAttributesResponse:
        params: dict[str, object] = {
            "platform_application_arn": platform_application_arn,
        }
        result = await self._native.get_platform_application_attributes(params)
        return result


    async def get_sms_attributes(
        self,
        *,
        attributes: list[str] | None = None,
    ) -> GetSMSAttributesResponse:
        params: dict[str, object] = {
        }
        if attributes is not None:
            params["attributes"] = attributes
        result = await self._native.get_sms_attributes(params)
        return result


    async def get_sms_sandbox_account_status(
        self,
    ) -> GetSMSSandboxAccountStatusResult:
        params: dict[str, object] = {
        }
        result = await self._native.get_sms_sandbox_account_status(params)
        return result


    async def get_subscription_attributes(
        self,
        *,
        subscription_arn: str,
    ) -> GetSubscriptionAttributesResponse:
        params: dict[str, object] = {
            "subscription_arn": subscription_arn,
        }
        result = await self._native.get_subscription_attributes(params)
        return result


    async def get_topic_attributes(
        self,
        *,
        topic_arn: str,
    ) -> GetTopicAttributesResponse:
        params: dict[str, object] = {
            "topic_arn": topic_arn,
        }
        result = await self._native.get_topic_attributes(params)
        return result


    async def list_endpoints_by_platform_application(
        self,
        *,
        platform_application_arn: str,
        next_token: str | None = None,
    ) -> ListEndpointsByPlatformApplicationResponse:
        params: dict[str, object] = {
            "platform_application_arn": platform_application_arn,
        }
        if next_token is not None:
            params["next_token"] = next_token
        result = await self._native.list_endpoints_by_platform_application(params)
        return result


    async def list_origination_numbers(
        self,
        *,
        next_token: str | None = None,
        max_results: int | None = None,
    ) -> ListOriginationNumbersResult:
        params: dict[str, object] = {
        }
        if next_token is not None:
            params["next_token"] = next_token
        if max_results is not None:
            params["max_results"] = max_results
        result = await self._native.list_origination_numbers(params)
        return result


    async def list_phone_numbers_opted_out(
        self,
        *,
        next_token: str | None = None,
    ) -> ListPhoneNumbersOptedOutResponse:
        params: dict[str, object] = {
        }
        if next_token is not None:
            params["next_token"] = next_token
        result = await self._native.list_phone_numbers_opted_out(params)
        return result


    async def list_platform_applications(
        self,
        *,
        next_token: str | None = None,
    ) -> ListPlatformApplicationsResponse:
        params: dict[str, object] = {
        }
        if next_token is not None:
            params["next_token"] = next_token
        result = await self._native.list_platform_applications(params)
        return result


    async def list_sms_sandbox_phone_numbers(
        self,
        *,
        next_token: str | None = None,
        max_results: int | None = None,
    ) -> ListSMSSandboxPhoneNumbersResult:
        params: dict[str, object] = {
        }
        if next_token is not None:
            params["next_token"] = next_token
        if max_results is not None:
            params["max_results"] = max_results
        result = await self._native.list_sms_sandbox_phone_numbers(params)
        return result


    async def list_subscriptions(
        self,
        *,
        next_token: str | None = None,
    ) -> ListSubscriptionsResponse:
        params: dict[str, object] = {
        }
        if next_token is not None:
            params["next_token"] = next_token
        result = await self._native.list_subscriptions(params)
        return result


    async def list_subscriptions_by_topic(
        self,
        *,
        topic_arn: str,
        next_token: str | None = None,
    ) -> ListSubscriptionsByTopicResponse:
        params: dict[str, object] = {
            "topic_arn": topic_arn,
        }
        if next_token is not None:
            params["next_token"] = next_token
        result = await self._native.list_subscriptions_by_topic(params)
        return result


    async def list_tags_for_resource(
        self,
        *,
        resource_arn: str,
    ) -> ListTagsForResourceResponse:
        params: dict[str, object] = {
            "resource_arn": resource_arn,
        }
        result = await self._native.list_tags_for_resource(params)
        return result


    async def list_topics(
        self,
        *,
        next_token: str | None = None,
    ) -> ListTopicsResponse:
        params: dict[str, object] = {
        }
        if next_token is not None:
            params["next_token"] = next_token
        result = await self._native.list_topics(params)
        return result


    async def opt_in_phone_number(
        self,
        *,
        phone_number: str,
    ) -> OptInPhoneNumberResponse:
        params: dict[str, object] = {
            "phone_number": phone_number,
        }
        result = await self._native.opt_in_phone_number(params)
        return result


    async def publish(
        self,
        *,
        message: str,
        topic_arn: str | None = None,
        target_arn: str | None = None,
        phone_number: str | None = None,
        subject: str | None = None,
        message_structure: str | None = None,
        message_attributes: dict[str, MessageAttributeValue] | None = None,
        message_deduplication_id: str | None = None,
        message_group_id: str | None = None,
    ) -> PublishResponse:
        params: dict[str, object] = {
            "message": message,
        }
        if topic_arn is not None:
            params["topic_arn"] = topic_arn
        if target_arn is not None:
            params["target_arn"] = target_arn
        if phone_number is not None:
            params["phone_number"] = phone_number
        if subject is not None:
            params["subject"] = subject
        if message_structure is not None:
            params["message_structure"] = message_structure
        if message_attributes is not None:
            params["message_attributes"] = message_attributes
        if message_deduplication_id is not None:
            params["message_deduplication_id"] = message_deduplication_id
        if message_group_id is not None:
            params["message_group_id"] = message_group_id
        result = await self._native.publish(params)
        return result


    async def publish_batch(
        self,
        *,
        topic_arn: str,
        publish_batch_request_entries: list[PublishBatchRequestEntry],
    ) -> PublishBatchResponse:
        params: dict[str, object] = {
            "topic_arn": topic_arn,
            "publish_batch_request_entries": publish_batch_request_entries,
        }
        result = await self._native.publish_batch(params)
        return result


    async def put_data_protection_policy(
        self,
        *,
        resource_arn: str,
        data_protection_policy: str,
    ) -> None:
        params: dict[str, object] = {
            "resource_arn": resource_arn,
            "data_protection_policy": data_protection_policy,
        }
        await self._native.put_data_protection_policy(params)
        return None


    async def remove_permission(
        self,
        *,
        topic_arn: str,
        label: str,
    ) -> None:
        params: dict[str, object] = {
            "topic_arn": topic_arn,
            "label": label,
        }
        await self._native.remove_permission(params)
        return None


    async def set_endpoint_attributes(
        self,
        *,
        endpoint_arn: str,
        attributes: dict[str, str],
    ) -> None:
        params: dict[str, object] = {
            "endpoint_arn": endpoint_arn,
            "attributes": attributes,
        }
        await self._native.set_endpoint_attributes(params)
        return None


    async def set_platform_application_attributes(
        self,
        *,
        platform_application_arn: str,
        attributes: dict[str, str],
    ) -> None:
        params: dict[str, object] = {
            "platform_application_arn": platform_application_arn,
            "attributes": attributes,
        }
        await self._native.set_platform_application_attributes(params)
        return None


    async def set_sms_attributes(
        self,
        *,
        attributes: dict[str, str],
    ) -> SetSMSAttributesResponse:
        params: dict[str, object] = {
            "attributes": attributes,
        }
        result = await self._native.set_sms_attributes(params)
        return result


    async def set_subscription_attributes(
        self,
        *,
        subscription_arn: str,
        attribute_name: str,
        attribute_value: str | None = None,
    ) -> None:
        params: dict[str, object] = {
            "subscription_arn": subscription_arn,
            "attribute_name": attribute_name,
        }
        if attribute_value is not None:
            params["attribute_value"] = attribute_value
        await self._native.set_subscription_attributes(params)
        return None


    async def set_topic_attributes(
        self,
        *,
        topic_arn: str,
        attribute_name: str,
        attribute_value: str | None = None,
    ) -> None:
        params: dict[str, object] = {
            "topic_arn": topic_arn,
            "attribute_name": attribute_name,
        }
        if attribute_value is not None:
            params["attribute_value"] = attribute_value
        await self._native.set_topic_attributes(params)
        return None


    async def subscribe(
        self,
        *,
        topic_arn: str,
        protocol: str,
        endpoint: str | None = None,
        attributes: dict[str, str] | None = None,
        return_subscription_arn: bool | None = None,
    ) -> SubscribeResponse:
        params: dict[str, object] = {
            "topic_arn": topic_arn,
            "protocol": protocol,
        }
        if endpoint is not None:
            params["endpoint"] = endpoint
        if attributes is not None:
            params["attributes"] = attributes
        if return_subscription_arn is not None:
            params["return_subscription_arn"] = return_subscription_arn
        result = await self._native.subscribe(params)
        return result


    async def tag_resource(
        self,
        *,
        resource_arn: str,
        tags: list[Tag],
    ) -> TagResourceResponse:
        params: dict[str, object] = {
            "resource_arn": resource_arn,
            "tags": tags,
        }
        result = await self._native.tag_resource(params)
        return result


    async def unsubscribe(
        self,
        *,
        subscription_arn: str,
    ) -> None:
        params: dict[str, object] = {
            "subscription_arn": subscription_arn,
        }
        await self._native.unsubscribe(params)
        return None


    async def untag_resource(
        self,
        *,
        resource_arn: str,
        tag_keys: list[str],
    ) -> UntagResourceResponse:
        params: dict[str, object] = {
            "resource_arn": resource_arn,
            "tag_keys": tag_keys,
        }
        result = await self._native.untag_resource(params)
        return result


    async def verify_sms_sandbox_phone_number(
        self,
        *,
        phone_number: str,
        one_time_password: str,
    ) -> VerifySMSSandboxPhoneNumberResult:
        params: dict[str, object] = {
            "phone_number": phone_number,
            "one_time_password": one_time_password,
        }
        result = await self._native.verify_sms_sandbox_phone_number(params)
        return result
