# Generated by rboto-codegen. DO NOT EDIT.
from rboto.exceptions import ServiceError


class SNSError(ServiceError):
    """Base exception for errors returned by sns."""


class AuthorizationError(SNSError):
    """Modeled sns error: AuthorizationErrorException."""


class BatchEntryIdsNotDistinctError(SNSError):
    """Modeled sns error: BatchEntryIdsNotDistinctException."""


class BatchRequestTooLongError(SNSError):
    """Modeled sns error: BatchRequestTooLongException."""


class ConcurrentAccessError(SNSError):
    """Modeled sns error: ConcurrentAccessException."""


class EmptyBatchRequestError(SNSError):
    """Modeled sns error: EmptyBatchRequestException."""


class EndpointDisabledError(SNSError):
    """Modeled sns error: EndpointDisabledException."""


class FilterPolicyLimitExceededError(SNSError):
    """Modeled sns error: FilterPolicyLimitExceededException."""


class InternalError(SNSError):
    """Modeled sns error: InternalErrorException."""


class InvalidBatchEntryIdError(SNSError):
    """Modeled sns error: InvalidBatchEntryIdException."""


class InvalidParameterError(SNSError):
    """Modeled sns error: InvalidParameterException."""


class InvalidParameterValueError(SNSError):
    """Modeled sns error: InvalidParameterValueException."""


class InvalidSecurityError(SNSError):
    """Modeled sns error: InvalidSecurityException."""


class InvalidStateError(SNSError):
    """Modeled sns error: InvalidStateException."""


class KMSAccessDeniedError(SNSError):
    """Modeled sns error: KMSAccessDeniedException."""


class KMSDisabledError(SNSError):
    """Modeled sns error: KMSDisabledException."""


class KMSInvalidStateError(SNSError):
    """Modeled sns error: KMSInvalidStateException."""


class KMSNotFoundError(SNSError):
    """Modeled sns error: KMSNotFoundException."""


class KMSOptInRequiredError(SNSError):
    """Modeled sns error: KMSOptInRequired."""


class KMSThrottlingError(SNSError):
    """Modeled sns error: KMSThrottlingException."""


class NotFoundError(SNSError):
    """Modeled sns error: NotFoundException."""


class OptedOutError(SNSError):
    """Modeled sns error: OptedOutException."""


class PlatformApplicationDisabledError(SNSError):
    """Modeled sns error: PlatformApplicationDisabledException."""


class ReplayLimitExceededError(SNSError):
    """Modeled sns error: ReplayLimitExceededException."""


class ResourceNotFoundError(SNSError):
    """Modeled sns error: ResourceNotFoundException."""


class StaleTagError(SNSError):
    """Modeled sns error: StaleTagException."""


class SubscriptionLimitExceededError(SNSError):
    """Modeled sns error: SubscriptionLimitExceededException."""


class TagLimitExceededError(SNSError):
    """Modeled sns error: TagLimitExceededException."""


class TagPolicyError(SNSError):
    """Modeled sns error: TagPolicyException."""


class ThrottledError(SNSError):
    """Modeled sns error: ThrottledException."""


class TooManyEntriesInBatchRequestError(SNSError):
    """Modeled sns error: TooManyEntriesInBatchRequestException."""


class TopicLimitExceededError(SNSError):
    """Modeled sns error: TopicLimitExceededException."""


class UserError(SNSError):
    """Modeled sns error: UserErrorException."""


class ValidationError(SNSError):
    """Modeled sns error: ValidationException."""


class VerificationError(SNSError):
    """Modeled sns error: VerificationException."""
