# Generated by rboto-codegen. DO NOT EDIT.
from __future__ import annotations

from typing import Literal, NotRequired, Required, TypeAlias, TypedDict

from ._native import ByteStream as ByteStream

LanguageCodeString: TypeAlias = Literal['en-US', 'en-GB', 'es-419', 'es-ES', 'de-DE', 'fr-CA', 'fr-FR', 'it-IT', 'ja-JP', 'pt-BR', 'kr-KR', 'zh-CN', 'zh-TW']
NumberCapability: TypeAlias = Literal['SMS', 'MMS', 'VOICE']
RouteType: TypeAlias = Literal['Transactional', 'Promotional', 'Premium']
SMSSandboxPhoneNumberVerificationStatus: TypeAlias = Literal['Pending', 'Verified']

AddPermissionInput = TypedDict(
    "AddPermissionInput",
    {
    "topic_arn": Required["str"],
    "label": Required["str"],
    "aws_account_id": Required["list[str]"],
    "action_name": Required["list[str]"],
    },
)

BatchResultErrorEntry = TypedDict(
    "BatchResultErrorEntry",
    {
    "id": Required["str"],
    "code": Required["str"],
    "message": NotRequired["str"],
    "sender_fault": Required["bool"],
    },
)

CheckIfPhoneNumberIsOptedOutInput = TypedDict(
    "CheckIfPhoneNumberIsOptedOutInput",
    {
    "phone_number": Required["str"],
    },
)

ConfirmSubscriptionInput = TypedDict(
    "ConfirmSubscriptionInput",
    {
    "topic_arn": Required["str"],
    "token": Required["str"],
    "authenticate_on_unsubscribe": NotRequired["str"],
    },
)

CreatePlatformApplicationInput = TypedDict(
    "CreatePlatformApplicationInput",
    {
    "name": Required["str"],
    "platform": Required["str"],
    "attributes": Required["dict[str, str]"],
    },
)

CreatePlatformEndpointInput = TypedDict(
    "CreatePlatformEndpointInput",
    {
    "platform_application_arn": Required["str"],
    "token": Required["str"],
    "custom_user_data": NotRequired["str"],
    "attributes": NotRequired["dict[str, str]"],
    },
)

CreateSMSSandboxPhoneNumberInput = TypedDict(
    "CreateSMSSandboxPhoneNumberInput",
    {
    "phone_number": Required["str"],
    "language_code": NotRequired["LanguageCodeString"],
    },
)

CreateTopicInput = TypedDict(
    "CreateTopicInput",
    {
    "name": Required["str"],
    "attributes": NotRequired["dict[str, str]"],
    "tags": NotRequired["list[Tag]"],
    "data_protection_policy": NotRequired["str"],
    },
)

DeleteEndpointInput = TypedDict(
    "DeleteEndpointInput",
    {
    "endpoint_arn": Required["str"],
    },
)

DeletePlatformApplicationInput = TypedDict(
    "DeletePlatformApplicationInput",
    {
    "platform_application_arn": Required["str"],
    },
)

DeleteSMSSandboxPhoneNumberInput = TypedDict(
    "DeleteSMSSandboxPhoneNumberInput",
    {
    "phone_number": Required["str"],
    },
)

DeleteTopicInput = TypedDict(
    "DeleteTopicInput",
    {
    "topic_arn": Required["str"],
    },
)

Endpoint = TypedDict(
    "Endpoint",
    {
    "endpoint_arn": NotRequired["str"],
    "attributes": NotRequired["dict[str, str]"],
    },
)

GetDataProtectionPolicyInput = TypedDict(
    "GetDataProtectionPolicyInput",
    {
    "resource_arn": Required["str"],
    },
)

GetEndpointAttributesInput = TypedDict(
    "GetEndpointAttributesInput",
    {
    "endpoint_arn": Required["str"],
    },
)

GetPlatformApplicationAttributesInput = TypedDict(
    "GetPlatformApplicationAttributesInput",
    {
    "platform_application_arn": Required["str"],
    },
)

GetSMSAttributesInput = TypedDict(
    "GetSMSAttributesInput",
    {
    "attributes": NotRequired["list[str]"],
    },
)

GetSMSSandboxAccountStatusInput = TypedDict(
    "GetSMSSandboxAccountStatusInput",
    {
    },
)

GetSubscriptionAttributesInput = TypedDict(
    "GetSubscriptionAttributesInput",
    {
    "subscription_arn": Required["str"],
    },
)

GetTopicAttributesInput = TypedDict(
    "GetTopicAttributesInput",
    {
    "topic_arn": Required["str"],
    },
)

ListEndpointsByPlatformApplicationInput = TypedDict(
    "ListEndpointsByPlatformApplicationInput",
    {
    "platform_application_arn": Required["str"],
    "next_token": NotRequired["str"],
    },
)

ListOriginationNumbersRequest = TypedDict(
    "ListOriginationNumbersRequest",
    {
    "next_token": NotRequired["str"],
    "max_results": NotRequired["int"],
    },
)

ListPhoneNumbersOptedOutInput = TypedDict(
    "ListPhoneNumbersOptedOutInput",
    {
    "next_token": NotRequired["str"],
    },
)

ListPlatformApplicationsInput = TypedDict(
    "ListPlatformApplicationsInput",
    {
    "next_token": NotRequired["str"],
    },
)

ListSMSSandboxPhoneNumbersInput = TypedDict(
    "ListSMSSandboxPhoneNumbersInput",
    {
    "next_token": NotRequired["str"],
    "max_results": NotRequired["int"],
    },
)

ListSubscriptionsByTopicInput = TypedDict(
    "ListSubscriptionsByTopicInput",
    {
    "topic_arn": Required["str"],
    "next_token": NotRequired["str"],
    },
)

ListSubscriptionsInput = TypedDict(
    "ListSubscriptionsInput",
    {
    "next_token": NotRequired["str"],
    },
)

ListTagsForResourceRequest = TypedDict(
    "ListTagsForResourceRequest",
    {
    "resource_arn": Required["str"],
    },
)

ListTopicsInput = TypedDict(
    "ListTopicsInput",
    {
    "next_token": NotRequired["str"],
    },
)

MessageAttributeValue = TypedDict(
    "MessageAttributeValue",
    {
    "data_type": Required["str"],
    "string_value": NotRequired["str"],
    "binary_value": NotRequired["bytes"],
    },
)

OptInPhoneNumberInput = TypedDict(
    "OptInPhoneNumberInput",
    {
    "phone_number": Required["str"],
    },
)

PhoneNumberInformation = TypedDict(
    "PhoneNumberInformation",
    {
    "created_at": NotRequired["str"],
    "phone_number": NotRequired["str"],
    "status": NotRequired["str"],
    "iso2_country_code": NotRequired["str"],
    "route_type": NotRequired["RouteType"],
    "number_capabilities": NotRequired["list[NumberCapability]"],
    },
)

PlatformApplication = TypedDict(
    "PlatformApplication",
    {
    "platform_application_arn": NotRequired["str"],
    "attributes": NotRequired["dict[str, str]"],
    },
)

PublishBatchInput = TypedDict(
    "PublishBatchInput",
    {
    "topic_arn": Required["str"],
    "publish_batch_request_entries": Required["list[PublishBatchRequestEntry]"],
    },
)

PublishBatchRequestEntry = TypedDict(
    "PublishBatchRequestEntry",
    {
    "id": Required["str"],
    "message": Required["str"],
    "subject": NotRequired["str"],
    "message_structure": NotRequired["str"],
    "message_attributes": NotRequired["dict[str, MessageAttributeValue]"],
    "message_deduplication_id": NotRequired["str"],
    "message_group_id": NotRequired["str"],
    },
)

PublishBatchResultEntry = TypedDict(
    "PublishBatchResultEntry",
    {
    "id": NotRequired["str"],
    "message_id": NotRequired["str"],
    "sequence_number": NotRequired["str"],
    },
)

PublishInput = TypedDict(
    "PublishInput",
    {
    "topic_arn": NotRequired["str"],
    "target_arn": NotRequired["str"],
    "phone_number": NotRequired["str"],
    "message": Required["str"],
    "subject": NotRequired["str"],
    "message_structure": NotRequired["str"],
    "message_attributes": NotRequired["dict[str, MessageAttributeValue]"],
    "message_deduplication_id": NotRequired["str"],
    "message_group_id": NotRequired["str"],
    },
)

PutDataProtectionPolicyInput = TypedDict(
    "PutDataProtectionPolicyInput",
    {
    "resource_arn": Required["str"],
    "data_protection_policy": Required["str"],
    },
)

RemovePermissionInput = TypedDict(
    "RemovePermissionInput",
    {
    "topic_arn": Required["str"],
    "label": Required["str"],
    },
)

SMSSandboxPhoneNumber = TypedDict(
    "SMSSandboxPhoneNumber",
    {
    "phone_number": NotRequired["str"],
    "status": NotRequired["SMSSandboxPhoneNumberVerificationStatus"],
    },
)

SetEndpointAttributesInput = TypedDict(
    "SetEndpointAttributesInput",
    {
    "endpoint_arn": Required["str"],
    "attributes": Required["dict[str, str]"],
    },
)

SetPlatformApplicationAttributesInput = TypedDict(
    "SetPlatformApplicationAttributesInput",
    {
    "platform_application_arn": Required["str"],
    "attributes": Required["dict[str, str]"],
    },
)

SetSMSAttributesInput = TypedDict(
    "SetSMSAttributesInput",
    {
    "attributes": Required["dict[str, str]"],
    },
)

SetSubscriptionAttributesInput = TypedDict(
    "SetSubscriptionAttributesInput",
    {
    "subscription_arn": Required["str"],
    "attribute_name": Required["str"],
    "attribute_value": NotRequired["str"],
    },
)

SetTopicAttributesInput = TypedDict(
    "SetTopicAttributesInput",
    {
    "topic_arn": Required["str"],
    "attribute_name": Required["str"],
    "attribute_value": NotRequired["str"],
    },
)

SubscribeInput = TypedDict(
    "SubscribeInput",
    {
    "topic_arn": Required["str"],
    "protocol": Required["str"],
    "endpoint": NotRequired["str"],
    "attributes": NotRequired["dict[str, str]"],
    "return_subscription_arn": NotRequired["bool"],
    },
)

Subscription = TypedDict(
    "Subscription",
    {
    "subscription_arn": NotRequired["str"],
    "owner": NotRequired["str"],
    "protocol": NotRequired["str"],
    "endpoint": NotRequired["str"],
    "topic_arn": NotRequired["str"],
    },
)

Tag = TypedDict(
    "Tag",
    {
    "key": Required["str"],
    "value": Required["str"],
    },
)

TagResourceRequest = TypedDict(
    "TagResourceRequest",
    {
    "resource_arn": Required["str"],
    "tags": Required["list[Tag]"],
    },
)

Topic = TypedDict(
    "Topic",
    {
    "topic_arn": NotRequired["str"],
    },
)

UnsubscribeInput = TypedDict(
    "UnsubscribeInput",
    {
    "subscription_arn": Required["str"],
    },
)

UntagResourceRequest = TypedDict(
    "UntagResourceRequest",
    {
    "resource_arn": Required["str"],
    "tag_keys": Required["list[str]"],
    },
)

VerifySMSSandboxPhoneNumberInput = TypedDict(
    "VerifySMSSandboxPhoneNumberInput",
    {
    "phone_number": Required["str"],
    "one_time_password": Required["str"],
    },
)
