service_id = "dynamodb"
python_name = "dynamodb"
distribution_name = "rboto-dynamodb"
python_package = "rboto_dynamodb"
client_class = "DynamoDBClient"
adapter_crate = "rboto-dynamodb-native"
rust_crate = "aws-sdk-dynamodb"
rust_module = "aws_sdk_dynamodb"
rust_crate_version = "1.102.0"
model_url = "https://raw.githubusercontent.com/awslabs/aws-sdk-rust/release-2026-01-15/aws-models/dynamodb.json"
model_sha256 = "d792ebabba602e08708515d3284b04e86b9c305e718189f9f95193d5b2c65b00"
aws_model_hash = "d05477eb1c9a85fdb84c3ffce5a061334126f1e8f44f03261f91e228dc4f08de"
smithy_codegen_revision = "79844ddd1a666a9d7020f5ac97746b5a578548fd"
customization = "dynamodb"
native_outputs = true
