service_id = "s3"
python_name = "s3"
distribution_name = "rboto-s3"
python_package = "rboto_s3"
client_class = "S3Client"
adapter_crate = "rboto-s3-native"
rust_crate = "aws-sdk-s3"
rust_module = "aws_sdk_s3"
rust_crate_version = "1.120.0"
model_url = "https://raw.githubusercontent.com/awslabs/aws-sdk-rust/release-2026-01-15/aws-models/s3.json"
model_sha256 = "0d26aa14aaebfb5fe0cb54822bcbe3cd8e3793ca19d059e824bff7bdf96c7a50"
aws_model_hash = "bfef977d8d97b60e00731c40167a8e53cf9a34aa25de64ccabdc63624081b279"
smithy_codegen_revision = "79844ddd1a666a9d7020f5ac97746b5a578548fd"
customization = "s3"
force_path_style_for_custom_endpoint = true
