service_id = "sns"
python_name = "sns"
distribution_name = "rboto-sns"
python_package = "rboto_sns"
client_class = "SNSClient"
adapter_crate = "rboto-sns-native"
rust_crate = "aws-sdk-sns"
rust_module = "aws_sdk_sns"
rust_crate_version = "1.93.0"
model_url = "https://raw.githubusercontent.com/awslabs/aws-sdk-rust/release-2026-01-15/aws-models/sns.json"
model_sha256 = "fa11f51b7c1dff24ef25007520253c27618905365cc67d5d7aa00700dcbc5e14"
aws_model_hash = "d21982672cd87d725ad6a0ebd7daae6068643b9650dd4b9363c54baa78308191"
smithy_codegen_revision = "79844ddd1a666a9d7020f5ac97746b5a578548fd"
native_outputs = true
