from __future__ import annotations

from collections.abc import AsyncIterator
from typing import final


@final
class ByteStream:
    def __aiter__(self) -> AsyncIterator[bytes]: ...
    async def __anext__(self) -> bytes: ...
    async def read(self) -> bytes: ...



@final
class ArchivalSummary:
    @property
    def archival_date_time(self) -> str | None: ...
    @property
    def archival_reason(self) -> str | None: ...
    @property
    def archival_backup_arn(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class AttributeDefinition:
    @property
    def attribute_name(self) -> str: ...
    @property
    def attribute_type(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class AutoScalingPolicyDescription:
    @property
    def policy_name(self) -> str | None: ...
    @property
    def target_tracking_scaling_policy_configuration(self) -> AutoScalingTargetTrackingScalingPolicyConfigurationDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class AutoScalingSettingsDescription:
    @property
    def minimum_units(self) -> int | None: ...
    @property
    def maximum_units(self) -> int | None: ...
    @property
    def auto_scaling_disabled(self) -> bool | None: ...
    @property
    def auto_scaling_role_arn(self) -> str | None: ...
    @property
    def scaling_policies(self) -> list[AutoScalingPolicyDescription] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class AutoScalingTargetTrackingScalingPolicyConfigurationDescription:
    @property
    def disable_scale_in(self) -> bool | None: ...
    @property
    def scale_in_cooldown(self) -> int | None: ...
    @property
    def scale_out_cooldown(self) -> int | None: ...
    @property
    def target_value(self) -> float: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class BackupDescription:
    @property
    def backup_details(self) -> BackupDetails | None: ...
    @property
    def source_table_details(self) -> SourceTableDetails | None: ...
    @property
    def source_table_feature_details(self) -> SourceTableFeatureDetails | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class BackupDetails:
    @property
    def backup_arn(self) -> str: ...
    @property
    def backup_name(self) -> str: ...
    @property
    def backup_size_bytes(self) -> int | None: ...
    @property
    def backup_status(self) -> str: ...
    @property
    def backup_type(self) -> str: ...
    @property
    def backup_creation_date_time(self) -> str: ...
    @property
    def backup_expiry_date_time(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class BackupSummary:
    @property
    def table_name(self) -> str | None: ...
    @property
    def table_id(self) -> str | None: ...
    @property
    def table_arn(self) -> str | None: ...
    @property
    def backup_arn(self) -> str | None: ...
    @property
    def backup_name(self) -> str | None: ...
    @property
    def backup_creation_date_time(self) -> str | None: ...
    @property
    def backup_expiry_date_time(self) -> str | None: ...
    @property
    def backup_status(self) -> str | None: ...
    @property
    def backup_type(self) -> str | None: ...
    @property
    def backup_size_bytes(self) -> int | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class BatchStatementError:
    @property
    def code(self) -> str | None: ...
    @property
    def message(self) -> str | None: ...
    @property
    def item(self) -> dict[str, dict[str, object]] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class BatchStatementResponse:
    @property
    def error(self) -> BatchStatementError | None: ...
    @property
    def table_name(self) -> str | None: ...
    @property
    def item(self) -> dict[str, dict[str, object]] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class BillingModeSummary:
    @property
    def billing_mode(self) -> str | None: ...
    @property
    def last_update_to_pay_per_request_date_time(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Capacity:
    @property
    def read_capacity_units(self) -> float | None: ...
    @property
    def write_capacity_units(self) -> float | None: ...
    @property
    def capacity_units(self) -> float | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ConsumedCapacity:
    @property
    def table_name(self) -> str | None: ...
    @property
    def capacity_units(self) -> float | None: ...
    @property
    def read_capacity_units(self) -> float | None: ...
    @property
    def write_capacity_units(self) -> float | None: ...
    @property
    def table(self) -> Capacity | None: ...
    @property
    def local_secondary_indexes(self) -> dict[str, Capacity] | None: ...
    @property
    def global_secondary_indexes(self) -> dict[str, Capacity] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ContinuousBackupsDescription:
    @property
    def continuous_backups_status(self) -> str: ...
    @property
    def point_in_time_recovery_description(self) -> PointInTimeRecoveryDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ContributorInsightsSummary:
    @property
    def table_name(self) -> str | None: ...
    @property
    def index_name(self) -> str | None: ...
    @property
    def contributor_insights_status(self) -> str | None: ...
    @property
    def contributor_insights_mode(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CsvOptions:
    @property
    def delimiter(self) -> str | None: ...
    @property
    def header_list(self) -> list[str] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DeleteRequest:
    @property
    def key(self) -> dict[str, dict[str, object]]: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class EnableKinesisStreamingConfiguration:
    @property
    def approximate_creation_date_time_precision(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Endpoint:
    @property
    def address(self) -> str: ...
    @property
    def cache_period_in_minutes(self) -> int: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ExportDescription:
    @property
    def export_arn(self) -> str | None: ...
    @property
    def export_status(self) -> str | None: ...
    @property
    def start_time(self) -> str | None: ...
    @property
    def end_time(self) -> str | None: ...
    @property
    def export_manifest(self) -> str | None: ...
    @property
    def table_arn(self) -> str | None: ...
    @property
    def table_id(self) -> str | None: ...
    @property
    def export_time(self) -> str | None: ...
    @property
    def client_token(self) -> str | None: ...
    @property
    def s3_bucket(self) -> str | None: ...
    @property
    def s3_bucket_owner(self) -> str | None: ...
    @property
    def s3_prefix(self) -> str | None: ...
    @property
    def s3_sse_algorithm(self) -> str | None: ...
    @property
    def s3_sse_kms_key_id(self) -> str | None: ...
    @property
    def failure_code(self) -> str | None: ...
    @property
    def failure_message(self) -> str | None: ...
    @property
    def export_format(self) -> str | None: ...
    @property
    def billed_size_bytes(self) -> int | None: ...
    @property
    def item_count(self) -> int | None: ...
    @property
    def export_type(self) -> str | None: ...
    @property
    def incremental_export_specification(self) -> IncrementalExportSpecification | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ExportSummary:
    @property
    def export_arn(self) -> str | None: ...
    @property
    def export_status(self) -> str | None: ...
    @property
    def export_type(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class FailureException:
    @property
    def exception_name(self) -> str | None: ...
    @property
    def exception_description(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GlobalSecondaryIndex:
    @property
    def index_name(self) -> str: ...
    @property
    def key_schema(self) -> list[KeySchemaElement]: ...
    @property
    def projection(self) -> Projection | None: ...
    @property
    def provisioned_throughput(self) -> ProvisionedThroughput | None: ...
    @property
    def on_demand_throughput(self) -> OnDemandThroughput | None: ...
    @property
    def warm_throughput(self) -> WarmThroughput | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GlobalSecondaryIndexDescription:
    @property
    def index_name(self) -> str | None: ...
    @property
    def key_schema(self) -> list[KeySchemaElement] | None: ...
    @property
    def projection(self) -> Projection | None: ...
    @property
    def index_status(self) -> str | None: ...
    @property
    def backfilling(self) -> bool | None: ...
    @property
    def provisioned_throughput(self) -> ProvisionedThroughputDescription | None: ...
    @property
    def index_size_bytes(self) -> int | None: ...
    @property
    def item_count(self) -> int | None: ...
    @property
    def index_arn(self) -> str | None: ...
    @property
    def on_demand_throughput(self) -> OnDemandThroughput | None: ...
    @property
    def warm_throughput(self) -> GlobalSecondaryIndexWarmThroughputDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GlobalSecondaryIndexInfo:
    @property
    def index_name(self) -> str | None: ...
    @property
    def key_schema(self) -> list[KeySchemaElement] | None: ...
    @property
    def projection(self) -> Projection | None: ...
    @property
    def provisioned_throughput(self) -> ProvisionedThroughput | None: ...
    @property
    def on_demand_throughput(self) -> OnDemandThroughput | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GlobalSecondaryIndexWarmThroughputDescription:
    @property
    def read_units_per_second(self) -> int | None: ...
    @property
    def write_units_per_second(self) -> int | None: ...
    @property
    def status(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GlobalTable:
    @property
    def global_table_name(self) -> str | None: ...
    @property
    def replication_group(self) -> list[Replica] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GlobalTableDescription:
    @property
    def replication_group(self) -> list[ReplicaDescription] | None: ...
    @property
    def global_table_arn(self) -> str | None: ...
    @property
    def creation_date_time(self) -> str | None: ...
    @property
    def global_table_status(self) -> str | None: ...
    @property
    def global_table_name(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GlobalTableWitnessDescription:
    @property
    def region_name(self) -> str | None: ...
    @property
    def witness_status(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ImportSummary:
    @property
    def import_arn(self) -> str | None: ...
    @property
    def import_status(self) -> str | None: ...
    @property
    def table_arn(self) -> str | None: ...
    @property
    def s3_bucket_source(self) -> S3BucketSource | None: ...
    @property
    def cloud_watch_log_group_arn(self) -> str | None: ...
    @property
    def input_format(self) -> str | None: ...
    @property
    def start_time(self) -> str | None: ...
    @property
    def end_time(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ImportTableDescription:
    @property
    def import_arn(self) -> str | None: ...
    @property
    def import_status(self) -> str | None: ...
    @property
    def table_arn(self) -> str | None: ...
    @property
    def table_id(self) -> str | None: ...
    @property
    def client_token(self) -> str | None: ...
    @property
    def s3_bucket_source(self) -> S3BucketSource | None: ...
    @property
    def error_count(self) -> int: ...
    @property
    def cloud_watch_log_group_arn(self) -> str | None: ...
    @property
    def input_format(self) -> str | None: ...
    @property
    def input_format_options(self) -> InputFormatOptions | None: ...
    @property
    def input_compression_type(self) -> str | None: ...
    @property
    def table_creation_parameters(self) -> TableCreationParameters | None: ...
    @property
    def start_time(self) -> str | None: ...
    @property
    def end_time(self) -> str | None: ...
    @property
    def processed_size_bytes(self) -> int | None: ...
    @property
    def processed_item_count(self) -> int: ...
    @property
    def imported_item_count(self) -> int: ...
    @property
    def failure_code(self) -> str | None: ...
    @property
    def failure_message(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class IncrementalExportSpecification:
    @property
    def export_from_time(self) -> str | None: ...
    @property
    def export_to_time(self) -> str | None: ...
    @property
    def export_view_type(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class InputFormatOptions:
    @property
    def csv(self) -> CsvOptions | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ItemCollectionMetrics:
    @property
    def item_collection_key(self) -> dict[str, dict[str, object]] | None: ...
    @property
    def size_estimate_range_gb(self) -> list[float] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ItemResponse:
    @property
    def item(self) -> dict[str, dict[str, object]] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class KeySchemaElement:
    @property
    def attribute_name(self) -> str: ...
    @property
    def key_type(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class KeysAndAttributes:
    @property
    def keys(self) -> list[dict[str, dict[str, object]]]: ...
    @property
    def attributes_to_get(self) -> list[str] | None: ...
    @property
    def consistent_read(self) -> bool | None: ...
    @property
    def projection_expression(self) -> str | None: ...
    @property
    def expression_attribute_names(self) -> dict[str, str] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class KinesisDataStreamDestination:
    @property
    def stream_arn(self) -> str | None: ...
    @property
    def destination_status(self) -> str | None: ...
    @property
    def destination_status_description(self) -> str | None: ...
    @property
    def approximate_creation_date_time_precision(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class LocalSecondaryIndexDescription:
    @property
    def index_name(self) -> str | None: ...
    @property
    def key_schema(self) -> list[KeySchemaElement] | None: ...
    @property
    def projection(self) -> Projection | None: ...
    @property
    def index_size_bytes(self) -> int | None: ...
    @property
    def item_count(self) -> int | None: ...
    @property
    def index_arn(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class LocalSecondaryIndexInfo:
    @property
    def index_name(self) -> str | None: ...
    @property
    def key_schema(self) -> list[KeySchemaElement] | None: ...
    @property
    def projection(self) -> Projection | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class OnDemandThroughput:
    @property
    def max_read_request_units(self) -> int | None: ...
    @property
    def max_write_request_units(self) -> int | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class OnDemandThroughputOverride:
    @property
    def max_read_request_units(self) -> int | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class PointInTimeRecoveryDescription:
    @property
    def point_in_time_recovery_status(self) -> str | None: ...
    @property
    def recovery_period_in_days(self) -> int | None: ...
    @property
    def earliest_restorable_date_time(self) -> str | None: ...
    @property
    def latest_restorable_date_time(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Projection:
    @property
    def projection_type(self) -> str | None: ...
    @property
    def non_key_attributes(self) -> list[str] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ProvisionedThroughput:
    @property
    def read_capacity_units(self) -> int: ...
    @property
    def write_capacity_units(self) -> int: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ProvisionedThroughputDescription:
    @property
    def last_increase_date_time(self) -> str | None: ...
    @property
    def last_decrease_date_time(self) -> str | None: ...
    @property
    def number_of_decreases_today(self) -> int | None: ...
    @property
    def read_capacity_units(self) -> int | None: ...
    @property
    def write_capacity_units(self) -> int | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ProvisionedThroughputOverride:
    @property
    def read_capacity_units(self) -> int | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class PutRequest:
    @property
    def item(self) -> dict[str, dict[str, object]]: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Replica:
    @property
    def region_name(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ReplicaAutoScalingDescription:
    @property
    def region_name(self) -> str | None: ...
    @property
    def global_secondary_indexes(self) -> list[ReplicaGlobalSecondaryIndexAutoScalingDescription] | None: ...
    @property
    def replica_provisioned_read_capacity_auto_scaling_settings(self) -> AutoScalingSettingsDescription | None: ...
    @property
    def replica_provisioned_write_capacity_auto_scaling_settings(self) -> AutoScalingSettingsDescription | None: ...
    @property
    def replica_status(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ReplicaDescription:
    @property
    def region_name(self) -> str | None: ...
    @property
    def replica_status(self) -> str | None: ...
    @property
    def replica_status_description(self) -> str | None: ...
    @property
    def replica_status_percent_progress(self) -> str | None: ...
    @property
    def kms_master_key_id(self) -> str | None: ...
    @property
    def provisioned_throughput_override(self) -> ProvisionedThroughputOverride | None: ...
    @property
    def on_demand_throughput_override(self) -> OnDemandThroughputOverride | None: ...
    @property
    def warm_throughput(self) -> TableWarmThroughputDescription | None: ...
    @property
    def global_secondary_indexes(self) -> list[ReplicaGlobalSecondaryIndexDescription] | None: ...
    @property
    def replica_inaccessible_date_time(self) -> str | None: ...
    @property
    def replica_table_class_summary(self) -> TableClassSummary | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ReplicaGlobalSecondaryIndexAutoScalingDescription:
    @property
    def index_name(self) -> str | None: ...
    @property
    def index_status(self) -> str | None: ...
    @property
    def provisioned_read_capacity_auto_scaling_settings(self) -> AutoScalingSettingsDescription | None: ...
    @property
    def provisioned_write_capacity_auto_scaling_settings(self) -> AutoScalingSettingsDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ReplicaGlobalSecondaryIndexDescription:
    @property
    def index_name(self) -> str | None: ...
    @property
    def provisioned_throughput_override(self) -> ProvisionedThroughputOverride | None: ...
    @property
    def on_demand_throughput_override(self) -> OnDemandThroughputOverride | None: ...
    @property
    def warm_throughput(self) -> GlobalSecondaryIndexWarmThroughputDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ReplicaGlobalSecondaryIndexSettingsDescription:
    @property
    def index_name(self) -> str: ...
    @property
    def index_status(self) -> str | None: ...
    @property
    def provisioned_read_capacity_units(self) -> int | None: ...
    @property
    def provisioned_read_capacity_auto_scaling_settings(self) -> AutoScalingSettingsDescription | None: ...
    @property
    def provisioned_write_capacity_units(self) -> int | None: ...
    @property
    def provisioned_write_capacity_auto_scaling_settings(self) -> AutoScalingSettingsDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ReplicaSettingsDescription:
    @property
    def region_name(self) -> str: ...
    @property
    def replica_status(self) -> str | None: ...
    @property
    def replica_billing_mode_summary(self) -> BillingModeSummary | None: ...
    @property
    def replica_provisioned_read_capacity_units(self) -> int | None: ...
    @property
    def replica_provisioned_read_capacity_auto_scaling_settings(self) -> AutoScalingSettingsDescription | None: ...
    @property
    def replica_provisioned_write_capacity_units(self) -> int | None: ...
    @property
    def replica_provisioned_write_capacity_auto_scaling_settings(self) -> AutoScalingSettingsDescription | None: ...
    @property
    def replica_global_secondary_index_settings(self) -> list[ReplicaGlobalSecondaryIndexSettingsDescription] | None: ...
    @property
    def replica_table_class_summary(self) -> TableClassSummary | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class RestoreSummary:
    @property
    def source_backup_arn(self) -> str | None: ...
    @property
    def source_table_arn(self) -> str | None: ...
    @property
    def restore_date_time(self) -> str: ...
    @property
    def restore_in_progress(self) -> bool: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class S3BucketSource:
    @property
    def s3_bucket_owner(self) -> str | None: ...
    @property
    def s3_bucket(self) -> str: ...
    @property
    def s3_key_prefix(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class SourceTableDetails:
    @property
    def table_name(self) -> str: ...
    @property
    def table_id(self) -> str: ...
    @property
    def table_arn(self) -> str | None: ...
    @property
    def table_size_bytes(self) -> int | None: ...
    @property
    def key_schema(self) -> list[KeySchemaElement]: ...
    @property
    def table_creation_date_time(self) -> str: ...
    @property
    def provisioned_throughput(self) -> ProvisionedThroughput | None: ...
    @property
    def on_demand_throughput(self) -> OnDemandThroughput | None: ...
    @property
    def item_count(self) -> int | None: ...
    @property
    def billing_mode(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class SourceTableFeatureDetails:
    @property
    def local_secondary_indexes(self) -> list[LocalSecondaryIndexInfo] | None: ...
    @property
    def global_secondary_indexes(self) -> list[GlobalSecondaryIndexInfo] | None: ...
    @property
    def stream_description(self) -> StreamSpecification | None: ...
    @property
    def time_to_live_description(self) -> TimeToLiveDescription | None: ...
    @property
    def sse_description(self) -> SseDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class SseDescription:
    @property
    def status(self) -> str | None: ...
    @property
    def sse_type(self) -> str | None: ...
    @property
    def kms_master_key_arn(self) -> str | None: ...
    @property
    def inaccessible_encryption_date_time(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class SseSpecification:
    @property
    def enabled(self) -> bool | None: ...
    @property
    def sse_type(self) -> str | None: ...
    @property
    def kms_master_key_id(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class StreamSpecification:
    @property
    def stream_enabled(self) -> bool: ...
    @property
    def stream_view_type(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class TableAutoScalingDescription:
    @property
    def table_name(self) -> str | None: ...
    @property
    def table_status(self) -> str | None: ...
    @property
    def replicas(self) -> list[ReplicaAutoScalingDescription] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class TableClassSummary:
    @property
    def table_class(self) -> str | None: ...
    @property
    def last_update_date_time(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class TableCreationParameters:
    @property
    def table_name(self) -> str: ...
    @property
    def attribute_definitions(self) -> list[AttributeDefinition]: ...
    @property
    def key_schema(self) -> list[KeySchemaElement]: ...
    @property
    def billing_mode(self) -> str | None: ...
    @property
    def provisioned_throughput(self) -> ProvisionedThroughput | None: ...
    @property
    def on_demand_throughput(self) -> OnDemandThroughput | None: ...
    @property
    def sse_specification(self) -> SseSpecification | None: ...
    @property
    def global_secondary_indexes(self) -> list[GlobalSecondaryIndex] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class TableDescription:
    @property
    def attribute_definitions(self) -> list[AttributeDefinition] | None: ...
    @property
    def table_name(self) -> str | None: ...
    @property
    def key_schema(self) -> list[KeySchemaElement] | None: ...
    @property
    def table_status(self) -> str | None: ...
    @property
    def creation_date_time(self) -> str | None: ...
    @property
    def provisioned_throughput(self) -> ProvisionedThroughputDescription | None: ...
    @property
    def table_size_bytes(self) -> int | None: ...
    @property
    def item_count(self) -> int | None: ...
    @property
    def table_arn(self) -> str | None: ...
    @property
    def table_id(self) -> str | None: ...
    @property
    def billing_mode_summary(self) -> BillingModeSummary | None: ...
    @property
    def local_secondary_indexes(self) -> list[LocalSecondaryIndexDescription] | None: ...
    @property
    def global_secondary_indexes(self) -> list[GlobalSecondaryIndexDescription] | None: ...
    @property
    def stream_specification(self) -> StreamSpecification | None: ...
    @property
    def latest_stream_label(self) -> str | None: ...
    @property
    def latest_stream_arn(self) -> str | None: ...
    @property
    def global_table_version(self) -> str | None: ...
    @property
    def replicas(self) -> list[ReplicaDescription] | None: ...
    @property
    def global_table_witnesses(self) -> list[GlobalTableWitnessDescription] | None: ...
    @property
    def restore_summary(self) -> RestoreSummary | None: ...
    @property
    def sse_description(self) -> SseDescription | None: ...
    @property
    def archival_summary(self) -> ArchivalSummary | None: ...
    @property
    def table_class_summary(self) -> TableClassSummary | None: ...
    @property
    def deletion_protection_enabled(self) -> bool | None: ...
    @property
    def on_demand_throughput(self) -> OnDemandThroughput | None: ...
    @property
    def warm_throughput(self) -> TableWarmThroughputDescription | None: ...
    @property
    def multi_region_consistency(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class TableWarmThroughputDescription:
    @property
    def read_units_per_second(self) -> int | None: ...
    @property
    def write_units_per_second(self) -> int | None: ...
    @property
    def status(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class Tag:
    @property
    def key(self) -> str: ...
    @property
    def value(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class TimeToLiveDescription:
    @property
    def time_to_live_status(self) -> str | None: ...
    @property
    def attribute_name(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class TimeToLiveSpecification:
    @property
    def enabled(self) -> bool: ...
    @property
    def attribute_name(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class UpdateKinesisStreamingConfiguration:
    @property
    def approximate_creation_date_time_precision(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class WarmThroughput:
    @property
    def read_units_per_second(self) -> int | None: ...
    @property
    def write_units_per_second(self) -> int | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class WriteRequest:
    @property
    def put_request(self) -> PutRequest | None: ...
    @property
    def delete_request(self) -> DeleteRequest | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class BatchExecuteStatementOutput:
    @property
    def responses(self) -> list[BatchStatementResponse] | None: ...
    @property
    def consumed_capacity(self) -> list[ConsumedCapacity] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class BatchGetItemOutput:
    @property
    def responses(self) -> dict[str, list[dict[str, dict[str, object]]]] | None: ...
    @property
    def unprocessed_keys(self) -> dict[str, KeysAndAttributes] | None: ...
    @property
    def consumed_capacity(self) -> list[ConsumedCapacity] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class BatchWriteItemOutput:
    @property
    def unprocessed_items(self) -> dict[str, list[WriteRequest]] | None: ...
    @property
    def item_collection_metrics(self) -> dict[str, list[ItemCollectionMetrics]] | None: ...
    @property
    def consumed_capacity(self) -> list[ConsumedCapacity] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CreateBackupOutput:
    @property
    def backup_details(self) -> BackupDetails | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CreateGlobalTableOutput:
    @property
    def global_table_description(self) -> GlobalTableDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class CreateTableOutput:
    @property
    def table_description(self) -> TableDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DeleteBackupOutput:
    @property
    def backup_description(self) -> BackupDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DeleteItemOutput:
    @property
    def attributes(self) -> dict[str, dict[str, object]] | None: ...
    @property
    def consumed_capacity(self) -> ConsumedCapacity | None: ...
    @property
    def item_collection_metrics(self) -> ItemCollectionMetrics | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DeleteResourcePolicyOutput:
    @property
    def revision_id(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DeleteTableOutput:
    @property
    def table_description(self) -> TableDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DescribeBackupOutput:
    @property
    def backup_description(self) -> BackupDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DescribeContinuousBackupsOutput:
    @property
    def continuous_backups_description(self) -> ContinuousBackupsDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DescribeContributorInsightsOutput:
    @property
    def table_name(self) -> str | None: ...
    @property
    def index_name(self) -> str | None: ...
    @property
    def contributor_insights_rule_list(self) -> list[str] | None: ...
    @property
    def contributor_insights_status(self) -> str | None: ...
    @property
    def last_update_date_time(self) -> str | None: ...
    @property
    def failure_exception(self) -> FailureException | None: ...
    @property
    def contributor_insights_mode(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DescribeEndpointsResponse:
    @property
    def endpoints(self) -> list[Endpoint]: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DescribeExportOutput:
    @property
    def export_description(self) -> ExportDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DescribeGlobalTableOutput:
    @property
    def global_table_description(self) -> GlobalTableDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DescribeGlobalTableSettingsOutput:
    @property
    def global_table_name(self) -> str | None: ...
    @property
    def replica_settings(self) -> list[ReplicaSettingsDescription] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DescribeImportOutput:
    @property
    def import_table_description(self) -> ImportTableDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DescribeKinesisStreamingDestinationOutput:
    @property
    def table_name(self) -> str | None: ...
    @property
    def kinesis_data_stream_destinations(self) -> list[KinesisDataStreamDestination] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DescribeLimitsOutput:
    @property
    def account_max_read_capacity_units(self) -> int | None: ...
    @property
    def account_max_write_capacity_units(self) -> int | None: ...
    @property
    def table_max_read_capacity_units(self) -> int | None: ...
    @property
    def table_max_write_capacity_units(self) -> int | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DescribeTableOutput:
    @property
    def table(self) -> TableDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DescribeTableReplicaAutoScalingOutput:
    @property
    def table_auto_scaling_description(self) -> TableAutoScalingDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DescribeTimeToLiveOutput:
    @property
    def time_to_live_description(self) -> TimeToLiveDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class DisableKinesisStreamingDestinationOutput:
    @property
    def table_name(self) -> str | None: ...
    @property
    def stream_arn(self) -> str | None: ...
    @property
    def destination_status(self) -> str | None: ...
    @property
    def enable_kinesis_streaming_configuration(self) -> EnableKinesisStreamingConfiguration | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class EnableKinesisStreamingDestinationOutput:
    @property
    def table_name(self) -> str | None: ...
    @property
    def stream_arn(self) -> str | None: ...
    @property
    def destination_status(self) -> str | None: ...
    @property
    def enable_kinesis_streaming_configuration(self) -> EnableKinesisStreamingConfiguration | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ExecuteStatementOutput:
    @property
    def items(self) -> list[dict[str, dict[str, object]]] | None: ...
    @property
    def next_token(self) -> str | None: ...
    @property
    def consumed_capacity(self) -> ConsumedCapacity | None: ...
    @property
    def last_evaluated_key(self) -> dict[str, dict[str, object]] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ExecuteTransactionOutput:
    @property
    def responses(self) -> list[ItemResponse] | None: ...
    @property
    def consumed_capacity(self) -> list[ConsumedCapacity] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ExportTableToPointInTimeOutput:
    @property
    def export_description(self) -> ExportDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetItemOutput:
    @property
    def item(self) -> dict[str, dict[str, object]] | None: ...
    @property
    def consumed_capacity(self) -> ConsumedCapacity | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class GetResourcePolicyOutput:
    @property
    def policy(self) -> str | None: ...
    @property
    def revision_id(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ImportTableOutput:
    @property
    def import_table_description(self) -> ImportTableDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListBackupsOutput:
    @property
    def backup_summaries(self) -> list[BackupSummary] | None: ...
    @property
    def last_evaluated_backup_arn(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListContributorInsightsOutput:
    @property
    def contributor_insights_summaries(self) -> list[ContributorInsightsSummary] | None: ...
    @property
    def next_token(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListExportsOutput:
    @property
    def export_summaries(self) -> list[ExportSummary] | None: ...
    @property
    def next_token(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListGlobalTablesOutput:
    @property
    def global_tables(self) -> list[GlobalTable] | None: ...
    @property
    def last_evaluated_global_table_name(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListImportsOutput:
    @property
    def import_summary_list(self) -> list[ImportSummary] | None: ...
    @property
    def next_token(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListTablesOutput:
    @property
    def table_names(self) -> list[str] | None: ...
    @property
    def last_evaluated_table_name(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ListTagsOfResourceOutput:
    @property
    def tags(self) -> list[Tag] | None: ...
    @property
    def next_token(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class PutItemOutput:
    @property
    def attributes(self) -> dict[str, dict[str, object]] | None: ...
    @property
    def consumed_capacity(self) -> ConsumedCapacity | None: ...
    @property
    def item_collection_metrics(self) -> ItemCollectionMetrics | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class PutResourcePolicyOutput:
    @property
    def revision_id(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class QueryOutput:
    @property
    def items(self) -> list[dict[str, dict[str, object]]] | None: ...
    @property
    def count(self) -> int: ...
    @property
    def scanned_count(self) -> int: ...
    @property
    def last_evaluated_key(self) -> dict[str, dict[str, object]] | None: ...
    @property
    def consumed_capacity(self) -> ConsumedCapacity | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class RestoreTableFromBackupOutput:
    @property
    def table_description(self) -> TableDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class RestoreTableToPointInTimeOutput:
    @property
    def table_description(self) -> TableDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class ScanOutput:
    @property
    def items(self) -> list[dict[str, dict[str, object]]] | None: ...
    @property
    def count(self) -> int: ...
    @property
    def scanned_count(self) -> int: ...
    @property
    def last_evaluated_key(self) -> dict[str, dict[str, object]] | None: ...
    @property
    def consumed_capacity(self) -> ConsumedCapacity | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class TransactGetItemsOutput:
    @property
    def consumed_capacity(self) -> list[ConsumedCapacity] | None: ...
    @property
    def responses(self) -> list[ItemResponse] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class TransactWriteItemsOutput:
    @property
    def consumed_capacity(self) -> list[ConsumedCapacity] | None: ...
    @property
    def item_collection_metrics(self) -> dict[str, list[ItemCollectionMetrics]] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class UpdateContinuousBackupsOutput:
    @property
    def continuous_backups_description(self) -> ContinuousBackupsDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class UpdateContributorInsightsOutput:
    @property
    def table_name(self) -> str | None: ...
    @property
    def index_name(self) -> str | None: ...
    @property
    def contributor_insights_status(self) -> str | None: ...
    @property
    def contributor_insights_mode(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class UpdateGlobalTableOutput:
    @property
    def global_table_description(self) -> GlobalTableDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class UpdateGlobalTableSettingsOutput:
    @property
    def global_table_name(self) -> str | None: ...
    @property
    def replica_settings(self) -> list[ReplicaSettingsDescription] | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class UpdateItemOutput:
    @property
    def attributes(self) -> dict[str, dict[str, object]] | None: ...
    @property
    def consumed_capacity(self) -> ConsumedCapacity | None: ...
    @property
    def item_collection_metrics(self) -> ItemCollectionMetrics | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class UpdateKinesisStreamingDestinationOutput:
    @property
    def table_name(self) -> str | None: ...
    @property
    def stream_arn(self) -> str | None: ...
    @property
    def destination_status(self) -> str | None: ...
    @property
    def update_kinesis_streaming_configuration(self) -> UpdateKinesisStreamingConfiguration | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class UpdateTableOutput:
    @property
    def table_description(self) -> TableDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class UpdateTableReplicaAutoScalingOutput:
    @property
    def table_auto_scaling_description(self) -> TableAutoScalingDescription | None: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class UpdateTimeToLiveOutput:
    @property
    def time_to_live_specification(self) -> TimeToLiveSpecification | None: ...
    def to_dict(self) -> dict[str, object]: ...



@final
class DynamoDBClient:
    def __init__(
        self,
        *,
        region: str | None = None,
        profile: str | None = None,
        endpoint_url: str | None = None,
    ) -> None: ...

    async def batch_execute_statement(self, params: dict[str, object]) -> BatchExecuteStatementOutput: ...

    async def batch_get_item(self, params: dict[str, object]) -> BatchGetItemOutput: ...

    async def batch_write_item(self, params: dict[str, object]) -> BatchWriteItemOutput: ...

    async def create_backup(self, params: dict[str, object]) -> CreateBackupOutput: ...

    async def create_global_table(self, params: dict[str, object]) -> CreateGlobalTableOutput: ...

    async def create_table(self, params: dict[str, object]) -> CreateTableOutput: ...

    async def delete_backup(self, params: dict[str, object]) -> DeleteBackupOutput: ...

    async def delete_item(self, params: dict[str, object]) -> DeleteItemOutput: ...

    async def delete_resource_policy(self, params: dict[str, object]) -> DeleteResourcePolicyOutput: ...

    async def delete_table(self, params: dict[str, object]) -> DeleteTableOutput: ...

    async def describe_backup(self, params: dict[str, object]) -> DescribeBackupOutput: ...

    async def describe_continuous_backups(self, params: dict[str, object]) -> DescribeContinuousBackupsOutput: ...

    async def describe_contributor_insights(self, params: dict[str, object]) -> DescribeContributorInsightsOutput: ...

    async def describe_endpoints(self, params: dict[str, object]) -> DescribeEndpointsResponse: ...

    async def describe_export(self, params: dict[str, object]) -> DescribeExportOutput: ...

    async def describe_global_table(self, params: dict[str, object]) -> DescribeGlobalTableOutput: ...

    async def describe_global_table_settings(self, params: dict[str, object]) -> DescribeGlobalTableSettingsOutput: ...

    async def describe_import(self, params: dict[str, object]) -> DescribeImportOutput: ...

    async def describe_kinesis_streaming_destination(self, params: dict[str, object]) -> DescribeKinesisStreamingDestinationOutput: ...

    async def describe_limits(self, params: dict[str, object]) -> DescribeLimitsOutput: ...

    async def describe_table(self, params: dict[str, object]) -> DescribeTableOutput: ...

    async def describe_table_replica_auto_scaling(self, params: dict[str, object]) -> DescribeTableReplicaAutoScalingOutput: ...

    async def describe_time_to_live(self, params: dict[str, object]) -> DescribeTimeToLiveOutput: ...

    async def disable_kinesis_streaming_destination(self, params: dict[str, object]) -> DisableKinesisStreamingDestinationOutput: ...

    async def enable_kinesis_streaming_destination(self, params: dict[str, object]) -> EnableKinesisStreamingDestinationOutput: ...

    async def execute_statement(self, params: dict[str, object]) -> ExecuteStatementOutput: ...

    async def execute_transaction(self, params: dict[str, object]) -> ExecuteTransactionOutput: ...

    async def export_table_to_point_in_time(self, params: dict[str, object]) -> ExportTableToPointInTimeOutput: ...

    async def get_item(self, params: dict[str, object]) -> GetItemOutput: ...

    async def get_resource_policy(self, params: dict[str, object]) -> GetResourcePolicyOutput: ...

    async def import_table(self, params: dict[str, object]) -> ImportTableOutput: ...

    async def list_backups(self, params: dict[str, object]) -> ListBackupsOutput: ...

    async def list_contributor_insights(self, params: dict[str, object]) -> ListContributorInsightsOutput: ...

    async def list_exports(self, params: dict[str, object]) -> ListExportsOutput: ...

    async def list_global_tables(self, params: dict[str, object]) -> ListGlobalTablesOutput: ...

    async def list_imports(self, params: dict[str, object]) -> ListImportsOutput: ...

    async def list_tables(self, params: dict[str, object]) -> ListTablesOutput: ...

    async def list_tags_of_resource(self, params: dict[str, object]) -> ListTagsOfResourceOutput: ...

    async def put_item(self, params: dict[str, object]) -> PutItemOutput: ...

    async def put_resource_policy(self, params: dict[str, object]) -> PutResourcePolicyOutput: ...

    async def query(self, params: dict[str, object]) -> QueryOutput: ...

    async def restore_table_from_backup(self, params: dict[str, object]) -> RestoreTableFromBackupOutput: ...

    async def restore_table_to_point_in_time(self, params: dict[str, object]) -> RestoreTableToPointInTimeOutput: ...

    async def scan(self, params: dict[str, object]) -> ScanOutput: ...

    async def tag_resource(self, params: dict[str, object]) -> None: ...

    async def transact_get_items(self, params: dict[str, object]) -> TransactGetItemsOutput: ...

    async def transact_write_items(self, params: dict[str, object]) -> TransactWriteItemsOutput: ...

    async def untag_resource(self, params: dict[str, object]) -> None: ...

    async def update_continuous_backups(self, params: dict[str, object]) -> UpdateContinuousBackupsOutput: ...

    async def update_contributor_insights(self, params: dict[str, object]) -> UpdateContributorInsightsOutput: ...

    async def update_global_table(self, params: dict[str, object]) -> UpdateGlobalTableOutput: ...

    async def update_global_table_settings(self, params: dict[str, object]) -> UpdateGlobalTableSettingsOutput: ...

    async def update_item(self, params: dict[str, object]) -> UpdateItemOutput: ...

    async def update_kinesis_streaming_destination(self, params: dict[str, object]) -> UpdateKinesisStreamingDestinationOutput: ...

    async def update_table(self, params: dict[str, object]) -> UpdateTableOutput: ...

    async def update_table_replica_auto_scaling(self, params: dict[str, object]) -> UpdateTableReplicaAutoScalingOutput: ...

    async def update_time_to_live(self, params: dict[str, object]) -> UpdateTimeToLiveOutput: ...
