from collections.abc import AsyncIterator
from typing import final

@final
class ByteStream:
    def __aiter__(self) -> AsyncIterator[bytes]: ...
    async def __anext__(self) -> bytes: ...
    async def read(self) -> bytes: ...



@final
class DynamoDBClient:
    def __init__(
        self,
        *,
        region: str | None = None,
        profile: str | None = None,
        endpoint_url: str | None = None,
    ) -> None: ...

    async def batch_execute_statement(self, params: dict[str, object]) -> object: ...

    async def batch_get_item(self, params: dict[str, object]) -> object: ...

    async def batch_write_item(self, params: dict[str, object]) -> object: ...

    async def create_backup(self, params: dict[str, object]) -> object: ...

    async def create_global_table(self, params: dict[str, object]) -> object: ...

    async def create_table(self, params: dict[str, object]) -> object: ...

    async def delete_backup(self, params: dict[str, object]) -> object: ...

    async def delete_item(self, params: dict[str, object]) -> object: ...

    async def delete_resource_policy(self, params: dict[str, object]) -> object: ...

    async def delete_table(self, params: dict[str, object]) -> object: ...

    async def describe_backup(self, params: dict[str, object]) -> object: ...

    async def describe_continuous_backups(self, params: dict[str, object]) -> object: ...

    async def describe_contributor_insights(self, params: dict[str, object]) -> object: ...

    async def describe_endpoints(self, params: dict[str, object]) -> object: ...

    async def describe_export(self, params: dict[str, object]) -> object: ...

    async def describe_global_table(self, params: dict[str, object]) -> object: ...

    async def describe_global_table_settings(self, params: dict[str, object]) -> object: ...

    async def describe_import(self, params: dict[str, object]) -> object: ...

    async def describe_kinesis_streaming_destination(self, params: dict[str, object]) -> object: ...

    async def describe_limits(self, params: dict[str, object]) -> object: ...

    async def describe_table(self, params: dict[str, object]) -> object: ...

    async def describe_table_replica_auto_scaling(self, params: dict[str, object]) -> object: ...

    async def describe_time_to_live(self, params: dict[str, object]) -> object: ...

    async def disable_kinesis_streaming_destination(self, params: dict[str, object]) -> object: ...

    async def enable_kinesis_streaming_destination(self, params: dict[str, object]) -> object: ...

    async def execute_statement(self, params: dict[str, object]) -> object: ...

    async def execute_transaction(self, params: dict[str, object]) -> object: ...

    async def export_table_to_point_in_time(self, params: dict[str, object]) -> object: ...

    async def get_item(self, params: dict[str, object]) -> object: ...

    async def get_resource_policy(self, params: dict[str, object]) -> object: ...

    async def import_table(self, params: dict[str, object]) -> object: ...

    async def list_backups(self, params: dict[str, object]) -> object: ...

    async def list_contributor_insights(self, params: dict[str, object]) -> object: ...

    async def list_exports(self, params: dict[str, object]) -> object: ...

    async def list_global_tables(self, params: dict[str, object]) -> object: ...

    async def list_imports(self, params: dict[str, object]) -> object: ...

    async def list_tables(self, params: dict[str, object]) -> object: ...

    async def list_tags_of_resource(self, params: dict[str, object]) -> object: ...

    async def put_item(self, params: dict[str, object]) -> object: ...

    async def put_resource_policy(self, params: dict[str, object]) -> object: ...

    async def query(self, params: dict[str, object]) -> object: ...

    async def restore_table_from_backup(self, params: dict[str, object]) -> object: ...

    async def restore_table_to_point_in_time(self, params: dict[str, object]) -> object: ...

    async def scan(self, params: dict[str, object]) -> object: ...

    async def tag_resource(self, params: dict[str, object]) -> object: ...

    async def transact_get_items(self, params: dict[str, object]) -> object: ...

    async def transact_write_items(self, params: dict[str, object]) -> object: ...

    async def untag_resource(self, params: dict[str, object]) -> object: ...

    async def update_continuous_backups(self, params: dict[str, object]) -> object: ...

    async def update_contributor_insights(self, params: dict[str, object]) -> object: ...

    async def update_global_table(self, params: dict[str, object]) -> object: ...

    async def update_global_table_settings(self, params: dict[str, object]) -> object: ...

    async def update_item(self, params: dict[str, object]) -> object: ...

    async def update_kinesis_streaming_destination(self, params: dict[str, object]) -> object: ...

    async def update_table(self, params: dict[str, object]) -> object: ...

    async def update_table_replica_auto_scaling(self, params: dict[str, object]) -> object: ...

    async def update_time_to_live(self, params: dict[str, object]) -> object: ...

