# Generated by rboto-codegen. DO NOT EDIT.
from __future__ import annotations



from ._native import DynamoDBClient as NativeClient, BatchExecuteStatementOutput, BatchGetItemOutput, BatchWriteItemOutput, CreateBackupOutput, CreateGlobalTableOutput, CreateTableOutput, DeleteBackupOutput, DeleteItemOutput, DeleteResourcePolicyOutput, DeleteTableOutput, DescribeBackupOutput, DescribeContinuousBackupsOutput, DescribeContributorInsightsOutput, DescribeEndpointsResponse, DescribeExportOutput, DescribeGlobalTableOutput, DescribeGlobalTableSettingsOutput, DescribeImportOutput, DescribeKinesisStreamingDestinationOutput, DescribeLimitsOutput, DescribeTableOutput, DescribeTableReplicaAutoScalingOutput, DescribeTimeToLiveOutput, DisableKinesisStreamingDestinationOutput, EnableKinesisStreamingDestinationOutput, ExecuteStatementOutput, ExecuteTransactionOutput, ExportTableToPointInTimeOutput, GetItemOutput, GetResourcePolicyOutput, ImportTableOutput, ListBackupsOutput, ListContributorInsightsOutput, ListExportsOutput, ListGlobalTablesOutput, ListImportsOutput, ListTablesOutput, ListTagsOfResourceOutput, PutItemOutput, PutResourcePolicyOutput, QueryOutput, RestoreTableFromBackupOutput, RestoreTableToPointInTimeOutput, ScanOutput, TransactGetItemsOutput, TransactWriteItemsOutput, UpdateContinuousBackupsOutput, UpdateContributorInsightsOutput, UpdateGlobalTableOutput, UpdateGlobalTableSettingsOutput, UpdateItemOutput, UpdateKinesisStreamingDestinationOutput, UpdateTableOutput, UpdateTableReplicaAutoScalingOutput, UpdateTimeToLiveOutput
from .types import (
    AttributeDefinition,
    AttributeValue,
    AttributeValueUpdate,
    AutoScalingSettingsUpdate,
    BackupTypeFilter,
    BatchStatementRequest,
    BillingMode,
    Condition,
    ConditionalOperator,
    ContributorInsightsAction,
    ContributorInsightsMode,
    EnableKinesisStreamingConfiguration,
    ExpectedAttributeValue,
    ExportFormat,
    ExportType,
    GlobalSecondaryIndex,
    GlobalSecondaryIndexAutoScalingUpdate,
    GlobalSecondaryIndexUpdate,
    GlobalTableGlobalSecondaryIndexSettingsUpdate,
    GlobalTableWitnessGroupUpdate,
    IncrementalExportSpecification,
    InputCompressionType,
    InputFormat,
    InputFormatOptions,
    KeySchemaElement,
    KeysAndAttributes,
    LocalSecondaryIndex,
    MultiRegionConsistency,
    OnDemandThroughput,
    ParameterizedStatement,
    PointInTimeRecoverySpecification,
    ProvisionedThroughput,
    Replica,
    ReplicaAutoScalingUpdate,
    ReplicaSettingsUpdate,
    ReplicaUpdate,
    ReplicationGroupUpdate,
    ReturnConsumedCapacity,
    ReturnItemCollectionMetrics,
    ReturnValue,
    ReturnValuesOnConditionCheckFailure,
    S3BucketSource,
    S3SseAlgorithm,
    SSESpecification,
    Select,
    StreamSpecification,
    TableClass,
    TableCreationParameters,
    Tag,
    TimeToLiveSpecification,
    TransactGetItem,
    TransactWriteItem,
    UpdateKinesisStreamingConfiguration,
    WarmThroughput,
    WriteRequest,
)


class DynamoDBClient:
    def __init__(
        self,
        *,
        region: str | None = None,
        profile: str | None = None,
        endpoint_url: str | None = None,
    ) -> None:
        self._native = NativeClient(
            region=region,
            profile=profile,
            endpoint_url=endpoint_url,
        )


    async def batch_execute_statement(
        self,
        *,
        statements: list[BatchStatementRequest],
        return_consumed_capacity: ReturnConsumedCapacity | None = None,
    ) -> BatchExecuteStatementOutput:
        params: dict[str, object] = {
            "statements": statements,
        }
        if return_consumed_capacity is not None:
            params["return_consumed_capacity"] = return_consumed_capacity
        result = await self._native.batch_execute_statement(params)
        return result


    async def batch_get_item(
        self,
        *,
        request_items: dict[str, KeysAndAttributes],
        return_consumed_capacity: ReturnConsumedCapacity | None = None,
    ) -> BatchGetItemOutput:
        params: dict[str, object] = {
            "request_items": request_items,
        }
        if return_consumed_capacity is not None:
            params["return_consumed_capacity"] = return_consumed_capacity
        result = await self._native.batch_get_item(params)
        return result


    async def batch_write_item(
        self,
        *,
        request_items: dict[str, list[WriteRequest]],
        return_consumed_capacity: ReturnConsumedCapacity | None = None,
        return_item_collection_metrics: ReturnItemCollectionMetrics | None = None,
    ) -> BatchWriteItemOutput:
        params: dict[str, object] = {
            "request_items": request_items,
        }
        if return_consumed_capacity is not None:
            params["return_consumed_capacity"] = return_consumed_capacity
        if return_item_collection_metrics is not None:
            params["return_item_collection_metrics"] = return_item_collection_metrics
        result = await self._native.batch_write_item(params)
        return result


    async def create_backup(
        self,
        *,
        table_name: str,
        backup_name: str,
    ) -> CreateBackupOutput:
        params: dict[str, object] = {
            "table_name": table_name,
            "backup_name": backup_name,
        }
        result = await self._native.create_backup(params)
        return result


    async def create_global_table(
        self,
        *,
        global_table_name: str,
        replication_group: list[Replica],
    ) -> CreateGlobalTableOutput:
        params: dict[str, object] = {
            "global_table_name": global_table_name,
            "replication_group": replication_group,
        }
        result = await self._native.create_global_table(params)
        return result


    async def create_table(
        self,
        *,
        attribute_definitions: list[AttributeDefinition],
        table_name: str,
        key_schema: list[KeySchemaElement],
        local_secondary_indexes: list[LocalSecondaryIndex] | None = None,
        global_secondary_indexes: list[GlobalSecondaryIndex] | None = None,
        billing_mode: BillingMode | None = None,
        provisioned_throughput: ProvisionedThroughput | None = None,
        stream_specification: StreamSpecification | None = None,
        sse_specification: SSESpecification | None = None,
        tags: list[Tag] | None = None,
        table_class: TableClass | None = None,
        deletion_protection_enabled: bool | None = None,
        warm_throughput: WarmThroughput | None = None,
        resource_policy: str | None = None,
        on_demand_throughput: OnDemandThroughput | None = None,
    ) -> CreateTableOutput:
        params: dict[str, object] = {
            "attribute_definitions": attribute_definitions,
            "table_name": table_name,
            "key_schema": key_schema,
        }
        if local_secondary_indexes is not None:
            params["local_secondary_indexes"] = local_secondary_indexes
        if global_secondary_indexes is not None:
            params["global_secondary_indexes"] = global_secondary_indexes
        if billing_mode is not None:
            params["billing_mode"] = billing_mode
        if provisioned_throughput is not None:
            params["provisioned_throughput"] = provisioned_throughput
        if stream_specification is not None:
            params["stream_specification"] = stream_specification
        if sse_specification is not None:
            params["sse_specification"] = sse_specification
        if tags is not None:
            params["tags"] = tags
        if table_class is not None:
            params["table_class"] = table_class
        if deletion_protection_enabled is not None:
            params["deletion_protection_enabled"] = deletion_protection_enabled
        if warm_throughput is not None:
            params["warm_throughput"] = warm_throughput
        if resource_policy is not None:
            params["resource_policy"] = resource_policy
        if on_demand_throughput is not None:
            params["on_demand_throughput"] = on_demand_throughput
        result = await self._native.create_table(params)
        return result


    async def delete_backup(
        self,
        *,
        backup_arn: str,
    ) -> DeleteBackupOutput:
        params: dict[str, object] = {
            "backup_arn": backup_arn,
        }
        result = await self._native.delete_backup(params)
        return result


    async def delete_item(
        self,
        *,
        table_name: str,
        key: dict[str, AttributeValue],
        expected: dict[str, ExpectedAttributeValue] | None = None,
        conditional_operator: ConditionalOperator | None = None,
        return_values: ReturnValue | None = None,
        return_consumed_capacity: ReturnConsumedCapacity | None = None,
        return_item_collection_metrics: ReturnItemCollectionMetrics | None = None,
        condition_expression: str | None = None,
        expression_attribute_names: dict[str, str] | None = None,
        expression_attribute_values: dict[str, AttributeValue] | None = None,
        return_values_on_condition_check_failure: ReturnValuesOnConditionCheckFailure | None = None,
    ) -> DeleteItemOutput:
        params: dict[str, object] = {
            "table_name": table_name,
            "key": key,
        }
        if expected is not None:
            params["expected"] = expected
        if conditional_operator is not None:
            params["conditional_operator"] = conditional_operator
        if return_values is not None:
            params["return_values"] = return_values
        if return_consumed_capacity is not None:
            params["return_consumed_capacity"] = return_consumed_capacity
        if return_item_collection_metrics is not None:
            params["return_item_collection_metrics"] = return_item_collection_metrics
        if condition_expression is not None:
            params["condition_expression"] = condition_expression
        if expression_attribute_names is not None:
            params["expression_attribute_names"] = expression_attribute_names
        if expression_attribute_values is not None:
            params["expression_attribute_values"] = expression_attribute_values
        if return_values_on_condition_check_failure is not None:
            params["return_values_on_condition_check_failure"] = return_values_on_condition_check_failure
        result = await self._native.delete_item(params)
        return result


    async def delete_resource_policy(
        self,
        *,
        resource_arn: str,
        expected_revision_id: str | None = None,
    ) -> DeleteResourcePolicyOutput:
        params: dict[str, object] = {
            "resource_arn": resource_arn,
        }
        if expected_revision_id is not None:
            params["expected_revision_id"] = expected_revision_id
        result = await self._native.delete_resource_policy(params)
        return result


    async def delete_table(
        self,
        *,
        table_name: str,
    ) -> DeleteTableOutput:
        params: dict[str, object] = {
            "table_name": table_name,
        }
        result = await self._native.delete_table(params)
        return result


    async def describe_backup(
        self,
        *,
        backup_arn: str,
    ) -> DescribeBackupOutput:
        params: dict[str, object] = {
            "backup_arn": backup_arn,
        }
        result = await self._native.describe_backup(params)
        return result


    async def describe_continuous_backups(
        self,
        *,
        table_name: str,
    ) -> DescribeContinuousBackupsOutput:
        params: dict[str, object] = {
            "table_name": table_name,
        }
        result = await self._native.describe_continuous_backups(params)
        return result


    async def describe_contributor_insights(
        self,
        *,
        table_name: str,
        index_name: str | None = None,
    ) -> DescribeContributorInsightsOutput:
        params: dict[str, object] = {
            "table_name": table_name,
        }
        if index_name is not None:
            params["index_name"] = index_name
        result = await self._native.describe_contributor_insights(params)
        return result


    async def describe_endpoints(
        self,
    ) -> DescribeEndpointsResponse:
        params: dict[str, object] = {
        }
        result = await self._native.describe_endpoints(params)
        return result


    async def describe_export(
        self,
        *,
        export_arn: str,
    ) -> DescribeExportOutput:
        params: dict[str, object] = {
            "export_arn": export_arn,
        }
        result = await self._native.describe_export(params)
        return result


    async def describe_global_table(
        self,
        *,
        global_table_name: str,
    ) -> DescribeGlobalTableOutput:
        params: dict[str, object] = {
            "global_table_name": global_table_name,
        }
        result = await self._native.describe_global_table(params)
        return result


    async def describe_global_table_settings(
        self,
        *,
        global_table_name: str,
    ) -> DescribeGlobalTableSettingsOutput:
        params: dict[str, object] = {
            "global_table_name": global_table_name,
        }
        result = await self._native.describe_global_table_settings(params)
        return result


    async def describe_import(
        self,
        *,
        import_arn: str,
    ) -> DescribeImportOutput:
        params: dict[str, object] = {
            "import_arn": import_arn,
        }
        result = await self._native.describe_import(params)
        return result


    async def describe_kinesis_streaming_destination(
        self,
        *,
        table_name: str,
    ) -> DescribeKinesisStreamingDestinationOutput:
        params: dict[str, object] = {
            "table_name": table_name,
        }
        result = await self._native.describe_kinesis_streaming_destination(params)
        return result


    async def describe_limits(
        self,
    ) -> DescribeLimitsOutput:
        params: dict[str, object] = {
        }
        result = await self._native.describe_limits(params)
        return result


    async def describe_table(
        self,
        *,
        table_name: str,
    ) -> DescribeTableOutput:
        params: dict[str, object] = {
            "table_name": table_name,
        }
        result = await self._native.describe_table(params)
        return result


    async def describe_table_replica_auto_scaling(
        self,
        *,
        table_name: str,
    ) -> DescribeTableReplicaAutoScalingOutput:
        params: dict[str, object] = {
            "table_name": table_name,
        }
        result = await self._native.describe_table_replica_auto_scaling(params)
        return result


    async def describe_time_to_live(
        self,
        *,
        table_name: str,
    ) -> DescribeTimeToLiveOutput:
        params: dict[str, object] = {
            "table_name": table_name,
        }
        result = await self._native.describe_time_to_live(params)
        return result


    async def disable_kinesis_streaming_destination(
        self,
        *,
        table_name: str,
        stream_arn: str,
        enable_kinesis_streaming_configuration: EnableKinesisStreamingConfiguration | None = None,
    ) -> DisableKinesisStreamingDestinationOutput:
        params: dict[str, object] = {
            "table_name": table_name,
            "stream_arn": stream_arn,
        }
        if enable_kinesis_streaming_configuration is not None:
            params["enable_kinesis_streaming_configuration"] = enable_kinesis_streaming_configuration
        result = await self._native.disable_kinesis_streaming_destination(params)
        return result


    async def enable_kinesis_streaming_destination(
        self,
        *,
        table_name: str,
        stream_arn: str,
        enable_kinesis_streaming_configuration: EnableKinesisStreamingConfiguration | None = None,
    ) -> EnableKinesisStreamingDestinationOutput:
        params: dict[str, object] = {
            "table_name": table_name,
            "stream_arn": stream_arn,
        }
        if enable_kinesis_streaming_configuration is not None:
            params["enable_kinesis_streaming_configuration"] = enable_kinesis_streaming_configuration
        result = await self._native.enable_kinesis_streaming_destination(params)
        return result


    async def execute_statement(
        self,
        *,
        statement: str,
        parameters: list[AttributeValue] | None = None,
        consistent_read: bool | None = None,
        next_token: str | None = None,
        return_consumed_capacity: ReturnConsumedCapacity | None = None,
        limit: int | None = None,
        return_values_on_condition_check_failure: ReturnValuesOnConditionCheckFailure | None = None,
    ) -> ExecuteStatementOutput:
        params: dict[str, object] = {
            "statement": statement,
        }
        if parameters is not None:
            params["parameters"] = parameters
        if consistent_read is not None:
            params["consistent_read"] = consistent_read
        if next_token is not None:
            params["next_token"] = next_token
        if return_consumed_capacity is not None:
            params["return_consumed_capacity"] = return_consumed_capacity
        if limit is not None:
            params["limit"] = limit
        if return_values_on_condition_check_failure is not None:
            params["return_values_on_condition_check_failure"] = return_values_on_condition_check_failure
        result = await self._native.execute_statement(params)
        return result


    async def execute_transaction(
        self,
        *,
        transact_statements: list[ParameterizedStatement],
        client_request_token: str | None = None,
        return_consumed_capacity: ReturnConsumedCapacity | None = None,
    ) -> ExecuteTransactionOutput:
        params: dict[str, object] = {
            "transact_statements": transact_statements,
        }
        if client_request_token is not None:
            params["client_request_token"] = client_request_token
        if return_consumed_capacity is not None:
            params["return_consumed_capacity"] = return_consumed_capacity
        result = await self._native.execute_transaction(params)
        return result


    async def export_table_to_point_in_time(
        self,
        *,
        table_arn: str,
        s3_bucket: str,
        export_time: str | None = None,
        client_token: str | None = None,
        s3_bucket_owner: str | None = None,
        s3_prefix: str | None = None,
        s3_sse_algorithm: S3SseAlgorithm | None = None,
        s3_sse_kms_key_id: str | None = None,
        export_format: ExportFormat | None = None,
        export_type: ExportType | None = None,
        incremental_export_specification: IncrementalExportSpecification | None = None,
    ) -> ExportTableToPointInTimeOutput:
        params: dict[str, object] = {
            "table_arn": table_arn,
            "s3_bucket": s3_bucket,
        }
        if export_time is not None:
            params["export_time"] = export_time
        if client_token is not None:
            params["client_token"] = client_token
        if s3_bucket_owner is not None:
            params["s3_bucket_owner"] = s3_bucket_owner
        if s3_prefix is not None:
            params["s3_prefix"] = s3_prefix
        if s3_sse_algorithm is not None:
            params["s3_sse_algorithm"] = s3_sse_algorithm
        if s3_sse_kms_key_id is not None:
            params["s3_sse_kms_key_id"] = s3_sse_kms_key_id
        if export_format is not None:
            params["export_format"] = export_format
        if export_type is not None:
            params["export_type"] = export_type
        if incremental_export_specification is not None:
            params["incremental_export_specification"] = incremental_export_specification
        result = await self._native.export_table_to_point_in_time(params)
        return result


    async def get_item(
        self,
        *,
        table_name: str,
        key: dict[str, AttributeValue],
        attributes_to_get: list[str] | None = None,
        consistent_read: bool | None = None,
        return_consumed_capacity: ReturnConsumedCapacity | None = None,
        projection_expression: str | None = None,
        expression_attribute_names: dict[str, str] | None = None,
    ) -> GetItemOutput:
        params: dict[str, object] = {
            "table_name": table_name,
            "key": key,
        }
        if attributes_to_get is not None:
            params["attributes_to_get"] = attributes_to_get
        if consistent_read is not None:
            params["consistent_read"] = consistent_read
        if return_consumed_capacity is not None:
            params["return_consumed_capacity"] = return_consumed_capacity
        if projection_expression is not None:
            params["projection_expression"] = projection_expression
        if expression_attribute_names is not None:
            params["expression_attribute_names"] = expression_attribute_names
        result = await self._native.get_item(params)
        return result


    async def get_resource_policy(
        self,
        *,
        resource_arn: str,
    ) -> GetResourcePolicyOutput:
        params: dict[str, object] = {
            "resource_arn": resource_arn,
        }
        result = await self._native.get_resource_policy(params)
        return result


    async def import_table(
        self,
        *,
        s3_bucket_source: S3BucketSource,
        input_format: InputFormat,
        table_creation_parameters: TableCreationParameters,
        client_token: str | None = None,
        input_format_options: InputFormatOptions | None = None,
        input_compression_type: InputCompressionType | None = None,
    ) -> ImportTableOutput:
        params: dict[str, object] = {
            "s3_bucket_source": s3_bucket_source,
            "input_format": input_format,
            "table_creation_parameters": table_creation_parameters,
        }
        if client_token is not None:
            params["client_token"] = client_token
        if input_format_options is not None:
            params["input_format_options"] = input_format_options
        if input_compression_type is not None:
            params["input_compression_type"] = input_compression_type
        result = await self._native.import_table(params)
        return result


    async def list_backups(
        self,
        *,
        table_name: str | None = None,
        limit: int | None = None,
        time_range_lower_bound: str | None = None,
        time_range_upper_bound: str | None = None,
        exclusive_start_backup_arn: str | None = None,
        backup_type: BackupTypeFilter | None = None,
    ) -> ListBackupsOutput:
        params: dict[str, object] = {
        }
        if table_name is not None:
            params["table_name"] = table_name
        if limit is not None:
            params["limit"] = limit
        if time_range_lower_bound is not None:
            params["time_range_lower_bound"] = time_range_lower_bound
        if time_range_upper_bound is not None:
            params["time_range_upper_bound"] = time_range_upper_bound
        if exclusive_start_backup_arn is not None:
            params["exclusive_start_backup_arn"] = exclusive_start_backup_arn
        if backup_type is not None:
            params["backup_type"] = backup_type
        result = await self._native.list_backups(params)
        return result


    async def list_contributor_insights(
        self,
        *,
        table_name: str | None = None,
        next_token: str | None = None,
        max_results: int | None = None,
    ) -> ListContributorInsightsOutput:
        params: dict[str, object] = {
        }
        if table_name is not None:
            params["table_name"] = table_name
        if next_token is not None:
            params["next_token"] = next_token
        if max_results is not None:
            params["max_results"] = max_results
        result = await self._native.list_contributor_insights(params)
        return result


    async def list_exports(
        self,
        *,
        table_arn: str | None = None,
        max_results: int | None = None,
        next_token: str | None = None,
    ) -> ListExportsOutput:
        params: dict[str, object] = {
        }
        if table_arn is not None:
            params["table_arn"] = table_arn
        if max_results is not None:
            params["max_results"] = max_results
        if next_token is not None:
            params["next_token"] = next_token
        result = await self._native.list_exports(params)
        return result


    async def list_global_tables(
        self,
        *,
        exclusive_start_global_table_name: str | None = None,
        limit: int | None = None,
        region_name: str | None = None,
    ) -> ListGlobalTablesOutput:
        params: dict[str, object] = {
        }
        if exclusive_start_global_table_name is not None:
            params["exclusive_start_global_table_name"] = exclusive_start_global_table_name
        if limit is not None:
            params["limit"] = limit
        if region_name is not None:
            params["region_name"] = region_name
        result = await self._native.list_global_tables(params)
        return result


    async def list_imports(
        self,
        *,
        table_arn: str | None = None,
        page_size: int | None = None,
        next_token: str | None = None,
    ) -> ListImportsOutput:
        params: dict[str, object] = {
        }
        if table_arn is not None:
            params["table_arn"] = table_arn
        if page_size is not None:
            params["page_size"] = page_size
        if next_token is not None:
            params["next_token"] = next_token
        result = await self._native.list_imports(params)
        return result


    async def list_tables(
        self,
        *,
        exclusive_start_table_name: str | None = None,
        limit: int | None = None,
    ) -> ListTablesOutput:
        params: dict[str, object] = {
        }
        if exclusive_start_table_name is not None:
            params["exclusive_start_table_name"] = exclusive_start_table_name
        if limit is not None:
            params["limit"] = limit
        result = await self._native.list_tables(params)
        return result


    async def list_tags_of_resource(
        self,
        *,
        resource_arn: str,
        next_token: str | None = None,
    ) -> ListTagsOfResourceOutput:
        params: dict[str, object] = {
            "resource_arn": resource_arn,
        }
        if next_token is not None:
            params["next_token"] = next_token
        result = await self._native.list_tags_of_resource(params)
        return result


    async def put_item(
        self,
        *,
        table_name: str,
        item: dict[str, AttributeValue],
        expected: dict[str, ExpectedAttributeValue] | None = None,
        return_values: ReturnValue | None = None,
        return_consumed_capacity: ReturnConsumedCapacity | None = None,
        return_item_collection_metrics: ReturnItemCollectionMetrics | None = None,
        conditional_operator: ConditionalOperator | None = None,
        condition_expression: str | None = None,
        expression_attribute_names: dict[str, str] | None = None,
        expression_attribute_values: dict[str, AttributeValue] | None = None,
        return_values_on_condition_check_failure: ReturnValuesOnConditionCheckFailure | None = None,
    ) -> PutItemOutput:
        params: dict[str, object] = {
            "table_name": table_name,
            "item": item,
        }
        if expected is not None:
            params["expected"] = expected
        if return_values is not None:
            params["return_values"] = return_values
        if return_consumed_capacity is not None:
            params["return_consumed_capacity"] = return_consumed_capacity
        if return_item_collection_metrics is not None:
            params["return_item_collection_metrics"] = return_item_collection_metrics
        if conditional_operator is not None:
            params["conditional_operator"] = conditional_operator
        if condition_expression is not None:
            params["condition_expression"] = condition_expression
        if expression_attribute_names is not None:
            params["expression_attribute_names"] = expression_attribute_names
        if expression_attribute_values is not None:
            params["expression_attribute_values"] = expression_attribute_values
        if return_values_on_condition_check_failure is not None:
            params["return_values_on_condition_check_failure"] = return_values_on_condition_check_failure
        result = await self._native.put_item(params)
        return result


    async def put_resource_policy(
        self,
        *,
        resource_arn: str,
        policy: str,
        expected_revision_id: str | None = None,
        confirm_remove_self_resource_access: bool | None = None,
    ) -> PutResourcePolicyOutput:
        params: dict[str, object] = {
            "resource_arn": resource_arn,
            "policy": policy,
        }
        if expected_revision_id is not None:
            params["expected_revision_id"] = expected_revision_id
        if confirm_remove_self_resource_access is not None:
            params["confirm_remove_self_resource_access"] = confirm_remove_self_resource_access
        result = await self._native.put_resource_policy(params)
        return result


    async def query(
        self,
        *,
        table_name: str,
        index_name: str | None = None,
        select: Select | None = None,
        attributes_to_get: list[str] | None = None,
        limit: int | None = None,
        consistent_read: bool | None = None,
        key_conditions: dict[str, Condition] | None = None,
        query_filter: dict[str, Condition] | None = None,
        conditional_operator: ConditionalOperator | None = None,
        scan_index_forward: bool | None = None,
        exclusive_start_key: dict[str, AttributeValue] | None = None,
        return_consumed_capacity: ReturnConsumedCapacity | None = None,
        projection_expression: str | None = None,
        filter_expression: str | None = None,
        key_condition_expression: str | None = None,
        expression_attribute_names: dict[str, str] | None = None,
        expression_attribute_values: dict[str, AttributeValue] | None = None,
    ) -> QueryOutput:
        params: dict[str, object] = {
            "table_name": table_name,
        }
        if index_name is not None:
            params["index_name"] = index_name
        if select is not None:
            params["select"] = select
        if attributes_to_get is not None:
            params["attributes_to_get"] = attributes_to_get
        if limit is not None:
            params["limit"] = limit
        if consistent_read is not None:
            params["consistent_read"] = consistent_read
        if key_conditions is not None:
            params["key_conditions"] = key_conditions
        if query_filter is not None:
            params["query_filter"] = query_filter
        if conditional_operator is not None:
            params["conditional_operator"] = conditional_operator
        if scan_index_forward is not None:
            params["scan_index_forward"] = scan_index_forward
        if exclusive_start_key is not None:
            params["exclusive_start_key"] = exclusive_start_key
        if return_consumed_capacity is not None:
            params["return_consumed_capacity"] = return_consumed_capacity
        if projection_expression is not None:
            params["projection_expression"] = projection_expression
        if filter_expression is not None:
            params["filter_expression"] = filter_expression
        if key_condition_expression is not None:
            params["key_condition_expression"] = key_condition_expression
        if expression_attribute_names is not None:
            params["expression_attribute_names"] = expression_attribute_names
        if expression_attribute_values is not None:
            params["expression_attribute_values"] = expression_attribute_values
        result = await self._native.query(params)
        return result


    async def restore_table_from_backup(
        self,
        *,
        target_table_name: str,
        backup_arn: str,
        billing_mode_override: BillingMode | None = None,
        global_secondary_index_override: list[GlobalSecondaryIndex] | None = None,
        local_secondary_index_override: list[LocalSecondaryIndex] | None = None,
        provisioned_throughput_override: ProvisionedThroughput | None = None,
        on_demand_throughput_override: OnDemandThroughput | None = None,
        sse_specification_override: SSESpecification | None = None,
    ) -> RestoreTableFromBackupOutput:
        params: dict[str, object] = {
            "target_table_name": target_table_name,
            "backup_arn": backup_arn,
        }
        if billing_mode_override is not None:
            params["billing_mode_override"] = billing_mode_override
        if global_secondary_index_override is not None:
            params["global_secondary_index_override"] = global_secondary_index_override
        if local_secondary_index_override is not None:
            params["local_secondary_index_override"] = local_secondary_index_override
        if provisioned_throughput_override is not None:
            params["provisioned_throughput_override"] = provisioned_throughput_override
        if on_demand_throughput_override is not None:
            params["on_demand_throughput_override"] = on_demand_throughput_override
        if sse_specification_override is not None:
            params["sse_specification_override"] = sse_specification_override
        result = await self._native.restore_table_from_backup(params)
        return result


    async def restore_table_to_point_in_time(
        self,
        *,
        target_table_name: str,
        source_table_arn: str | None = None,
        source_table_name: str | None = None,
        use_latest_restorable_time: bool | None = None,
        restore_date_time: str | None = None,
        billing_mode_override: BillingMode | None = None,
        global_secondary_index_override: list[GlobalSecondaryIndex] | None = None,
        local_secondary_index_override: list[LocalSecondaryIndex] | None = None,
        provisioned_throughput_override: ProvisionedThroughput | None = None,
        on_demand_throughput_override: OnDemandThroughput | None = None,
        sse_specification_override: SSESpecification | None = None,
    ) -> RestoreTableToPointInTimeOutput:
        params: dict[str, object] = {
            "target_table_name": target_table_name,
        }
        if source_table_arn is not None:
            params["source_table_arn"] = source_table_arn
        if source_table_name is not None:
            params["source_table_name"] = source_table_name
        if use_latest_restorable_time is not None:
            params["use_latest_restorable_time"] = use_latest_restorable_time
        if restore_date_time is not None:
            params["restore_date_time"] = restore_date_time
        if billing_mode_override is not None:
            params["billing_mode_override"] = billing_mode_override
        if global_secondary_index_override is not None:
            params["global_secondary_index_override"] = global_secondary_index_override
        if local_secondary_index_override is not None:
            params["local_secondary_index_override"] = local_secondary_index_override
        if provisioned_throughput_override is not None:
            params["provisioned_throughput_override"] = provisioned_throughput_override
        if on_demand_throughput_override is not None:
            params["on_demand_throughput_override"] = on_demand_throughput_override
        if sse_specification_override is not None:
            params["sse_specification_override"] = sse_specification_override
        result = await self._native.restore_table_to_point_in_time(params)
        return result


    async def scan(
        self,
        *,
        table_name: str,
        index_name: str | None = None,
        attributes_to_get: list[str] | None = None,
        limit: int | None = None,
        select: Select | None = None,
        scan_filter: dict[str, Condition] | None = None,
        conditional_operator: ConditionalOperator | None = None,
        exclusive_start_key: dict[str, AttributeValue] | None = None,
        return_consumed_capacity: ReturnConsumedCapacity | None = None,
        total_segments: int | None = None,
        segment: int | None = None,
        projection_expression: str | None = None,
        filter_expression: str | None = None,
        expression_attribute_names: dict[str, str] | None = None,
        expression_attribute_values: dict[str, AttributeValue] | None = None,
        consistent_read: bool | None = None,
    ) -> ScanOutput:
        params: dict[str, object] = {
            "table_name": table_name,
        }
        if index_name is not None:
            params["index_name"] = index_name
        if attributes_to_get is not None:
            params["attributes_to_get"] = attributes_to_get
        if limit is not None:
            params["limit"] = limit
        if select is not None:
            params["select"] = select
        if scan_filter is not None:
            params["scan_filter"] = scan_filter
        if conditional_operator is not None:
            params["conditional_operator"] = conditional_operator
        if exclusive_start_key is not None:
            params["exclusive_start_key"] = exclusive_start_key
        if return_consumed_capacity is not None:
            params["return_consumed_capacity"] = return_consumed_capacity
        if total_segments is not None:
            params["total_segments"] = total_segments
        if segment is not None:
            params["segment"] = segment
        if projection_expression is not None:
            params["projection_expression"] = projection_expression
        if filter_expression is not None:
            params["filter_expression"] = filter_expression
        if expression_attribute_names is not None:
            params["expression_attribute_names"] = expression_attribute_names
        if expression_attribute_values is not None:
            params["expression_attribute_values"] = expression_attribute_values
        if consistent_read is not None:
            params["consistent_read"] = consistent_read
        result = await self._native.scan(params)
        return result


    async def tag_resource(
        self,
        *,
        resource_arn: str,
        tags: list[Tag],
    ) -> None:
        params: dict[str, object] = {
            "resource_arn": resource_arn,
            "tags": tags,
        }
        await self._native.tag_resource(params)
        return None


    async def transact_get_items(
        self,
        *,
        transact_items: list[TransactGetItem],
        return_consumed_capacity: ReturnConsumedCapacity | None = None,
    ) -> TransactGetItemsOutput:
        params: dict[str, object] = {
            "transact_items": transact_items,
        }
        if return_consumed_capacity is not None:
            params["return_consumed_capacity"] = return_consumed_capacity
        result = await self._native.transact_get_items(params)
        return result


    async def transact_write_items(
        self,
        *,
        transact_items: list[TransactWriteItem],
        return_consumed_capacity: ReturnConsumedCapacity | None = None,
        return_item_collection_metrics: ReturnItemCollectionMetrics | None = None,
        client_request_token: str | None = None,
    ) -> TransactWriteItemsOutput:
        params: dict[str, object] = {
            "transact_items": transact_items,
        }
        if return_consumed_capacity is not None:
            params["return_consumed_capacity"] = return_consumed_capacity
        if return_item_collection_metrics is not None:
            params["return_item_collection_metrics"] = return_item_collection_metrics
        if client_request_token is not None:
            params["client_request_token"] = client_request_token
        result = await self._native.transact_write_items(params)
        return result


    async def untag_resource(
        self,
        *,
        resource_arn: str,
        tag_keys: list[str],
    ) -> None:
        params: dict[str, object] = {
            "resource_arn": resource_arn,
            "tag_keys": tag_keys,
        }
        await self._native.untag_resource(params)
        return None


    async def update_continuous_backups(
        self,
        *,
        table_name: str,
        point_in_time_recovery_specification: PointInTimeRecoverySpecification,
    ) -> UpdateContinuousBackupsOutput:
        params: dict[str, object] = {
            "table_name": table_name,
            "point_in_time_recovery_specification": point_in_time_recovery_specification,
        }
        result = await self._native.update_continuous_backups(params)
        return result


    async def update_contributor_insights(
        self,
        *,
        table_name: str,
        contributor_insights_action: ContributorInsightsAction,
        index_name: str | None = None,
        contributor_insights_mode: ContributorInsightsMode | None = None,
    ) -> UpdateContributorInsightsOutput:
        params: dict[str, object] = {
            "table_name": table_name,
            "contributor_insights_action": contributor_insights_action,
        }
        if index_name is not None:
            params["index_name"] = index_name
        if contributor_insights_mode is not None:
            params["contributor_insights_mode"] = contributor_insights_mode
        result = await self._native.update_contributor_insights(params)
        return result


    async def update_global_table(
        self,
        *,
        global_table_name: str,
        replica_updates: list[ReplicaUpdate],
    ) -> UpdateGlobalTableOutput:
        params: dict[str, object] = {
            "global_table_name": global_table_name,
            "replica_updates": replica_updates,
        }
        result = await self._native.update_global_table(params)
        return result


    async def update_global_table_settings(
        self,
        *,
        global_table_name: str,
        global_table_billing_mode: BillingMode | None = None,
        global_table_provisioned_write_capacity_units: int | None = None,
        global_table_provisioned_write_capacity_auto_scaling_settings_update: AutoScalingSettingsUpdate | None = None,
        global_table_global_secondary_index_settings_update: list[GlobalTableGlobalSecondaryIndexSettingsUpdate] | None = None,
        replica_settings_update: list[ReplicaSettingsUpdate] | None = None,
    ) -> UpdateGlobalTableSettingsOutput:
        params: dict[str, object] = {
            "global_table_name": global_table_name,
        }
        if global_table_billing_mode is not None:
            params["global_table_billing_mode"] = global_table_billing_mode
        if global_table_provisioned_write_capacity_units is not None:
            params["global_table_provisioned_write_capacity_units"] = global_table_provisioned_write_capacity_units
        if global_table_provisioned_write_capacity_auto_scaling_settings_update is not None:
            params["global_table_provisioned_write_capacity_auto_scaling_settings_update"] = global_table_provisioned_write_capacity_auto_scaling_settings_update
        if global_table_global_secondary_index_settings_update is not None:
            params["global_table_global_secondary_index_settings_update"] = global_table_global_secondary_index_settings_update
        if replica_settings_update is not None:
            params["replica_settings_update"] = replica_settings_update
        result = await self._native.update_global_table_settings(params)
        return result


    async def update_item(
        self,
        *,
        table_name: str,
        key: dict[str, AttributeValue],
        attribute_updates: dict[str, AttributeValueUpdate] | None = None,
        expected: dict[str, ExpectedAttributeValue] | None = None,
        conditional_operator: ConditionalOperator | None = None,
        return_values: ReturnValue | None = None,
        return_consumed_capacity: ReturnConsumedCapacity | None = None,
        return_item_collection_metrics: ReturnItemCollectionMetrics | None = None,
        update_expression: str | None = None,
        condition_expression: str | None = None,
        expression_attribute_names: dict[str, str] | None = None,
        expression_attribute_values: dict[str, AttributeValue] | None = None,
        return_values_on_condition_check_failure: ReturnValuesOnConditionCheckFailure | None = None,
    ) -> UpdateItemOutput:
        params: dict[str, object] = {
            "table_name": table_name,
            "key": key,
        }
        if attribute_updates is not None:
            params["attribute_updates"] = attribute_updates
        if expected is not None:
            params["expected"] = expected
        if conditional_operator is not None:
            params["conditional_operator"] = conditional_operator
        if return_values is not None:
            params["return_values"] = return_values
        if return_consumed_capacity is not None:
            params["return_consumed_capacity"] = return_consumed_capacity
        if return_item_collection_metrics is not None:
            params["return_item_collection_metrics"] = return_item_collection_metrics
        if update_expression is not None:
            params["update_expression"] = update_expression
        if condition_expression is not None:
            params["condition_expression"] = condition_expression
        if expression_attribute_names is not None:
            params["expression_attribute_names"] = expression_attribute_names
        if expression_attribute_values is not None:
            params["expression_attribute_values"] = expression_attribute_values
        if return_values_on_condition_check_failure is not None:
            params["return_values_on_condition_check_failure"] = return_values_on_condition_check_failure
        result = await self._native.update_item(params)
        return result


    async def update_kinesis_streaming_destination(
        self,
        *,
        table_name: str,
        stream_arn: str,
        update_kinesis_streaming_configuration: UpdateKinesisStreamingConfiguration | None = None,
    ) -> UpdateKinesisStreamingDestinationOutput:
        params: dict[str, object] = {
            "table_name": table_name,
            "stream_arn": stream_arn,
        }
        if update_kinesis_streaming_configuration is not None:
            params["update_kinesis_streaming_configuration"] = update_kinesis_streaming_configuration
        result = await self._native.update_kinesis_streaming_destination(params)
        return result


    async def update_table(
        self,
        *,
        table_name: str,
        attribute_definitions: list[AttributeDefinition] | None = None,
        billing_mode: BillingMode | None = None,
        provisioned_throughput: ProvisionedThroughput | None = None,
        global_secondary_index_updates: list[GlobalSecondaryIndexUpdate] | None = None,
        stream_specification: StreamSpecification | None = None,
        sse_specification: SSESpecification | None = None,
        replica_updates: list[ReplicationGroupUpdate] | None = None,
        table_class: TableClass | None = None,
        deletion_protection_enabled: bool | None = None,
        multi_region_consistency: MultiRegionConsistency | None = None,
        global_table_witness_updates: list[GlobalTableWitnessGroupUpdate] | None = None,
        on_demand_throughput: OnDemandThroughput | None = None,
        warm_throughput: WarmThroughput | None = None,
    ) -> UpdateTableOutput:
        params: dict[str, object] = {
            "table_name": table_name,
        }
        if attribute_definitions is not None:
            params["attribute_definitions"] = attribute_definitions
        if billing_mode is not None:
            params["billing_mode"] = billing_mode
        if provisioned_throughput is not None:
            params["provisioned_throughput"] = provisioned_throughput
        if global_secondary_index_updates is not None:
            params["global_secondary_index_updates"] = global_secondary_index_updates
        if stream_specification is not None:
            params["stream_specification"] = stream_specification
        if sse_specification is not None:
            params["sse_specification"] = sse_specification
        if replica_updates is not None:
            params["replica_updates"] = replica_updates
        if table_class is not None:
            params["table_class"] = table_class
        if deletion_protection_enabled is not None:
            params["deletion_protection_enabled"] = deletion_protection_enabled
        if multi_region_consistency is not None:
            params["multi_region_consistency"] = multi_region_consistency
        if global_table_witness_updates is not None:
            params["global_table_witness_updates"] = global_table_witness_updates
        if on_demand_throughput is not None:
            params["on_demand_throughput"] = on_demand_throughput
        if warm_throughput is not None:
            params["warm_throughput"] = warm_throughput
        result = await self._native.update_table(params)
        return result


    async def update_table_replica_auto_scaling(
        self,
        *,
        table_name: str,
        global_secondary_index_updates: list[GlobalSecondaryIndexAutoScalingUpdate] | None = None,
        provisioned_write_capacity_auto_scaling_update: AutoScalingSettingsUpdate | None = None,
        replica_updates: list[ReplicaAutoScalingUpdate] | None = None,
    ) -> UpdateTableReplicaAutoScalingOutput:
        params: dict[str, object] = {
            "table_name": table_name,
        }
        if global_secondary_index_updates is not None:
            params["global_secondary_index_updates"] = global_secondary_index_updates
        if provisioned_write_capacity_auto_scaling_update is not None:
            params["provisioned_write_capacity_auto_scaling_update"] = provisioned_write_capacity_auto_scaling_update
        if replica_updates is not None:
            params["replica_updates"] = replica_updates
        result = await self._native.update_table_replica_auto_scaling(params)
        return result


    async def update_time_to_live(
        self,
        *,
        table_name: str,
        time_to_live_specification: TimeToLiveSpecification,
    ) -> UpdateTimeToLiveOutput:
        params: dict[str, object] = {
            "table_name": table_name,
            "time_to_live_specification": time_to_live_specification,
        }
        result = await self._native.update_time_to_live(params)
        return result

