# Generated by rboto-codegen. DO NOT EDIT.
from rboto.exceptions import ServiceError


class DynamoDBError(ServiceError):
    """Base exception for errors returned by dynamodb."""


class BackupInUseError(DynamoDBError):
    """Modeled dynamodb error: BackupInUseException."""


class BackupNotFoundError(DynamoDBError):
    """Modeled dynamodb error: BackupNotFoundException."""


class ConditionalCheckFailedError(DynamoDBError):
    """Modeled dynamodb error: ConditionalCheckFailedException."""


class ContinuousBackupsUnavailableError(DynamoDBError):
    """Modeled dynamodb error: ContinuousBackupsUnavailableException."""


class DuplicateItemError(DynamoDBError):
    """Modeled dynamodb error: DuplicateItemException."""


class ExportConflictError(DynamoDBError):
    """Modeled dynamodb error: ExportConflictException."""


class ExportNotFoundError(DynamoDBError):
    """Modeled dynamodb error: ExportNotFoundException."""


class GlobalTableAlreadyExistsError(DynamoDBError):
    """Modeled dynamodb error: GlobalTableAlreadyExistsException."""


class GlobalTableNotFoundError(DynamoDBError):
    """Modeled dynamodb error: GlobalTableNotFoundException."""


class IdempotentParameterMismatchError(DynamoDBError):
    """Modeled dynamodb error: IdempotentParameterMismatchException."""


class ImportConflictError(DynamoDBError):
    """Modeled dynamodb error: ImportConflictException."""


class ImportNotFoundError(DynamoDBError):
    """Modeled dynamodb error: ImportNotFoundException."""


class IndexNotFoundError(DynamoDBError):
    """Modeled dynamodb error: IndexNotFoundException."""


class InternalServerError(DynamoDBError):
    """Modeled dynamodb error: InternalServerError."""


class InvalidEndpointError(DynamoDBError):
    """Modeled dynamodb error: InvalidEndpointException."""


class InvalidExportTimeError(DynamoDBError):
    """Modeled dynamodb error: InvalidExportTimeException."""


class InvalidRestoreTimeError(DynamoDBError):
    """Modeled dynamodb error: InvalidRestoreTimeException."""


class ItemCollectionSizeLimitExceededError(DynamoDBError):
    """Modeled dynamodb error: ItemCollectionSizeLimitExceededException."""


class LimitExceededError(DynamoDBError):
    """Modeled dynamodb error: LimitExceededException."""


class PointInTimeRecoveryUnavailableError(DynamoDBError):
    """Modeled dynamodb error: PointInTimeRecoveryUnavailableException."""


class PolicyNotFoundError(DynamoDBError):
    """Modeled dynamodb error: PolicyNotFoundException."""


class ProvisionedThroughputExceededError(DynamoDBError):
    """Modeled dynamodb error: ProvisionedThroughputExceededException."""


class ReplicaAlreadyExistsError(DynamoDBError):
    """Modeled dynamodb error: ReplicaAlreadyExistsException."""


class ReplicaNotFoundError(DynamoDBError):
    """Modeled dynamodb error: ReplicaNotFoundException."""


class ReplicatedWriteConflictError(DynamoDBError):
    """Modeled dynamodb error: ReplicatedWriteConflictException."""


class RequestLimitExceededError(DynamoDBError):
    """Modeled dynamodb error: RequestLimitExceeded."""


class ResourceInUseError(DynamoDBError):
    """Modeled dynamodb error: ResourceInUseException."""


class ResourceNotFoundError(DynamoDBError):
    """Modeled dynamodb error: ResourceNotFoundException."""


class TableAlreadyExistsError(DynamoDBError):
    """Modeled dynamodb error: TableAlreadyExistsException."""


class TableInUseError(DynamoDBError):
    """Modeled dynamodb error: TableInUseException."""


class TableNotFoundError(DynamoDBError):
    """Modeled dynamodb error: TableNotFoundException."""


class ThrottlingError(DynamoDBError):
    """Modeled dynamodb error: ThrottlingException."""


class TransactionCanceledError(DynamoDBError):
    """Modeled dynamodb error: TransactionCanceledException."""


class TransactionConflictError(DynamoDBError):
    """Modeled dynamodb error: TransactionConflictException."""


class TransactionInProgressError(DynamoDBError):
    """Modeled dynamodb error: TransactionInProgressException."""
