# Generated by rboto-codegen. DO NOT EDIT.
from __future__ import annotations

from typing import Literal, NotRequired, Required, TypeAlias, TypedDict

from ._native import ByteStream as ByteStream

ApproximateCreationDateTimePrecision: TypeAlias = Literal['MILLISECOND', 'MICROSECOND']
AttributeAction: TypeAlias = Literal['ADD', 'PUT', 'DELETE']
BackupStatus: TypeAlias = Literal['CREATING', 'DELETED', 'AVAILABLE']
BackupType: TypeAlias = Literal['USER', 'SYSTEM', 'AWS_BACKUP']
BackupTypeFilter: TypeAlias = Literal['USER', 'SYSTEM', 'AWS_BACKUP', 'ALL']
BatchStatementErrorCodeEnum: TypeAlias = Literal['ConditionalCheckFailed', 'ItemCollectionSizeLimitExceeded', 'RequestLimitExceeded', 'ValidationError', 'ProvisionedThroughputExceeded', 'TransactionConflict', 'ThrottlingError', 'InternalServerError', 'ResourceNotFound', 'AccessDenied', 'DuplicateItem']
BillingMode: TypeAlias = Literal['PROVISIONED', 'PAY_PER_REQUEST']
ComparisonOperator: TypeAlias = Literal['EQ', 'NE', 'IN', 'LE', 'LT', 'GE', 'GT', 'BETWEEN', 'NOT_NULL', 'NULL', 'CONTAINS', 'NOT_CONTAINS', 'BEGINS_WITH']
ConditionalOperator: TypeAlias = Literal['AND', 'OR']
ContinuousBackupsStatus: TypeAlias = Literal['ENABLED', 'DISABLED']
ContributorInsightsAction: TypeAlias = Literal['ENABLE', 'DISABLE']
ContributorInsightsMode: TypeAlias = Literal['ACCESSED_AND_THROTTLED_KEYS', 'THROTTLED_KEYS']
ContributorInsightsStatus: TypeAlias = Literal['ENABLING', 'ENABLED', 'DISABLING', 'DISABLED', 'FAILED']
DestinationStatus: TypeAlias = Literal['ENABLING', 'ACTIVE', 'DISABLING', 'DISABLED', 'ENABLE_FAILED', 'UPDATING']
ExportFormat: TypeAlias = Literal['DYNAMODB_JSON', 'ION']
ExportStatus: TypeAlias = Literal['IN_PROGRESS', 'COMPLETED', 'FAILED']
ExportType: TypeAlias = Literal['FULL_EXPORT', 'INCREMENTAL_EXPORT']
ExportViewType: TypeAlias = Literal['NEW_IMAGE', 'NEW_AND_OLD_IMAGES']
GlobalTableStatus: TypeAlias = Literal['CREATING', 'ACTIVE', 'DELETING', 'UPDATING']
ImportStatus: TypeAlias = Literal['IN_PROGRESS', 'COMPLETED', 'CANCELLING', 'CANCELLED', 'FAILED']
IndexStatus: TypeAlias = Literal['CREATING', 'UPDATING', 'DELETING', 'ACTIVE']
InputCompressionType: TypeAlias = Literal['GZIP', 'ZSTD', 'NONE']
InputFormat: TypeAlias = Literal['DYNAMODB_JSON', 'ION', 'CSV']
KeyType: TypeAlias = Literal['HASH', 'RANGE']
MultiRegionConsistency: TypeAlias = Literal['EVENTUAL', 'STRONG']
PointInTimeRecoveryStatus: TypeAlias = Literal['ENABLED', 'DISABLED']
ProjectionType: TypeAlias = Literal['ALL', 'KEYS_ONLY', 'INCLUDE']
ReplicaStatus: TypeAlias = Literal['CREATING', 'CREATION_FAILED', 'UPDATING', 'DELETING', 'ACTIVE', 'REGION_DISABLED', 'INACCESSIBLE_ENCRYPTION_CREDENTIALS', 'ARCHIVING', 'ARCHIVED', 'REPLICATION_NOT_AUTHORIZED']
ReturnConsumedCapacity: TypeAlias = Literal['INDEXES', 'TOTAL', 'NONE']
ReturnItemCollectionMetrics: TypeAlias = Literal['SIZE', 'NONE']
ReturnValue: TypeAlias = Literal['NONE', 'ALL_OLD', 'UPDATED_OLD', 'ALL_NEW', 'UPDATED_NEW']
ReturnValuesOnConditionCheckFailure: TypeAlias = Literal['ALL_OLD', 'NONE']
S3SseAlgorithm: TypeAlias = Literal['AES256', 'KMS']
SSEStatus: TypeAlias = Literal['ENABLING', 'ENABLED', 'DISABLING', 'DISABLED', 'UPDATING']
SSEType: TypeAlias = Literal['AES256', 'KMS']
ScalarAttributeType: TypeAlias = Literal['S', 'N', 'B']
Select: TypeAlias = Literal['ALL_ATTRIBUTES', 'ALL_PROJECTED_ATTRIBUTES', 'SPECIFIC_ATTRIBUTES', 'COUNT']
StreamViewType: TypeAlias = Literal['NEW_IMAGE', 'OLD_IMAGE', 'NEW_AND_OLD_IMAGES', 'KEYS_ONLY']
TableClass: TypeAlias = Literal['STANDARD', 'STANDARD_INFREQUENT_ACCESS']
TableStatus: TypeAlias = Literal['CREATING', 'UPDATING', 'DELETING', 'ACTIVE', 'INACCESSIBLE_ENCRYPTION_CREDENTIALS', 'ARCHIVING', 'ARCHIVED', 'REPLICATION_NOT_AUTHORIZED']
TimeToLiveStatus: TypeAlias = Literal['ENABLING', 'DISABLING', 'ENABLED', 'DISABLED']
WitnessStatus: TypeAlias = Literal['CREATING', 'DELETING', 'ACTIVE']

ArchivalSummary = TypedDict(
    "ArchivalSummary",
    {
    "archival_date_time": NotRequired["str"],
    "archival_reason": NotRequired["str"],
    "archival_backup_arn": NotRequired["str"],
    },
)

AttributeDefinition = TypedDict(
    "AttributeDefinition",
    {
    "attribute_name": Required["str"],
    "attribute_type": Required["ScalarAttributeType"],
    },
)

AttributeValueS = TypedDict("AttributeValueS", {"s": Required["str"]})
AttributeValueN = TypedDict("AttributeValueN", {"n": Required["str"]})
AttributeValueB = TypedDict("AttributeValueB", {"b": Required["bytes"]})
AttributeValueSS = TypedDict("AttributeValueSS", {"ss": Required["list[str]"]})
AttributeValueNS = TypedDict("AttributeValueNS", {"ns": Required["list[str]"]})
AttributeValueBS = TypedDict("AttributeValueBS", {"bs": Required["list[bytes]"]})
AttributeValueM = TypedDict("AttributeValueM", {"m": Required["dict[str, AttributeValue]"]})
AttributeValueL = TypedDict("AttributeValueL", {"l": Required["list[AttributeValue]"]})
AttributeValueNULL = TypedDict("AttributeValueNULL", {"null": Required["bool"]})
AttributeValueBOOL = TypedDict("AttributeValueBOOL", {"bool": Required["bool"]})
AttributeValueUnknown = TypedDict("AttributeValueUnknown", {"unknown": Required[bool]})
AttributeValue: TypeAlias = AttributeValueS | AttributeValueN | AttributeValueB | AttributeValueSS | AttributeValueNS | AttributeValueBS | AttributeValueM | AttributeValueL | AttributeValueNULL | AttributeValueBOOL | AttributeValueUnknown

AttributeValueUpdate = TypedDict(
    "AttributeValueUpdate",
    {
    "value": NotRequired["AttributeValue"],
    "action": NotRequired["AttributeAction"],
    },
)

AutoScalingPolicyDescription = TypedDict(
    "AutoScalingPolicyDescription",
    {
    "policy_name": NotRequired["str"],
    "target_tracking_scaling_policy_configuration": NotRequired["AutoScalingTargetTrackingScalingPolicyConfigurationDescription"],
    },
)

AutoScalingPolicyUpdate = TypedDict(
    "AutoScalingPolicyUpdate",
    {
    "policy_name": NotRequired["str"],
    "target_tracking_scaling_policy_configuration": Required["AutoScalingTargetTrackingScalingPolicyConfigurationUpdate"],
    },
)

AutoScalingSettingsDescription = TypedDict(
    "AutoScalingSettingsDescription",
    {
    "minimum_units": NotRequired["int"],
    "maximum_units": NotRequired["int"],
    "auto_scaling_disabled": NotRequired["bool"],
    "auto_scaling_role_arn": NotRequired["str"],
    "scaling_policies": NotRequired["list[AutoScalingPolicyDescription]"],
    },
)

AutoScalingSettingsUpdate = TypedDict(
    "AutoScalingSettingsUpdate",
    {
    "minimum_units": NotRequired["int"],
    "maximum_units": NotRequired["int"],
    "auto_scaling_disabled": NotRequired["bool"],
    "auto_scaling_role_arn": NotRequired["str"],
    "scaling_policy_update": NotRequired["AutoScalingPolicyUpdate"],
    },
)

AutoScalingTargetTrackingScalingPolicyConfigurationDescription = TypedDict(
    "AutoScalingTargetTrackingScalingPolicyConfigurationDescription",
    {
    "disable_scale_in": NotRequired["bool"],
    "scale_in_cooldown": NotRequired["int"],
    "scale_out_cooldown": NotRequired["int"],
    "target_value": Required["float"],
    },
)

AutoScalingTargetTrackingScalingPolicyConfigurationUpdate = TypedDict(
    "AutoScalingTargetTrackingScalingPolicyConfigurationUpdate",
    {
    "disable_scale_in": NotRequired["bool"],
    "scale_in_cooldown": NotRequired["int"],
    "scale_out_cooldown": NotRequired["int"],
    "target_value": Required["float"],
    },
)

BackupDescription = TypedDict(
    "BackupDescription",
    {
    "backup_details": NotRequired["BackupDetails"],
    "source_table_details": NotRequired["SourceTableDetails"],
    "source_table_feature_details": NotRequired["SourceTableFeatureDetails"],
    },
)

BackupDetails = TypedDict(
    "BackupDetails",
    {
    "backup_arn": Required["str"],
    "backup_name": Required["str"],
    "backup_size_bytes": NotRequired["int"],
    "backup_status": Required["BackupStatus"],
    "backup_type": Required["BackupType"],
    "backup_creation_date_time": Required["str"],
    "backup_expiry_date_time": NotRequired["str"],
    },
)

BackupSummary = TypedDict(
    "BackupSummary",
    {
    "table_name": NotRequired["str"],
    "table_id": NotRequired["str"],
    "table_arn": NotRequired["str"],
    "backup_arn": NotRequired["str"],
    "backup_name": NotRequired["str"],
    "backup_creation_date_time": NotRequired["str"],
    "backup_expiry_date_time": NotRequired["str"],
    "backup_status": NotRequired["BackupStatus"],
    "backup_type": NotRequired["BackupType"],
    "backup_size_bytes": NotRequired["int"],
    },
)

BatchExecuteStatementInput = TypedDict(
    "BatchExecuteStatementInput",
    {
    "statements": Required["list[BatchStatementRequest]"],
    "return_consumed_capacity": NotRequired["ReturnConsumedCapacity"],
    },
)

BatchGetItemInput = TypedDict(
    "BatchGetItemInput",
    {
    "request_items": Required["dict[str, KeysAndAttributes]"],
    "return_consumed_capacity": NotRequired["ReturnConsumedCapacity"],
    },
)

BatchStatementError = TypedDict(
    "BatchStatementError",
    {
    "code": NotRequired["BatchStatementErrorCodeEnum"],
    "message": NotRequired["str"],
    "item": NotRequired["dict[str, AttributeValue]"],
    },
)

BatchStatementRequest = TypedDict(
    "BatchStatementRequest",
    {
    "statement": Required["str"],
    "parameters": NotRequired["list[AttributeValue]"],
    "consistent_read": NotRequired["bool"],
    "return_values_on_condition_check_failure": NotRequired["ReturnValuesOnConditionCheckFailure"],
    },
)

BatchStatementResponse = TypedDict(
    "BatchStatementResponse",
    {
    "error": NotRequired["BatchStatementError"],
    "table_name": NotRequired["str"],
    "item": NotRequired["dict[str, AttributeValue]"],
    },
)

BatchWriteItemInput = TypedDict(
    "BatchWriteItemInput",
    {
    "request_items": Required["dict[str, list[WriteRequest]]"],
    "return_consumed_capacity": NotRequired["ReturnConsumedCapacity"],
    "return_item_collection_metrics": NotRequired["ReturnItemCollectionMetrics"],
    },
)

BillingModeSummary = TypedDict(
    "BillingModeSummary",
    {
    "billing_mode": NotRequired["BillingMode"],
    "last_update_to_pay_per_request_date_time": NotRequired["str"],
    },
)

CancellationReason = TypedDict(
    "CancellationReason",
    {
    "item": NotRequired["dict[str, AttributeValue]"],
    "code": NotRequired["str"],
    "message": NotRequired["str"],
    },
)

Capacity = TypedDict(
    "Capacity",
    {
    "read_capacity_units": NotRequired["float"],
    "write_capacity_units": NotRequired["float"],
    "capacity_units": NotRequired["float"],
    },
)

Condition = TypedDict(
    "Condition",
    {
    "attribute_value_list": NotRequired["list[AttributeValue]"],
    "comparison_operator": Required["ComparisonOperator"],
    },
)

ConditionCheck = TypedDict(
    "ConditionCheck",
    {
    "key": Required["dict[str, AttributeValue]"],
    "table_name": Required["str"],
    "condition_expression": Required["str"],
    "expression_attribute_names": NotRequired["dict[str, str]"],
    "expression_attribute_values": NotRequired["dict[str, AttributeValue]"],
    "return_values_on_condition_check_failure": NotRequired["ReturnValuesOnConditionCheckFailure"],
    },
)

ConsumedCapacity = TypedDict(
    "ConsumedCapacity",
    {
    "table_name": NotRequired["str"],
    "capacity_units": NotRequired["float"],
    "read_capacity_units": NotRequired["float"],
    "write_capacity_units": NotRequired["float"],
    "table": NotRequired["Capacity"],
    "local_secondary_indexes": NotRequired["dict[str, Capacity]"],
    "global_secondary_indexes": NotRequired["dict[str, Capacity]"],
    },
)

ContinuousBackupsDescription = TypedDict(
    "ContinuousBackupsDescription",
    {
    "continuous_backups_status": Required["ContinuousBackupsStatus"],
    "point_in_time_recovery_description": NotRequired["PointInTimeRecoveryDescription"],
    },
)

ContributorInsightsSummary = TypedDict(
    "ContributorInsightsSummary",
    {
    "table_name": NotRequired["str"],
    "index_name": NotRequired["str"],
    "contributor_insights_status": NotRequired["ContributorInsightsStatus"],
    "contributor_insights_mode": NotRequired["ContributorInsightsMode"],
    },
)

CreateBackupInput = TypedDict(
    "CreateBackupInput",
    {
    "table_name": Required["str"],
    "backup_name": Required["str"],
    },
)

CreateGlobalSecondaryIndexAction = TypedDict(
    "CreateGlobalSecondaryIndexAction",
    {
    "index_name": Required["str"],
    "key_schema": Required["list[KeySchemaElement]"],
    "projection": Required["Projection"],
    "provisioned_throughput": NotRequired["ProvisionedThroughput"],
    "on_demand_throughput": NotRequired["OnDemandThroughput"],
    "warm_throughput": NotRequired["WarmThroughput"],
    },
)

CreateGlobalTableInput = TypedDict(
    "CreateGlobalTableInput",
    {
    "global_table_name": Required["str"],
    "replication_group": Required["list[Replica]"],
    },
)

CreateGlobalTableWitnessGroupMemberAction = TypedDict(
    "CreateGlobalTableWitnessGroupMemberAction",
    {
    "region_name": Required["str"],
    },
)

CreateReplicaAction = TypedDict(
    "CreateReplicaAction",
    {
    "region_name": Required["str"],
    },
)

CreateReplicationGroupMemberAction = TypedDict(
    "CreateReplicationGroupMemberAction",
    {
    "region_name": Required["str"],
    "kms_master_key_id": NotRequired["str"],
    "provisioned_throughput_override": NotRequired["ProvisionedThroughputOverride"],
    "on_demand_throughput_override": NotRequired["OnDemandThroughputOverride"],
    "global_secondary_indexes": NotRequired["list[ReplicaGlobalSecondaryIndex]"],
    "table_class_override": NotRequired["TableClass"],
    },
)

CreateTableInput = TypedDict(
    "CreateTableInput",
    {
    "attribute_definitions": Required["list[AttributeDefinition]"],
    "table_name": Required["str"],
    "key_schema": Required["list[KeySchemaElement]"],
    "local_secondary_indexes": NotRequired["list[LocalSecondaryIndex]"],
    "global_secondary_indexes": NotRequired["list[GlobalSecondaryIndex]"],
    "billing_mode": NotRequired["BillingMode"],
    "provisioned_throughput": NotRequired["ProvisionedThroughput"],
    "stream_specification": NotRequired["StreamSpecification"],
    "sse_specification": NotRequired["SSESpecification"],
    "tags": NotRequired["list[Tag]"],
    "table_class": NotRequired["TableClass"],
    "deletion_protection_enabled": NotRequired["bool"],
    "warm_throughput": NotRequired["WarmThroughput"],
    "resource_policy": NotRequired["str"],
    "on_demand_throughput": NotRequired["OnDemandThroughput"],
    },
)

CsvOptions = TypedDict(
    "CsvOptions",
    {
    "delimiter": NotRequired["str"],
    "header_list": NotRequired["list[str]"],
    },
)

Delete = TypedDict(
    "Delete",
    {
    "key": Required["dict[str, AttributeValue]"],
    "table_name": Required["str"],
    "condition_expression": NotRequired["str"],
    "expression_attribute_names": NotRequired["dict[str, str]"],
    "expression_attribute_values": NotRequired["dict[str, AttributeValue]"],
    "return_values_on_condition_check_failure": NotRequired["ReturnValuesOnConditionCheckFailure"],
    },
)

DeleteBackupInput = TypedDict(
    "DeleteBackupInput",
    {
    "backup_arn": Required["str"],
    },
)

DeleteGlobalSecondaryIndexAction = TypedDict(
    "DeleteGlobalSecondaryIndexAction",
    {
    "index_name": Required["str"],
    },
)

DeleteGlobalTableWitnessGroupMemberAction = TypedDict(
    "DeleteGlobalTableWitnessGroupMemberAction",
    {
    "region_name": Required["str"],
    },
)

DeleteItemInput = TypedDict(
    "DeleteItemInput",
    {
    "table_name": Required["str"],
    "key": Required["dict[str, AttributeValue]"],
    "expected": NotRequired["dict[str, ExpectedAttributeValue]"],
    "conditional_operator": NotRequired["ConditionalOperator"],
    "return_values": NotRequired["ReturnValue"],
    "return_consumed_capacity": NotRequired["ReturnConsumedCapacity"],
    "return_item_collection_metrics": NotRequired["ReturnItemCollectionMetrics"],
    "condition_expression": NotRequired["str"],
    "expression_attribute_names": NotRequired["dict[str, str]"],
    "expression_attribute_values": NotRequired["dict[str, AttributeValue]"],
    "return_values_on_condition_check_failure": NotRequired["ReturnValuesOnConditionCheckFailure"],
    },
)

DeleteReplicaAction = TypedDict(
    "DeleteReplicaAction",
    {
    "region_name": Required["str"],
    },
)

DeleteReplicationGroupMemberAction = TypedDict(
    "DeleteReplicationGroupMemberAction",
    {
    "region_name": Required["str"],
    },
)

DeleteRequest = TypedDict(
    "DeleteRequest",
    {
    "key": Required["dict[str, AttributeValue]"],
    },
)

DeleteResourcePolicyInput = TypedDict(
    "DeleteResourcePolicyInput",
    {
    "resource_arn": Required["str"],
    "expected_revision_id": NotRequired["str"],
    },
)

DeleteTableInput = TypedDict(
    "DeleteTableInput",
    {
    "table_name": Required["str"],
    },
)

DescribeBackupInput = TypedDict(
    "DescribeBackupInput",
    {
    "backup_arn": Required["str"],
    },
)

DescribeContinuousBackupsInput = TypedDict(
    "DescribeContinuousBackupsInput",
    {
    "table_name": Required["str"],
    },
)

DescribeContributorInsightsInput = TypedDict(
    "DescribeContributorInsightsInput",
    {
    "table_name": Required["str"],
    "index_name": NotRequired["str"],
    },
)

DescribeEndpointsRequest = TypedDict(
    "DescribeEndpointsRequest",
    {
    },
)

DescribeExportInput = TypedDict(
    "DescribeExportInput",
    {
    "export_arn": Required["str"],
    },
)

DescribeGlobalTableInput = TypedDict(
    "DescribeGlobalTableInput",
    {
    "global_table_name": Required["str"],
    },
)

DescribeGlobalTableSettingsInput = TypedDict(
    "DescribeGlobalTableSettingsInput",
    {
    "global_table_name": Required["str"],
    },
)

DescribeImportInput = TypedDict(
    "DescribeImportInput",
    {
    "import_arn": Required["str"],
    },
)

DescribeKinesisStreamingDestinationInput = TypedDict(
    "DescribeKinesisStreamingDestinationInput",
    {
    "table_name": Required["str"],
    },
)

DescribeLimitsInput = TypedDict(
    "DescribeLimitsInput",
    {
    },
)

DescribeTableInput = TypedDict(
    "DescribeTableInput",
    {
    "table_name": Required["str"],
    },
)

DescribeTableReplicaAutoScalingInput = TypedDict(
    "DescribeTableReplicaAutoScalingInput",
    {
    "table_name": Required["str"],
    },
)

DescribeTimeToLiveInput = TypedDict(
    "DescribeTimeToLiveInput",
    {
    "table_name": Required["str"],
    },
)

EnableKinesisStreamingConfiguration = TypedDict(
    "EnableKinesisStreamingConfiguration",
    {
    "approximate_creation_date_time_precision": NotRequired["ApproximateCreationDateTimePrecision"],
    },
)

Endpoint = TypedDict(
    "Endpoint",
    {
    "address": Required["str"],
    "cache_period_in_minutes": Required["int"],
    },
)

ExecuteStatementInput = TypedDict(
    "ExecuteStatementInput",
    {
    "statement": Required["str"],
    "parameters": NotRequired["list[AttributeValue]"],
    "consistent_read": NotRequired["bool"],
    "next_token": NotRequired["str"],
    "return_consumed_capacity": NotRequired["ReturnConsumedCapacity"],
    "limit": NotRequired["int"],
    "return_values_on_condition_check_failure": NotRequired["ReturnValuesOnConditionCheckFailure"],
    },
)

ExecuteTransactionInput = TypedDict(
    "ExecuteTransactionInput",
    {
    "transact_statements": Required["list[ParameterizedStatement]"],
    "client_request_token": NotRequired["str"],
    "return_consumed_capacity": NotRequired["ReturnConsumedCapacity"],
    },
)

ExpectedAttributeValue = TypedDict(
    "ExpectedAttributeValue",
    {
    "value": NotRequired["AttributeValue"],
    "exists": NotRequired["bool"],
    "comparison_operator": NotRequired["ComparisonOperator"],
    "attribute_value_list": NotRequired["list[AttributeValue]"],
    },
)

ExportDescription = TypedDict(
    "ExportDescription",
    {
    "export_arn": NotRequired["str"],
    "export_status": NotRequired["ExportStatus"],
    "start_time": NotRequired["str"],
    "end_time": NotRequired["str"],
    "export_manifest": NotRequired["str"],
    "table_arn": NotRequired["str"],
    "table_id": NotRequired["str"],
    "export_time": NotRequired["str"],
    "client_token": NotRequired["str"],
    "s3_bucket": NotRequired["str"],
    "s3_bucket_owner": NotRequired["str"],
    "s3_prefix": NotRequired["str"],
    "s3_sse_algorithm": NotRequired["S3SseAlgorithm"],
    "s3_sse_kms_key_id": NotRequired["str"],
    "failure_code": NotRequired["str"],
    "failure_message": NotRequired["str"],
    "export_format": NotRequired["ExportFormat"],
    "billed_size_bytes": NotRequired["int"],
    "item_count": NotRequired["int"],
    "export_type": NotRequired["ExportType"],
    "incremental_export_specification": NotRequired["IncrementalExportSpecification"],
    },
)

ExportSummary = TypedDict(
    "ExportSummary",
    {
    "export_arn": NotRequired["str"],
    "export_status": NotRequired["ExportStatus"],
    "export_type": NotRequired["ExportType"],
    },
)

ExportTableToPointInTimeInput = TypedDict(
    "ExportTableToPointInTimeInput",
    {
    "table_arn": Required["str"],
    "export_time": NotRequired["str"],
    "client_token": NotRequired["str"],
    "s3_bucket": Required["str"],
    "s3_bucket_owner": NotRequired["str"],
    "s3_prefix": NotRequired["str"],
    "s3_sse_algorithm": NotRequired["S3SseAlgorithm"],
    "s3_sse_kms_key_id": NotRequired["str"],
    "export_format": NotRequired["ExportFormat"],
    "export_type": NotRequired["ExportType"],
    "incremental_export_specification": NotRequired["IncrementalExportSpecification"],
    },
)

FailureException = TypedDict(
    "FailureException",
    {
    "exception_name": NotRequired["str"],
    "exception_description": NotRequired["str"],
    },
)

Get = TypedDict(
    "Get",
    {
    "key": Required["dict[str, AttributeValue]"],
    "table_name": Required["str"],
    "projection_expression": NotRequired["str"],
    "expression_attribute_names": NotRequired["dict[str, str]"],
    },
)

GetItemInput = TypedDict(
    "GetItemInput",
    {
    "table_name": Required["str"],
    "key": Required["dict[str, AttributeValue]"],
    "attributes_to_get": NotRequired["list[str]"],
    "consistent_read": NotRequired["bool"],
    "return_consumed_capacity": NotRequired["ReturnConsumedCapacity"],
    "projection_expression": NotRequired["str"],
    "expression_attribute_names": NotRequired["dict[str, str]"],
    },
)

GetResourcePolicyInput = TypedDict(
    "GetResourcePolicyInput",
    {
    "resource_arn": Required["str"],
    },
)

GlobalSecondaryIndex = TypedDict(
    "GlobalSecondaryIndex",
    {
    "index_name": Required["str"],
    "key_schema": Required["list[KeySchemaElement]"],
    "projection": Required["Projection"],
    "provisioned_throughput": NotRequired["ProvisionedThroughput"],
    "on_demand_throughput": NotRequired["OnDemandThroughput"],
    "warm_throughput": NotRequired["WarmThroughput"],
    },
)

GlobalSecondaryIndexAutoScalingUpdate = TypedDict(
    "GlobalSecondaryIndexAutoScalingUpdate",
    {
    "index_name": NotRequired["str"],
    "provisioned_write_capacity_auto_scaling_update": NotRequired["AutoScalingSettingsUpdate"],
    },
)

GlobalSecondaryIndexDescription = TypedDict(
    "GlobalSecondaryIndexDescription",
    {
    "index_name": NotRequired["str"],
    "key_schema": NotRequired["list[KeySchemaElement]"],
    "projection": NotRequired["Projection"],
    "index_status": NotRequired["IndexStatus"],
    "backfilling": NotRequired["bool"],
    "provisioned_throughput": NotRequired["ProvisionedThroughputDescription"],
    "index_size_bytes": NotRequired["int"],
    "item_count": NotRequired["int"],
    "index_arn": NotRequired["str"],
    "on_demand_throughput": NotRequired["OnDemandThroughput"],
    "warm_throughput": NotRequired["GlobalSecondaryIndexWarmThroughputDescription"],
    },
)

GlobalSecondaryIndexInfo = TypedDict(
    "GlobalSecondaryIndexInfo",
    {
    "index_name": NotRequired["str"],
    "key_schema": NotRequired["list[KeySchemaElement]"],
    "projection": NotRequired["Projection"],
    "provisioned_throughput": NotRequired["ProvisionedThroughput"],
    "on_demand_throughput": NotRequired["OnDemandThroughput"],
    },
)

GlobalSecondaryIndexUpdate = TypedDict(
    "GlobalSecondaryIndexUpdate",
    {
    "update": NotRequired["UpdateGlobalSecondaryIndexAction"],
    "create": NotRequired["CreateGlobalSecondaryIndexAction"],
    "delete": NotRequired["DeleteGlobalSecondaryIndexAction"],
    },
)

GlobalSecondaryIndexWarmThroughputDescription = TypedDict(
    "GlobalSecondaryIndexWarmThroughputDescription",
    {
    "read_units_per_second": NotRequired["int"],
    "write_units_per_second": NotRequired["int"],
    "status": NotRequired["IndexStatus"],
    },
)

GlobalTable = TypedDict(
    "GlobalTable",
    {
    "global_table_name": NotRequired["str"],
    "replication_group": NotRequired["list[Replica]"],
    },
)

GlobalTableDescription = TypedDict(
    "GlobalTableDescription",
    {
    "replication_group": NotRequired["list[ReplicaDescription]"],
    "global_table_arn": NotRequired["str"],
    "creation_date_time": NotRequired["str"],
    "global_table_status": NotRequired["GlobalTableStatus"],
    "global_table_name": NotRequired["str"],
    },
)

GlobalTableGlobalSecondaryIndexSettingsUpdate = TypedDict(
    "GlobalTableGlobalSecondaryIndexSettingsUpdate",
    {
    "index_name": Required["str"],
    "provisioned_write_capacity_units": NotRequired["int"],
    "provisioned_write_capacity_auto_scaling_settings_update": NotRequired["AutoScalingSettingsUpdate"],
    },
)

GlobalTableWitnessDescription = TypedDict(
    "GlobalTableWitnessDescription",
    {
    "region_name": NotRequired["str"],
    "witness_status": NotRequired["WitnessStatus"],
    },
)

GlobalTableWitnessGroupUpdate = TypedDict(
    "GlobalTableWitnessGroupUpdate",
    {
    "create": NotRequired["CreateGlobalTableWitnessGroupMemberAction"],
    "delete": NotRequired["DeleteGlobalTableWitnessGroupMemberAction"],
    },
)

ImportSummary = TypedDict(
    "ImportSummary",
    {
    "import_arn": NotRequired["str"],
    "import_status": NotRequired["ImportStatus"],
    "table_arn": NotRequired["str"],
    "s3_bucket_source": NotRequired["S3BucketSource"],
    "cloud_watch_log_group_arn": NotRequired["str"],
    "input_format": NotRequired["InputFormat"],
    "start_time": NotRequired["str"],
    "end_time": NotRequired["str"],
    },
)

ImportTableDescription = TypedDict(
    "ImportTableDescription",
    {
    "import_arn": NotRequired["str"],
    "import_status": NotRequired["ImportStatus"],
    "table_arn": NotRequired["str"],
    "table_id": NotRequired["str"],
    "client_token": NotRequired["str"],
    "s3_bucket_source": NotRequired["S3BucketSource"],
    "error_count": NotRequired["int"],
    "cloud_watch_log_group_arn": NotRequired["str"],
    "input_format": NotRequired["InputFormat"],
    "input_format_options": NotRequired["InputFormatOptions"],
    "input_compression_type": NotRequired["InputCompressionType"],
    "table_creation_parameters": NotRequired["TableCreationParameters"],
    "start_time": NotRequired["str"],
    "end_time": NotRequired["str"],
    "processed_size_bytes": NotRequired["int"],
    "processed_item_count": NotRequired["int"],
    "imported_item_count": NotRequired["int"],
    "failure_code": NotRequired["str"],
    "failure_message": NotRequired["str"],
    },
)

ImportTableInput = TypedDict(
    "ImportTableInput",
    {
    "client_token": NotRequired["str"],
    "s3_bucket_source": Required["S3BucketSource"],
    "input_format": Required["InputFormat"],
    "input_format_options": NotRequired["InputFormatOptions"],
    "input_compression_type": NotRequired["InputCompressionType"],
    "table_creation_parameters": Required["TableCreationParameters"],
    },
)

IncrementalExportSpecification = TypedDict(
    "IncrementalExportSpecification",
    {
    "export_from_time": NotRequired["str"],
    "export_to_time": NotRequired["str"],
    "export_view_type": NotRequired["ExportViewType"],
    },
)

InputFormatOptions = TypedDict(
    "InputFormatOptions",
    {
    "csv": NotRequired["CsvOptions"],
    },
)

ItemCollectionMetrics = TypedDict(
    "ItemCollectionMetrics",
    {
    "item_collection_key": NotRequired["dict[str, AttributeValue]"],
    "size_estimate_range_gb": NotRequired["list[float]"],
    },
)

ItemResponse = TypedDict(
    "ItemResponse",
    {
    "item": NotRequired["dict[str, AttributeValue]"],
    },
)

KeySchemaElement = TypedDict(
    "KeySchemaElement",
    {
    "attribute_name": Required["str"],
    "key_type": Required["KeyType"],
    },
)

KeysAndAttributes = TypedDict(
    "KeysAndAttributes",
    {
    "keys": Required["list[dict[str, AttributeValue]]"],
    "attributes_to_get": NotRequired["list[str]"],
    "consistent_read": NotRequired["bool"],
    "projection_expression": NotRequired["str"],
    "expression_attribute_names": NotRequired["dict[str, str]"],
    },
)

KinesisDataStreamDestination = TypedDict(
    "KinesisDataStreamDestination",
    {
    "stream_arn": NotRequired["str"],
    "destination_status": NotRequired["DestinationStatus"],
    "destination_status_description": NotRequired["str"],
    "approximate_creation_date_time_precision": NotRequired["ApproximateCreationDateTimePrecision"],
    },
)

KinesisStreamingDestinationInput = TypedDict(
    "KinesisStreamingDestinationInput",
    {
    "table_name": Required["str"],
    "stream_arn": Required["str"],
    "enable_kinesis_streaming_configuration": NotRequired["EnableKinesisStreamingConfiguration"],
    },
)

ListBackupsInput = TypedDict(
    "ListBackupsInput",
    {
    "table_name": NotRequired["str"],
    "limit": NotRequired["int"],
    "time_range_lower_bound": NotRequired["str"],
    "time_range_upper_bound": NotRequired["str"],
    "exclusive_start_backup_arn": NotRequired["str"],
    "backup_type": NotRequired["BackupTypeFilter"],
    },
)

ListContributorInsightsInput = TypedDict(
    "ListContributorInsightsInput",
    {
    "table_name": NotRequired["str"],
    "next_token": NotRequired["str"],
    "max_results": NotRequired["int"],
    },
)

ListExportsInput = TypedDict(
    "ListExportsInput",
    {
    "table_arn": NotRequired["str"],
    "max_results": NotRequired["int"],
    "next_token": NotRequired["str"],
    },
)

ListGlobalTablesInput = TypedDict(
    "ListGlobalTablesInput",
    {
    "exclusive_start_global_table_name": NotRequired["str"],
    "limit": NotRequired["int"],
    "region_name": NotRequired["str"],
    },
)

ListImportsInput = TypedDict(
    "ListImportsInput",
    {
    "table_arn": NotRequired["str"],
    "page_size": NotRequired["int"],
    "next_token": NotRequired["str"],
    },
)

ListTablesInput = TypedDict(
    "ListTablesInput",
    {
    "exclusive_start_table_name": NotRequired["str"],
    "limit": NotRequired["int"],
    },
)

ListTagsOfResourceInput = TypedDict(
    "ListTagsOfResourceInput",
    {
    "resource_arn": Required["str"],
    "next_token": NotRequired["str"],
    },
)

LocalSecondaryIndex = TypedDict(
    "LocalSecondaryIndex",
    {
    "index_name": Required["str"],
    "key_schema": Required["list[KeySchemaElement]"],
    "projection": Required["Projection"],
    },
)

LocalSecondaryIndexDescription = TypedDict(
    "LocalSecondaryIndexDescription",
    {
    "index_name": NotRequired["str"],
    "key_schema": NotRequired["list[KeySchemaElement]"],
    "projection": NotRequired["Projection"],
    "index_size_bytes": NotRequired["int"],
    "item_count": NotRequired["int"],
    "index_arn": NotRequired["str"],
    },
)

LocalSecondaryIndexInfo = TypedDict(
    "LocalSecondaryIndexInfo",
    {
    "index_name": NotRequired["str"],
    "key_schema": NotRequired["list[KeySchemaElement]"],
    "projection": NotRequired["Projection"],
    },
)

OnDemandThroughput = TypedDict(
    "OnDemandThroughput",
    {
    "max_read_request_units": NotRequired["int"],
    "max_write_request_units": NotRequired["int"],
    },
)

OnDemandThroughputOverride = TypedDict(
    "OnDemandThroughputOverride",
    {
    "max_read_request_units": NotRequired["int"],
    },
)

ParameterizedStatement = TypedDict(
    "ParameterizedStatement",
    {
    "statement": Required["str"],
    "parameters": NotRequired["list[AttributeValue]"],
    "return_values_on_condition_check_failure": NotRequired["ReturnValuesOnConditionCheckFailure"],
    },
)

PointInTimeRecoveryDescription = TypedDict(
    "PointInTimeRecoveryDescription",
    {
    "point_in_time_recovery_status": NotRequired["PointInTimeRecoveryStatus"],
    "recovery_period_in_days": NotRequired["int"],
    "earliest_restorable_date_time": NotRequired["str"],
    "latest_restorable_date_time": NotRequired["str"],
    },
)

PointInTimeRecoverySpecification = TypedDict(
    "PointInTimeRecoverySpecification",
    {
    "point_in_time_recovery_enabled": Required["bool"],
    "recovery_period_in_days": NotRequired["int"],
    },
)

Projection = TypedDict(
    "Projection",
    {
    "projection_type": NotRequired["ProjectionType"],
    "non_key_attributes": NotRequired["list[str]"],
    },
)

ProvisionedThroughput = TypedDict(
    "ProvisionedThroughput",
    {
    "read_capacity_units": Required["int"],
    "write_capacity_units": Required["int"],
    },
)

ProvisionedThroughputDescription = TypedDict(
    "ProvisionedThroughputDescription",
    {
    "last_increase_date_time": NotRequired["str"],
    "last_decrease_date_time": NotRequired["str"],
    "number_of_decreases_today": NotRequired["int"],
    "read_capacity_units": NotRequired["int"],
    "write_capacity_units": NotRequired["int"],
    },
)

ProvisionedThroughputOverride = TypedDict(
    "ProvisionedThroughputOverride",
    {
    "read_capacity_units": NotRequired["int"],
    },
)

Put = TypedDict(
    "Put",
    {
    "item": Required["dict[str, AttributeValue]"],
    "table_name": Required["str"],
    "condition_expression": NotRequired["str"],
    "expression_attribute_names": NotRequired["dict[str, str]"],
    "expression_attribute_values": NotRequired["dict[str, AttributeValue]"],
    "return_values_on_condition_check_failure": NotRequired["ReturnValuesOnConditionCheckFailure"],
    },
)

PutItemInput = TypedDict(
    "PutItemInput",
    {
    "table_name": Required["str"],
    "item": Required["dict[str, AttributeValue]"],
    "expected": NotRequired["dict[str, ExpectedAttributeValue]"],
    "return_values": NotRequired["ReturnValue"],
    "return_consumed_capacity": NotRequired["ReturnConsumedCapacity"],
    "return_item_collection_metrics": NotRequired["ReturnItemCollectionMetrics"],
    "conditional_operator": NotRequired["ConditionalOperator"],
    "condition_expression": NotRequired["str"],
    "expression_attribute_names": NotRequired["dict[str, str]"],
    "expression_attribute_values": NotRequired["dict[str, AttributeValue]"],
    "return_values_on_condition_check_failure": NotRequired["ReturnValuesOnConditionCheckFailure"],
    },
)

PutRequest = TypedDict(
    "PutRequest",
    {
    "item": Required["dict[str, AttributeValue]"],
    },
)

PutResourcePolicyInput = TypedDict(
    "PutResourcePolicyInput",
    {
    "resource_arn": Required["str"],
    "policy": Required["str"],
    "expected_revision_id": NotRequired["str"],
    "confirm_remove_self_resource_access": NotRequired["bool"],
    },
)

QueryInput = TypedDict(
    "QueryInput",
    {
    "table_name": Required["str"],
    "index_name": NotRequired["str"],
    "select": NotRequired["Select"],
    "attributes_to_get": NotRequired["list[str]"],
    "limit": NotRequired["int"],
    "consistent_read": NotRequired["bool"],
    "key_conditions": NotRequired["dict[str, Condition]"],
    "query_filter": NotRequired["dict[str, Condition]"],
    "conditional_operator": NotRequired["ConditionalOperator"],
    "scan_index_forward": NotRequired["bool"],
    "exclusive_start_key": NotRequired["dict[str, AttributeValue]"],
    "return_consumed_capacity": NotRequired["ReturnConsumedCapacity"],
    "projection_expression": NotRequired["str"],
    "filter_expression": NotRequired["str"],
    "key_condition_expression": NotRequired["str"],
    "expression_attribute_names": NotRequired["dict[str, str]"],
    "expression_attribute_values": NotRequired["dict[str, AttributeValue]"],
    },
)

Replica = TypedDict(
    "Replica",
    {
    "region_name": NotRequired["str"],
    },
)

ReplicaAutoScalingDescription = TypedDict(
    "ReplicaAutoScalingDescription",
    {
    "region_name": NotRequired["str"],
    "global_secondary_indexes": NotRequired["list[ReplicaGlobalSecondaryIndexAutoScalingDescription]"],
    "replica_provisioned_read_capacity_auto_scaling_settings": NotRequired["AutoScalingSettingsDescription"],
    "replica_provisioned_write_capacity_auto_scaling_settings": NotRequired["AutoScalingSettingsDescription"],
    "replica_status": NotRequired["ReplicaStatus"],
    },
)

ReplicaAutoScalingUpdate = TypedDict(
    "ReplicaAutoScalingUpdate",
    {
    "region_name": Required["str"],
    "replica_global_secondary_index_updates": NotRequired["list[ReplicaGlobalSecondaryIndexAutoScalingUpdate]"],
    "replica_provisioned_read_capacity_auto_scaling_update": NotRequired["AutoScalingSettingsUpdate"],
    },
)

ReplicaDescription = TypedDict(
    "ReplicaDescription",
    {
    "region_name": NotRequired["str"],
    "replica_status": NotRequired["ReplicaStatus"],
    "replica_status_description": NotRequired["str"],
    "replica_status_percent_progress": NotRequired["str"],
    "kms_master_key_id": NotRequired["str"],
    "provisioned_throughput_override": NotRequired["ProvisionedThroughputOverride"],
    "on_demand_throughput_override": NotRequired["OnDemandThroughputOverride"],
    "warm_throughput": NotRequired["TableWarmThroughputDescription"],
    "global_secondary_indexes": NotRequired["list[ReplicaGlobalSecondaryIndexDescription]"],
    "replica_inaccessible_date_time": NotRequired["str"],
    "replica_table_class_summary": NotRequired["TableClassSummary"],
    },
)

ReplicaGlobalSecondaryIndex = TypedDict(
    "ReplicaGlobalSecondaryIndex",
    {
    "index_name": Required["str"],
    "provisioned_throughput_override": NotRequired["ProvisionedThroughputOverride"],
    "on_demand_throughput_override": NotRequired["OnDemandThroughputOverride"],
    },
)

ReplicaGlobalSecondaryIndexAutoScalingDescription = TypedDict(
    "ReplicaGlobalSecondaryIndexAutoScalingDescription",
    {
    "index_name": NotRequired["str"],
    "index_status": NotRequired["IndexStatus"],
    "provisioned_read_capacity_auto_scaling_settings": NotRequired["AutoScalingSettingsDescription"],
    "provisioned_write_capacity_auto_scaling_settings": NotRequired["AutoScalingSettingsDescription"],
    },
)

ReplicaGlobalSecondaryIndexAutoScalingUpdate = TypedDict(
    "ReplicaGlobalSecondaryIndexAutoScalingUpdate",
    {
    "index_name": NotRequired["str"],
    "provisioned_read_capacity_auto_scaling_update": NotRequired["AutoScalingSettingsUpdate"],
    },
)

ReplicaGlobalSecondaryIndexDescription = TypedDict(
    "ReplicaGlobalSecondaryIndexDescription",
    {
    "index_name": NotRequired["str"],
    "provisioned_throughput_override": NotRequired["ProvisionedThroughputOverride"],
    "on_demand_throughput_override": NotRequired["OnDemandThroughputOverride"],
    "warm_throughput": NotRequired["GlobalSecondaryIndexWarmThroughputDescription"],
    },
)

ReplicaGlobalSecondaryIndexSettingsDescription = TypedDict(
    "ReplicaGlobalSecondaryIndexSettingsDescription",
    {
    "index_name": Required["str"],
    "index_status": NotRequired["IndexStatus"],
    "provisioned_read_capacity_units": NotRequired["int"],
    "provisioned_read_capacity_auto_scaling_settings": NotRequired["AutoScalingSettingsDescription"],
    "provisioned_write_capacity_units": NotRequired["int"],
    "provisioned_write_capacity_auto_scaling_settings": NotRequired["AutoScalingSettingsDescription"],
    },
)

ReplicaGlobalSecondaryIndexSettingsUpdate = TypedDict(
    "ReplicaGlobalSecondaryIndexSettingsUpdate",
    {
    "index_name": Required["str"],
    "provisioned_read_capacity_units": NotRequired["int"],
    "provisioned_read_capacity_auto_scaling_settings_update": NotRequired["AutoScalingSettingsUpdate"],
    },
)

ReplicaSettingsDescription = TypedDict(
    "ReplicaSettingsDescription",
    {
    "region_name": Required["str"],
    "replica_status": NotRequired["ReplicaStatus"],
    "replica_billing_mode_summary": NotRequired["BillingModeSummary"],
    "replica_provisioned_read_capacity_units": NotRequired["int"],
    "replica_provisioned_read_capacity_auto_scaling_settings": NotRequired["AutoScalingSettingsDescription"],
    "replica_provisioned_write_capacity_units": NotRequired["int"],
    "replica_provisioned_write_capacity_auto_scaling_settings": NotRequired["AutoScalingSettingsDescription"],
    "replica_global_secondary_index_settings": NotRequired["list[ReplicaGlobalSecondaryIndexSettingsDescription]"],
    "replica_table_class_summary": NotRequired["TableClassSummary"],
    },
)

ReplicaSettingsUpdate = TypedDict(
    "ReplicaSettingsUpdate",
    {
    "region_name": Required["str"],
    "replica_provisioned_read_capacity_units": NotRequired["int"],
    "replica_provisioned_read_capacity_auto_scaling_settings_update": NotRequired["AutoScalingSettingsUpdate"],
    "replica_global_secondary_index_settings_update": NotRequired["list[ReplicaGlobalSecondaryIndexSettingsUpdate]"],
    "replica_table_class": NotRequired["TableClass"],
    },
)

ReplicaUpdate = TypedDict(
    "ReplicaUpdate",
    {
    "create": NotRequired["CreateReplicaAction"],
    "delete": NotRequired["DeleteReplicaAction"],
    },
)

ReplicationGroupUpdate = TypedDict(
    "ReplicationGroupUpdate",
    {
    "create": NotRequired["CreateReplicationGroupMemberAction"],
    "update": NotRequired["UpdateReplicationGroupMemberAction"],
    "delete": NotRequired["DeleteReplicationGroupMemberAction"],
    },
)

RestoreSummary = TypedDict(
    "RestoreSummary",
    {
    "source_backup_arn": NotRequired["str"],
    "source_table_arn": NotRequired["str"],
    "restore_date_time": Required["str"],
    "restore_in_progress": Required["bool"],
    },
)

RestoreTableFromBackupInput = TypedDict(
    "RestoreTableFromBackupInput",
    {
    "target_table_name": Required["str"],
    "backup_arn": Required["str"],
    "billing_mode_override": NotRequired["BillingMode"],
    "global_secondary_index_override": NotRequired["list[GlobalSecondaryIndex]"],
    "local_secondary_index_override": NotRequired["list[LocalSecondaryIndex]"],
    "provisioned_throughput_override": NotRequired["ProvisionedThroughput"],
    "on_demand_throughput_override": NotRequired["OnDemandThroughput"],
    "sse_specification_override": NotRequired["SSESpecification"],
    },
)

RestoreTableToPointInTimeInput = TypedDict(
    "RestoreTableToPointInTimeInput",
    {
    "source_table_arn": NotRequired["str"],
    "source_table_name": NotRequired["str"],
    "target_table_name": Required["str"],
    "use_latest_restorable_time": NotRequired["bool"],
    "restore_date_time": NotRequired["str"],
    "billing_mode_override": NotRequired["BillingMode"],
    "global_secondary_index_override": NotRequired["list[GlobalSecondaryIndex]"],
    "local_secondary_index_override": NotRequired["list[LocalSecondaryIndex]"],
    "provisioned_throughput_override": NotRequired["ProvisionedThroughput"],
    "on_demand_throughput_override": NotRequired["OnDemandThroughput"],
    "sse_specification_override": NotRequired["SSESpecification"],
    },
)

S3BucketSource = TypedDict(
    "S3BucketSource",
    {
    "s3_bucket_owner": NotRequired["str"],
    "s3_bucket": Required["str"],
    "s3_key_prefix": NotRequired["str"],
    },
)

SSEDescription = TypedDict(
    "SSEDescription",
    {
    "status": NotRequired["SSEStatus"],
    "sse_type": NotRequired["SSEType"],
    "kms_master_key_arn": NotRequired["str"],
    "inaccessible_encryption_date_time": NotRequired["str"],
    },
)

SSESpecification = TypedDict(
    "SSESpecification",
    {
    "enabled": NotRequired["bool"],
    "sse_type": NotRequired["SSEType"],
    "kms_master_key_id": NotRequired["str"],
    },
)

ScanInput = TypedDict(
    "ScanInput",
    {
    "table_name": Required["str"],
    "index_name": NotRequired["str"],
    "attributes_to_get": NotRequired["list[str]"],
    "limit": NotRequired["int"],
    "select": NotRequired["Select"],
    "scan_filter": NotRequired["dict[str, Condition]"],
    "conditional_operator": NotRequired["ConditionalOperator"],
    "exclusive_start_key": NotRequired["dict[str, AttributeValue]"],
    "return_consumed_capacity": NotRequired["ReturnConsumedCapacity"],
    "total_segments": NotRequired["int"],
    "segment": NotRequired["int"],
    "projection_expression": NotRequired["str"],
    "filter_expression": NotRequired["str"],
    "expression_attribute_names": NotRequired["dict[str, str]"],
    "expression_attribute_values": NotRequired["dict[str, AttributeValue]"],
    "consistent_read": NotRequired["bool"],
    },
)

SourceTableDetails = TypedDict(
    "SourceTableDetails",
    {
    "table_name": Required["str"],
    "table_id": Required["str"],
    "table_arn": NotRequired["str"],
    "table_size_bytes": NotRequired["int"],
    "key_schema": Required["list[KeySchemaElement]"],
    "table_creation_date_time": Required["str"],
    "provisioned_throughput": Required["ProvisionedThroughput"],
    "on_demand_throughput": NotRequired["OnDemandThroughput"],
    "item_count": NotRequired["int"],
    "billing_mode": NotRequired["BillingMode"],
    },
)

SourceTableFeatureDetails = TypedDict(
    "SourceTableFeatureDetails",
    {
    "local_secondary_indexes": NotRequired["list[LocalSecondaryIndexInfo]"],
    "global_secondary_indexes": NotRequired["list[GlobalSecondaryIndexInfo]"],
    "stream_description": NotRequired["StreamSpecification"],
    "time_to_live_description": NotRequired["TimeToLiveDescription"],
    "sse_description": NotRequired["SSEDescription"],
    },
)

StreamSpecification = TypedDict(
    "StreamSpecification",
    {
    "stream_enabled": Required["bool"],
    "stream_view_type": NotRequired["StreamViewType"],
    },
)

TableAutoScalingDescription = TypedDict(
    "TableAutoScalingDescription",
    {
    "table_name": NotRequired["str"],
    "table_status": NotRequired["TableStatus"],
    "replicas": NotRequired["list[ReplicaAutoScalingDescription]"],
    },
)

TableClassSummary = TypedDict(
    "TableClassSummary",
    {
    "table_class": NotRequired["TableClass"],
    "last_update_date_time": NotRequired["str"],
    },
)

TableCreationParameters = TypedDict(
    "TableCreationParameters",
    {
    "table_name": Required["str"],
    "attribute_definitions": Required["list[AttributeDefinition]"],
    "key_schema": Required["list[KeySchemaElement]"],
    "billing_mode": NotRequired["BillingMode"],
    "provisioned_throughput": NotRequired["ProvisionedThroughput"],
    "on_demand_throughput": NotRequired["OnDemandThroughput"],
    "sse_specification": NotRequired["SSESpecification"],
    "global_secondary_indexes": NotRequired["list[GlobalSecondaryIndex]"],
    },
)

TableDescription = TypedDict(
    "TableDescription",
    {
    "attribute_definitions": NotRequired["list[AttributeDefinition]"],
    "table_name": NotRequired["str"],
    "key_schema": NotRequired["list[KeySchemaElement]"],
    "table_status": NotRequired["TableStatus"],
    "creation_date_time": NotRequired["str"],
    "provisioned_throughput": NotRequired["ProvisionedThroughputDescription"],
    "table_size_bytes": NotRequired["int"],
    "item_count": NotRequired["int"],
    "table_arn": NotRequired["str"],
    "table_id": NotRequired["str"],
    "billing_mode_summary": NotRequired["BillingModeSummary"],
    "local_secondary_indexes": NotRequired["list[LocalSecondaryIndexDescription]"],
    "global_secondary_indexes": NotRequired["list[GlobalSecondaryIndexDescription]"],
    "stream_specification": NotRequired["StreamSpecification"],
    "latest_stream_label": NotRequired["str"],
    "latest_stream_arn": NotRequired["str"],
    "global_table_version": NotRequired["str"],
    "replicas": NotRequired["list[ReplicaDescription]"],
    "global_table_witnesses": NotRequired["list[GlobalTableWitnessDescription]"],
    "restore_summary": NotRequired["RestoreSummary"],
    "sse_description": NotRequired["SSEDescription"],
    "archival_summary": NotRequired["ArchivalSummary"],
    "table_class_summary": NotRequired["TableClassSummary"],
    "deletion_protection_enabled": NotRequired["bool"],
    "on_demand_throughput": NotRequired["OnDemandThroughput"],
    "warm_throughput": NotRequired["TableWarmThroughputDescription"],
    "multi_region_consistency": NotRequired["MultiRegionConsistency"],
    },
)

TableWarmThroughputDescription = TypedDict(
    "TableWarmThroughputDescription",
    {
    "read_units_per_second": NotRequired["int"],
    "write_units_per_second": NotRequired["int"],
    "status": NotRequired["TableStatus"],
    },
)

Tag = TypedDict(
    "Tag",
    {
    "key": Required["str"],
    "value": Required["str"],
    },
)

TagResourceInput = TypedDict(
    "TagResourceInput",
    {
    "resource_arn": Required["str"],
    "tags": Required["list[Tag]"],
    },
)

ThrottlingReason = TypedDict(
    "ThrottlingReason",
    {
    "reason": NotRequired["str"],
    "resource": NotRequired["str"],
    },
)

TimeToLiveDescription = TypedDict(
    "TimeToLiveDescription",
    {
    "time_to_live_status": NotRequired["TimeToLiveStatus"],
    "attribute_name": NotRequired["str"],
    },
)

TimeToLiveSpecification = TypedDict(
    "TimeToLiveSpecification",
    {
    "enabled": Required["bool"],
    "attribute_name": Required["str"],
    },
)

TransactGetItem = TypedDict(
    "TransactGetItem",
    {
    "get": Required["Get"],
    },
)

TransactGetItemsInput = TypedDict(
    "TransactGetItemsInput",
    {
    "transact_items": Required["list[TransactGetItem]"],
    "return_consumed_capacity": NotRequired["ReturnConsumedCapacity"],
    },
)

TransactWriteItem = TypedDict(
    "TransactWriteItem",
    {
    "condition_check": NotRequired["ConditionCheck"],
    "put": NotRequired["Put"],
    "delete": NotRequired["Delete"],
    "update": NotRequired["Update"],
    },
)

TransactWriteItemsInput = TypedDict(
    "TransactWriteItemsInput",
    {
    "transact_items": Required["list[TransactWriteItem]"],
    "return_consumed_capacity": NotRequired["ReturnConsumedCapacity"],
    "return_item_collection_metrics": NotRequired["ReturnItemCollectionMetrics"],
    "client_request_token": NotRequired["str"],
    },
)

UntagResourceInput = TypedDict(
    "UntagResourceInput",
    {
    "resource_arn": Required["str"],
    "tag_keys": Required["list[str]"],
    },
)

Update = TypedDict(
    "Update",
    {
    "key": Required["dict[str, AttributeValue]"],
    "update_expression": Required["str"],
    "table_name": Required["str"],
    "condition_expression": NotRequired["str"],
    "expression_attribute_names": NotRequired["dict[str, str]"],
    "expression_attribute_values": NotRequired["dict[str, AttributeValue]"],
    "return_values_on_condition_check_failure": NotRequired["ReturnValuesOnConditionCheckFailure"],
    },
)

UpdateContinuousBackupsInput = TypedDict(
    "UpdateContinuousBackupsInput",
    {
    "table_name": Required["str"],
    "point_in_time_recovery_specification": Required["PointInTimeRecoverySpecification"],
    },
)

UpdateContributorInsightsInput = TypedDict(
    "UpdateContributorInsightsInput",
    {
    "table_name": Required["str"],
    "index_name": NotRequired["str"],
    "contributor_insights_action": Required["ContributorInsightsAction"],
    "contributor_insights_mode": NotRequired["ContributorInsightsMode"],
    },
)

UpdateGlobalSecondaryIndexAction = TypedDict(
    "UpdateGlobalSecondaryIndexAction",
    {
    "index_name": Required["str"],
    "provisioned_throughput": NotRequired["ProvisionedThroughput"],
    "on_demand_throughput": NotRequired["OnDemandThroughput"],
    "warm_throughput": NotRequired["WarmThroughput"],
    },
)

UpdateGlobalTableInput = TypedDict(
    "UpdateGlobalTableInput",
    {
    "global_table_name": Required["str"],
    "replica_updates": Required["list[ReplicaUpdate]"],
    },
)

UpdateGlobalTableSettingsInput = TypedDict(
    "UpdateGlobalTableSettingsInput",
    {
    "global_table_name": Required["str"],
    "global_table_billing_mode": NotRequired["BillingMode"],
    "global_table_provisioned_write_capacity_units": NotRequired["int"],
    "global_table_provisioned_write_capacity_auto_scaling_settings_update": NotRequired["AutoScalingSettingsUpdate"],
    "global_table_global_secondary_index_settings_update": NotRequired["list[GlobalTableGlobalSecondaryIndexSettingsUpdate]"],
    "replica_settings_update": NotRequired["list[ReplicaSettingsUpdate]"],
    },
)

UpdateItemInput = TypedDict(
    "UpdateItemInput",
    {
    "table_name": Required["str"],
    "key": Required["dict[str, AttributeValue]"],
    "attribute_updates": NotRequired["dict[str, AttributeValueUpdate]"],
    "expected": NotRequired["dict[str, ExpectedAttributeValue]"],
    "conditional_operator": NotRequired["ConditionalOperator"],
    "return_values": NotRequired["ReturnValue"],
    "return_consumed_capacity": NotRequired["ReturnConsumedCapacity"],
    "return_item_collection_metrics": NotRequired["ReturnItemCollectionMetrics"],
    "update_expression": NotRequired["str"],
    "condition_expression": NotRequired["str"],
    "expression_attribute_names": NotRequired["dict[str, str]"],
    "expression_attribute_values": NotRequired["dict[str, AttributeValue]"],
    "return_values_on_condition_check_failure": NotRequired["ReturnValuesOnConditionCheckFailure"],
    },
)

UpdateKinesisStreamingConfiguration = TypedDict(
    "UpdateKinesisStreamingConfiguration",
    {
    "approximate_creation_date_time_precision": NotRequired["ApproximateCreationDateTimePrecision"],
    },
)

UpdateKinesisStreamingDestinationInput = TypedDict(
    "UpdateKinesisStreamingDestinationInput",
    {
    "table_name": Required["str"],
    "stream_arn": Required["str"],
    "update_kinesis_streaming_configuration": NotRequired["UpdateKinesisStreamingConfiguration"],
    },
)

UpdateReplicationGroupMemberAction = TypedDict(
    "UpdateReplicationGroupMemberAction",
    {
    "region_name": Required["str"],
    "kms_master_key_id": NotRequired["str"],
    "provisioned_throughput_override": NotRequired["ProvisionedThroughputOverride"],
    "on_demand_throughput_override": NotRequired["OnDemandThroughputOverride"],
    "global_secondary_indexes": NotRequired["list[ReplicaGlobalSecondaryIndex]"],
    "table_class_override": NotRequired["TableClass"],
    },
)

UpdateTableInput = TypedDict(
    "UpdateTableInput",
    {
    "attribute_definitions": NotRequired["list[AttributeDefinition]"],
    "table_name": Required["str"],
    "billing_mode": NotRequired["BillingMode"],
    "provisioned_throughput": NotRequired["ProvisionedThroughput"],
    "global_secondary_index_updates": NotRequired["list[GlobalSecondaryIndexUpdate]"],
    "stream_specification": NotRequired["StreamSpecification"],
    "sse_specification": NotRequired["SSESpecification"],
    "replica_updates": NotRequired["list[ReplicationGroupUpdate]"],
    "table_class": NotRequired["TableClass"],
    "deletion_protection_enabled": NotRequired["bool"],
    "multi_region_consistency": NotRequired["MultiRegionConsistency"],
    "global_table_witness_updates": NotRequired["list[GlobalTableWitnessGroupUpdate]"],
    "on_demand_throughput": NotRequired["OnDemandThroughput"],
    "warm_throughput": NotRequired["WarmThroughput"],
    },
)

UpdateTableReplicaAutoScalingInput = TypedDict(
    "UpdateTableReplicaAutoScalingInput",
    {
    "global_secondary_index_updates": NotRequired["list[GlobalSecondaryIndexAutoScalingUpdate]"],
    "table_name": Required["str"],
    "provisioned_write_capacity_auto_scaling_update": NotRequired["AutoScalingSettingsUpdate"],
    "replica_updates": NotRequired["list[ReplicaAutoScalingUpdate]"],
    },
)

UpdateTimeToLiveInput = TypedDict(
    "UpdateTimeToLiveInput",
    {
    "table_name": Required["str"],
    "time_to_live_specification": Required["TimeToLiveSpecification"],
    },
)

WarmThroughput = TypedDict(
    "WarmThroughput",
    {
    "read_units_per_second": NotRequired["int"],
    "write_units_per_second": NotRequired["int"],
    },
)

WriteRequest = TypedDict(
    "WriteRequest",
    {
    "put_request": NotRequired["PutRequest"],
    "delete_request": NotRequired["DeleteRequest"],
    },
)
